### ISSUE TITLE
Problem: [/moderator] unable to review new currency for approval

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1010]
Problem: unable to review a new currency for approval when creating a new currency. All you can do is review the coin name.

Solution: Create a new review currency coin page.

**Comment by gazhayes** [comment]
FYI this doesn't need to allow any editing.

**Comment by gazhayes** [comment]
By the way @AshHimself what happened to the proposed changes mod queue?

**Comment by AshHimself** [comment]
Fixed in #1040
