### ISSUE TITLE
Problem: [/wallet] krazor notifications not being marked as read

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1011]
Problem: krazor notifications are not being marked as read when user clicks on the KZR currency card in wallet.

Potential solution: notifications for other currencies have a currency property which we query by and mark as read save for KZR notifications. We'll have to make an assumption that when a notification doesn't have a currency property, its by default a KZR notification - we mark these ones as read when user clicks on the KZR card in wallet.

**Comment by gazhayes** [comment]
Sounds like the simplest solution.

**Comment by samuelralak** [comment]
done in [#1029](https://github.com/Blockrazor/blockrazor/pull/1029)

**Comment by gazhayes** [comment]
Looks like someone broke this. Frontend tests weren't implemented when this was dong but they are now ;)

**Comment by gazhayes** [comment]
Was a database artefact
