### ISSUE TITLE
Problem: [problem/:id] no error message shown when github repo isn't found

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1013]
Problem: when user enters invalid github urls for the below input fields, user doesn't get an error response that the inputs failed.
<img width="1111" alt="screen shot 2018-04-08 at 4 32 40 pm" src="https://user-images.githubusercontent.com/4476552/38468128-8812b9d2-3b4a-11e8-834b-bdd91472f335.png">
Solution: show error message to user when github urls isnt't found.

**Comment by anbud** [comment]
I believe there's a check for this on the server side that's just not showing on the client side.
