### ISSUE TITLE
Problem: app content no longer centered when side menu is open

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1015]
Problem: app content is no longer centered and instead, its being pushed closer to the side menu. I changed the initial implementation for this in [#970](https://github.com/Blockrazor/blockrazor/pull/970) with the intention of getting rid of the extra white space to the right of smaller screens; and I can confirm everything was working fine after.

**Comment by gazhayes** [comment]
I logged #1018 before I noticed this. Have closed it but please see my comment for reference:

> if the display is wide enough to fit the content nicely without messing around then do that (push it past the edge of the sidebar). If the display is not wide enough for this, add a shadow to the sidebar to indicate that it is is floating. In both cases, use a font awesome icon to add a close arrow to the menu to remind the user that it can be closed.

**Comment by chamidu-supeshala** [comment]
@gazhayes as @bstarr322 fixed this, i will reopen #1018 and will do further changes that you mentioned

**Comment by gazhayes** [comment]
@bstarr322 You should comment to claim an issue _before_ starting to work on something, otherwise multiple people end up working on the same thing.
