### ISSUE TITLE
Problem: on large screens, when sidebar is open, it covers content

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1018]
Problem: 
<img width="1068" alt="screen shot 2018-04-08 at 9 22 20 pm" src="https://user-images.githubusercontent.com/8143945/38468551-80703f3a-3b7a-11e8-8569-7d2727e14a5b.png">

Solution: if the display is wide enough to fit the content nicely without messing around then do that (push it past the edge of the sidebar). If the display is not wide enough for this, add a shadow to the sidebar to indicate that it is is floating. In both cases, use a font awesome icon to add a close arrow to the menu to remind the user that it can be closed.

**Comment by chamidu-supeshala** [comment]
done in #1025
