### ISSUE TITLE
Problem: Side menu items not shown unless the user is a moderator

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1020]
Problem: side navigation bar items not displayed even after signed in, unless the user is a moderator

Solution: display side menu items also for the normal users,after they have signed in

![screenshot from 2018-04-08 23-26-19](https://user-images.githubusercontent.com/27463355/38470758-03c7626e-3b85-11e8-8e11-3844d1c8e11d.png)

**Comment by gazhayes** [comment]
@chamidu-supeshala you can close this if you are happy with the result on production.
