### ISSUE TITLE
Problem: [/] Recaptcha always shown in home route

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1021]
Problem: a recaptcha is always displaying in the main route, which won't fade away even after verifying it.

Solution: render that only when necessary

![screenshot from 2018-04-08 23-38-48](https://user-images.githubusercontent.com/27463355/38470867-cd7512cc-3b86-11e8-9085-c9fbedd733dd.png)

**Comment by bstarr322** [comment]
I can't see recaptcha at all

**Comment by chamidu-supeshala** [comment]
It fires when bot activity detected. After rendered, wont go away
