### ISSUE TITLE
problem: Its unknown what community images you have uploaded

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1042]
Problem: Its unknown what community images you have uploaded
Solution: Display a tick stating the image has been uploaded and/or approved.

@gazhayes - have we lost communities and ratings page from the UI or am I blind?

**Comment by gazhayes** [comment]
They've been removed from the menu but you can get them through the bounty page.

**Comment by AshHimself** [comment]
Fixed in #1047
