### ISSUE TITLE
problem: blockrazorbot documentation not integrated into readme

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1049]
Problem: blockrazorbot documentation not integrated into readme

**Comment by gazhayes** [comment]
Fixed in #1050

**Comment by gazhayes** [comment]
@blockrazorbot abandon

**Comment by gazhayes** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
@blockrazorbot remove "done"

**Comment by gazhayes** [comment]
@blockrazorbot abandon

**Comment by gazhayes** [comment]
Everyone feel free to use this thread to experiment with the bot ;)

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@blockrazorbot abandon

**Comment by samuelralak** [comment]
@blockrazorbot label "done"
