### ISSUE TITLE
Problem: [/] fast render doesn't work

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1051]
Problem: This subscription stops fast-render from working: https://github.com/Blockrazor/blockrazor/blob/1c0d76cbdb8b73b1a8fa03b98f906fdaec651030/imports/ui/pages/returnedCurrencies/returnedCurrencies.js#L35.
Allegedly [/problems/:id] also has the issue.

**Comment by gazhayes** [comment]
Do you have any ideas for a solution?

**Comment by janat08** [comment]
SubsCache is acting up, I'll do that one.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
This is what's preventing from fast-render working. I'll let someone else actually fix it. https://github.com/Blockrazor/blockrazor/blob/1c0d76cbdb8b73b1a8fa03b98f906fdaec651030/imports/ui/pages/returnedCurrencies/returnedCurrencies.js#L35

**Comment by janat08** [comment]
@blockrazorbot unclaim

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Fixed on `/` in #1088, but I can't reproduce it on `/problem/x`.

@blockrazorbot label "done"

**Comment by janat08** [comment]
So the solution is just to add {}, cuz it's breaking for me with trying to set limit on publication because I'm passing a param to publicaiton.

**Comment by janat08** [comment]
Logged issue here: https://github.com/abecks/meteor-fast-render/issues/16

**Comment by gazhayes** [comment]
@janat08 since the original issue is solved I'll close this. Please carefully document the problem you are having with passing params in a new issue.
