### ISSUE TITLE
Problem: [/compareCurrencies] Chart data disappears on page refresh

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1055]
Problem: When the page is refreshed after adding currencies to compare, it seems like the charts get reset and data is no longer shown. Selecting new coins doesn't help as well as the old coin info is still not reflected on the charts.

I don't have a solution for this yet as I have not taken a look at the source code to find out whats breaking this. Anyone who can do it faster - possibly before am able to investigate - can take a look.

**Comment by samuelralak** [comment]
currently working on [#1054](https://github.com/Blockrazor/blockrazor/issues/1054)

**Comment by AshHimself** [comment]
So this ticket is related and you are also working on this? You can claim it if you are.

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
fixed in [#1076](https://github.com/Blockrazor/blockrazor/pull/1076)
