### ISSUE TITLE
Problem: bot unassigns after closing issue

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1058]
Problem: I'd rather bot didn't unassign an issue when its closed as it's a matter of record.

**Comment by gazhayes** [comment]
Yeah you raise a valid point.

**Comment by gazhayes** [comment]
@blockrazorbot label done

**Comment by gazhayes** [comment]
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
@blockrazorbot remove "done"

**Comment by gazhayes** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
@blockrazorbot remove "in progress"

**Comment by gazhayes** [comment]
Yeah it works.

**Comment by gazhayes** [comment]
Finished experimenting. I'll fix this.

@blockrazorbot claim

**Comment by gazhayes** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
This requires a bit too much work to make it worthwhile. You can still see who sent the pull request to resolve it which is the important thing. You can also see who was assigned just before it was closed.
