### ISSUE TITLE
problem: [currency] SubsCache.ready() always returning false

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1068]
Problem: SubsCache.ready() always returning false therefore the LOADING indicator never goes. 

Solution: Unknown

**Comment by AshHimself** [comment]
#1057 seems to be the last PR I can see that it was working.

**Comment by janat08** [comment]
I actually turned on SubsCache in #1052.

**Comment by AshHimself** [comment]
Any ideas on what’s going on ?

**Comment by janat08** [comment]
Would you like me to find out?

**Comment by AshHimself** [comment]
Sure

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
Is upstream issue: https://github.com/ccorcos/meteor-subs-cache/issues/20

this is workaround: ``_(SubsCache.cache).chain().values().map((x) => x.ready()).reduce((a,b) => a && b).value()``
@gazhayes should I look into merging this into our subsCache. What does "_" and chain() mean?

**Comment by AshHimself** [comment]
Does enabling debug bring anymore light to the issue?

`SubsCache = new Sub(5, 10, true);`

**Comment by janat08** [comment]
Some subscriptions don't pass in params when they should.

**Comment by janat08** [comment]
Stops a bunch of subscriptions.

**Comment by janat08** [comment]
I replied in upstream issue, and we kind of have a workaround. @blockrazorbot unclaim

**Comment by gazhayes** [comment]
@janat08 are they fixing it upstream? Or if you know how to fix it just pull request to our version.

**Comment by AshHimself** [comment]
@gazhayes I believe @janat08 may of resolve the issue in #1070 waiting on merge from you to confirm.

**Comment by janat08** [comment]
That doesn't resolve.

**Comment by janat08** [comment]
_(SubsCache.cache).chain().values().map((x) => x.ready()).reduce((a,b) => a && b).value()

Will return true value, but I don't know what any of this means.

**Comment by janat08** [comment]
They have an issue for it, I guess they'd like to.

**Comment by gazhayes** [comment]
You mean because you aren't sure what it's doing upstream or just because it's confusing?
It's Functionalized  ES6, @anbud can probably explain this to you better than I can.

**Comment by anbud** [comment]
The functional code you've posted above just checks if all caches are ready (map maps them to x.ready() and reduce checks if all of them are true, if any of them is not ready, reduce will return false, otherwise the result is true).

**Comment by janat08** [comment]
That's what original code does: https://github.com/ccorcos/meteor-subs-cache/blob/07a13c0de27dcf9c81e3874edce3df6887cc02d0/src/SubsCache.js#L246

**Comment by anbud** [comment]
The only difference between the two is that the one you've posted above uses underscore/lodash chaining and respective map and reduce, while the original code uses native js map and reduce. This shouldn't make any difference though, but I'm guessing it does.

**Comment by janat08** [comment]
@blockrazorbot label "done", resolution in #1196
