### ISSUE TITLE
Problem: fast-render is sending every currency in collection for [/] despite infinite scroll

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1072]
Problem: Turning off fast render with ``FastRender.debugger.blockDDP()`` will let infinite-load continue loading rather than just the first load/set, which indicates that it will essentially send the whole collection on every visit.

**Comment by gazhayes** [comment]
If this is happening in the background it's ok (I guess it will help with searching/filtering).

But if it's waiting on load this is a major problem.

The next step here is to verify what the actual problem is.

**Comment by janat08** [comment]
It will be slower to load as it sends whole collection right of the bat, otherwise to clarify fast-render works as it should increase page load it only does so expensively.

**Comment by gazhayes** [comment]
Ah so the problem is that fast render is sending the whole collection?

**Comment by janat08** [comment]
Yes.

**Comment by gazhayes** [comment]
Ok that's definitely worth dealing with.

**Comment by gazhayes** [comment]
Yeah, very likely, but can filter/search work if we use limits?

**Comment by janat08** [comment]
you just pass reactive limit to subscription parameter.

**Comment by janat08** [comment]
All that happens is it will stop the search once it gets the amount of documents you want which is generally all that you show.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
@blockrazorbot label "unmet dependency"
