### ISSUE TITLE
Problem: [/mypending] Getting TypeError messages in browser console

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1078]
Problem: Getting the below error messages in browser console when navigating to /myPending.
<img width="1318" alt="screen shot 2018-04-12 at 8 17 06 am" src="https://user-images.githubusercontent.com/4476552/38657799-d7e20b2e-3e2a-11e8-8129-ea201473a29f.png">
Solution: find and add checks for `undefined` variables.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"
