### ISSUE TITLE
Problem:Facebook configure login popup over flows the desktop view, when not full screened

### ISSUE THREAD

**Issue by madguy02** [Blockrazor/blockrazor#108]
Problem: After clicking on configure facebook login, the popup that comes up over flows desktop view, which makes it hard to enter the credentials for facebook login

Solution: Please add a scrollbar to the pop up

**Comment by madguy02** [comment]
@gazhayes can you please look into this issue

**Comment by gazhayes** [comment]
This is a problem with the service configuration plugin. But anyway, on blockrazor.org it's already configured.

For local development you can try a web developer plugin for chrome or firefox and resize the screen for mobile/tablet simulation, for some reason that makes it work. As this only affects developers and _not_ users, and as there are workarounds to make it work on the rare situation that devs need this feature locally, it's not a big deal.

**Comment by madguy02** [comment]
@gazhayes  got it, thanks
