### ISSUE TITLE
Problem: menu close button looks bad

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1080]
Problem: the menu close button (x) looks bad. 

solution:

Use an arrow type close button (e.g. fa-angle-left) and put it further down the menu. This is more like something users are traditionally used to seeing.

**Comment by AshHimself** [comment]
i'll fix this same time I am fixing the menu @blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1084 (some testing will need to be done on mobile as it includes gestures for the menu)

**Comment by AshHimself** [comment]
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
There's an issue on small screens. 
![screenshot_2018-04-12-18-50-46-738_org mozilla firefox](https://user-images.githubusercontent.com/8143945/38673121-ec33f17a-3e82-11e8-92d0-1e7a7362dbf4.png)

The menu button does weird things. Sometimes it's an arrow, sometimes a hamburger, but it's not consistent. Sometimes it's even both.

The simplest solution is to only use the hamburger icon in the nav bar, but add a chevron arrow on the outer right hand edge of the sidebar for larger screens (and keep the hamburger as normal).

**Comment by samuelralak** [comment]
Something needs to be done about that wallet UI too :D

Samuel Ralak
Web & Mobile Software Consultant
skype: samuel.ralak | tel: (254) 706 344 347

**Comment by AshHimself** [comment]
Investigating.

**Comment by AshHimself** [comment]
@gazhayes - was there something you did to get this? I can't seem to replicate.

**Comment by gazhayes** [comment]
I randomly opened and closed (using the button as well as 'tap outside of the sidebar' gesture).

**Comment by gazhayes** [comment]
Just make it a permanent hamburger, then it's definitely solved.

**Comment by gazhayes** [comment]
And maybe on of these 
<img width="327" alt="screen shot 2018-04-12 at 7 52 42 pm" src="https://user-images.githubusercontent.com/8143945/38675755-65450c5e-3e8b-11e8-9621-0bb9b4e1b8c5.png">

**Comment by gazhayes** [comment]
I just had another look, and since this is only causing problems on small screens (where gestures are used and there's shadowing etc) maybe just make *that* a hamburger only and leave the full size screen stuff as it is since nothing is actually broken there.

**Comment by AshHimself** [comment]
@gazhayes - no problems #1091
