### ISSUE TITLE
Problem: Broken Master

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1087]
Problem: getting a blank screen when visiting `https://blockrazor.org/`. Getting the below error on the browser console
<img width="1665" alt="screen shot 2018-04-12 at 1 06 45 pm" src="https://user-images.githubusercontent.com/4476552/38670780-6d3b71b6-3e52-11e8-8ffd-816088114f29.png">

**Comment by gazhayes** [comment]
Resolved

**Comment by samuelralak** [comment]
sweet
