### ISSUE TITLE
problem: [problems] Received error from server:  Malformed method invocation

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1092]
Problem: I am getting Received error from server:  Malformed method invocation in the console but can't seem to see what the root method or code is. Anyone know?

**Comment by samuelralak** [comment]
on which page are you getting this?

**Comment by AshHimself** [comment]
ok i think I found the cause, but will need @janat08 to take a look as it relates to his code.

**Comment by gazhayes** [comment]
Which route?

**Comment by AshHimself** [comment]
@blockrazorbot  claim

**Comment by AshHimself** [comment]
@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@gazhayes - shouldn't the bot remove the in-progress label?

**Comment by gazhayes** [comment]
> shouldn't the bot remove the in-progress label?

try `@blockrazorbot done`

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by gazhayes** [comment]
What am I doing. This is for you to verify and close.

**Comment by AshHimself** [comment]
Clearly not following C4.. you won't win developer of the month ;)

**Comment by gazhayes** [comment]
No matter which emoticon I use to respond to that it will be taken the wrong way by someone. I have brought shame upon six generations of my ancestors :(

**Comment by janat08** [comment]
if there's no method name perhaps an error could be thrown.
