### ISSUE TITLE
problem: [/moderator] when rejecting a new currency no action can be taken

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1095]
Problem: when rejecting a new currency no action can be taken; it's like a modal is trying to show but it can't.
<img width="1418" alt="screen shot 2018-04-13 at 9 32 45 am" src="https://user-images.githubusercontent.com/8143945/38712367-bbfadca0-3efd-11e8-962f-eaa2234e1442.png">

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim
