### ISSUE TITLE
problem: [/moderator] approvals etc can be ignored and not given full attention

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1097]
Problem: items waiting for approval are shown in a large list, as are proposed changes, suspended users, flagged content. It's easy for moderators to skip over each item without really reading them or thinking about them if they look 'too hard'.

Possible Solution: Only show one item at a time, in a similar way to /ratings. No extra steps should be needed (e.g. the 'view' button for currency approval).

An additional problem is that the DOM will keep re-rendering if a few moderators are working at the same time, this is because every time they approve something it will vanish from everyone else's queue. The simplest solution to this problem (I guess) is to use random() on something in each relevant collection to choose a random item to display so that there's less chance someone else will be shown the same thing at the same time. 

To make this work (easily and simply) different items (wallet images, new currencies, etc) might need to be put in their own view since they are all different and in different collections. 

One way to deal with this to make it simple and easy for the moderators would be to cycle through views (new currency, wallet image, community image, proposed change, suspended user, flagged content). So after a currency is approved, it sends the moderators to /walletimageapproval (or whatever), and so on.

We shouldn't trash the other views as they could still be useful, this would be a new addition.

**Comment by gazhayes** [comment]
That's just an idea I'm throwing out there. Since there are numerous types of things to approve or reject they can't all use the same template. So instead, we could send them to a new route after they process an item, the new route would be a different type of item for approval/rejection. Just using it as an example to prompt some thinking about this issue.

**Comment by samuelralak** [comment]
Oh I get it now, so the route changes according to the next item in the approval queue. Yeah that makes perfect sense

**Comment by samuelralak** [comment]
@gazhayes would this be worth closing [#1079](https://github.com/Blockrazor/blockrazor/issues/1079) and track this issue instead?

**Comment by gazhayes** [comment]
Definitely yes

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@gazhayes items in `/moderator/flagged-users` are not actionable. moderators cannot do anything other than look at the info. what should happen to flagged users?

**Comment by gazhayes** [comment]
Only these are relevant to this issue:

new currency, wallet image, community image, proposed change, suspended user, flagged content

**Comment by gazhayes** [comment]
And this part is critical:

> We shouldn't trash the other views as they could still be useful, this would be a new addition.

So each new route (or however you want to do it) is new, not a modification of the existing stuff.

**Comment by samuelralak** [comment]
I have ended up creating a single new route `/approvals/:approval_id`for the approval items i.e Bounties, WalletImages, CommunityImages and PendingCurrencies

**Comment by samuelralak** [comment]
I would probably be breaking this down into smaller composable issues

**Comment by gazhayes** [comment]
Those are both _very_ good ideas.

**Comment by samuelralak** [comment]
Breaking this down into the following:

**Comment by chamidu-supeshala** [comment]
Hi @samuelralak , whats the progress on this buddy? Because If you do not have enough time to do it, i can give it a try.

**Comment by gazhayes** [comment]
@samuelralak if you've done work on it but are too busy to finish, you could push what you have to your fork and then @chamidu-supeshala can pick up where you left off.

**Comment by anbud** [comment]
@chamidu-supeshala, until @samuelralak responds, I believe you can take one of the following: #1276, #1277, #1278, as they're not taken by anyone and they're similar to this.

**Comment by samuelralak** [comment]
@chamidu-supeshala sorry man just seeing this now, yeah sure you can go ahead and take  it. Wouldn't want to delay this any longer

**Comment by chamidu-supeshala** [comment]
As i have already implemented #1275 in my local, i will go with it first.

**Comment by samuelralak** [comment]
ok cool

**Comment by samuelralak** [comment]
Will complete this one and make a PR today.

**Comment by chamidu-supeshala** [comment]
Hey, i didnt understand this? what do you mean ? `Will complete this one and make a PR today.`

As you have already broke this one to #1275, #1276, #1277 and #1278

**Comment by chamidu-supeshala** [comment]
@samuelralak im sorry if you are about to complete #1275. I have pushed it since i couldn't move on to any other task without either pushing or trashing my changes. And i don't know whether it is against C4. If so, feel free to close my PR and push your own changes after you completing. And again sorry for the inconvenience.

**Comment by samuelralak** [comment]
Naah @chamidu-supeshala thats perfectly fine man. don't worry about it. if I'll need to make another patch I can still create an issue and push the patch. its perfectly fine man 👍

**Comment by chamidu-supeshala** [comment]
Its my fault, i would have go with #1276 or something, as @anbud mentioned. But actually i completed work on #1275, last Saturday itself, as i had no any other work that day. Today I saw @anbud 's suggestion to go with #1276 or something, but there was no option than rejecting or pushing my changes that i made on Saturday. Only After pushing and coming back here, i saw your recent comment that you are also about to complete it tonight. Hope you understood mate. :+1:

**Comment by samuelralak** [comment]
@chamidu-supeshala thats very ok chief

**Comment by samuelralak** [comment]
@gazhayes all these tickets are done, though there are still other admin pages such as `/moderator/flagged-hashpower`,  `/moderator/exchanges` and `/moderator/solved-problems` which may also need to follow the same format

>  [/moderator] approval Items #1275
  [/changedCurrencies] proposed changes #1276
  [/moderator/pardon] suspended users #1277
  [/moderator/flagged] flagged content #1278

Some UI modifications are also needed for some admin pages that do not require any user action - these are mostly read-only pages with tables.

Also please advise on the status of `/moderator/questions`, should we still leave it as it is for now?

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot remove "unmet dependency"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
done in [#1275](https://github.com/Blockrazor/blockrazor/issues/1275), [#1276](https://github.com/Blockrazor/blockrazor/issues/1276), [#1277](https://github.com/Blockrazor/blockrazor/issues/1277) and  [#1278](https://github.com/Blockrazor/blockrazor/issues/1278)
