### ISSUE TITLE
problem: [/] no filtering for future projects

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1101]
Problem: many projects added to Blockrazor will be future projects (genesis block not yet mined). These are ICOs and altcoins etc that are proposed but haven't been launched yet.

Solution: from the UI perspective this can be as simple as a checkbox in the filter "show projects that haven't launched yet". There are existing flags for project type in the currencies collection in "launchtags".

The simplest solution to this _might_ require solving this too: the add coin form has to be verified to be working properly and putting the right stuff in the currencies collection for future projects. A genesis block timestamp is a very accurate and fixed timestamp, while a planned future launch date is not, so they should (probably) not be using the same field in the collection.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
#1130 is a dependency for testing this one

**Comment by chamidu-supeshala** [comment]
fixed in #1160

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"
