### ISSUE TITLE
problem: no krazor distribution metrics

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1102]
Problem: only a fixed amount of Krazor can be distributed per year. Bounties might need to be adjusted to ensure that the available Krazor doesn't run out. At the moment, there's no easy way to see projections of how soon the available Krazor will run out if expenses continue at the current rate.

Solution: calculate the total Krazor earned through auctions and expended through boubties, project this out for a month/6 months/a year so that the community can make the right decision about bounty rate adjustment.

**Comment by anbud** [comment]
I'll take this one.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1106.

@blockrazorbot done
