### ISSUE TITLE
Problem: top navbar menu looks bad, is not using bootswatch

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1108]
Problem: standard bootswatch should be used for all UI elements, it is not being used for the top navbar menu items (currently only 'bounties').

Solution: use standard bootswatch for menu items, don't use custom fonts etc.

Bootswatch elements can be seen here: https://bootswatch.com/lux/

It should end up looking something like this:

<img width="604" alt="screen shot 2018-04-14 at 11 33 44 am" src="https://user-images.githubusercontent.com/8143945/38763893-dfd8ed30-3fd7-11e8-9aa1-a800fda8e1fd.png">

**Comment by gazhayes** [comment]
ping @AshHimself @chamidu-supeshala

**Comment by AshHimself** [comment]
@blockrazorbot claim will do whilst finishing off #631

**Comment by chamidu-supeshala** [comment]
Just saw this, hope @AshHimself  already started.

**Comment by AshHimself** [comment]
I have. @gazhayes any more menu items you want added to top too? or we leaving the same icons and BOUNTIES.

**Comment by gazhayes** [comment]
The C4 will probably have something to say about it later but I can't think of anything right now.

**Comment by AshHimself** [comment]
Fixed in #1129 wow this was harder than I thought. I didn't realize that everything there was all custom :/

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by AshHimself** [comment]
@blockrazorbot label "done"

**Comment by AshHimself** [comment]
Ok, so the reason there was no highlighting was because the highlight was white and we default the text to white, so will need custom CSS for different highlight which is fine.

As for the heights its at the Bootwatch default right now but reducing it is no issues. @blockrazorbot claim

**Comment by gazhayes** [comment]
OK can you document everything you know about this in a new issue?

**Comment by AshHimself** [comment]
You got it mate..
