### ISSUE TITLE
problem: [/bounties] filtering is annoying to use

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1110]
Problem: the current way that bounties are filtered is to use a dropdown box and select the Type of bounties you want to see. This is clunky and annoying.

Possible solution: use checkboxes instead of a dropdown, and save the state of checkboxes so users don't have to change settings every time they go to the page.

Set the default to all checked so that users see all bounties initially.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
done in #1122

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
Really nice job on this. I know it's only simply but this is so much nicer to use now.
