### ISSUE TITLE
Problem: fast-render can't accept publication params

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1116]
Problem: Fast render stops working if you pass params into sub and pub doesn't even have to use the param to fail in fast render which is tested with ``FastRender.debugger.blockDDP()``.

**Comment by janat08** [comment]
#1072 dependant

**Comment by janat08** [comment]
logged issue here: https://github.com/abecks/meteor-fast-render/issues/16

**Comment by gazhayes** [comment]
No client or server error messages etc? Or it simply doesn't do anything?

So no one who uses fast render in their projects can pass params, and no one has noticed this yet?

You have to be more specific on that issue you logged upstream, they definitely aren't going to help unless you make it **really** easy for them to help. They need to know exactly how to reproduce this problem without putting any effort into it.

**Comment by janat08** [comment]
No error messages, and doesn't fast-render. I'll try to debug this @blockrazorbot claim

**Comment by janat08** [comment]
Turned out to be that subsCache can't handle duplicate subscriptions with different params.
