### ISSUE TITLE
Problem: editCoin method doesn't use SimpleSchema that is elaborate

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1118]
Problem: edit coin method should be converted to SimpleSchema use once addCoin has been converted.

Solution: Once #617 has finished SimpleSchema editCoin should also be converted. @blockrazorbot claim.

**Comment by janat08** [comment]
@blockrazorbot unclaim.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1485. The old method actually had no validation at all, just some random validation code copied from the old addCoin method which did nothing in this case.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
