### ISSUE TITLE
Problem: [/problems] doesn't have list readiness messages (loading/nothing found)

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1124]
Problem: [/problems] doesn't determine if list is loading or has loaded but there's nothing found.

Solution: Use what all the other lists in repo use with else in each block and global helper for SubsCache.ready().

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1137.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
