### ISSUE TITLE
problem: [/auction] auctions do not show the price per Krazor

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1126]
Problem: auctions show the total highest bid for the amount of Krazor on sale (or vice versa) but do not show the price per coin.

Since we know the price in USD of the other currencies that Krazor is traded with, we could show the price in the bid currency *and* USD, this would be much more useful.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1136.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
