### ISSUE TITLE
problem: [/wallet] logos are incorrect

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1127]
Problem: the wrong logos are used on the /wallet page. 

solution: look for existing logos for each currency from the currencies collection and use them (dynamically) from there. This will also have the effect of keeping the logo up to date if it changes upstream.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
No real reason, but only a few coins are needed (the ones that are already there) so they can't just be pulled from the currencies collection.

**Comment by AshHimself** [comment]
Fixed in #1140

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by gazhayes** [comment]
@AshHimself can you look into why the ethereum logo isn't working?

**Comment by AshHimself** [comment]
Sure can, just had a look and I had etherium-classic instead of etherium on
the currency lookup... ooops.

**Comment by AshHimself** [comment]
Fixed in #1194 @gazhayes 

@blockrazorbot label "done"

**Comment by gazhayes** [comment]
Looks like you fixed the notification thing but not the logo with that PR?

**Comment by AshHimself** [comment]
I think I actually fixed the notification issue by mistake as that was also looking for etherium-classic as well lol PR sent.

**Comment by AshHimself** [comment]
@blockrazorbot label "done"
