### ISSUE TITLE
problem: we are using two versions of bootstrap

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1133]
problem: we are using two versions of bootstrap and this seems to be causing issues with fonts and other styling issues. The meteor bootstrap version we have is a beta version and its out of beta.

Solution: Remove Bootstrap beta version and only use the Bootstrap JS file and not the CSS as we are using the Bootswatch custom CSS file.

**Comment by AshHimself** [comment]
Ok so I think I have this sorted. I have;
- Removed Bootstrap Meteor package and we are now using NPM.
- Had to remove the X-editable package which we were using on Atmosphere as it was loading before bootstrap and causing havoc. 
- I tried the NPM package of X-editable but wasn't able to get it to work (future task possibly)
- I then moved it locally but was still getting an error, I did make a minor change to the code to fix that which it should probably have anyway, I would submit a PR but the project looks to of not processed a PR in some time.

**Comment by gazhayes** [comment]
You still have to claim things before working on them even if you logged them, otherwise the system breaks down and we get stuck in a time loop (end of the world as we know it).

**Comment by gazhayes** [comment]
> I tried the NPM package of X-editable but wasn't able to get it to work

It's very likely that @anbud or @janat08 will be able to fix this later, just log a problem once you send a PR

> I would submit a PR but the project looks to of not processed a PR in some time.

We can fork it under blockrazor and maintain it ourselves, unless there's someone else who's been doing anything more recent.

**Comment by AshHimself** [comment]
Great Scott I forgot!

I would say let's try NPM first because I believe the issue is the X-editable package loads before bootstrap which is why i'm getting the error (can't control load order with Meteor packages)

@blockrazorbot claim

**Comment by AshHimself** [comment]
@blockrazorbot done
