### ISSUE TITLE
Problem: no indication of how many users have recently signed up

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1143]
Problem: It's not very clear (to end users) how active the site is or how fast it's growing.

Solution: display how many users have signed up in the last x days (last 30 days I guess?).

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1157.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
