### ISSUE TITLE
Problem: "Loading" everywhere, refresh often needed

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1144]
Problem: "Loading" is displayed in many places and it just sits there until the page is refreshed.

It is especially noticeable on the curencydetails route but happens everywhere.

@janat08 is this subscache related?

**Comment by janat08** [comment]
Is fast-render.debugger.block() enbaled?

**Comment by gazhayes** [comment]
Not unless it's enabled by default everywhere.

**Comment by gazhayes** [comment]
If I block DDP it's much worse.

**Comment by janat08** [comment]
Global readiness check used everywhere, but otherwise: ``for (var x in SubsCache.cache){console.log(x, SubsCache.cache[x].ready())}`` will say everything is ready.

**Comment by janat08** [comment]
Is this new after my last commit?

**Comment by gazhayes** [comment]
It's after one of your recent commits but not sure which one. 

Disabling fast render and enabling DDP makes things like the / route completely break on refresh too.

**Comment by janat08** [comment]
I think I'll change the global helper try and filter out subs that are genuinely in use and then check them one by one. @blockrazorbot claim

**Comment by janat08** [comment]
Couldn't reproduce DDP blocked refresh breaking down.

**Comment by gazhayes** [comment]
On production server or local?

**Comment by janat08** [comment]
yes.

**Comment by janat08** [comment]
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
This is still a problem in some places, for example I just noticed it on the /changedCurrencies route.

**Comment by gazhayes** [comment]
Actually it's just slow loading, different issue.
