### ISSUE TITLE
Problem: [/] infinite scroll forces user back to top of page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1145]
Problem: when the user hits the bottom of the page and infinite scroll is triggered, all currencies disappear and "Loading" is displayed, it then forces the user back to the top of the page and starts displaying currencies again.

Probably subscache related.

**Comment by janat08** [comment]
I was trying to destroy the previous sub, and didn't account for lag. Using global ready() check is probably a bad idea altogether. The sub should probably stop being incremented once local collection is in use.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
@blockrazorbot label "done"
