### ISSUE TITLE
Problem: [/auctions] dropdown selector is annoying

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1148]
Problem: the dropdown selector to show closed auctions is not very nice UX.

Solution: use checkboxes ("show open auctions", "show completed auctions"). No need to show cancelled auctions, only complete and open.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1191 @blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by gazhayes** [comment]
Just to make this a bit easier for users, can you default 'show open' to true and 'show completed' to false?

Also, to make the UI nicer, can you use these (below) bootswatch checkboxes (whenever you edit anything with checkboxes in it):

<img width="381" alt="screen shot 2018-04-17 at 11 33 20 am" src="https://user-images.githubusercontent.com/8143945/38847233-2bdc50a2-4233-11e8-8cb9-4c7b7f3b6f15.png">

https://bootswatch.com/lux/

**Comment by AshHimself** [comment]
Ooo, didn't realise they had custom elements on the right side of the page :)

Done in #1193

**Comment by AshHimself** [comment]
@blockrazorbot label "done"
