### ISSUE TITLE
Problem: [/auctions] only auction creator needs to see 'cancel' option on auctions

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1150]
Problem: at present, there's an entire column dedicated to cancelling auctions and it's not necessary.

solution: put the cancellation link on the auction detail page instead, and only display to the creator of the auction.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed in #1162

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"
