### ISSUE TITLE
problem: [/auctions] time displayed is absolute

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1151]
Problem: the auction end time is displayed as an absolute time which is a bit difficult for users to wrap their heads around. 

Solution: either use momentjs to give a "ends in 9 days" type time, or use a countdown timer: 
<img width="270" alt="screen shot 2018-04-16 at 6 13 54 pm" src="https://user-images.githubusercontent.com/8143945/38803491-ff7f0b08-41a1-11e8-8d0f-a346514731e2.png">

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1181.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
