### ISSUE TITLE
Problem: [/auctions] users have to click into an auction to see the price and highest bid

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1153]
Problem: the price per Krazor in the bidding currency and USD not shown on the auction table so users have to click into an auction to see the price. Same for the highest bid.

Solution: display this data on the auction table.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1172.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
