### ISSUE TITLE
problem: checkbox and Datepicker styles missing

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1161]
Problem: checkbox and date picker styles were missing

Solution: need to fix styles

**Comment by gazhayes** [comment]
Bootswatch should be used in preference to bootstrap for this if possible.

**Comment by gazhayes** [comment]
Ping @AshHimself is this a missing library from your bootstrap issue?

**Comment by gazhayes** [comment]
Bootswatch checkbox examples:

```
<div class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" id="customCheck1" checked="">
      <label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>
</div>
```
https://bootswatch.com/lux/

**Comment by gazhayes** [comment]
@AshHimself they are broken in many places for me (e.g. the bounties page)

**Comment by AshHimself** [comment]
Right... so we have two choices.. figure out why the current checkboxes are broken, or fix them broken ones to conform to the bootwatch style which I know works.

**Comment by gazhayes** [comment]
> fix them broken ones to conform to the bootwatch style

That's the simplest solution.

However it would be nice to know why they broke and if there are any landmines waiting for us so keep your eyes out.

**Comment by AshHimself** [comment]
I'll do both but concentrate on the bootwatch style. My guess is that's its
an old class that's been retired. In some cases I found class names to be
different from Bootstrap 4 beta and the official which drove me insane.

**Comment by gazhayes** [comment]
>  In some cases I found class names to be different from Bootstrap 4 beta and the official which drove me insane.

They should be using the C4. The C4 would never allow that to happen. We do not break userspace!

**Comment by chamidu-supeshala** [comment]
Yes it may use some class from previous versions of bootstrap, @AshHimself did you started checking on this? if not i will check.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed in #1161

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"
