### ISSUE TITLE
Problem: [navbar] wallet icon is redundant

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1163]
Problem: there is a wallet icon, as well as a KZR amount, it's not necessary to have both.

Solution: remove the wallet icon, move wallet notification badge to the KRZ amount instead. Bootswatch should be used for the badge. The "light" badge from bootswatch would probably look best but I don't know.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
@gazhayes as light badge is also white, it might conflict with text to see. First I will apply and see.  Other thing is, for small screens, i think it is better to have wallet icon again, as KZR amount moved to side-nav when screen size is small

**Comment by chamidu-supeshala** [comment]
fixed in #1173

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"
