### ISSUE TITLE
Problem: winning currency displayed at same time as "put your coin here" item

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1164]
Problem: if there's a winning currency, it should be at the top. If not, there should be a 'put your ICO or coin here' notice. The problem is that *both* are shown.

![screen shot 2018-04-16 at 8 36 58 pm](https://user-images.githubusercontent.com/8143945/38809465-2a0e7cd2-41b6-11e8-893b-872a2c6dbc60.png)

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1178.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
