### ISSUE TITLE
Problem: [navbar] icon logo missing from top navbar on small screens

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1165]
Problem: on small screens, there isn't enough space for the full logo. There was a placeholder icon before, but it has disappeared.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed in #1175

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"
