### ISSUE TITLE
Problem: [/] "new users in the last month" loads slowly

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1166]
Problem: "new users in the last month" loads slowly and might give people a bad immediate impression. 

Possible Solution: add it to fast render
Possible solution: I haven't checked how this has been coded but if it's doing a .count every time it would be easier on the CPU to run a cron job once every 12 hours (or whatever) and denormalize this into an existing collection that is already used on the [/] route.

**Comment by anbud** [comment]
@blockrazorbot claim

I'll implement the second solution, it seems better.

**Comment by anbud** [comment]
Done in #1176.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
