### ISSUE TITLE
Problem: [/changedcurrencies] Exception while simulating the effect of invoking 'voteOnCurrencyChange' TypeError: Cannot read property 'clientAddress' of undefined

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1167]
Problem: 
When merging or downvoting changes:
```
Exception while simulating the effect of invoking 'voteOnCurrencyChange' TypeError: Cannot read property 'clientAddress' of undefined
```
We do not need to check client IP address here anyway as this is done in a separate system which should be robust enough to catch cheats (and if it isn't that's the thing to be improved).

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed #1179

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"
