### ISSUE TITLE
problem: [/transactions] incorrect total coin count

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1169]
Problem: this is most likely very incorrect
![screen shot 2018-04-16 at 9 11 30 pm](https://user-images.githubusercontent.com/8143945/38810984-e00b4084-41ba-11e8-9ee7-48da35d2a646.png)

**Comment by anbud** [comment]
It probably takes all currencies into account now, and I've deposited quite a lot of USD on my account. :D 
I'll fix it.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1174.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
