### ISSUE TITLE
problem: unable to limit views or menu by role

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#117]
Problem: unable to limit views or menu by role.

Solution: Implement meteor-roles to offer role base security.

**Comment by gazhayes** [comment]
FYI if you look at the extra users collection there's a moderator flag somewhere there which is what I've been using so far.

There was some reason I didnt use meteor roles but cant remember why, does it require allow/deny?

**Comment by gazhayes** [comment]
I had a think about this:

1. Implementing this means all existing code that checks for a user's role would need to be reworked 
2. There are only really 2 roles: user, and moderator. Both these roles are already implemented.

So adding meteor-roles just adds complexity.

I think the reason I looked at this as a solution before and decided to just simply set and check for a flag was that this package is big and complicated but not necessary.

**Comment by gazhayes** [comment]
#123 is slightly related

**Comment by AshHimself** [comment]
@gazhayes  - I agree, I was not aware of your current implementation prior to raising this. Closing ticket as no longer required.
