### ISSUE TITLE
Problem: [/transactions] incorrect amounts displayed

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1183]
Problem: the amounts displayed on /transactions are incorrect. For example there are a number of 0.1KZR transactions which are being displayed in scientific notation (horrible for users) *and* they are the wrong value (0.000000e+0 instead of 0.1).

**Comment by samuelralak** [comment]
Is this an old transaction or a new one?

**Comment by gazhayes** [comment]
These are new. That reminds me I need to log an issue to show dates and types.

**Comment by samuelralak** [comment]
thats strange. all new KZR transactions after April 3rd should have their correct amounts displayed. If its earlier than that then its just stale data - we agreed not to do anything for older transactions. If this is happening to new data, then it needs some further investigation.

**Comment by samuelralak** [comment]
aah yeah, I see it now. was looking in the wrong, brain was probably still initialising, lol.

**Comment by samuelralak** [comment]
simply returning `this.amount` seems to clear up this issue. pushing this change

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"
