### ISSUE TITLE
problem: [auction] cannot bid small amounts 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1185]
Problem: the minimum bid accuracy is 0.00, however this seriously limits the minimum amount of KZR someone can sell for (for example) XMR or BTC because other uses would have to bid a very high amount (e.g. a minimum of about US$100 if using BTC). 

Solution: allow bids down to 0.00000 of accuracy.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1202 

@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by gazhayes** [comment]
Looks like jQuery is still stopping this from happening. Did you test?

**Comment by AshHimself** [comment]
I did, how is it stopping you? I can look into it more.

@blockrazorbot claim

**Comment by gazhayes** [comment]
I get this: 

<img width="750" alt="screen shot 2018-04-18 at 5 37 19 pm" src="https://user-images.githubusercontent.com/8143945/38924301-2e32b010-432f-11e8-9144-4445a8e71d8d.png">

**Comment by AshHimself** [comment]
@gazhayes - ok sorry I missed testing actually posting the form itself. 

This opens a larger issue. We seem to have multiple methods of validating data on this.
 - sAlert is prompting users of missing values
- jquery validation is prompting users at the attribute level of incorrect values

**Comment by AshHimself** [comment]
@gazhayes - what is actually enforcing this error is the actual step values I have defined on the input. e.g. I have defined 0.00001 so it will ONLY accept those. 

- Do we want the validation to be this strict? 
- We can remove the stepper and just make sure the value is an integer
- Investigate my previous post and fix the wild wild west.

**Comment by AshHimself** [comment]
@gazhayes any thoughts on this mate?

**Comment by gazhayes** [comment]
> We can remove the stepper and just make sure the value is an integer

Yeah just do that, and should probably kill sAlert for that page and just use inline jquery on the fields themselves (onBlur). Also default reserve to 0 so that if they don't type anything in it doesn't give an error.

**Comment by AshHimself** [comment]
Fixed in #1238
@gazhayes - Good thing to know is that those error messages you were getting were not actually jquery but Chrome validation as part of html5 attributes (ewww) I have removed them entirely and used bootstrap validation instead. 

Stepper was also not removed but changed it value to 'any' (learned that you could do that today. 

@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done
