### ISSUE TITLE
problem: [/transactions] date of transaction not shown

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1186]
Problem: transaction dates are not shown.

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
fixed in [#1192](https://github.com/Blockrazor/blockrazor/pull/1192)
