### ISSUE TITLE
problem: [/transactions] transaction types are not shown

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1187]
Problem: the Type of transactions are not shown. @AshHimself added these (apparently) to the methods that add transactions to the database so it should just be a matter of adding them to the UI.

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
fixed in [#1190](https://github.com/Blockrazor/blockrazor/pull/1190)
