### ISSUE TITLE
Problem: changes to subscription parameters can easily break subscache

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1196]
Problem: changes to subscription parameters can easily break subscache, creating serious and immediate problems that are sometimes hard to debug.

Possible solution: make subscache tolerant of fast render using different parameters (I'm listing this here for reference but it's most likely not the simplest solution).

Possible solution: write tests for every subscription to make sure that subs and fast render use the same parameters.

Possible solution: create a replacement method to handle subscriptions and use that instead of using subscriptions and fast render directly.

ping @janat08 @anbud

**Comment by janat08** [comment]
Changing params shouldn't actually break the page for good anymore instead just breaking fast-render.

If you properly label test that compares what fast render's params and subsCache's params then it should work.

https://stackoverflow.com/questions/17221573/is-it-possible-to-view-all-active-subscriptions
SubsCache.cache hold subscriptions as "["subName", ...params ]"

**Comment by janat08** [comment]
@andbud will supposedly write first test.

**Comment by anbud** [comment]
The example is in #1211.

**Comment by janat08** [comment]
I think the label should be changed to fast-render params.

**Comment by anbud** [comment]
@janat08, we can call it whatever we want. :)

**Comment by janat08** [comment]
How did #1252 pass?

**Comment by anbud** [comment]
Those subscriptions inside global helpers in #1237 weren't defined in the Router properly, so there was a param mismatch. #1252 passed as the params are perfectly fine again. The test falls back to checking regular subscriptions if it can't find FastRender subscriptions.

**Comment by janat08** [comment]
I took a look at the publication and it's broken, because there wasn't even accompanying fast-render subscription (that was working) to break subscache.

**Comment by janat08** [comment]
Test is fine, the most recent ordeal had to do with bad publication.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
@anbud check out the last pull request.

**Comment by anbud** [comment]
@janat08, I'll do it tomorrow. :)

**Comment by janat08** [comment]
thats how i had it beofre.

**Comment by janat08** [comment]
Could you install chrome in default location so than then people wouldn't have to try and follow this instruction for resetting config: https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-Using-a-Chrome-executable-in-a-non-standard-location.

**Comment by janat08** [comment]
I'll create a separate config for debugging on windows.

**Comment by anbud** [comment]
The test should be fixed in #1340. (we'll see for sure when CI finishes)

**Comment by janat08** [comment]
@blockrazorbot label "done"
