### ISSUE TITLE
Problem: [/bounties] checkbox state not saved

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1199]
Problem:  when users select or clear checkboxes they have to do it again next time they visit the page. This is annoying, especially since if someone hides the stuff where coding skills are required because they will probably never want to see those items if they aren't developers.

Solution: I guess use cookies? Or it could be put into their userdata document so it survives across devices.

**Comment by chamidu-supeshala** [comment]
This is already implemented. ( saving user's preference in UserData collection) It should work if not broken somewhere

**Comment by chamidu-supeshala** [comment]
I just checked and it is working for me, though it is harder to see which are checked and which are not, due to #1161

**Comment by gazhayes** [comment]
Huh, you're right. Not sure how I missed this.
