### ISSUE TITLE
Problem: No filter on ratings page

### ISSUE THREAD

**Issue by anbud** [Blockrazor/blockrazor#120]
Problem: No filter on `ratings` page which will be a problem when the number of cryptocurrencies available on the site rises

Solution: Add a way to filter cryptocurrencies by name (and possibly some other fields)
I'm taking this and implementing the solution above right away.

**Comment by anbud** [comment]
Fixed in #121.

**Comment by gazhayes** [comment]
@anbud As the issue creator, you can close this if you are satisfied that it is fixed.
