### ISSUE TITLE
Problem: [/auctions] new auctions are not showing up

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1200]
Problem: creating a new auction to sell Krazor for USD doesn't appear to be working. The KZR is deducted from the wallet but the auction does not display.

Solution: not sure if this is UI or something deeper as I haven't looked.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1203 
@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done
