### ISSUE TITLE
problem: users cannot add an email address to be notified on launch

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1201]
Problem: users cannot add an email address to be notified on launch

solution: add an email address input field on the modal that shows up on first use. Allow not-logged-in and logged-in users to submit an email address. Using a captcha here would also be a good idea but it's not critical.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes you thinking just a temp collection we store these in and get rid of after launch? Probably the easiest thing being we want to capture logged in and not.

**Comment by gazhayes** [comment]
Yeah exactly what I was thinking.

**Comment by AshHimself** [comment]
@gazhayes almost done this. Do you want these emails going somewhere for a mailing list? segment can do that for us easily.

**Comment by gazhayes** [comment]
Nah just dirt simple list

**Comment by AshHimself** [comment]
PR inbound.

**Comment by AshHimself** [comment]
Fixed in #1227 I didn't add the captcha as I didn't want to waste time figuring out how to do it. Best best is to just export the list to excel remove duplicate if any and remove the shit if any. I have email validation on it so should remove most of the crap.

@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by gazhayes** [comment]
Which collection are these going into?

**Comment by AshHimself** [comment]
http://drmongo.blockrazor/meteor/meteor/launchemails
