### ISSUE TITLE
Problem: [/bounties] repeating bounties are not reset if page is left open

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1208]
Problem: repeating bounty values are not reset after another user completes the bounty if the page is left open. Values are only reset once page is refreshed (or navigated away from and back to). What should happen is the bounty resets reactively.

Solution: there's a possibility this is subscache related, but it also might not be.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1270.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
