### ISSUE TITLE
Problem: initial load of / route is too slow

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1209]
Problem: the initial load of the / route is too slow

Solution: please propose possible solutions to increase initial load speed and then this can be broken up into individual problems.

ping @janat08 @anbud @AshHimself @samuelralak @kevgathuku

**Comment by anbud** [comment]
We could possibly reduce and/or optimize subscriptions for the home page, it'll help.

**Comment by janat08** [comment]
dynamic imports could help. I believe besides it serving as cache it will also defer initializing rest of the app?

**Comment by gazhayes** [comment]
Definitely, dynamic imports are key. Can you make a new issue for that and tag this master issue?

**Comment by AshHimself** [comment]
#332 will tell us a lot more too. As well as looking at all the data we are loading onto / and if correct indexes are setup or even exist.

**Comment by gazhayes** [comment]
This is a report from Pingdom:

<img width="1047" alt="screen shot 2018-04-19 at 6 52 04 pm" src="https://user-images.githubusercontent.com/8143945/38987555-ce64f8f8-4402-11e8-8b7e-8d15daad91d3.png">

It would kind of be cool to know why there are all these 1/2 second 'connect' and 'wait' periods which add almost 4 seconds to load time. I guess it's just ping time which Meteor can do nothing about, but worth confirming. DNS lookup is also taking almost 700ms but again that's out of Meteor's control so I'll dig into that later.

It takes 1 second to find the server, then another 1 second to get past SSL negotiation. I'll see what I can do about that.

**Comment by AshHimself** [comment]
Another thing to add is that at our total meteor package is almost at 800kb now so that'll obviously have a little download time for slower connections.

**Comment by gazhayes** [comment]
@janat08 is implementing dynamic imports wherever possible on / route to help with that.

**Comment by janat08** [comment]
You know you could probably parse spacebars and blaze into nx-framework since it can inherit state and has proxies (like 10% of peoples browsers not supported), and use SSR.

**Comment by janat08** [comment]
more like 5%

**Comment by gazhayes** [comment]
That would be too much of a sweeping change anyway.

**Comment by janat08** [comment]
I meant mapping blaze api to nx-framework api calls, converting all of blaze files to nx engine, possibly even for minimongo. I'd like to give it a try with the money back guarantee, with a ceiling of 8 hours payable. Blaze isn't actively maintained since 2015, and it's behind in terms of reactivity by generations with getters/setters and then proxies following it.

**Comment by gazhayes** [comment]
I'll close this now, just log discrete issues for any speed and size related problems.
