### ISSUE TITLE
Problem: [/currency/x] UI is very ugly

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1210]
Problem: the currency detail UI is probably the ugliest page on the whole site.

Solution: make this look as nice as possible, whoever takes this has free reign to do what they think is right. The C4 will refine it after that.

Requirements: use bootswatch as much as possible, avoid any custom styles. Bootswatch elements can be seen here: https://bootswatch.com/lux/

ping @chamidu-supeshala @MadanBhandari @samuelralak

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
done in #1240

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
