### ISSUE TITLE
Problem: something weird going on with Ethereum Classic hashpower calculations

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1215]
Problem: there's something strange going on with ethereum classic hashpower calculations, it's much higher than it should be. In fact I can't even see how it's getting these calculations at all, there could be some weird interaction with Ethereum itself.

Solution: work out what the haspower *should* be and then work out what's happening.

ping @anbud

**Comment by anbud** [comment]
I think I know what's going on here.

@blockrazorbot claim

**Comment by anbud** [comment]
Fixed in #1224.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
