### ISSUE TITLE
Problem: can't easily determine which accounts are duplicate and ban them

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1216]
Problem: We log IP addresses in the event log, and when more than one user has the same IP address the users are flagged, but this is just a list of usernames and IPs. This isn't enough to determine if something nefarious is going on.

Possible solution:

Create a view showing (side by side) all users who share the same IP address. Show as much of their recent data as possible (comments/features/etc, completed bounties, bounties they have approved (if moderator), upvotes/downvotes. This is not a strict list, just an example - some of these might be painful to add, and there might be other things that are also indicative of user similarities that are easier to add. At the bottom of the page put a "these accounts are the same people" and "these accounts are probably not the same person" link on each. Require +3 or -3 cumulative votes (from moderators) to either suspend the user (this can use the existing strike system), or to ignore this IP address for a month.

Requirements: the IP addresses to look for must be sign up, login, or access. E.g. if someone accesses the site from an IP that was used by someone else to sign up with a month ago (and never again) this should trigger the review above. This may introduce another problem to be solved first.

ping @anbud I'm pretty sure this is for you.

**Comment by anbud** [comment]
Agreed, this one's for me. :)

@blockrazorbot claim

**Comment by anbud** [comment]
Basic functionality is in #1226. We can, of course, extend the list of data shown on the page.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
