### ISSUE TITLE
Problem: no home link in sidebar

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1217]
Problem: some people testing the site so far have complained that it's hard to navigate back to home as not everyone knows about the customary UI protocol of "the logo goes back to home".

Solution: add a "home" menu item as the first item on the sidebar.

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
done in [#1225](https://github.com/Blockrazor/blockrazor/pull/1225)

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"
@blockrazorbot label "done"
