### ISSUE TITLE
Problem: [/] subscriptions are not optimized for speed

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1222]
Problem: home route subscriptions are not optimized for speed and this is making the home route slower than necessary.

**Comment by anbud** [comment]
I've optimized subscriptions in #1233.
But, we should probably leave this open for some time if somebody else has more ideas on how to further optimize them.

@blockrazorbot abandon

**Comment by janat08** [comment]
I don't really know what transpires in publication, but if it concatenates parameters from client-side query and publication the extra sort operators aren't helping, as there're indexing limitations with some of the rougher ones touching on needless sort operations, that is if u query by ``x1`` and sort by ``x2``, it will only ever use the x1 index or x2 index.
