### ISSUE TITLE
Problem: [/] route does not use dynamic imports

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1223]
Problem: the home route does not use dynamic imports and this degrades loading speed.

Solution: implement [dynamic import](https://docs.meteor.com/packages/dynamic-import.html) on home route and test with bundle visualizer.

**Comment by gazhayes** [comment]
@janat08 I updated your problem to one that is more C4ish.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
You can implement dynamic route for a page, and expect any speed improvements on that page. The way it works is that you dynamically import other pages so that they don't drag down the page that should speed up.

**Comment by janat08** [comment]
I believe what happens is that essentially home route is considered an add-on to initial bundle, which is then asked once initial bundle consisting of everything other than home-route is loaded.

**Comment by janat08** [comment]
2. .. seconds on fast 3g. 3.12mb bundle.
8 seconds on 4x slow down without 3g throttling.
10 seconds on 4x and 3g fast.

**Comment by janat08** [comment]
It's what bundle visualizer shows, presumably an unzipped bundle.

**Comment by janat08** [comment]
Anyway the tests are bad i had cache enabled.

**Comment by gazhayes** [comment]
Ah yes probably unzipped. Also, FYI I'm pretty sure meteor doesn't add compression or minification unless you use --production.

**Comment by AshHimself** [comment]
--production isn't supposed to be used in 'production' its used to simulate
it. You should really use meteor build for actual production use.

Source: https://guide.meteor.com/deployment.html

**Comment by gazhayes** [comment]
I'm just talking about 'dev' production

**Comment by AshHimself** [comment]
haha 10-4

**Comment by janat08** [comment]
6.81, 5.34, 5.4/ 2.78, 1.73, 1.78. in order of finished, DOM loaded, and load. and fast render broke too.

**Comment by gazhayes** [comment]
> I don't think it even does dynamic imports in dev.

It will if you use --production

**Comment by janat08** [comment]
I had to use https://github.com/VeliovGroup/flow-router, and that doesn't work with our fast-render package.

**Comment by janat08** [comment]
Should I continue persuing this? I'll look at a number of MB I could hypothetically remove from home route, on top of compatibility (which was heavy) folder which appeared to hold non-essential packages that yet broke home-route.

**Comment by janat08** [comment]
If you want to take a look yourself at whats going on with bundle: ``meteor --extra-packages bundle-visualizer --production`` Some of the packages like graphs that are used only on some routes are also hefty, but dynamically importing every route will add another roundtrip to loading which isn't properly simulated in the network.

**Comment by janat08** [comment]
Like 280kb, and I graph library just dissapeard from bundle visualizer.

**Comment by gazhayes** [comment]
This should probably be it's own issue but we should actually be using `ostrio:flow-router-extra` (https://github.com/VeliovGroup/flow-router/) anyway because the one we are using is no longer maintained.

**Comment by gazhayes** [comment]
> I had to use https://github.com/VeliovGroup/flow-router, and that doesn't work with our fast-render package.

What happened with fast-render when you did that?

**Comment by gazhayes** [comment]
> Should I continue persuing this?

It's worth playing around a bit more to see what you can come up with, but if it's not interesting you could also just send a PR with any improvement at all that you have so far, I can take a look at this myself later.

**Comment by janat08** [comment]
@blockrazorbot label "unmet dependency" #1268

**Comment by janat08** [comment]
@blockrazorbot remove "unmet dependency"

**Comment by janat08** [comment]
simple-schema makes it into bundle thanks to global helpers in main.js
Other offenders:
xmlbuilder
sweetalert
making like 130kb in total of 3 packages
theres also core-js and mime-db that I don't know what they do at 200kb

Main page breaks and only main page*:
![screenshot 32](https://user-images.githubusercontent.com/11337345/39399344-d3febbc2-4b3d-11e8-8000-ad6c0843a062.png)

**Comment by janat08** [comment]
*I moved files in compatibility to dynamic import, which might break pages where they're used if user lands directly there.

**Comment by janat08** [comment]
Should I make a pull request? 

Also stop using random package which I added personally I think as that contributes like 700kb. https://github.com/meteor/node-stubs/issues/6

**Comment by gazhayes** [comment]
> I moved files in compatibility to dynamic import, which might break pages where they're used if user lands directly there.

How painful is it to fix that?

> Should I make a pull request?

The only concern I have is trying not to break anything ;) If you're pretty sure that nothing breaks then send a PR.

**Comment by janat08** [comment]
- [ ] chart is not defined when landing on elsewhere and then moving to [/compareCurrencies]. It doesn't use reusable component (chart).

- [ ] currencyDetails blank

- [ ] bootsrap edtiable images not imported dynamically (this might work https://atmospherejs.com/nathantreid/static-assets, but I don't know like under what namespace those images are used.)

- [ ] home page broken

**Comment by janat08** [comment]
anyone knows what is core-js and mimedb and if they're an issue in this context, or knows why node-meteor-stubs is in the bundle (im not great with npm). I would just create an issue for these 3.

**Comment by gazhayes** [comment]
Ping @anbud

**Comment by janat08** [comment]
btw package random is also used for analytics I think.

**Comment by anbud** [comment]
@janat08,  as far as I remember, core-js provides shims and polyfills for es5, es6 and even es7+ proposals. I believe it's used by Meteor itself.
Mimedb (mime-types) is used for mime type checking on upload forms, I don't think we have any of those on the home route.

**Comment by janat08** [comment]
Theres ecmascript package that I argues does what core-js does, so Id like to just delete it. As for mimedb, lol, I imagine it's bundled as part of methods. Ill look into making it a stubbed out global, and deleting every reference.

**Comment by janat08** [comment]
Simply removing random package kept the node-stubs in bundle, so I'll give up on that although it will make up possibly third of app bundle with these and other issues resolved (and I imagine it contributes to initialization time).

**Comment by janat08** [comment]
I think Ill move the mime methods back out of client. unless @anbud wants to implement global that replicates mime functionality for the select methods and filetypes we use.

**Comment by janat08** [comment]
Lol I skipped the part where you said core-js is used by meteor itself.
