### ISSUE TITLE
problem: some views require redirection to a login page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#123]
For example: users who are not logged in should be able to see a "add currency" menu item or button in the UI but then be redirected to a login/signup page when they click it. Currently this login page does not exist so when this situation rises there's nowhere to redirect users.

It would also be nice if the login page can redirect a user back to the referring page after they have logged in.

**Comment by anbud** [comment]
I'm taking this one.

**Comment by gazhayes** [comment]
@anbud if possible could you also do a well documented example of how to use your solution (in a separate commit), maybe apply it to the 'add currency' page.

**Comment by anbud** [comment]
The new login page is in #124, and the documented example of how to use it (on /addcoin) is in #125.
