### ISSUE TITLE
Problem: not possible to add new moderators/maintainers

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1230]
First a quick note about terminology. Moderators in Blockrazor are akin to Maintainers under the C4. The C4 is what should be guiding the process of collecting data and problem solving with Blockrazor, but things are obviously a little different when comparing the Blockrazor platform to software development and we are going out into the unknown here to see what works and what doesn't.

------
Problem: It's not currently possible to add new moderators. 

Solution: The simplest way to do this is probably to rank users by a variety of metrics and invite the x percentile of users to become moderators. This should not be _completely_ automated though, existing maintainers should still have to approve them.

This is just a suggestion, other metrics might be just as valuable but easier to use:
- Overall comment rating (this already exists)
- Total number of comments in the last 30 days (by comments, I mean summaries, features, comments, etc)
- Total bounties completed

Limits:
- 0 strikes in the last 30 days
- No duplicate IP flags
- Obviously cannot already be a moderator, so don't check users with the moderator flag.

Users who rank in the top 30% of total users based on these metrics should be added to the approval list (I guess a daily cron job), and then existing moderators can vote. This can basically be the same as the duplicate IP voting page - +3/-3 cumulative vote required to approve or decline.

ping @anbud pretty sure this is another one for you.

**Comment by anbud** [comment]
Lovely, I'm taking this one, I like it.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1253.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
