### ISSUE TITLE
Problem: style guide is a reference and not actually a C4 style guide

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1232]
Problem: C4 projects are inherently messy but they become even more messy if there isn't a style guide. This isn't the only reason for a style guide however, though the other reasons are quite a lot deeper and center around detecting and purging bad actors (C4 projects attract 'graffiti' in the same way Wikipedia does). This is why the C4 states that *if* there's a style guide, it *must* be followed. However our style guide is a really just a reference and not a C4 style guide, it can't be used with the C4 process because it's too long and involved.

Solution: move the existing style guide to docs and use it as a suggested reference only.  Define a new style guide. This should only contain the most critical things that help prevent people from going insane.
Whoever claims this can go first, but anyone can add to it at any time by following the C4 process. If there's something that other people keep doing that annoys you then _you_ should add it to the style guide as a regular problem/solution (one problem at a time).  If you aren't annoyed enough by something to add it to the style guide then it's not a problem worth solving. If there's something in the style guide that is causing a problem, you can document the problem and updated the style guide.

That way, the style guide will be relevant to our actual use-case, it will grow and refine itself along with the project instead of being a list of arbitrary rules.

**Comment by janat08** [comment]
Why don't we go for VS Code style that is chiefly goes as always write on new line with indentation when using ``{`` or ``.`` in succession and ``, ``if the line is large.
```
Template.currendata()
Template.
  name.
  onCreated(function{
    ...
```

**Comment by gazhayes** [comment]
Yeah, I don't see any problems with that. You could add that as the first rule in the style guide :)

**Comment by janat08** [comment]
I switched to webstorm so two spaces as a tab.
