### ISSUE TITLE
problem: [/addcoin] ReferenceError: addCoin is not defined

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1235]
Problem: [/addcoin] ReferenceError: addCoin is not defined

Solution: fix and add test.

**Comment by janat08** [comment]
I'm on [/addcoin] and there're no error mentioned.

**Comment by gazhayes** [comment]
The error was in the console. The GUI had no response and just didn't do anything.

**Comment by janat08** [comment]
can't reproduce.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
Can you reporoduce?

**Comment by janat08** [comment]
Yes, it not even working on my branch that I copied over by hand.

**Comment by janat08** [comment]
@blockrazorbot label "done"
