### ISSUE TITLE
Problem: [/currency/x & /addcoin] cannot add exchanges to currencies 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1236]
Problem: it's not possible for users to add exchanges to coins on the currency detail page.

Solution: Allow users to add an exchange to a currency from the _existing list of exchanges_ or _add a new exchange_. The simplest solution here is probably a dropdown or typeahead with a "add new" button next to it.

Any solution should also denormalize the data into the currencies collection so that currencies on the home route can be filtered by "is currently listed on an exchange".

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
Opened again as the original issue still exists.

**Comment by gazhayes** [comment]
You're going to add it to the add currency page right?

**Comment by janat08** [comment]
y

**Comment by janat08** [comment]
@blockrazorbot label "done"
