### ISSUE TITLE
problem: compare currencies UX is very bad on small screens

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1244]
Problem: the compare currencies page is one of the pages that needs to work on mobile because casual and first time users are likely to use it. It is currently pretty bad on mobile / small screen.

**Comment by samuelralak** [comment]
IMHO I think a partial redesign of this page - the table section especially - is required to make this page better than it already is now and perhaps make it more intuitive. 

I would also propose having the currencies displayed vertically and comparison data horizontal instead. Currently its abit confusing when adding a currency to compare - you don't see the data unless you scroll to right.

**Comment by gazhayes** [comment]
Yeah I don't disagree with any of that. Do you want to do it?

**Comment by gazhayes** [comment]
Actually vertically might cause problems because there's a fair bit of data to display, it would end up being a very wide page, or are you envisioning something that you think will deal with that?

**Comment by MadanBhandari** [comment]
Anyone working on this ? I would like to start from this.

**Comment by samuelralak** [comment]
@MadanBhandari nop. you can go ahead and claim it

**Comment by MadanBhandari** [comment]
@blockrazorbot claim
@gazhayes It's great to be back :) I love working with you guys.

Nice UI job so far :D

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
Fixed in #1736.

@blockrazorbot label "done"

**Comment by geekyd** [comment]
@blockrazorbot remove "in progress"
