### ISSUE TITLE
Problem: typeahead add action if empty [/currency/:x] button is ugly/decoupled

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1246]
Problem: the button that activates on [/currency/:x] is ugly and decoupled from the input. I didn't put it in typeahead element because it's unstyled.

Solution: style the button, and if you like don't bother with logic making a new issue for that.

**Comment by chamidu-supeshala** [comment]
fixed #1254
@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by janat08** [comment]
I'll keep the logic/button decoupled then
