### ISSUE TITLE
Problem: typeahead can't handle external changes well [/currency/:x]

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1248]
Problem: in [/currency/:x] is you add exchange twice, the second time it won't clear the input. The props that are passed to typeahead don't directly indicate that a change has occured with it happening roundabout manner where method is run updating ``currentData()`` it then being bount to ``reactiveVar`` and then getting passed to typeahead props. It might be related to #1247, or caused by.

Solution: The part that governs this behavour is in onRendered hook and uses this.search('') to determine if it should reinitialize typeahead clearing input if typeahead is focused.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
@janat08, I've tested this one, and, as far as I can tell, the input field is not reset even if you add an exchange only once.
What's the desired behavior here? Am I missing something? :)

**Comment by janat08** [comment]
If you select an item it shouldn't populate the field, meanwhile removing the selection. Once you add another exchange input will not clear.

**Comment by anbud** [comment]
Done in #1298.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
