### ISSUE TITLE
Problem: [/addcoin] responsively overflows behind sidebar

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1249]
Problem: [/addcoin] forms will hide behind sidebar at large resolution.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed in #1258
@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"
