### ISSUE TITLE
Problem: no overall user rank

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1257]
Problem: users progress towards 'moderatorship' as they complete bounties, make comments, etc. This was implemented in #1253. However, this progress is not clear to the users.

Solution: display a user rank on the user profile page using the same metrics as are used in #1253.

ping @anbud

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
blockrazorbot was down for a while (DDoS on the node our dev server is on)

**Comment by anbud** [comment]
Done in #1260.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
