### ISSUE TITLE
Problem: [/addCoin] validation errors not shown in frontend

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1263]
Problem: SimpleSchema validation fail errors not showing in front end (they are shown in console, though). So user might not understand why he/she cannot add a new coin

![screenshot from 2018-04-22 13-36-13](https://user-images.githubusercontent.com/27463355/39092780-9fdaddae-4632-11e8-80fb-cc7b9584c9a8.png)

Solution: display validation error messages in front-end

**Comment by gazhayes** [comment]
These should be displayed inline with JQuery instead of using popup/sAlert type notifications.

**Comment by AshHimself** [comment]
To be add to @gazhayes,  it should use bootstrap inline validation not custom jquery validation code.

**Comment by AshHimself** [comment]
@blockrazorbot claim 

Let me take a look at this first as I believe this is going to be a little challenge as some fields which are turned from the server as having errors don't align one to one with the ids in the DOM. Mapping table or some rework may be needed.

**Comment by gazhayes** [comment]
Also just think through which items should be required in what situation (based on the checkboxes at the top and thinking through cryptocurrencies in general). Ping me for any specifics.

**Comment by AshHimself** [comment]
@gazhayes - give this a test, I did a lot of testing to make sure the inputs were validated when they should be whilst having a good UX.

Ideas - right now I believe its just validating type and if its required so the error message isn't really offering the best UX. Also, validation get performed again on focus would be good as well. 

@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done
