### ISSUE TITLE
Problem: [/addCoin] heavy with needless validations

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1264]
Problem: validations like `curency_log_file=> required` might not needed. (as if user adding a coin which is not yet released, there may be no exact logo yet)

other thing is user cannot add exchanges to his/her new coin, because in order to pass current validation checks, it is not enough to provide exchange name, it also asks for slug and _id.

![screenshot from 2018-04-22 13-48-10](https://user-images.githubusercontent.com/27463355/39092876-038dcc8e-4634-11e8-855e-95948a4da2c7.png)

Solution: i think these are automated validations from SimpleSchema. we need to adjust things from backend

**Comment by gazhayes** [comment]
The image requirement can be disabled when the coin launch date is in the future.

> other thing is user cannot add exchanges to his/her new coin

This was raised in #1236, looks like it hasn't actually been done.

**Comment by chamidu-supeshala** [comment]
Sorry i forgot that when i opening this ticket, i will close this down
