### ISSUE TITLE
Problem: migration to flow-router-extra with dynamic imports support but no fast-render

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1268]
Problem: https://github.com/VeliovGroup/flow-router, has support for dynamic imports, but doesn't cooperate with fast-render, and they appear to suggest the use of complete blaze SSR (which I saw before, but it wasn't obvious to me how to use in route), which helps with improving the speed with [/].

Solution: Look for fast-render or look for complete SSR.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
closed in favour of #1269 which is this same issue but logged as a C4 problem.
