### ISSUE TITLE
Problem: red flag text doesn't display

### ISSUE THREAD

**Issue by sjmackenzie** [Blockrazor/blockrazor#1271]
Problem: inserting a new red flag doesn't display the data when on that currency's page

Solution: make it display the recently inserted data.

**Comment by AshHimself** [comment]
@blockrazorbot claim

Working in file on another ticket.

**Comment by chamidu-supeshala** [comment]
@AshHimself i have just checked this (as i worked recently on this), and it's a typo, please make `{{featureName}}` in line 20 of redflag.html to `{{name}}`. This will make redflags visible again. I'm Sorry i think this may be broken by me when working on UI redesigning.  

![screenshot from 2018-04-23 20-08-27](https://user-images.githubusercontent.com/27463355/39133768-a45fb830-4732-11e8-9696-d2725d4157f6.png)

**Comment by gazhayes** [comment]
@AshHimself you still on this?

**Comment by AshHimself** [comment]
Yes I am, was just waiting for you to merge my last change so I didn't have
to deal with conflicts.

**Comment by AshHimself** [comment]
I'm on BlackRazor today so inbound shortly.

**Comment by AshHimself** [comment]
Fixed in #1299

@blockrazorbot label 'done'
