### ISSUE TITLE
problem: its not obvious that red flags/features are scrollable

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1273]
Problem: its not obvious that red flags/features are scrollable

Solution: enforce a cross browser technique to show a scroll bar and offer a better UX to users.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
A simpler solution is to limit the total number of items on display since there's already a load more button and login.

**Comment by AshHimself** [comment]
I think the problem here is that the cards are fixed so the load more won't enlarge the cards, same when you show messages to a feature. So we either needs to remove fixed cards or force scroll bars (I did this for another app like last week so its a 10min job).

**Comment by gazhayes** [comment]
Ah ok, fair enough. In that case the best thing to do is still limit the initial results to whatever can fit without scrolling (in addition to the load more button), then scrolling only needs to happen after the user has made that action.

**Comment by AshHimself** [comment]
I lie this is not a 10min job.. i'll go with option one for now and keep this at the back of my mind :/

**Comment by gazhayes** [comment]
Scrolling *works* everywhere right? Just that scroll bars are not visible?

**Comment by AshHimself** [comment]
Correct, and only a OSX issue I believe :)

**Comment by chamidu-supeshala** [comment]
Actually scrollbars visible properly in ubuntu, windows and android. :smile:  may be only issue with mac and ios

**Comment by gazhayes** [comment]
I just tested on OSX and they are visible when actually scrolling but not normally. Anyway I think the load more thing being visible will make it clear enough.

**Comment by AshHimself** [comment]
fixed in #1287

@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by AshHimself** [comment]
Is LOAD MORE broken just for me? or everyone, this isn't something I touched so must of been broken before.

**Comment by gazhayes** [comment]
It was working for me earlier today.
