### ISSUE TITLE
Problem: no page listing all the exchanges

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1285]
Problem: there's no page listing all the exchanges

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes just want the exchange name in a table?

**Comment by gazhayes** [comment]
Yeah table will be fine.

**Comment by gazhayes** [comment]
Just dirt simple for now. I'll be listing new problems once this one is closed, need something like a currency detail page for exchanges and some data from there will probably want to be in the table.

**Comment by AshHimself** [comment]
Do we want to list the currencies against each exchange? Could get messy
displaying that :/

**Comment by gazhayes** [comment]
Nah don't worry about that.

**Comment by AshHimself** [comment]
Ok it looks a wee bit boring at the moment with one column and doesn't offer value besides looking at the exchanges we have. Open for ideas on how to expand it if it needs to? 

@blockrazorbot label "done"
