### ISSUE TITLE
Problem: compare with other currencies does not populate currency comparison page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1288]
Problem: [/currencydetail/x] compare with other currencies does not populate currency comparison page. When clicking on the 'compare with other currencies' button it directs users to the currency comparison route but does not populate the page with the currency they just came from.

**Comment by samuelralak** [comment]
A solution for this would be to add a helper function that returns the currencySymbol from `thiscurrency` object or simply call `thiscurrency.currencySymbol` on
```html
<a class="btn btn-outline-primary pull-right m-3 no-margin" href="/compareCurrencies/{{currencySymbol}}">Compare with other currencies</a>
```

**Comment by samuelralak** [comment]
this should be a quick one. @blockrazorbot claim
