### ISSUE TITLE
problem: incorrect bootwatch font being used

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1293]
Problem: incorrect bootwatch font being used and should be using the LUX font.

Solution: Investigate what font is being used, remove it and reference the LUX font globally.

**Comment by gdevdeiv** [comment]
@AshHimself, seems right to me, the font file is being loaded correctly and this is the current value used on the site:

`font-family: "Nunito Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`

**Comment by AshHimself** [comment]
Must of fixed itself in a previous issue as this is all good now.
