### ISSUE TITLE
problem: [currencyAuction] TypeError: Cannot set property 'highlight' of undefined

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1295]
Problem: TypeError: Cannot set property 'highlight' of undefined is given on load in console.

**Comment by anbud** [comment]
I believe I've seen this error on some other pages as well. Possibly, it's related to one of the global components.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1298.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
