### ISSUE TITLE
problem: [/currency/X] distribution graph is deformed on small screens

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1302]
Problem: the distribution graph becomes deformed when displayed on small screens.

**Comment by gazhayes** [comment]
![screenshot_2018-04-25-19-14-07-657_org mozilla firefox](https://user-images.githubusercontent.com/8143945/39242610-2ec87526-48bd-11e8-8edc-88f5b54d682a.png)

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Should be fixed in #1307.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
