### ISSUE TITLE
Problem: swipe gestures on mobile are annoying

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1305]
Problem: the swipe gestures on mobile end up opening and closing the menu when you want to horizontal scroll etc. A number of people have told me this is annoying and I concur.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1309

@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done
