### ISSUE TITLE
Problem: users are not notified when someone replies to their comment

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1308]
Problem: [/addcoin, /problems] users are not notified when someone replies to something they have written (comment/red flag/summary/etc).

Solution: notify uses of reply and link back to the original problem or currency.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1312.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
