### ISSUE TITLE
Problem: users cannot deposit Monero into their wallet

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1313]
Problem: users cannot deposit Monero into their wallet.

Solution:

Use the `get_bulk_payments` API call offered by `monero-wallet-rpc`.

There's an existing wrapper that might help here, but it could also be just as easy to write it from scratch since it's pretty trivial to poll for payments: https://github.com/PsychicCat/monero-nodejs 

The Monero testnet can be used for now, and we can convert over to mainnet later.

### Running monero locally
I will get everything running on the production server and take care of security, but for local development this is how you get Monero up and running so you can use the wallet API:

Fetch the binaries:
https://github.com/monero-project/monero/releases

Create a new wallet file:
`monero-wallet-cli --testnet`
Follow the steps to create a new wallet. Set a password. It will complain about not being able to connect to the daemon but it doesn't matter, it will create a wallet file anyway. Save the address somewhere. You can now `exit`.

Start the wallet RPC server:
 ```
monero-wallet-rpc --testnet --daemon-address hk0.blockrazor.org:28081 --rpc-bind-port 28088 --password "xxxxx"(whatever you set above) --wallet-file xxxxx (from above) --rpc-login qwerty:12345
```
This will connect to my testnet server so that you don't have to download the blockchain

You can test it with:
```
curl -X POST http://127.0.0.1:28088/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getheight"}' -H 'Content-Type: application/json' -u qwerty:12345 --digest
```
That should give you the current block height, right now it's 1089242.

The rest of the API details are here: getmonero.org/resources/developer-guides/wallet-rpc.html

Then go to https://dis.gratis and paste in your address from above to send yourself some testnet coins. Within about 5-10 minutes you should see them in your wallet.

### Solution requirements
Monero is a little bit different to Bitcoin because it's not really necessary to use a new address each time. Instead of generating a new address for users to send payments to, we generate a new 64 character hex string to use as a payment ID. This *unique* payment ID is how we differentiate between different users' deposits.

In order to provide some level of redundancy without any extra overhead it might be a good idea to take a concatenation of the MD5 hash of the user's _id and slug, since MD5 is 128 bits that should always be 32 hex chars so the concatenation will be 64 which is the right length. This is not a hard requirement but might make it easier to recover users' funds in case of a serious screwup.

It's probably best to use a Meteor cron job to poll for incoming payments and credit users wallets. I think what will ultimately happen is cryptocurrency nodes will all be run on a server behind a firewall and the only connection to everything else will be through syncing the relevant mongo collections for deposits and withdrawals (probably through an ssh tunnel or something).  

The overall process is as follows:

1. Generate a payment ID (a random 64 character hexadecimal string)
2. Communicate the payment ID and Monero address to user
User then sends coins to us.

3. Get the current block height from the daemon, only proceed if it has increased since our last scan
4. Call the get_bulk_payments RPC API call with our last scanned height and the list of all payment IDs in our system
5. Store the current block height as our last scanned height
6. Remove duplicates based on transaction hashes we have already received and processed

a transaction will typically have multiple outputs that add up to the total required for the payment, the amounts should be grouped by the tx_hash or the payment_id and added together. Additionally, as multiple outputs can have the same amount, it is imperative not to try and filter out the returned data from a single get_bulk_payments call.

ping @anbud

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
I updated the OP with more details.

**Comment by gazhayes** [comment]
> This one seems quite interesting. :)

Yeah, I'd say this and the next few related ones for Bitcoin and Krazor will be some of the most interesting things to work on.

**Comment by anbud** [comment]
@gazhayes, thanks for the update. I'll try setting it up now, and I'll get back to you if something doesn't work correctly. :)

**Comment by AshHimself** [comment]
Ooo that does sound fun 😃

**Comment by gazhayes** [comment]
@anbud I've mined some testnet coins in case you need more and the faucet doesn't have enough. You can --restore-deterministic-wallet with these seed words:
```
zebra itinerary fictional video number velvet tyrant pioneer mirror ahead gawk airport adept tsunami sprig gypsy oars theatrics flippant inorganic baby noted pact pirate video
```

**Comment by anbud** [comment]
The basic functionality is done in #1327. I've left the localhost RPC server as a placeholder for connections. I couldn't get it to work with HTTP digest auth, but I believe that's due to the local RPC server acting up and it should work when the production server is up. It currently recognizes deposits and credits correct users based on the payment id. I've generated the payment id using user's _id and slug, it's probably the best approach,

I do have one question though, how do we check for duplicates in step 6? You've said that there'll be multiple transactions with the same txId and different (possibly same) outputs that add up to the total amount, so I've commented out the filtering part. But, what parameters are uniquely identifying a transaction, so we can know it's a duplicate when we see it again?

I'm not marking it as done yet, as it still needs to be connected to a production RPC server.

**Comment by anbud** [comment]
Yap, it works correctly after disabling auth. 

Ok, I already wrote the code that filters it, but I've commented it out, so I just need to remove the comments. I'll send a PR later today, when I return from a marathon.

**Comment by anbud** [comment]
Uncommented the code in #1336.

**Comment by gazhayes** [comment]
Does this handle duplicate txid (tx hash) in the *same* get_bulk_payments response (these are valid)?

**Comment by anbud** [comment]
Sorry for the confusion, it'll handle it in the next PR. :)
