### ISSUE TITLE
Problem: [currency/:x] typeahead create exchange, and then add it doesn't pass correct created item id

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1315]
Problem: Creating exchange and then trying to add it will throw an error from ``appendExchange`` method for exchange or currency not existing. I believe the issue being that minimongo on simulation of the method makes up random id, after which it then corrects the actual ID used on the server, with the bad id being passed into typeahead.

Possible Solution: revert to creating and adding an item

Possible Solution: use exchange name as param for method, pretending there isn't an issue

Possible Solution: observe created item and on change/update call any add item events for the item

@blockrazorbot label "unmet dependency" claim #1314

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
@blockrazorbot remove "unmet dependency"

**Comment by janat08** [comment]
I take it from previous comments that behaviour should be reverted.

**Comment by gazhayes** [comment]
which behaviour?

**Comment by gazhayes** [comment]
But what do you mean by reverting it? It hasn't been fixed yet. You are fixing that issue right?

Also it looks like new exchanges can't be added at all now, I'm not sure which pull request broke it though, either yours or @chamidu-supeshala when he did the button layout issue.

**Comment by janat08** [comment]
Mine simple created the exchange. It was then changed to waiting for the response to add it. I changed it back to creating the exchange and showing it to add it which didn't work.

**Comment by janat08** [comment]
@blockrazorbot label "done"
