### ISSUE TITLE
problem: clicking add exchange in [/addcoin] trigger form submit

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1317]
Problem: I belief the issue is that any button in form triggers submit event.

Solution: the submit button should be input of type submit.

**Comment by janat08** [comment]
Solution doesn't work, i take it it's not important anyway, with the form being change.

**Comment by gazhayes** [comment]
Yeah you can redo the typeahead stuff after the new form is implemented anyway.
