### ISSUE TITLE
Problem: typeahead doesn't react to mongo cursor change

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1319]
Problem: typeahead currently will not react to cursor change, instead only reacting to reactiveVars, which is important only if you're making custom create button and don't wish to perform add action straight after. 

There're also a bunch of other ramifications that include typeahead value being nullified if reactiveVars change while user types, created typeahead menu items outside typeahead templae not being reflected in the typeahead until input change.

Solution: move reactions to events away from this.search() autorun and move them to events. pass current typeahead value into this.search(). While making sure that there's a projection that will cause updates only on displayed fields.

**Comment by gazhayes** [comment]
Is this the cause of #1320?

**Comment by janat08** [comment]
@blockrazorbot claim
