### ISSUE TITLE
Problem: smart contracts cannot be added to Blockrazor

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1324]
Problem: Currently, the add currency wizard doesn't cater to smart contract tokens, only discrete blockchains. It's important to be able to add tokens because many serious projects are now smartcontract based tokens that exist on another blockchain (such as the Ethereum chain).

Solution:
On the first page of the wizard, ask the user if the coin they are adding is a smart contract, e.g. an ERC20 contract.

If so, the following action should be taken:
1. Add another 'launchTag' in the collection if this currency is a smart contract ("contract" I guess?).
2. Replace "...blockchain..." with "...contract..." throughout the wizard UI, where appropriate (and make things make sense).
3. Genesis block timestamp should be 'contract launch date' instead but can be stored in the collection as the genesis timestamp.
4. If the user indicated in step 1 that this contract has already been launched, askd for a link to the contract itself (for example, here is a link to the OmiseGo contract: https://etherscan.io/token/0xd26114cd6ee289accf82350c8d8487fedb8a0c07)

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@blockrazorbot label 'done'

**Comment by AshHimself** [comment]
Fixed in #1388 
@blockrazorbot done
