### ISSUE TITLE
Problem: [/] red flags on currency cards are not obvious

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1325]
Problem: the red flags listed on currency cards on the home route are not obvious.

Solution: maybe remove the 'top red flag' text to make the UI a bit nicer, and put the red flag inside a bootstrap `danger` alert (https://getbootstrap.com/docs/4.1/components/alerts/). 

Another solution could be to use a font-awesome exclamation mark or something.

**Comment by chamidu-supeshala** [comment]
fixed in #1328
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
