### ISSUE TITLE
Problem: [/addCoin] added exchanges appearing in a table, which is not so good

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1330]
Problem: When adding a new currency, if we add some exchanges to the currency, those exchanges will appear in a table. A table inside a form not looking good.

Solution: replace the table with a list like this

![screenshot from 2018-04-28 10-37-17](https://user-images.githubusercontent.com/27463355/39392428-4a41bc82-4ad3-11e8-992a-5d730b8d8dba.png)

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
FYI we are using a new wizard instead of the form now.

**Comment by chamidu-supeshala** [comment]
fixed in #1342
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
