### ISSUE TITLE
Problem: cannot specify instances for syncedcron jobs to run on

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1334]
Problem: syncedcron tries to run on all instances and logs the time it runs so that other instances don't run the same job. This is a problem for Blockrazor because some syncedcron jobs should only run on specific instances. For example, processing cryptocurrency payments should only happen on the node where the cryptocurrency wallets are, it should not try and run these cron jobs on other nodes.

solution: possibly use an environment variable to specify the node type, and use an if statement or whatever to control whether that job actually runs or not based on the env variable.

ping @anbud

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
@gazhayes, an example is in #1338.

Do you possibly already have a list of which cronjobs will run where, or will we implement that later?

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by gazhayes** [comment]
> Do you possibly already have a list of which cronjobs will run where, or will we implement that later?

No, will work that out later, the only one I'm certain of right now is receiving and sending coins.
