### ISSUE TITLE
problem: UserData collection is only exported on the server

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#134]
Problem: UserData collection is only exported on the server

Solution: Create a publication on the lib folder to subscribe to the logged in users UserData record.

**Comment by gazhayes** [comment]
Can you specify what the actual problem is? I intentionally left UserData as server side only.

**Comment by AshHimself** [comment]
@gazhayes - Apologies for not clarifying. I was coding a helper on the client side which could be used to hide/display elements based on if you are a moderator or not. We could do this via a method but it would mean calling the method a lot. Open for suggestions if others have a more elegant solution?

**Comment by gazhayes** [comment]
Ok that's fine. Just make sure you use methods for verifying their account levels for any actual actions of course.
