### ISSUE TITLE
Problem: users not told about the importance of adding bounty to bug reports

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1343]
Problem: when users add a bug report or a feature request (which, by the way, are the exact same thing under the C4), they are able to proceed without contributing to the bounty to solve it. This is a problem because new users might not understand the importance of taking some responsibility and donating some of their Krazor to solving issues. Ideally there will be no need for any centralized decision making if users take control of this process.

Possible solution: a modal explaining this to users if they do not add any KZR to their bug report or feature request. This probably should not be shown if the user doesn't actually have any coins in their wallet.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
done in #1348
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
