### ISSUE TITLE
Problem: [/currency/x] The exchanges cannot untagged / deleted

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1344]
Problem: When editing a coin, clicking on typeahead item immediately tags that exchange to the currency. if we mistakenly click on an item, there is no way to undo.

Solution: better to add a remove option (in the table view) which un-tags that exchange from the coin.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot unclaim
@gazhayes first i would like to know whether this a necessary feature.

**Comment by gazhayes** [comment]
Yeah it's worth solving - what's really happening is users can't make mistakes the way it currently is (and users always make mistakes).

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed in #1413
@blockrazorbot remove "in progress"
@blockrazorbot label "done"
