### ISSUE TITLE
problem: not obvious how to close side menu

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1345]
Problem: it's not always clear to users that the side menu can be closed.

Solution: add a font awesome carat half way down the side menu itself, near the right hand edge (and definitely not in the nav bar, this was attempted before with poor results).

**Comment by gdevdeiv** [comment]
@blockrazorbot claim

**Comment by gdevdeiv** [comment]
Proposed pull request #1349

**Comment by gdevdeiv** [comment]
@gazhayes this issue can be closed.

**Comment by gazhayes** [comment]
FYI you can:
@blockrazorbot label "done"
