### ISSUE TITLE
Problem: No data for rows & pages shown on /exchanges

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1351]
Problem: No data for rows & pages shown on /exchanges although the user can change the values but it remains hidden.

![b2072dc7-1fe5-4237-ad8e-aeaf75674614 3](https://user-images.githubusercontent.com/12807846/39407580-9883e4ac-4be5-11e8-80a2-c6a6d984d946.png)

**Comment by gazhayes** [comment]
Don't worry about this one, the page itself is going to be different very soon anyway.
