### ISSUE TITLE
Problem: [/] broke after being dynamically imported

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1352]
Problem: [/] breaks after being dynamically imported.

**Comment by gdevdeiv** [comment]
@blockrazorbot claim.

**Comment by gdevdeiv** [comment]
@blockrazorbot label "done"

**Comment by gdevdeiv** [comment]
@blockrazorbot remove "in progress"

**Comment by gdevdeiv** [comment]
@janat08 They are being `import`ed when needed, in each route. Is that causing any issues?

**Comment by dr-dimitru** [comment]
@gdevdeiv
 1. Is it went broken after moving dynamic import(s) to `action` hook? 
 2. Why `waitOn` hooks are removed?

**Comment by gdevdeiv** [comment]
@dr-dimitru, it broke when the imports where moved to the `waitOn` hook. Yesterday I tinkered with that for a bit, and realised it worked just fine when using async/await in the `action` hook (except for the home page, as it was requiring some CSS that belonged to another view, so I additionally imported that file (currency.scss) to the home view).

**Comment by dr-dimitru** [comment]
@gdevdeiv 

> it broke

 1. Could you tell me more? It's isn't imported at all, or imported in a wrong order?
 2. Have you tried to use `whileWaiting` hook?

**Comment by janat08** [comment]
it broke only the home route css in isolation.

**Comment by janat08** [comment]
navigation did break, where I mistakenly assumed it was about the page to which home page links in the list items, which is no longer a problem.
