### ISSUE TITLE
Problem: bootstrap editable images not dynamically imported.

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1353]
Problem: bootstrap editable images belong in ui/components/compatibility folder where index dynamically imports them in bundle. I don't know how to handle them, but heres a tip: https://atmospherejs.com/nathantreid/static-assets.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1434.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
