### ISSUE TITLE
Problem: sweetaleart not dynamically imported.

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1354]
Problem: sweetaleart is part of bundle, and should be dynamically imported.

Solution: make it global only after it has been imported with ``import('sweetaleart).then((alerts)=>window.sAlert=alerts)``. Run ``meteor --extra-packages bundle-visualizer --production`` to check.

**Comment by anbud** [comment]
Done in #1433.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
