### ISSUE TITLE
Problem: xmlbuilder isn't dynamically imported

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1355]
Problem: xmlbuilder isn't dynamically imported, and could be imported where it's needed (on one of the routes) which will make it dynamically imported.

Solution: syntax for dynamic imports, and making global. import('sweetaleart).then((alerts)=>window.sAlert=alerts). Run ``meteor --extra-packages bundle-visualizer --production`` to check.

**Comment by anbud** [comment]
@janat08, I can't seem to find where `xmlbuilder` is imported, and I can't see it with bundle-visualizer.
Am I missing something? :)

**Comment by janat08** [comment]
I guess that it went away once all of the routes were moved to dynamic imports, or something.
