### ISSUE TITLE
Problem: simple schema is in initial bundle

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1356]
Problem: simple schema makes it into client bundle through main.js when it imports collections.

Solution: Create stub for global helpers that use them, dynamically import the collections and then overwrite the stub helpers.  Run ``meteor --extra-packages bundle-visualizer --production`` to check.
``` js
import('collections').then((collections)=>{
  globalHelpers(... //using collections
})

**Comment by anbud** [comment]
Done in #1400.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by janat08** [comment]
compatibility itself is dynamically imported.
