### ISSUE TITLE
Problem: no lighthouse audit (chrome>devtools>audits)

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1359]
Problem: Lighthouse audit is concerned with how quickly a page loads, as well as PWA tech. Currently its unavailable since dynamic imports in breaking home page also break the audit. @blockrazorbot label "unmet dependency" #1352.

Solution: Will look at scores for [/] as per #1209.

**Comment by gdevdeiv** [comment]
Closed #1352, I guess this Issue can be taken now, @janat08, do you want it? ;)

**Comment by janat08** [comment]
fine do it

**Comment by gdevdeiv** [comment]
This ticket requires some time for investigation and testing, so I'll claim it for now, although any external input is appreciated ;)

@blockrazorbot claim

**Comment by janat08** [comment]
Technically the issue is about reporting issues discovered.

**Comment by gdevdeiv** [comment]
As I'm pretty new to Meteor, I must ask you all about this before doing anything. After some tinkering and a lot of reading I have lowered the bundle size from ~600KB to 385KB, and the only change I've made is the following:

imports/startup/client/index.js, line 4
~~`import '../both/index.js'`~~
`import '../both/routes.js'`

BUT, I don't really know if that is actually correct. My judgement was the following: the only thing `both/index.js` seems to do is to load all server-side API modules, SimpleSchema AND THEN the routes file. What if the client skipped all API and SimpleSchema and loaded the routes directly?

Maybe that breaks something or has been proposed before, but again, I'm practically new to this piece of tech, so any additional input is highly appreciated.

**Comment by gdevdeiv** [comment]
Nonetheless, I must point out that the main issue I see regarding load times is whatever is serving the app, and by that I mean that something is not right in the web server itself.. I mean, the full JS file is barely 600KB, and it's slow.. Just doesn't make sense, a review of the web server config files or web server technology/serving strategy is recommended from my humble opinion.

**Comment by janat08** [comment]
theres --production flag (meteor --production) that does the config of files or serving strategy. It does that intentionally in regards to both/index.js for optimistic ui.

**Comment by janat08** [comment]
Anyway the dynamic import for every route/home page isn't necesserily good, except that for no good reason it turned out to be unreallistically faster compared to it being in initial bundle. Otherwise, blaze hails from 2009-2013.

**Comment by gazhayes** [comment]
> a review of the web server config files or web server technology/serving strategy is recommended from my humble opinion.

Absolutely. There's a lot of time spent on DNS lookup for some reason, as well as redirecting from http to https, stuff like that. I'm looking into that.

**Comment by gdevdeiv** [comment]
Although it's showing poor results, Lighthouse auditing is working fine now, we probably should open Issues to improve the score soon.

@blockrazorbot remove "in progress"
@blockrazorbot label "done"

**Comment by janat08** [comment]
lux.min.js delays by 1.3 ms, its advised to separate essential CSS.
chart.js -> animations needs 900ms to evaluate
fonts shouldn't be invisible by 1300ms
fonts too small 76%, more than 75% of text should be over 16px for mobile (in SEO category)

for interpretation of screenshots
lux.min.js = bf8d...
meteor bundle/app = 743...

![screenshot 34](https://user-images.githubusercontent.com/11337345/39475615-bbfe3d74-4d7a-11e8-9abc-a308561ee424.png)
![screenshot 35](https://user-images.githubusercontent.com/11337345/39475617-bd5160d4-4d7a-11e8-8e17-55ab50d3db12.png)
![screenshot 36](https://user-images.githubusercontent.com/11337345/39475619-beb0373e-4d7a-11e8-84f0-dc2339bf6b29.png)
![screenshot 37](https://user-images.githubusercontent.com/11337345/39475620-c09d122e-4d7a-11e8-94f1-6e113a14f209.png)

**Comment by janat08** [comment]
Feel free to open issues.

**Comment by gazhayes** [comment]
Will close this now as Lighthouse is working. Please add individual issues for any low-hanging fruit, I added #1395 as an example.

**Comment by janat08** [comment]
added rest of the issues
