### ISSUE TITLE
Problem: can't navigate to and from [/currency/:x] using back and forward (using history)

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1368]
Problem: can't navigate to and from [/currency/:x] using back and forward (using history).

**Comment by jigartankhupp** [comment]
@janat08 works fine for me with the latest code in master. Can you tell me browser / os stack you are facing this trouble ?

**Comment by janat08** [comment]
It's just gone, I might not have checked master with dynamic imports fixed.
