### ISSUE TITLE
Problem: [/addCoin] cant navigate to addCoin page

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1370]
Problem: cannot navigate to addcoin page. An error shown in console

Solution: check and solve it

**Comment by AshHimself** [comment]
@chamidu-supeshala i'm actually in this file now merging the new add-coin wizard code in. 
Do you know the answer as i'll fix in my current PR.

**Comment by chamidu-supeshala** [comment]
@AshHimself i think the issue is in routes.js file. I checked and just need to comment the lines 431 and 460. then uncomment the line 426 and 455

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1371

**Comment by AshHimself** [comment]
@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by AshHimself** [comment]
Should we wait until its merged and tested before closing?

**Comment by AshHimself** [comment]
Fixed in #1375

**Comment by chamidu-supeshala** [comment]
@AshHimself Do i need to reopen it? Actually i created this because the problems are two separate problems, as this ticket refers to a routing failure due to a dynamic import (which occurred today), while other problem related to migrating newWizard to addCoin. (occurred past week). I didn't aware that you are working on migration process when i raising this new problem. Sorry for the inconvenience.
