### ISSUE TITLE
Problem: mime-db ('mime-types') bundled into the client

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1372]
Problem: mime-types is being used in methods for uploading images and thus bundled for method simulation.

Solution: We use very little of functionality of mime-db I belief so we could just reproduce it, hack away the package to make a script file with what's needed, or just move the methods to server.

**Comment by anbud** [comment]
I agree, this thing is roughly 200kb, and we use a small subset of its functionality.
I'll create a smaller script with things we need on the client.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1378.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
