### ISSUE TITLE
Problem: autocomplete interferes with typeahead on [/currencyAuction]

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1380]
Problem: enter a value (i presume with enter), type it out again.
![screenshot 33](https://user-images.githubusercontent.com/11337345/39440487-e0b2c954-4ccc-11e8-8a2e-e20e2192be0b.png)

**Comment by gdevdeiv** [comment]
@blockrazorbot claim.

**Comment by gdevdeiv** [comment]
Two possible ways: either we disable the browser built-in autocomplete, or we try to handle it and insert it into the field.

**Comment by janat08** [comment]
I used to think that autocomplete is something developer enables with some attribute.

**Comment by gdevdeiv** [comment]
Not really, comes enabled by default, unless you disable it :/

**Comment by janat08** [comment]
Oh well, disable it for in typeahead.html

**Comment by gdevdeiv** [comment]
Closed in #1383.

**Comment by gdevdeiv** [comment]
@blockrazorbot remove "in progress"
@blockrazorbot label "done"
