### ISSUE TITLE
Problem: no Krazor price chart

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1384]
Problem: there's no current Krazor price, and no price chart.

Solution: use auction results to generate a chart.js chart showing price history in USD. For auctions denominated in other currencies this will require fetching the current USD prices from the currencies collection when the auction ends.

**Comment by jigartankhupp** [comment]
@gazhayes It's the same issue for Cloakcoin as well.
For some clarity - question : You are having this issue on compare currencies screen - correct ?
I see that prices don't show up for both the above mentioned currencies.
Also on currency detail screen there isn't any distribution added. Confirm please.

**Comment by jigartankhupp** [comment]
Just checked this. The currency name in collection for KZR does not match the currency Name in response given by coinmarketcap api. They don't have it in their system, just checked their site as well.
@gazhayes What other market place api would you like me to use here in place of coinmarketcap ?

**Comment by jigartankhupp** [comment]
@blockrazorbot  claim

**Comment by gazhayes** [comment]
@jigartankhupp I noticed you took two issues at once. Unless issues are directly related, you should not take more than one issue at a time as this is a _blocking process_ and slows down the project because other people can't work on the issues you have 'reserved'.

**Comment by gazhayes** [comment]
@jigartankhupp Krazor is a different situation. If you notice in the issue, I mention _"use auction results..."_

That's because there is no API for Krazor, the price for Krazor is determined by the [auction/trading results](https://blockrazor.org/auctions) on Blockrazor.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1412. Please note that the solution is not entirely backward compatible and may show inconsistent data for auctions completed before this.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
