### ISSUE TITLE
Problem: Hybrid security model shows PoS and PoW algorithms

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1386]
Problem: [/addcoin] when users select the hybrid security model, the algorithm list populates with proof of stake and proof of work algorithms to choose from. Proof of stake algorithms should not be populated in this list, only proof of work.

**Comment by gdevdeiv** [comment]
@blockrazorbot claim

**Comment by gdevdeiv** [comment]
Done in #1393.

@blockrazorbot remove "in progress"
@blockrazorbot label "done"
