### ISSUE TITLE
problem: smart contract URL captured but not in currencyDetail

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1389]
Problem: smart contract URL captured but not in currencyDetail

Solution: add smart contract attributes to currencyDetail view

@gazhayes - any further requirements you want to add?

**Comment by gazhayes** [comment]
No, but while you're in there can you move exchanges out of a modal and into a box on one of those tabs?

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes - i've added the URL, but I think it makes sense to state some where on the page that this is a blockchain vs smart contract?

**Comment by gazhayes** [comment]
Yes, that too.

**Comment by gazhayes** [comment]
Also, where on addcoin is the URL input meant to be? Have you checked it's working on production?

**Comment by AshHimself** [comment]
@gazhayes https://blockrazor.org/currency/omisego you can see smartContract URL on this page if you want to check it out.
