### ISSUE TITLE
Problem: modals no longer working

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#139]
Problem: There are numerous modals throughout blockrazor. For an example see the help icon when adding a new feature to a currency.

Modals work here: 
https://github.com/Blockrazor/blockrazor/commit/339a3fc01bbf9a4f46e5a22699cea11d0290e5c5

Something that happened after this has broken them. Possibly package related (someone adding a package). Something @janat08 did has definitely contributed to this but can't pinpoint exactly what. I reverted his changes almost immediately after seeing 60k+ lines of code had been changed, but it's still broken. Weird.

**Comment by AshHimself** [comment]
I'm on it.

**Comment by AshHimself** [comment]
@gazhayes - This is related to having multiple version of jquery included. We are including a version of jquery in root.html and the meteor jquery package is also included. [339a3fc](https://github.com/Blockrazor/blockrazor/commit/339a3fc01bbf9a4f46e5a22699cea11d0290e5c5) does not have jquery as a package.

We should ideally not being including scripts via <script> tags and avoid meteor packages and include jquery via ES modules. e.g. `import { $ } from 'meteor/jquery';`

**Comment by AshHimself** [comment]
#140 created... Another ticket is probably deserved to look into this further, furthermore it worth looking into why bootstrap v3 and v4 are included :/ I can't imagine that is a good idea :)
