### ISSUE TITLE
Problem: [/compareCurrencies] messes up navigation history

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1390]
Problem: Using back and forth after using typeahead will break back and forth navigation.

**Comment by anbud** [comment]
I can't seem to replicate this one on production. What's exactly happening? Tried going back and forth, but it always landed on the page it's supposed to land.

**Comment by janat08** [comment]
Land on [/], go to auctions via link, go to compare currencies, press enter, try to go back.

**Comment by janat08** [comment]
Yes that works reliably. I tried this a bunch before it popped up again.

**Comment by janat08** [comment]
#1445 related.

**Comment by janat08** [comment]
it's likely not related, since while it will still look a navigation history even with every possible routing module removed, in addCoin the external button was used and so it didn't initialize properly.

**Comment by janat08** [comment]
nx-js/framework#25
I'd try commenting out nx-framework component, and not importing the library to see if behaviour is fixed.

**Comment by janat08** [comment]
nx is the culprit.

**Comment by janat08** [comment]
@blockrazorbot label "low_priority" "unmet dependency"
