### ISSUE TITLE
Problem: typeahead constant refocusing on keyup triggers animation

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1392]
Problem: typeahead has to constantly destroy and initiate typeahead to be able to react to changes outside the template updating typeahead menu and then refocus since it creates 2 other input fields.

Solution: Block the animation on line 149 of typeahead.js ``!reset`` letting it run animation when select event fires and typeahead is refocused.

**Comment by gdevdeiv** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
In case I was unclear, all I'm asking for is:
``` js
148: if (!reset || (reset && autoFocus){
              if (!reset) apply blocking style
149        original code
               if (!reset) remove blocking style

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
@janat08 Can you please specify the steps to reproduce the situation?

**Comment by janat08** [comment]
``refocusing on keyup triggers animation``

**Comment by geekyd** [comment]
@blockrazorbot remove "in progress"
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
Blockrazorbot closed this automatically. Re-opening it so that @janat08 can validate and close.

**Comment by janat08** [comment]
I imagine @geekyd was asking where a typeahead component could be found. Anyway the issue with what you did is that now if you go to comparedCurrencies, and then delete currency from list it won't reappear on typeahead menu until you type again (so long as currency should've shown up on the list in first place). There're comments explaining almost as much. @blockrazorbot remove "done". Please revert, and report here.

**Comment by geekyd** [comment]
@janat08 I tested the scenario & the item reappears in the typeahead menu after removing it from the comparison. 
![screen shot 2018-05-04 at 12 38 00 am](https://user-images.githubusercontent.com/12807846/39597571-80b27982-4f33-11e8-8e49-ca4abedc6c3a.png)
![screen shot 2018-05-04 at 12 38 15 am](https://user-images.githubusercontent.com/12807846/39597572-810de7e0-4f33-11e8-815c-2e4cbfe33123.png)




Please correct me if I'm wrong here.

**Comment by janat08** [comment]
You typed in "e".

**Comment by geekyd** [comment]
It is there even when the user does not type. 
![screen shot 2018-05-04 at 1 11 13 am](https://user-images.githubusercontent.com/12807846/39599046-200f7b98-4f38-11e8-89c1-41b7a14b99d8.png)

**Comment by janat08** [comment]
Right, before giving up I gave my comments a try and this turns out to be right: ``this destroy/init dance is required since you can't open menu without refocusing after select``.

**Comment by janat08** [comment]
refocusing manually that is.

**Comment by janat08** [comment]
and I meant that to update menu from the collection observers if user is typing in stuff specifically which you won't be able to test on this page, so if you get the chance to make the menu open up on focus after some event and input focused it would be somewhat redundant given how it's really only used on things that don't change.

**Comment by geekyd** [comment]
@janat08 Okay I will look into it. Thanks

**Comment by janat08** [comment]
or you could just follow suggested solution of overriding animation in css.

**Comment by janat08** [comment]
revert the changes

**Comment by janat08** [comment]
@geekyd  would you finally revert your changes: #1507

**Comment by geekyd** [comment]
@janat08 Thanks for the detailed description. I'm sending a PR for reverting the changes.

**Comment by janat08** [comment]
I'm not sure if this is fixed.
