### ISSUE TITLE
Problem: smartcontract selection does not update fields correctly

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1394]
Problem: [/addcoin] selecting the smartcontract checkbox should update the fields as follows:

This blockchain has been launched (genesis block has been mined) => This contract has launched been launched

This is a planned fork of the Bitcoin blockchain => null (this option should be removed when smartcontract is selected, a smart contract cannot be a bitcoin fork)

This is/was planned as an ICO => this is currently updated when smartcontract is selected, however it should not be. It should _only_ be updated if the 'this has been launched' checkbox is changed.

This issue may or may not only be a UI issue, I haven't looked at the code so don't make any assumptions.

**Comment by AshHimself** [comment]
Fixed in #1414
@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done
