### ISSUE TITLE
Problem:  chart.js animations needs 900ms to evaluate

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1395]
Problem: it takes almost a whole second to evaluate chart.js animations.

Solution: disable chart animations on [/] and [/currency/:x]. Leave enabled on currency comparison page as the benefits outweigh the costs.

**Comment by janat08** [comment]
I suspect that evaluation encompasses animation duration, it would be good to see if changing animation time to 1 will impact the figure.

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
