### ISSUE TITLE
Problem: currency cards don't look very good

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1396]
Problem: the currency cards on [/] don't look very professional.

<img width="437" alt="screen shot 2018-05-01 at 10 50 08 pm" src="https://user-images.githubusercontent.com/8143945/39477503-0e1ecae4-4d92-11e8-9427-d891e88a5839.png">

Solution: propose mockups and see what everyone else says, or just send a pull request with UI changes.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes - first draft PR sent on this. thoughts? #1418

Honestly I think we need to remove that light blue background and decide on a graph color as part of the overall theme to show a bit of flow in the design.

**Comment by gazhayes** [comment]
> Honestly I think we need to remove that light blue background and decide on a graph color as part of the overall theme to show a bit of flow in the design.

Feel free to experiment ;)

Here are some colour schemes to think about: 
https://coolors.co/15a29c-293571-131a36-e8e9f3-cecece
https://coolors.co/495867-577399-bdd5ea-f7f7ff-fe5f55
https://coolors.co/dcdcdd-c5c3c6-46494c-4c5c68-1985a1

**Comment by AshHimself** [comment]
@gazhayes we can add a little consistency then to other elements like i've done here so its just not all GREY :)

![image](https://user-images.githubusercontent.com/148682/39564816-48ef1cee-4ee8-11e8-8413-1c7d4edfe828.png)

**Comment by gazhayes** [comment]
That's considerably nicer.

However this should be done in a new Bootswatch file, we'll slowly end up with a 'blockrazor' bootswatch theme that can also be contributed to the Bootswatch project itself.
