### ISSUE TITLE
Problem: lux.min.js + Google font blocks render

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1397]
Problem: chrome>devtools>audit says it takes 1300ms longer to render bf8d... file which beginning of which matches lux.min.js. It might be the case that time to render being so long might have to do with font import from CDN, **with lighthouse reporting that render was blocked also by 1300ms thanks to fonts being downloaded.** Light house suggested rendering some other font or something along those lines, I include another/second screenshot for exhibition (relevant into at the very top).
Note ``reduce render blocking stylesheets`` header:
![screenshot 34](https://user-images.githubusercontent.com/11337345/39478681-ef900b5e-4d84-11e8-91a0-732d7e2effae.png)
![screenshot 36](https://user-images.githubusercontent.com/11337345/39479182-3e9849d6-4d86-11e8-9eb3-13f7f7013f94.png)

Solution 1: see if there's anything that can be done to speed up fetching of the font.
Solution 2: load css asynchronously so that rendering does not wait on it.

**Comment by janat08** [comment]
the issue is that page waits for the font to load before rendering, where a browsers font could be used instead, and loading CSS that is pretty much entirely responsible for how app looks asynchronously will mean that the app will load faster but will be ugly as hell when it does.

**Comment by anbud** [comment]
Would using something like [skeleton screens](https://www.sitepoint.com/how-to-speed-up-your-ux-with-skeleton-screens/) help in this situation? e.g. loading some simple CSS outline synchronously and then asynchronously loading the rest of the CSS and fonts that are responsible for how the app actually looks. I guess it would solve the problem of the app being ugly as hell initially.

**Comment by gazhayes** [comment]
> Would using something like skeleton screens help in this situation?

Yeah I was thinking the exact same thing.

**Comment by gazhayes** [comment]
Fixing the font issue will probably be enough though, that should be tried first. It till probably get us 80% of the way there, which is good enough. CSS can probably still be synchronous since it's really not that big.

**Comment by janat08** [comment]
Im out of my depth. What the lighthouse would want you to do is in lux.min.js:
``` css
/*old: @import url("https://fonts.googleapis.com/css?family=Nunito+Sans:400,600");  new:*/
@font-face {
  font-family: "Nunito Sans";
  font-display: fallback;
  src: local('Nunito Sans'), url("https://fonts.googleapis.com/css?family=Nunito+Sans:400,600")
}
```
Except that then fortawesome meteor package begins use fortawesome that doesn't use this too. There's also ``optional`` param to font-display that may decide to not load things altogether if its too much a bother, fallback potentially not switching to the downloaded font on the first visit. @blockrazorbot unclaim

**Comment by gazhayes** [comment]
ping @anbud

**Comment by anbud** [comment]
I'll check it out.

@blockrazorbot claim
