### ISSUE TITLE
Problem: 3500ish ms boot up time for js according to lighthouse

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1399]
Problem: It takes 4 seconds to init js alone according to lighthouse (albeit with some major offenders w/o which its 2secs). Benchmarks: https://github.com/mitar/meteor-web-rendering-framework-benchmark, by blaze maintainer.

Solution: Use nx-framework which is expandable and based on proxies (5% audience usage unsupported) to render things reactively without editing any of the templates, but is as unmaintained as blaze. My offer of trying this for halfway free stands. This will also enable SSR.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
Is nx meant to be used *instead* of Blaze?

**Comment by janat08** [comment]
No we can still use and keep all of blaze html templates and helpers and hooks (the power of proxies).

**Comment by janat08** [comment]
Although I'm unsure about the compilation steps, as in detecting the html that goes with a template.

**Comment by janat08** [comment]
Ill wait for reply here https://github.com/nx-js/framework/issues/15, or a sign of life or 10-15 days. @blockrazorbot label "unmet dependency".

**Comment by gazhayes** [comment]
In the longer term, we can always fork it and maintain it ourselves, but it had better work really well to justify it.

**Comment by janat08** [comment]
- [ ] look into blaze compiler to see how this gets bundled, and yet isn't compatible with static-html package and so SSR, or look to how frameworks like vue bundle things

- [ ] register components bundling relevant html by creating component with js attached, and a parent one with HTML passed in into js component (since you have to pass in html into it separately), or/and look at migrating into web-components v1.

- [ ] triggering tracker dependencies with current computation and invalidation hooks in autorun attached to Template[x], and assignments of reactiveVars.

- [ ] attaching global helpers

- [ ] making template helpers lazy, and attaching them along with the hooks,

- [ ] parsing spacebars into nx-framework, or hacking nx parser.

**Comment by janat08** [comment]
Blaze.toHTML(Template.mainLayout). Basically gives me what I want.

**Comment by janat08** [comment]
Blaze has special template for body, which would be the root.

**Comment by janat08** [comment]
@blockrazorbot remove "unmet dependency"

**Comment by janat08** [comment]
templatetag.js and codegen contain parsers in spacebars-compiler.
templating-tools produces render function
and templating-runtime consumes it producing code for client

**Comment by janat08** [comment]
This will take more like over 20 hours. I spend 8 hours on this, and you could fairly say that I got nowhere with 100 lines of empty code written (doesn't work, isn't very meaningful), and no way to get spacebars format that I want (in form of SpacebarsCompiler.parse(html string) at least on client, forget having it built by meteor.

**Comment by janat08** [comment]
NX-framework doesn't have SSR, and I believe meteor's server-render definitely expects static-html for it's compiler instead of blaze compiler.

**Comment by janat08** [comment]
@gazhayes I offered special terms for this which went along the lines of I can be paid up to 8 hours, and if I can't deliver I don't get paid, do I close this?

**Comment by gazhayes** [comment]
What do you feel like doing?

**Comment by janat08** [comment]
Im totally interested but would like to make money.

**Comment by gazhayes** [comment]
Ok close it off. We can open this again later if it becomes 'interesting'.

**Comment by janat08** [comment]
but it is.

**Comment by gazhayes** [comment]
I'll implement Kadira to get some more data first.

**Comment by janat08** [comment]
I belief kadira is for server.

**Comment by janat08** [comment]
I'll go do a tracker conversion. If it works/helps I'm billing it.

**Comment by gazhayes** [comment]
OK. That's fine with me. But it's best to keep an eye out for higher priority things (errors etc) and do this as a lower priority.

**Comment by janat08** [comment]
1. onInvalidatedCallbacks

**Comment by janat08** [comment]
I've decided that it's easier to map oberve-utils onto tracker.api rather than other way around. 

api:

- [ ] autorun

- [ ] flush

- [ ] nonreactive

- [ ] active

- [ ] inflush

- [ ] currentComputation

- [ ] oninvalidate

- [ ] afterflush

- [ ] stop

- [ ] oninvalidate

- [ ] onstop

- [ ] stopped

- [ ] invalidated

- [ ] firstrun

- [ ] changed

- [ ] depend

- [ ] hasdependents

**Comment by janat08** [comment]
Currently the issue is that I'm not initializing ids for dependency or in nx mapEntry for new Dependency, which would then be used in Dependency.depend when things run at first.

**Comment by janat08** [comment]
There's limitation on manipulating reactiveVars in autorun. https://github.com/nx-js/observer-util/issues/25

**Comment by janat08** [comment]
@blockrazorbot label 'unmet dependency'

**Comment by janat08** [comment]
@blockrazorbot remove label "in progress"

**Comment by janat08** [comment]
@blockrazorbot unlabel "in progress"
