### ISSUE TITLE
Problem: Uncaught ReferenceError: mime is not defined

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1401]
Problem: when uploading images (I tested by uploading a new currency logo on the currency detail page), this error is reported in the console and the image doesn't upload. 

Solution: I believe this was broken here: https://github.com/Blockrazor/blockrazor/pull/1400/files
A test should probably be added too, so that this doesn't happen again.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Fixed and added tests in #1402.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by geekyd** [comment]
@gazhayes We can close this issue.
