### ISSUE TITLE
Problem: No client-side validation on add-feature form

### ISSUE THREAD

**Issue by jigartankhupp** [Blockrazor/blockrazor#1404]
Problem: Form validation are bulkier on server side.

Solution: So implementing the client side validation as per meteor schema so it won't let data pass as long as it satisfies the criteria for add feature form inside currency detail screen.

This is one of the many issues that will be raised with regards to #681

**Comment by jigartankhupp** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
I updated the heading to make it C4.

**Comment by gazhayes** [comment]
> Problem: Form validation are bulkier on server side.

Should be something like:
"Problem: [/currencies/:x] no client-side form validation on add feature form

Solution: use validated-method and simpl-schema with bootstrap UX warnings. This means that data will not be sent to the server for validation unless it passes client side validation, and users will see nice errors directly on the form when there are errors."

**Comment by jigartankhupp** [comment]
@gazhayes Noted
@blockrazorbot label "done"

**Comment by jigartankhupp** [comment]
@blockrazorbot remove "in progress"

**Comment by jigartankhupp** [comment]
Done #1406

**Comment by gazhayes** [comment]
@jigartankhupp #1406 was not merged.

**Comment by jigartankhupp** [comment]
Done #1425
