### ISSUE TITLE
Problem : FlowRouter deprecated warning in browser console

### ISSUE THREAD

**Issue by jigartankhupp** [Blockrazor/blockrazor#1407]
Problem: FlowRouter.notFound is deprecated warning in browser console.
Solution: use FlowRouter.route('*', { /*...*/ }) instead!

**Comment by jigartankhupp** [comment]
@blockrazorbot claim

**Comment by jigartankhupp** [comment]
@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by jigartankhupp** [comment]
Done #1408

**Comment by gazhayes** [comment]
Since you logged this issue yourself, you can close it after you have validated that the solution works on the production server.
