### ISSUE TITLE
Problem: official website not displayed on currency detail page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1411]
Problem: official website for each currency is not displayed on currency detail page.

Solution: add official website to one of the tabs on the currency detail page. Also allow it to be edited like everything else.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
done in #1441
@blockrazorbot done
@blockrazorbot label "done"
