### ISSUE TITLE
Problem: router points at addCoin2 that doesn't exist

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1426]
Problem: router has addcoin2 route that no longer exists

Solution: delete it. 
@blockrazorbot claim

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1491
@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done
