### ISSUE TITLE
Problem : Sidemenu close button position not center

### ISSUE THREAD

**Issue by jigartankhupp** [Blockrazor/blockrazor#1428]
Problem: In sidebar close icon not showing in center and also not visible in smaller screen.
![screenshot from 2018-05-03 17-58-43](https://user-images.githubusercontent.com/38810839/39576753-d5e62444-4efc-11e8-89bb-9654a062759a.png)
Solution:  Add css to set icon in center.

**Comment by jigartankhupp** [comment]
@blockrazorbot  "claim"

**Comment by gazhayes** [comment]
It also covers things, it would be better to make it much more slim.

**Comment by jigartankhupp** [comment]
@gazhayes ok - the image above is an image of issue. I'll push the fix you asked and also the one I found.
but why can't I claim the issue ? any idea ?

**Comment by gazhayes** [comment]
> but why can't I claim the issue ? any idea ?

I'm looking into it now.

**Comment by gazhayes** [comment]
OK. You can only claim a maximum of two issues at once. That's why. When you have finished an issue you can `@blockrazorbot done` in addition to `@blockrazorbot label "done"` and it will free you up to claim more.

**Comment by jigartankhupp** [comment]
@blockrazorbot  Done #1429 
@blockrazorbot  label "done"
@blockrazorbot  remove "in progress"
