### ISSUE TITLE
Problem: uploaded logos not included in database

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#143]
Problem: logos are uploaded but are not included in the database so they cannot be used.

Solution: include filename in database, ensure that the filename is copied over from pending to active database on approval.

**Comment by gazhayes** [comment]
ping @AshHimself

**Comment by AshHimself** [comment]
@gazhayes - should we have a ticket related to no ability to edit currencies? or this something we are expecting to do manually if needed? Seems like more of an admin role not even moderator. Thoughts?

**Comment by gazhayes** [comment]
> no ability to edit currencies   
I'll elaborate on this later
