### ISSUE TITLE
Problem: newFeature method has validation removed

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1431]
Problem: newFeature method is stripped of validation in #1425. Issue being that a hacker would still call method from console passing book "war and peace" as a feature.

Solution: Ideal refractor would involve usage of MDG validated method, although that would be pretty esoteric if you had to design a schema and plug-in client validation, something that should've happened in /addcoin.

**Comment by janat08** [comment]
the schema for this is located in non-standard location and should be moved (under some ``validation`` folder).

**Comment by gazhayes** [comment]
Is it simpler to revert #1425 and then solve #1404 properly?

**Comment by janat08** [comment]
@jigartankhupp you still should make the original method validate data, you can do that with simpleSchema, (add coin method does that), and move the schema to another file.

**Comment by anbud** [comment]
I'll convert it to validated-method.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1502.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
