### ISSUE TITLE
Problem: ....sweetalert2 are not dynamically imported

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1438]
Problem: There's aslagle:reactive-table, moment which could be converted to the npm version and sweetalert2. The reason why they're still bundled is because they're asking for meteor version below 1.5 or they require Meteor.startup hook or because they have no mainmodule.
https://github.com/sweetalert2/sweetalert2
https://github.com/aslagle/reactive-table/blob/master/package.js

These total about 100kb.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
I've gotten rid of `momentjs` and `sweetalert2` in #1455. I don't know what to do about `reactive-table`, as I can't seem to find an easy way to dynamically import a package that includes Blaze components.

Please note that this PR may cause issues with `sweetalert` as I've updated it to `sweetalert2`. I've fixed most of the caused issues, but if something happens, please create new issues. I've mostly followed [this guide](https://github.com/sweetalert2/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2) for upgrading.

@janat08 or anybody else, if you have any ideas on what to do with `reactive-table`, go for it. I'm unclaiming this issue for now if somebody else wants to fix `reactive- table`.

@blockrazorbot abandon

**Comment by anbud** [comment]
@janat08, both `sweetalert` and `sweetalert2` are used for popups/modals. `sweetalert2` is just an update for `sweetalert` which is not entirely backward compatible. We use `sAlert` for method completion notifications, which is, I guess, not connected to either `sweetalert` nor `sweetalert2`.

**Comment by janat08** [comment]
@AshHimself any chance sAlert stands for "sweetalert"(1).

**Comment by janat08** [comment]
i'll close this since modals don't pop up at my face for basic actions.

**Comment by anbud** [comment]
@janat08, this is the one, https://github.com/juliancwirko/meteor-s-alert
