### ISSUE TITLE
Problem: Elo ranking does weird stuff when tie

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#144]
Problem: the ELO ranking Method (probably not the ranking algorithm) does weird stuff when two currencies are tied. Sometimes it leaves the score as is, and sometimes it decreases it substantially. I haven't looked into what exactly is going on but I think I wrote something so that one of the currencies would be given a win/loss when there's a tie (based on how much difference there is between the existing scores). In retrospect this is pretty silly.

Solution: Later on we should probably compute ties properly but for now we can simply ignore any ties.

**Comment by anbud** [comment]
Fixed in #162.
