### ISSUE TITLE
Problem: comment layout is broken

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1442]
Problem: [/currency/x] comment layout is broken. There should be a horizontal row at the bottom.

<img width="503" alt="screen shot 2018-05-04 at 2 12 39 pm" src="https://user-images.githubusercontent.com/8143945/39614833-5ab6b780-4fa5-11e8-942b-603f31c47e23.png">

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed in #1447
@blockrazorbot done
@blockrazorbot label "done"
