### ISSUE TITLE
Problem: TypeError: Cannot read property 'params' of null

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1445]
Problem: console error on /addcoin: `TypeError: Cannot read property 'params' of null`

Solution: work out the cause of the problem and then decide if it's worth solving it.

**Comment by janat08** [comment]
@blockrazorbot claim.

**Comment by janat08** [comment]
The issue is about it not being able to parse navigation history, ill look into disabled that middleware even if I already looked into it before concluding that it actually isn't suppose to be enabled.

**Comment by janat08** [comment]
I don't think that the error does anything.

**Comment by janat08** [comment]
It's not an error with typeahead template either, nx-framework itself is interacting with router history.

**Comment by janat08** [comment]
https://github.com/nx-js/framework/issues/25
@blockrazorbot label "low_priority"

**Comment by janat08** [comment]
@blockrazorbot label "unmet dependency". unclaim

**Comment by janat08** [comment]
@blockrazorbot unclaim

**Comment by gazhayes** [comment]
What's the dependency?

**Comment by janat08** [comment]
nx-js/framework#25

**Comment by anbud** [comment]
Closing this one in favor of #1629.
