### ISSUE TITLE
Problem: unterminated character class at exchanges at [/addcoin]

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1457]
Problem: regular expression param to mongo query is causing issues in typeahead

Solution: follow example on typeahead docs.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
@janayt08, what's the exact problem here? :) I can't seem to find what actually needs fixing here.

**Comment by janat08** [comment]
can't reproduce
