### ISSUE TITLE
Problem: no Blockrazor bootswatch theme

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1461]
Problem: we are currently using lux.min.js which is difficult to modify.

Solution: copy the unminified lux bootswatch style to a new blockrazor.bootswach.css file which can be more easily customized.

For future reference, all changes should stick to the existing bootswatch API so that our theme can be shared back to the Bootswatch project as a new theme.

**Comment by AshHimself** [comment]
I sorta already stated this mate in the ticket I have opened assigned to me
which I need you input on ?

**Comment by gazhayes** [comment]
Oh ok just take this then and send a PR

**Comment by AshHimself** [comment]
@gazhayes

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1468
@blockrazorbot label 'done'

**Comment by AshHimself** [comment]
@blockrazorbot done
