### ISSUE TITLE
problem: main body div is not responsive

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1469]
Problem: main body div is not responsive and is causing me to have to scroll right on all pages to see some content. This is providing a horrible UX

http://g.recordit.co/9YqJKuT9Bp.gif

Solution: ensure CSS is responsive

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
Fixed in #1498
@blockrazorbot label "done"
@blockrazorbot done
