### ISSUE TITLE
Problem: wallet shows incorrect notification after placing bid from /currencyAuction

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1477]
Problem: After placing a bid on a currency from /currecnyAuction, the wallet shows a notification, but on visiting /wallet there is no notification for transactions. 

![b2072dc7-1fe5-4237-ad8e-aeaf75674614 7](https://user-images.githubusercontent.com/12807846/39725962-246b451a-526b-11e8-9c17-25346e5108a3.png)

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed in #1503
@blockrazorbot label "done"
@blockrazorbot done

**Comment by chamidu-supeshala** [comment]
fixed in #1504
