### ISSUE TITLE
Problem: user can submit empty problems from /problems

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1478]
Problem: The user can create new problems without inputting data in the form at /problem.

Solution: The user must not be able to create such problems in the system. We must add proper validations to the form at /problems

![screen shot 2018-05-08 at 3 02 53 am](https://user-images.githubusercontent.com/12807846/39726547-04ad59aa-526d-11e8-8886-770420e6bc34.png)

**Comment by gazhayes** [comment]
@anbud I just checked and it seems to be happening on production, weird I thought we had validation there.

I guess validated-method and simpl-schema should be used.

**Comment by jigartankhupp** [comment]
@blockrazorbot  claim

**Comment by jigartankhupp** [comment]
@blockrazorbot claim

**Comment by jigartankhupp** [comment]
@gazhayes  Not able to claim issue.

**Comment by gazhayes** [comment]
The dev server VPS where blockrazorbot is down, it happens sometimes.

**Comment by jigartankhupp** [comment]
@gazhayes  Live site also not working.

**Comment by jigartankhupp** [comment]
@blockrazorbot  label "done"
@blockrazorbot  remove "in progress"

**Comment by jigartankhupp** [comment]
@blockrazorbot  #1483  Done

**Comment by jigartankhupp** [comment]
@gazhayes  validation already there. 
Just need to clean before checking.

  ```
validate: new SimpleSchema({
    listId: { type: String }
  }).validator({ clean: true }),
```

**Comment by gazhayes** [comment]
@geekyd you can close issues if you added them (after you verify that it's actually solved).
