### ISSUE TITLE
Problem: bad design of cards on /problem for mobile screens

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1479]
Problem: bad design of cards on /problem for mobile screens. The status of the problem overflows the parent element.

![screen shot 2018-05-08 at 3 14 06 am](https://user-images.githubusercontent.com/12807846/39726795-e9fedcea-526d-11e8-92fb-735dad0e2d7c.png)

Solution: The status of the problem must not overflow the parent. We can change the design to something like this.
![screen shot 2018-05-08 at 3 13 31 am](https://user-images.githubusercontent.com/12807846/39726776-d1bb7544-526d-11e8-926a-0aaa2d37b456.png)

**Comment by gazhayes** [comment]
This isn't such a big problem, the only pages that matter for mobile are the home route and compare currencies.

**Comment by gazhayes** [comment]
@blockrazorbot label "UI-UX"

**Comment by geekyd** [comment]
@blockrazorbot claim
