### ISSUE TITLE
Problem: missing icon for bounties in nav bar

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1480]
Problem: missing icon for bounties in nav bar.

![screen shot 2018-05-08 at 3 40 47 am](https://user-images.githubusercontent.com/12807846/39727844-fea81bda-5271-11e8-844e-86111356a9be.png)

Solution: Add an icon for the bounties in nav bar.

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
Done in #1481
@blockrazorbot remove "in progress"
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
FYI @geekyd you can close any issues you create once the fix has been merged and you verify it works on the production server.
