### ISSUE TITLE
Problem: not all regular contributors are listed on Github organization 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1487]
Problem: not all regular contributors are listed at https://github.com/orgs/Blockrazor/people and this might lead people to think we are not being transparent.

Solution:
Go to https://github.com/orgs/Blockrazor/people

If you see <img width="75" alt="screen shot 2018-05-09 at 9 41 31 am" src="https://user-images.githubusercontent.com/8143945/39791241-33a2aafc-536d-11e8-9a2a-413b03c9a8d6.png"> next to your name then change it to 'public'.

ping @anbud @AshHimself @chamidu-supeshala

**Comment by AshHimself** [comment]
Done

**Comment by chamidu-supeshala** [comment]
Done
