### ISSUE TITLE
problem: when adding a new auction error if no reserve

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1488]
Problem: when a user adds a new auction there's an error if they don't put anything into the reserve field.
<img width="595" alt="screen shot 2018-05-09 at 9 55 54 am" src="https://user-images.githubusercontent.com/8143945/39791639-5c953234-536f-11e8-984f-689c1227db47.png">

Solution: default this to 0 if field is empty, don't prompt user for a 0.

**Comment by AshHimself** [comment]
@blockrazorbot label "done"
fixed in #1494

**Comment by AshHimself** [comment]
@blockrazorbot done
