### ISSUE TITLE
problem: cannot bid low amount on auction

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1489]
Problem: in chrome, I get this error when attempting to bid on an auction.
<img width="905" alt="screen shot 2018-05-09 at 10 00 16 am" src="https://user-images.githubusercontent.com/8143945/39791744-e2845064-536f-11e8-9d69-b3b743691267.png">

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@blockrazorbot label "done"
fixed in #1492

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by AshHimself** [comment]
@gazhayes - this problem looks to be globally throughout the site. Should I do another PR to fix this globally on this ticket?

**Comment by gazhayes** [comment]
@AshHimself 

> this problem looks to be globally throughout the site. Should I do another PR to fix this globally on this ticket?

Yeah, if you haven't already
