### ISSUE TITLE
problem: ETH balance incorrect

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1490]
Problem: ETH balance is not updating correctly.

To test this, try adding ETH to your wallet. You will see no change in your balance and will be unable to use the additional coins in auctions.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes are you sure? can you test again I can do it no issues.

**Comment by gazhayes** [comment]
Weird. Testing again now.

**Comment by gazhayes** [comment]
Must have been a weird thing with my local cache or something.
