### ISSUE TITLE
problem: [wallet] US dollar on wallets can't have an icon as its not a currency

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1497]
Problem: [wallet] US dollar on wallets can't have an icon as its not a currency

Solution: Add a fontawesome dollar sign for the US currency.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
Should probably use font awesome

**Comment by gazhayes** [comment]
Actually I noticed that font awesome has monero, bitcoin, and ethereum too. It could make the style nice, I don't know.

**Comment by AshHimself** [comment]
ha... beat me to it. have updated my solution.

**Comment by AshHimself** [comment]
hmmm couldn't see one for monero

**Comment by AshHimself** [comment]
@gazhayes 
![image](https://user-images.githubusercontent.com/148682/39802133-d6660f4a-539f-11e8-853f-cd6a1a787bef.png)

**Comment by gazhayes** [comment]
https://fontawesome.com/icons/monero?style=brands

**Comment by gazhayes** [comment]
I should probably make a Krazor logo.

**Comment by AshHimself** [comment]
yay or nay

**Comment by AshHimself** [comment]
As for the logo.. you got like 3-5 logos you like and I can probably photoshop one up and start getting one together for launch?

**Comment by gazhayes** [comment]
> yay or nay 

Push! don't ask ;)

**Comment by AshHimself** [comment]
@blockrazorbot label "done"
fixed in #1499

**Comment by AshHimself** [comment]
@blockrazorbot done
