### ISSUE TITLE
problem: cannot upload new currency logo

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1500]
Problem: [/currency/:x] can't upload new logo

<img width="435" alt="screen shot 2018-05-09 at 4 45 31 pm" src="https://user-images.githubusercontent.com/8143945/39805128-8be028f8-53a8-11e8-9f67-1bb39d1643df.png">

**Comment by anbud** [comment]
This one is on me, I thought it was in the schema already.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1501.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
