### ISSUE TITLE
Problem: meteor packages in test environment

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1514]
Problem: Since meteor packages are not recognized by npm, they can't be used in testing solutions outside webdriver which makes them bad tests since they'll be implementation dependent. I think that both typeahead and localizable collection tests would be better served by being independent of their implementations.

Solution: There's https://github.com/TheBrainFamily/testable-meteor, which I tried doing for the jest framework.

Possible Solution: Meteor intends to package itself for npm. Maybe that comes with the next release.

**Comment by gazhayes** [comment]
Waiting is probably the simplest solution here. And also removing any meteor packages if npm packages can be used instead.

**Comment by janat08** [comment]
So closing and writing tests in webdriver
