### ISSUE TITLE
Problem: make collections global in tests in webdriver

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1518]
Problem: you have to run queries in webdriver and the collections are out of scope nor can they be imported/required.

Solution: import things from indexDB.js as * as ``objectContainingAllImports`` to introduce as globals for development environment in startup/client folder which hopefully is what web driver is run in. @blockrazorbot claim

**Comment by anbud** [comment]
@janat08, if I'm correct, this has been done in #1529, right?
