### ISSUE TITLE
Problem: [/currency/x] Add new contributions to blockchain not implemented

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1519]
Problem: In some currencies (ex: Cloakcoin) , some of the block chain details not yet added. When going to [/currency/x], we can see the `+contribute` button. However clicking it goes to a [/currencyEdit/x] route which is not defined.

To reproduce the issue go to [/currency/cloakcoin] route and click contribute button for one of the blockchain details.

![screenshot from 2018-05-11 18-31-20](https://user-images.githubusercontent.com/27463355/39925971-4ffec2be-554b-11e8-81ee-fe66ef1bc9f8.png)

Solution: Contributing new details should be same as proposing changes. Need to go through moderator proposal and voting system.

**Comment by chamidu-supeshala** [comment]
ping @anbud

**Comment by anbud** [comment]
You're right, it's interesting, I'll see what's the best possible approach.

@blockrazorbot claim

**Comment by anbud** [comment]
The basic solution is in #1520, which fixes the issue.

@gazhayes, contributions for data fetched from various APIs (`maxCoins`, `cpc`, `cpt`, `price`, `marketCap`, `circulating`) are disabled (as they were before).
Should we allow users to contribute these things as well, if, for example, the API is not available or something? We could possibly let them contribute `maxCoins`, `circulating` and `price` while we can generate `cpc` and `cpt` automatically from this data.

Marking this issue as done, as the main problem is fixed.
@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by gazhayes** [comment]
> Should we allow users to contribute these things as well, if, for example, the API is not available or something? 

No in that case we should just ask for an API instead because it's such a moving target.

The one thing that we can ask for though is maxcoins, since sometimes that's not in an API.
