### ISSUE TITLE
Problem: localized collections used inefficient callback option by default in observer tap

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1521]
Problem: The localized collection will tap observers (queries run in autorun) and use observedChanges option for that which supports inefficient beforeAdded option that's required if limits and skips are used.

Solution: Try using added, and if the query uses limit or skip it should throw an error somewhere (there's a github issue describing why an error is thrown) at which point beforeAdded could be used.

**Comment by anbud** [comment]
As far as I can tell, it's currently using `added` by default, and it's only switching to `addedBefore` in case there's a limit or a sort field in the projection. Isn't that what's the solution you've proposed describing?

**Comment by janat08** [comment]
Yes. Yet it warns against including the option in callbacks in meteor api: https://docs.meteor.com/api/collections.html#Mongo-Cursor-observeChanges.

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
Right, andbud made it with the solution.
