### ISSUE TITLE
Problem: missing validations on steps of form in /addCoin

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1525]
Problem: missing validations on each step of form in/addCoin, which lets user jump to the finish without completing the form. Currently if the user completes a form & misses a field he/she will have to manually move to the step to complete the missing detail.

Solution: Add validations on each step of the form. This will help user to fill the form & provide a better user experience than the current scenario.

@gazhayes @anbud What do you think? Can you please specify the required fields for the addCoin form?
I would like to work on this if its feasible

**Comment by anbud** [comment]
I honestly thought this was already in place. I think it would be a good idea to check each step, as it is kinda frustrating if you have to go back a few steps just to fix a certain field.

@gazhayes will have to confirm this, but I believe that required fields are the ones you can see in `Currencies.schema`. Issues #868 and #617 probably have meaningful information about this as well.

**Comment by gazhayes** [comment]
I also thought this was done. 

If you go back in history to the old addcoin form that's probably the best way to see what is and isn't required as it changes based on what boxes are selected on the first screen.

The only addition to this is the smart contract thing.

**Comment by geekyd** [comment]
@gazhayes @anbud Thanks for the response. I will go ahead with this and add proper validations on each step.

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
If you have specific questions about anything just ask and I'll probably reply almost immediately :)

**Comment by janat08** [comment]
issue #868 is meant to bring simpleSchema to client side to govern what steps should be shown, and by loose extension if they can be used with previous ones being valid.

**Comment by janat08** [comment]
I think what happened here is that he was testing validation on dev with devValidationEnabledFalse.
