### ISSUE TITLE
Problem: testing docs aren't on exhibit from #1035

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1526]
Problem: #1035 holds documentation for testing, and that issue was closed, and so unlikely to be discovered and difficult to be found.

**Comment by gazhayes** [comment]
These should be added to the docs folder

**Comment by anbud** [comment]
I'll add them to the docs folder.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1528.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
