### ISSUE TITLE
Problem: collections in global scope may be used successfully in development environment

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1527]
Problem: collections were introduced into global scope for development environment since testing one doesn't exist and access is to them is desired, for testing typeahead.js. It would be a good idea to test against them being used, as that will break in production.

Solution: You could set up proxy against collections exposed into global that would throw an error or something, and have tests look out for any such errors.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
The basic functionality is done in #1534, if someone tries to use a global collection in production, it'll throw an error.

Now, I'm not sure about what's the best approach to testing this. When we run WDIO tests in CI, they're being run on a server instance that has `isDevelopment` flag set to true, and hence, this behavior can't be tested there. 

There are two possible solutions that I can think of:
- First, we could run two Meteor instances in CI (one production, one development) and run tests that don't require development environment (like this issue) on a production instance and run other tests on the instance with `isDevelopment` set to true. A drawback to this solution would be that the testing time would increase by at least 5 minutes, and the tests are already taking quite long. Another possible issue here is that the test would have to go through all routes to check if errors are occurring somewhere.
- Second, we could implement a simple script that would catch client-side errors and save that data somewhere (could be regular Meteor collections, or it could ping GitHub API or something). It could be global, and this way we could catch other possible errors as well. [Rollbar](https://docs.rollbar.com/docs/javascript/) does this quite successfully, but it may be a little bit bloated for our usage scenario.

Ping @gazhayes and @janat08 for opinions on this one.

**Comment by janat08** [comment]
We could just expose the globals under a different name, testingOnlyCurrencies.

**Comment by anbud** [comment]
Done in #1603.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
