### ISSUE TITLE
Problem: addCoin doesn't use localizableCollection

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1530]
Problem: #1507 removed initialization of transcient option, and disabled the option for addCoin whereas it should remain on.

Solution: uncomment transcient code, enable transcient prop for addcoin.js

**Comment by anbud** [comment]
The commented code wasn't there before, that was just me testing something out. I'm not sure it should be there.

**Comment by anbud** [comment]
Also, I couldn't get data to update with transcient option on, it just used old cache.

**Comment by janat08** [comment]
Lol I didn't really recognize that comment. The way transcient option worked (if it ever did) was that an observer would be set up outside the typeahead, and the cache would wiretap the observer to update itself. I'm unsure that creating added observer would be worthwhile.

**Comment by janat08** [comment]
closing in favour of #1531.
