### ISSUE TITLE
problem: unable to create/edit your profile

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#154]
Problem: unable to create/edit your profile.

Solution: Create view profile page and edit profile page.

**Comment by AshHimself** [comment]
@gazhayes - I have created a boiletplate page to;
- edit: fullname
- edit: avatar
- edit: email

Current signup process only captures email. Do you think its plausible to just leave it as is and users finish their profile once signed up? or we can create a ticket to change signup flow or figure that out later.

**Comment by gazhayes** [comment]
Email signup will be disabled for production, only facebook and github will remain.

Users should be able to change (or add) their email for notifications but this can be done after signup.

Also need a bio field too (again, after signup).
