### ISSUE TITLE
Problem: trading auctions immediately jump to the highest bid

### ISSUE THREAD

**Issue by gsovereignty** [Blockrazor/blockrazor#1541]
Problem: when users bid on an auction at /auctions the way the auction works is the user must bid their maximum nominal amount and the auction then increases to that price. Users cannot set a maximum bid price and then let the system automatically increase their bid depending on the other bids (in a similar way to eBay).

ping @anbud I haven't looked at the auction code, how hard is it to implement this?

**Comment by anbud** [comment]
Not that hard, I have an idea on how to implement it, it doesn't require big changes.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1577. I've set the increment to 0.0001, we can change it whenever we want.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
