### ISSUE TITLE
problem: [/addcoin] TypeError: d.BTCFork is undefined

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1545]
Problem: when creating a new currency that is not a bitcoin fork this error appears in the console and the form can't be submitted.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed #1547
@blockrazorbot label "done"
@blockrazorbot done

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"
