### ISSUE TITLE
Problem: [/] Type Error while scrolling down in home: Cannot read property 'hasAttribute' of null

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1550]
Problem: when scrolling further down in the home route, following console error showing

![screenshot from 2018-05-16 10-34-59](https://user-images.githubusercontent.com/27463355/40098292-665de462-58f8-11e8-8fb7-cde87152e9fe.png)

Solution: check what causes it and fix

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Fixed in #1601.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
