### ISSUE TITLE
Problem: [/problems] problems can submitted without description

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1553]
Problem: anyone can just add new problem without even any description. (currently only requires problem summary, to submit a new problem)

those loosly submitted problems appear in the problem page as follows, without any description:

![screenshot from 2018-05-16 11-33-26](https://user-images.githubusercontent.com/27463355/40099442-a5a4008e-58fd-11e8-8f7a-e7e9831e78d2.png)

Solution:  make problem description `required`

**Comment by chamidu-supeshala** [comment]
i have edited this issue and logged new one for searching issue

**Comment by anbud** [comment]
Fixed in #1579.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
