### ISSUE TITLE
Problem: [/problems] no consistency in app for selections

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1554]
Problem: in the other pages, we replaced top most select boxes with check boxes.
Dunno why the select element with ALL, OPEN, INPROGRESS, SOLVED, CLOSED still not replaced with check boxes to make the UI of app consistent across pages.

Solution: if there is no any reason to keep the select element, we can replace it with check boxes.
(if check boxes is not the ideal solution for this particular usecase, please  close this issue :) )

@blockrazorbot label "UI-UX"

**Comment by gazhayes** [comment]
Yeah the select box is annoying, it should be check boxes instead. The default state should be whatever makes the most sense as a user, so I guess "open" only, and everything else unchecked.

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
Is this done or in progress?

**Comment by chamidu-supeshala** [comment]
It was done, but the label text incorrect, though

![screenshot from 2018-05-18 10-24-01](https://user-images.githubusercontent.com/27463355/40216684-cfdd1668-5a85-11e8-9f5c-80aea0619f72.png)

**Comment by chamidu-supeshala** [comment]
I'll close this as original problem solved
