### ISSUE TITLE
Problem: page not found bad UI UX

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1555]
Problem: to make the website more professional, it is better to consider page not found page also. currently it looks as below

![screenshot from 2018-05-16 11-51-19](https://user-images.githubusercontent.com/27463355/40099886-89ad31c8-58ff-11e8-8a96-88c4c62c4b1a.png)

Solution: make it use same theme of the app or any other good solution

**Comment by jigartankhupp** [comment]
@blockrazorbot  claim

**Comment by jigartankhupp** [comment]
@blockrazorbot  Done #1563 
@blockrazorbot remove "in progress"
@blockrazorbot  label "done"
