### ISSUE TITLE
Problem: [/problems] the searching of existing problems happened for problem description and not for the problem summary

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1557]
Problem: the searching of existing problems happened for problem description and not for the problem summary

Solution: change search to look for keyword in problem summary, rather than problem description

**Comment by gazhayes** [comment]
It should really search description *and* summary.

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
fixed #1572 
@blockrazorbot remove "in progress"
@blockrazorbot label "done"
