### ISSUE TITLE
Probelm: [/problems] just after submitting an issue, immediately open it causes series of console exceptions and problem wont properly displayed

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1558]
Problem: if we open a submitted problem immediately after submitting it, causes following console exceptions:

`Exception in template helper: TypeError: Cannot read property 'type' of undefined`

`Exception in template helper: TypeError: Cannot read property 'cancelled' of undefined`

`Exception in template helper: TypeError: Cannot read property 'taken' of undefined`

`Exception in template helper: TypeError: Cannot read property 'open' of undefined`

`Exception in template helper: TypeError: Cannot read property 'cancelled' of undefined`

Opened problem not displayed as well

![screenshot from 2018-05-16 12-33-25](https://user-images.githubusercontent.com/27463355/40101556-683bb3b0-5905-11e8-9d83-1a703ed3d6b1.png)

But When navigate to some other page and opening the issue, properly opens it. !
As this is strange bug, i checked both locally and production. It happens only when opening problem immediately after submitting it.

Solution: looks like some variable not initializing, when redirecting to [/problem] after submitting new problem report

**Comment by gazhayes** [comment]
Ping @janat08

**Comment by janat08** [comment]
Why adding add observer works since I think the problem was that minimongo runs method on client creating wrong ID, and then passes wrong ID into problemView that starts non-local find method and can't find any records from server that created it's own ID.

**Comment by janat08** [comment]
I'll move this to new issue for optimizing added document detection strategy.

**Comment by janat08** [comment]
@blockrazorbot label "done"
