### ISSUE TITLE
problem: [/profile] No proper page not found redirection after logged out

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1560]
Problem: when use not logged in, the [/profile] route should not be accessible. but when goes to [/profile], the following console error shown, and not redirected to page not found page.

![screenshot from 2018-05-16 10-26-49](https://user-images.githubusercontent.com/27463355/40102335-d4c71856-5907-11e8-9793-a0d7a99f7414.png)

Solution: 
1. restrict access to [/profile] url when not logged in
or
2.allow unregistered users to see profiles of others by navigate to [/profile/x]. but still the [/profile] (without user slug)  url should redirected to `page not found`, if not logged in.

@blockrazorbot label "low_priority"

**Comment by gazhayes** [comment]
> restrict access to [/profile] url when not logged in

That looks like the simplest solution.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed #1593
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
@blockrazorbot done
