### ISSUE TITLE
Probelm: [/mypending] Bad UI/UX and not consistent with other pages

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1561]
Problem:  the UI looks not good at [/mypending] and specially it is not consistent with other pages.

![screenshot from 2018-05-16 13-03-29](https://user-images.githubusercontent.com/27463355/40103001-aa5b143a-5909-11e8-8bb3-b793bdb2a575.png)

Solution: the following adjustments can be made:

1. add the heading and header outer just like other pages
2. bootswatchify elements and use grey theme rather than different different colors
3. titles and no result messages should not be similar.
4. better if page can completely refined with using cards or collapse or something similar

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "UI-UX"

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@blockrazorbot label "done"
fixed in #1582

**Comment by AshHimself** [comment]
@blockrazorbot done
