### ISSUE TITLE
Problem: add problem/coin require validation on dev

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1566]
Problem: adding things when you run meteor without any flags for the environment shouldn't run validations complicating testing using devValidationEnabledFalse variable exported from /imports/api/indexDB that turns to true in production environment.

Solution: revert changes from #1525 in case that that issue is erroneous, since validation is done entirely is poor form with usage of notifications and non simpleSchema validation. Otherwise do that validation conditionally, and bypass add problem validation in dev, too.

**Comment by janat08** [comment]
Perhaps this should be labeled as noteworthy.

**Comment by janat08** [comment]
yes, these validations shouldn't run when you launch with "meteor", and previous validations wouldn't have run either if there were some.

**Comment by janat08** [comment]
@blockrazorbot claim, fixing is part of validation adjustment for /addcoin issue.

**Comment by anbud** [comment]
This one was also fixed for `/addCoin` page in #1660.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by janat08** [comment]
@blockrazorbot unclaim.

**Comment by janat08** [comment]
Problems is left.

**Comment by AshHimself** [comment]
Maybe you can close this it he requestor isn't around now @anbud
