### ISSUE TITLE
Problem: typeahead doesn't add created items to selection in [/addCoin]

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1567]
Problem: sAlerts on success imply and that exchanges are created and automatically added while they're not.

Solution: Run add method on results of create methods.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1578.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
