### ISSUE TITLE
Problem: Iterating through the same collection multiple times is inefficient

### ISSUE THREAD

**Issue by kevgathuku** [Blockrazor/blockrazor#157]
Problem: Iterating through the same collection multiple times is inefficient
This is specifically for this instance:
https://github.com/Blockrazor/blockrazor/blob/master/server/serverdb/addCoin.js#L48-L51

Solution: 
Use one loop with multiple if..else statements to achieve the same functionality

**Comment by kevgathuku** [comment]
I'll work on this.

**Comment by gazhayes** [comment]
Not sure how/why I closed this prematurely.

Looks like this is fixed in #158, @kevgathuku can you confirm and close if so?

A great first pull request by the way :)

**Comment by kevgathuku** [comment]
Hey @gazhayes yes, this fixes the issue.
Happy to help out 😄
