### ISSUE TITLE
Problem: inconsistent size of cards on /wallet 

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1575]
Problem: inconsistent design of cards on /wallet
![b2072dc7-1fe5-4237-ad8e-aeaf75674614](https://user-images.githubusercontent.com/12807846/40138609-d0fd9368-596a-11e8-82de-7fe2b636f8f3.png)

Solution: Make the size of all the cards equal.

**Comment by samuelralak** [comment]
@blockrazorbot claim
@blockrazorbot label "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"
@blockrazorbot lable "done"

**Comment by samuelralak** [comment]
fixed in [#1618](https://github.com/Blockrazor/blockrazor/pull/1618)

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@geekyd feel free to close this one
