### ISSUE TITLE
Problem: icon not rendered properly in /wallet/:x

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1576]
Problem: icon not rendered properly in /wallet/:x for reset button 
![b2072dc7-1fe5-4237-ad8e-aeaf75674614 1](https://user-images.githubusercontent.com/12807846/40138899-bf5e26ee-596b-11e8-9296-4038b8bad6f8.png)

Solution: Make sure that the icon is rendered properly. Use `fa-times` instead of `fa-close`

**Comment by jigartankhupp** [comment]
@blockrazorbot  claim

**Comment by jigartankhupp** [comment]
@blockrazorbot  Done #1594 
@blockrazorbot  label "done"
@blockrazorbot  remove "in progress"
