### ISSUE TITLE
problem: full bid amount is not reserved from wallet

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1580]
Problem: [/auctions] when bidding on an auction only the current bid amount is reserved from a user's wallet, the full bid amount is not reserved. This means that they could accidentally spend more than is currently in their wallet on other auctions, or other parts of the site.

ping @anbud

**Comment by anbud** [comment]
This one is mine, I'll fix it.

@blockrazorbot claim
