### ISSUE TITLE
problem: add coin UI errors are annoying

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1584]
Problem: some of the errors on /addcoin are using sAlert rather than showing inline bootstrap errors.

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
Ping @janat08 for reference

**Comment by geekyd** [comment]
@gazhayes Yeah. I will be sending a PR soon

**Comment by janat08** [comment]
Ill wait for you to send the pr then, and then continue working on /addcoin validation.

**Comment by janat08** [comment]
make errors inline

**Comment by geekyd** [comment]
Done in #1627 .

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
