### ISSUE TITLE
Problem: typeahead custom empty messages are untested

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1585]
Problem: typeahead doesn't have test for custom empty message for inline button or external integrated button. The inline button function prop has params for current value. There're currently no pages that have custom message, but you might just test default one.

Solution: edit typeahead.ui-test.js with new tests.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Default value is tested in #1635.

@blockrazorbot remove "in progress"
@blockrazorbot label "done"
