### ISSUE TITLE
Problem: typeahead limit/autofocus/placeholder/displayField props untested

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1586]
Problem: typeahead has props like limit that isn't actually used anywhere, along with others- as per the title- that are used in various placed. It should be checked that these props have an effect and expected output, or otherwise that defaults work (all the prop defaults are at the top of created hook.

Solution: Searching repository for "typeaheadProps" will find you the files/pages that use typeahead to test custom/default props.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1692.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
