### ISSUE TITLE
Problem: inline/external-integrated button dynamics not tested.

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1589]
Problem: There's no prop that decides if there's external-integrated button or inline button in typeahead, but if there's integrated-external one then clicking on inline message/button shouldn't trigger the create event. If customAddButtonExists prop is false it renders integrated button, if it's true and the create event is true- exists- then it renders inline test fires an event.

Solution: addCoin has integrated button, currencyDetails has inline one, and auction has no create event or button. Btw the event in inline button is attached to text rather than the list block, and with long enough text the two don't overlap.

**Comment by anbud** [comment]
Testing is fun. :)

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1630.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by janat08** [comment]
the test is about if one of and only one of external-integrated, inline, and non-butttons exist.

**Comment by anbud** [comment]
Oh, ok, I'll update it for those things as well.

@blockrazorbot remove "done"
@blockrazorbot label "in progress"

**Comment by anbud** [comment]
Done in #1676.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
