### ISSUE TITLE
Problem: graphdata is being populated incorrectly

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#159]
Problem: `graphdata` should be populated with the maximum and minimum values from `currencies:communityRanking` and `currencies:walletRanking`. The existing Methods to populate this are floating around in https://github.com/Blockrazor/blockrazor/blob/master/server/methods/elorankings.js

While you're doing this: the existing code is mixed in with other methods, please make this its own method and deprecate the existing code. Also please add a fixture like this to make this run from a cron job every 10 minutes: https://github.com/Blockrazor/blockrazor/blob/e42906aed4365e522481d832f3ea1925500e83a3/server/API_requests/github.js#L6

**Comment by gazhayes** [comment]
> looks like we are getting the data from the EloRanking table filtered on the category:wallet

Yeah that's probably the problem. Graphdata should be populated from the `currencies` collection (and the currencies collection should be populated by averageEloWallet and averageEloCommunity). I put these in the same Method (I think) which was a dumb idea.

So basically split off anything related to graphdata in all the methods in that file and create a new method dedicated to popuating graphdata.

**Comment by gazhayes** [comment]
@anbud there's also of course the recently added codebase comparison thing to add to this.

**Comment by anbud** [comment]
@gazhayes, of course. I'm on it.

**Comment by anbud** [comment]
Done in #168.
