### ISSUE TITLE
Problem: [/problems] label text of filters is incorrect

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1592]
Problem: label text displays "filter bounties" in problems page

![screenshot from 2018-05-18 10-24-01](https://user-images.githubusercontent.com/27463355/40216770-64d3c4ec-5a86-11e8-8921-00c9b384ac65.png)

@blockrazorbot label "UI-UX"

**Comment by geekyd** [comment]
Sorry about this. 
@blockrazorbot claim
