### ISSUE TITLE
Problem: level of decentralization is not measured

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#160]
Problem: the level of decentralization is not measured. Some subjective questions asked when ranking the community (https://blockrazor.org/communities) and the codebase (not yet implemented) will also reflect on the relative levels of decentralization. For example, if pull requests to a codebase need to comply with someone's vision for the future of the currency, that would be more centralized than something that uses (for example) a contribution policy like Blockrazor where pull requests must comply with the process but there's no direction (except for paid contributions).

There are also aspects of decentralization that are absolute and not comparative, such as whether or not the founder of a cryptocurrency is known or not. For example the founder of Bitcoin is unknown and so there's no scope for centralized 'spiritual leadership', whereas Ethereum (for example) is extremely centralized and Vitalik Buterin essentially dictates policy.

This must somehow be captured by Blockrazor.

**Comment by gazhayes** [comment]
ping @AshHimself @sjmackenzie  @anbud for any ideas or suggestions.

**Comment by anbud** [comment]
@gazhayes, 
The explicit questions (the example with the founder) could be asked directly for each currency the user adds (adding a currency could be a similar process to adding a currency for community or wallet comparison). These results should probably have a higher priority in the overall ranking.
The implicit part, however, could be solved by adding an array of metrics the question implicitly affects to each question (of course, the array could be empty). Maybe we can even include a coefficient (0..1) to determine how much it affects the metric. That way, for example, when a user answers a community comparison question, it will also affect the decentralization metric accordingly (or any other metric, this would be a general solution).

**Comment by gazhayes** [comment]
> could be solved by adding an array of metrics the question implicitly affects to each question

I think that's a good partial solution to start with. The coefficient probably isn't necessary, we can add it later if it solves a problem.

> The explicit questions (the example with the founder) could be asked directly for each currency the user adds (adding a currency could be a similar process to adding a currency for community or wallet comparison).

Do you have any thoughts on how to introduce this to the the existing Elo metric type system we are using?

**Comment by anbud** [comment]
@gazhayes, it could a little bit tricky, since ELO is a match ranking system. But, a possible simple solution to explicit questions would be just to increase or decrease the metric value based on the question answer (i.e, we could increase or decrease by 5). So, the ELO ranking would be used implicitly, and the explicit questions would affect the metric directly.

**Comment by anbud** [comment]
I've implemented a possible solution in #170, based on my previous answer. It supports both implicit (question's `affects` field) and explicit rankings (`/decentralization`).

**Comment by gazhayes** [comment]
@anbud do you remember how the 'affects' questions are treated when used for ELO rankings? I added a test question locally (community and affects decentralization) but when answering the question I can't see anything in the ratings collection that could be used for processing the decentralization part.

**Comment by anbud** [comment]
@gazhayes, There's no separate entry in the `Ratings` collection, the `affects` field is enough. The current calculation is quite basic, it increases or decreases the current decentralization ranking by 2. (in [elorankings.js](https://github.com/Blockrazor/blockrazor/blob/master/server/methods/elorankings.js#L145-L162))
