### ISSUE TITLE
Problem: no 2FA for user actions

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1602]
Problem: users are going to have to be able to withdraw cryptocurrency from Blockrazor, however at present there's no 2FA implemented.

Possible solution: It looks like the simplest solution is probably using something like https://github.com/speakeasyjs/speakeasy

Users should be able to activate it on their account and once activated they can't log in without it.

ping @anbud

**Comment by anbud** [comment]
Agreed, this one is important and `speakeasy` seems quite simple.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1604.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
