### ISSUE TITLE
Problem: 2FA doesn't have backup codes

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1605]
Problem: if users lose their phone (or whatever) there's no way to restore their 2FA and they will be permanently locked out of their account.

ping @anbud

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1606. 
Please note that if you've activated 2FA before, you'll have to click on the `regenerate` link to get the first set of backup 2fa tokens.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
