### ISSUE TITLE
problem: unknown what exchanges have already been flagged for deletion

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1607]
Problem: unknown what exchanges have already been flagged for deletion

Solution: Add a flag

@gazhayes - this an actual problem in your opinion?

**Comment by gazhayes** [comment]
I'm not actually sure I understand what you mean. Can you be more specific?

**Comment by AshHimself** [comment]
Sorry.. on the exchanges page you can mark them for deletion but actually never know what items you have clicked and what others have clicked.

![image](https://user-images.githubusercontent.com/148682/40278666-1741ebee-5c68-11e8-8d87-df0deeb755b9.png)

**Comment by gazhayes** [comment]
Oh ok, no I don't think it's a problem. It does have to be handled correctly on the moderation side though: 3 cumulative up/downvotes, and then it must be removed from individual currencies too. I haven't checked if that's all working properly, you might want to have a look.

**Comment by anbud** [comment]
@AshHimself, the item is flagged only the first time someone reports it, other reports basically do nothing. If you want to add some kind of UI flag to it, there's a field `proposedRemoval` in the document that basically holds the flag. It's not a big issue though, I agree.
