### ISSUE TITLE
problem: [currency] Exception in template helper: TypeError: val[0].join is not a function

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1608]
Problem: [currency] Exception in template helper: TypeError: val[0].join is not a function

Solution: Debug and resolve

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1609
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
@blockrazorbot done

**Comment by AshHimself** [comment]
@gazhayes is our little bot broken :/ can't seem to update this ticket.

**Comment by gazhayes** [comment]
@blockrazorbot  claim

**Comment by gazhayes** [comment]
Server went down, its working again now
