### ISSUE TITLE
Problem: smart contract isn't validated for /addCoin

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1612]
Problem: there's a smartContractUrl field for currency schema, but it's not being reference anywhere including client side, also it's a conditional field therefore I imagine there should be a boolean field too. It appears at top level of client (first step of form).  @blockrazorbot label "unmet dependency"

**Comment by gazhayes** [comment]
It's on the community part when the appropriate checkbox is selected on the first page.

**Comment by gazhayes** [comment]
What's the dependency? I.e. which issue must be completed before this one can be attempted?

**Comment by janat08** [comment]
It didn't appear to be really validated on client side either, so I thought it should wait until I'm done.

**Comment by janat08** [comment]
The url isn't required according schema.

**Comment by gazhayes** [comment]
OK, it *should* be required *if* the smart contract box is checked.

**Comment by janat08** [comment]
@blockrazorbot unlabel "unmet dependency"

**Comment by janat08** [comment]
@blockrazorbot remove "unmet dependency"

**Comment by AshHimself** [comment]
Can't fix this issue until #1673 is resolved

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes - can you close this.
