### ISSUE TITLE
Problem: [/myPending] pending bounties and approved bounties not shown 

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1614]
Problem: pending bounties and approved bounties are not shown in [/mypending]

Solution: this might because lack of `exact name` in the bounty schema for persisting id of the user who completed it.  Previously in the backend, the completed user id saved under `completedBy` in the bounty document , however recently it changed to `userId` in some places in the backend code base. However frontend still uses `completedBy` field name for querying. So no new pending and approved bounties will shown.

So better to use a single field name

**Comment by anbud** [comment]
I'll take a look.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1616.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
