### ISSUE TITLE
Problem: hide vote for changes by moderator on changes dashboard

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1619]
Problem:  hide changes by moderator /moderator/changedCurrencies. The moderator who proposed the change can't vote for the change therefore showing voting buttons is redundant.

Solution: We should hide the buttons for voting on the dashboard for the changes proposed by the moderator himself.

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
Done in #1620 .

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by gazhayes** [comment]
@geekyd please be more careful with your problem reports. You reported a solution here not a problem.
