### ISSUE TITLE
problem: [/addcoin] planned altcoins cannot be added

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1624]
Problem: planned altcoins cannot be added (when none of the boxes on step 1 are checked, it's a planned altcoin).

**Comment by anbud** [comment]
I believe this one is related to #1549, as it's a validation problem as far as I can see.
ping @janat08

**Comment by gazhayes** [comment]
I only had a quick look, but it seems like it might simply be a client side validation thing not in the schema, if that's the case it only requires a one line change.

**Comment by janat08** [comment]
noted and ignored

**Comment by anbud** [comment]
This one was fixed as a part of #1660.

@blockrazorbot label "done"
