### ISSUE TITLE
problem: [/] subscriptions not finalizing

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1631]
Problem: this waits for subscription and never updates:
<img width="328" alt="screen shot 2018-05-23 at 9 13 03 pm" src="https://user-images.githubusercontent.com/8143945/40426650-32798530-5ece-11e8-95c6-16fab84fd086.png">

**Comment by anbud** [comment]
I'll check it out.

@blockrazorbot claim

**Comment by anbud** [comment]
Should be fixed in #1633. It's also related to #1565.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
