### ISSUE TITLE
Problem: [/signup] Broken styles on sign up form

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1634]
Problem: The styling on sign up from is broken; input group icons appear out of place and the sign up button cannot be seen.

Solution: Fix broken styles - borrow solution from from sign in from.

<img width="427" alt="screen shot 2018-05-23 at 6 12 40 pm" src="https://user-images.githubusercontent.com/4476552/40433564-f9015fa8-5eb4-11e8-80db-884dac9a9efc.png">

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
Done in #1639 

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
