### ISSUE TITLE
Problem: No notification shown /wallet after completing bounty

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1637]
Problem: No notification shown on /wallet after completing bounty. Although there is a notification on the side bar & nav bar.

Solution: After some investigation I found that an attribute currency is used to retrieve the `currencyNotifications` on /wallet which does not exist in the schema. We can either add an attribute to the schema or use a solution similar to the one used in wallet/walletTransactions

@anbud @gazhayes @janat08 Please suggest a solution here.

Steps to reproduce:
- Take up & complete a hash bounty
- Visit /wallet

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
From what I remember bounties is no singular collection or document with a schema, therefore it will have a bunch of unique methods for dealing with bounty completions wherein its likely that a function call is amiss. Might it be possible that you stumbled on bounty type that has bad method call, although if the sidebar and navbar notifications have the same query as [/wallet] then it's a bad subscription?

**Comment by geekyd** [comment]
@janat08 
The problem is when a transaction is completed when a bounty completes. 
The transactions on `wallet/walletTransactions` are fetched using the `message` attribute of the wallet. But in case of `/wallet` we are querying using an attribute `currency`. There is no attribute called `currency` in the `/wallet` schema.

We can either use the `message` attribute or we can add `currency` to the schema.

**Comment by geekyd** [comment]
Done in  #1657

@blockrazorbot remove "in progress"
@blockrazorbot label "done"
