### ISSUE TITLE
Problem: different icons for reset filters in /transactions/:x & /wallet/:x

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1640]
Problem: different icons for reset filters in /transactions/:x & /wallet/:x

Solution: Use same icon for resetting filter on both the pages

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
fixed in [#1656](https://github.com/Blockrazor/blockrazor/pull/1656)
