### ISSUE TITLE
Problem: redundant button show on moderator/applogs when there is no data

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1642]
Problem: redundant button show on moderator/applogs when there is no data

Solution: Hide the button if there is no data available to be displayed.

![b2072dc7-1fe5-4237-ad8e-aeaf75674614 1](https://user-images.githubusercontent.com/12807846/40455566-35aae770-5f0b-11e8-9a0a-8e63e76de749.jpeg)

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
fixed in [#1666](https://github.com/Blockrazor/blockrazor/pull/1666)
