### ISSUE TITLE
Problem: moderator is shown self proposed changes for vote changedCurrencies/:x

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1645]
Problem: moderator is shown self proposed changes for vote changedCurrencies/:x. This leads to a frustrating experience for the user. 

Solution: We can either hide the voting buttons from the page for self proposed changes or never show the self proposed changes on the moderator dashboard.

@gazhayes What are your views on this?

**Comment by samuelralak** [comment]
I would propose not showing the changes. If the item isn't actionable, then isn't any need of showing it to the admin/moderator.

**Comment by gazhayes** [comment]
> @gazhayes What are your views on this?

The same as @samuelralak

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
fixed in [#1647](https://github.com/Blockrazor/blockrazor/pull/1647)
