### ISSUE TITLE
Problem: Blockrazor.org server down

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1648]
Problem: Blockrazor.org cannot be accessed; getting `503 Service Unavailable` when trying to access https://blockrazor.org

ping @gazhayes @anbud 

![img_ec219daacff5-1](https://user-images.githubusercontent.com/4476552/40499526-e054a704-5f8a-11e8-9ebc-53f2b7732774.jpeg)

**Comment by anbud** [comment]
I'll bring it back up in a sec.

**Comment by anbud** [comment]
The SSH is also not working currently, I'll try again later, but it may have to wait for @gazhayes.

**Comment by gazhayes** [comment]
Woops. Fixed.
