### ISSUE TITLE
Problem: paid contributors required for Emurgo

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1650]
Problem: Emurgo (https://emurgo.io) requires paid contributors to help build out some of their infrastructure. The development protocol and the stack for most things they build will be the same as Blockrazor (Meteor + C4). They have a LOT of stuff to build (e.g. Blockrazor x20), this will basically be an unlimited oppourtunity for the next 2 years, this is a well funded Blockchain group within the Cardano ecosystem - people who earn the trust of the Emurgo staff will not need any other freelance clients (or a full time job) for a long time.

If you wish to become a paid contributor for Emurgo, the first step is to watch the Emurgis repository (https://github.com/EmurgoHK/Emurgis) and start making comments or sending pull requests whenever you can.  Emurgo IT staff are watching the repository and will select people to bring on as paid contributors after seeing their pull requests and comments etc. There will be more repositories created over the coming weeks/months/years so it's also a good idea to look at the github organization itself periodically.

**Comment by AshHimself** [comment]
Great news.. so no timesheets on Emurgis until selected?

**Comment by gazhayes** [comment]
For that issue you are doing right now just add it to the blockrazor timesheet, but this is an exception, once hired 'officially' I or someone else will give you a new timesheet for Emurgo work.

**Comment by samuelralak** [comment]
@gazhayes thats very fine. sounds good to me

**Comment by geekyd** [comment]
@gazhayes Sounds great.

**Comment by anbud** [comment]
Agreed, it does sound great. :)

**Comment by gazhayes** [comment]
One more repo to watch: https://github.com/EmurgoHK/Emurpas/

**Comment by chamidu-supeshala** [comment]
Seems interesting for me also. I also will take a look :) :+1:
