### ISSUE TITLE
problem: [/] users online is always 0

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1651]
Problem: I see this even when logged in:

<img width="144" alt="screen shot 2018-05-25 at 12 43 08 pm" src="https://user-images.githubusercontent.com/8143945/40526468-4397199e-6019-11e8-867a-2e73a2d5f4c4.png">

**Comment by gazhayes** [comment]
The plot thickens: <img width="147" alt="screen shot 2018-05-26 at 9 18 24 am" src="https://user-images.githubusercontent.com/8143945/40571119-cc87db9c-60c5-11e8-8ce2-141e61a86f62.png">

**Comment by anbud** [comment]
@gazhayes, do you happen to remember if this was happening before switching to the now hosting solution (production meteor with load balancing)? As this works on localhost, I can only imagine that this info is stored in memory on each instance and the data gets messed up. Saving the data to a real mongodb collection will probably fix it.

**Comment by gazhayes** [comment]
Yeah now that I think about it, it did start when I moved servers.

That must be what's happening.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Should be fixed in #1667.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by gazhayes** [comment]
It's still -1 and 0 on production.

Is there anything I can do on the server to help with diagnostics?

**Comment by anbud** [comment]
It's quite possible that the data was corrupted. After cleaning the collection, it seems to work ok, I've tested out a couple of users and the counter was updated correctly every time.

Please try it out to see if the issue persists. :)

**Comment by anbud** [comment]
I've added a fix to prevent future data corruption in #1699.
