### ISSUE TITLE
Problem: cannot cancel 2FA login

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1663]
Problem: when 2FA is enabled, users cannot cancel their login (for example if they lost their code) and cannot view the site.

Solution: add a cancel button

**Comment by samuelralak** [comment]
@gazhayes I would also propose adding an alternative option that would allow users to verify and recover their accounts in the event that they loose their codes. This is subject to discussion though.

**Comment by samuelralak** [comment]
The cancel button would terminate the login process but users would still have no way to get their accounts back

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
@samuelralak, I agree, we should have some kind of a process that lets users recover accounts locked by losing 2fa codes. We have a list of 10 backup codes already, maybe there should be a way to somehow send them the backup list. Now, we shouldn't send it by email of course as that would defeat the purpose of 2fa, but we could possibly let them contact support or something.

As for the cancel button, it should just call `Meteor.logout()` if I'm not mistaken.

**Comment by samuelralak** [comment]
Yes, this is very correct 

> As for the cancel button, it should just call Meteor.logout() if I'm not mistaken.

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

fixed in [#1669](https://github.com/Blockrazor/blockrazor/pull/1669)
