### ISSUE TITLE
Problem: [/wallet] scientific figure displayed as wallet kzr balance

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1670]
Problem: When the kzr balance figure is too small, the scientific representation of the balance is displayed instead of a number.

<img width="258" alt="screen shot 2018-05-27 at 8 05 20 pm" src="https://user-images.githubusercontent.com/4476552/40590091-a42d5d74-6201-11e8-9b2e-c376cdcfba31.png">

**Comment by AshHimself** [comment]
I'll create a helper as part of #1671 which this ticket can make use of. Stay tuned.

**Comment by samuelralak** [comment]
[#1675](https://github.com/Blockrazor/blockrazor/pull/1675) should fix this one as well

**Comment by samuelralak** [comment]
@blockrazorbot label "done"
