### ISSUE TITLE
Problem: navbar balance displayed as scientific figure 

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1671]
Problem: The kzr balance on the navbar is displayed in a scientific format when the actual figure is too small. Logging this as a seperate issue simply because we need to keep UI/UX in mind for this one. We cannot render the actual balance because the navbar space is limited and we may end up breaking the UI.

Potential solution: I would propose showing the balance as `0.000` when balance is below a certain point or rounding off to the nearest `x` decimal places. Suggestions are welcomed for this one.

<img width="127" alt="screen shot 2018-05-27 at 8 05 01 pm" src="https://user-images.githubusercontent.com/4476552/40590174-387bcf8c-6203-11e8-874a-d801228005f7.png">

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@AshHimself you can reproduce this by creating a new account and answering a few ratings questions - basically anything that rewards you a little kzr

**Comment by gazhayes** [comment]
@AshHimself ah yeah I need to put drmongo on the new server.

**Comment by AshHimself** [comment]
Still can't replicate.. if you know how to replicate feel free take take the issue as no point me wasting time on it if you have a resolution.

**Comment by AshHimself** [comment]
@blockrazorbot unclaim

**Comment by samuelralak** [comment]
@sjmackenzie no worries mate. will take a look

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
fixed in [#1675](https://github.com/Blockrazor/blockrazor/pull/1675)
