### ISSUE TITLE
Problem: [/addcoin] hash algorithm invalid error

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1673]
Problem: the hash algorithm question reports an error even when there's no error.

<img width="316" alt="screen shot 2018-05-28 at 4 59 46 pm" src="https://user-images.githubusercontent.com/8143945/40606673-a5f4f792-6298-11e8-89e8-4eab22e27a45.png">

**Comment by AshHimself** [comment]
@gazhayes can you replicate this consistently?

**Comment by gazhayes** [comment]
Ah I didn't try, but I started with none of the initial boxes checked so try that.

**Comment by anbud** [comment]
It's in the new coin schema schema (/imports/api/coins/methods.js - Currencies.newCoinSchema) which takes most of the values from currencies schema (/imports/api/coins/currencies.js - Currencies.schema)

I'm on a mobile device, so paths may not be 100% accurate, but it's there somewhere. :)

**Comment by AshHimself** [comment]
@gazhayes - working for me. Try again after merging #1674

**Comment by anbud** [comment]
This also works for me as well. :)
