### ISSUE TITLE
Problem: UI layout is bad in some places after switching to full bootswatch

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1680]
Problem: it looks like we weren't actually using bootswatch properly before, but now that we are some of the UI looks weird.

Solution: seek and destroy weird layouts, misaligned stuff, whatever.

ping @geekyd this one is probably best suited to you.

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
Fixed in #1698 

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
