### ISSUE TITLE
Problem: currency detail page does not show many details

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#169]
Problem: All available data for a currency should be shown on the currency detail page (in a manner that is simple visually and from a UX/UI perspective.

Additional data will also be coming later so keep this in mind.

Just to be specific, the currency detail page is the /currency:xxxxxxxx route.

I have started using some tab type structure but this should not influence the decision making process about how to solve this one.

**Comment by anbud** [comment]
@AshHimself, are you already working on this?

**Comment by AshHimself** [comment]
Yes sir. Got a bit delayed on another ticket.

**Comment by AshHimself** [comment]
@gazhayes - Idea, the idea is for the community to make changes if data is incorrect or missing right? If data does not exist for a currency should we have a button visible to propose a change perhaps?

**Comment by gazhayes** [comment]
> If data does not exist for a currency should we have a button visible to propose a change perhaps?

Yes, exactly what I was thinking.

There's different 'standard data' for different types of currencies though. For now, just do the bare minimim and see what happens.

**Comment by AshHimself** [comment]
@gazhayes - Just created a PR with a basic table and created a few helpers to display a contribute button if data is null. A suggest is that instead of just going to currencyEdit:currency we actually do currencyEdit:currency/fieldBeingEdited. This way we can focus to that field and they can edit it right away.

**Comment by gazhayes** [comment]
> instead of just going to currencyEdit:currency we actually do currencyEdit:currency/fieldBeingEdited   

Yes I agree, that was my original intention/idea with the edit currency ticket.

**Comment by gazhayes** [comment]
#183
