### ISSUE TITLE
Problem: Most of the codebase expects user balance to be numerical

### ISSUE THREAD

**Issue by anbud** [Blockrazor/blockrazor#1694]
Problem: After #1675, user balance is stored as a string, which can cause issues as most of the codebase still expects that user balance is numerical. For example, `/add-problem` doesn't show available KZR balance as the helper breaks because it's not expecting a string (string doesn't have `toFixed` method).

Possible solution 1: Go through the codebase and fix helpers/methods/everything else that manipulate user balance.

Possible solution 2: Store user balance as it was stored before, as a numerical value, and format it on the client.

**Comment by gazhayes** [comment]
Solution 2 seems a lot more reasonable. A lot of messing around to do maths on strings everywhere in the codebase otherwise.

**Comment by geekyd** [comment]
Solution 2 seems the way to go here, we should keep any mathematically value numeric in the application.

**Comment by samuelralak** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
@samuelralak how's this one going?

**Comment by samuelralak** [comment]
I haven’t started on it yet. I intend on getting it resolved today.

**Comment by gazhayes** [comment]
Just to be clear, please don't rewrite the codebase to accept strings, just fix whatever requires it to be a string instead.

**Comment by samuelralak** [comment]
@blockrazorbot remove "in progress"

**Comment by samuelralak** [comment]
@blockrazorbot label "done"

**Comment by samuelralak** [comment]
@anbud #1745 reverses all changes made by #1675. This doesn't fix the `add-problem` krazor balance issue. Will a have fix for that in a different PR
