### ISSUE TITLE
Problem: add coin (next button link broke)

### ISSUE THREAD

**Issue by kriswormwood** [Blockrazor/blockrazor#1695]
Problem: the next button (step 2 going to step 3) does not respond - possible broken link. 

Solution: fix link or skip the steps and put them all on one page?

**Comment by anbud** [comment]
The next button will not respond if data is missing, so I'm guessing that something was missing, but the error was not properly displayed on the UI.

**Comment by gazhayes** [comment]
Will get proper UI testing happening to catch all these errors.
