### ISSUE TITLE
problem: Error with Litecoin detail page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1700]
Problem: `Exception in defer callback: Error: Meteor does not currently support objects other than ObjectID as ids` when trying to get to Litecoin's detail page.

What I'm concerned about is getting to the bottom of the underlying problem not Litecoin itself, but this doesn't seem to be happening with any other currencies.

**Comment by anbud** [comment]
This has been happening on local for me, but I thought it was only a local issue, as I couldn't find it in production until now.

It has to do something with exchanges, I'll get to the bottom of it.

@blockrazorbot claim

**Comment by anbud** [comment]
Fixed in #1701. `_id` was stored as an object, and not as a string which caused issues.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
