### ISSUE TITLE
Problem: misaligned modals in the application

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1702]
Problem: misaligned modals in the application.
![screen shot 2018-06-01 at 2 50 49 pm](https://user-images.githubusercontent.com/12807846/40834096-80130cea-65ad-11e8-93a5-d778493523e3.png)

Solution: centre align the modals through out the application.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
@chamidu-supeshala you're back! I haven't seen you for ages! You ok?

**Comment by chamidu-supeshala** [comment]
@gazhayes yes i was away in past week due to some of my research things. And now i'm back to work :) 
@blockrazorbot done
@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by gazhayes** [comment]
Have a look at #1650 (closed but still relevant for you)
