### ISSUE TITLE
Problem: user able to submit empty features on currency/x

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1704]
Problem: user able to submit empty features on currency/x

Solution: add validation to check if the feature is empty & show proper message to the user.

**Comment by gazhayes** [comment]
This should be using simpl-schema and validated method.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
I've just checked, you can't add an empty feature on production (the error is `Feature name is required`), but you can on localhost as the validation is turned off. `addFeature` method is a validated method and it uses a proper schema. So, I'm guessing this is not an issue, if I'm not missing something of course.

@blockrazorbot remove "in progress"
