### ISSUE TITLE
Problem: Blockrazor UI doesn't look very good

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1708]
Problem: Blockrazor UI doesn't look very good and isn't very consistent.

Solution: implement coreUI. However, we need to use our own colour schemes so this has to be taken into account (ease of changing colours globally).

ping @samuelralak

**Comment by AshHimself** [comment]
@samuelralak - you getting to this or want me to?

**Comment by AshHimself** [comment]
Fixed in #1711
@blockrazorbot label done
