### ISSUE TITLE
problem: menu is not functioning correctly

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1712]
Problem: menu is not functioning correctly

Solution: implement coreUI/bootstrap responsive tags to correctly open and close menu on small screens and open on large screens.

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
@chamidu-supeshala since @AshHimself has redone the UI with CoreUI it's probably a good idea to go through everything and hunt for problems and log them, there should be a lot of them.

**Comment by chamidu-supeshala** [comment]
@gazhayes yes, sure. i will check and log any issues exist.

**Comment by chamidu-supeshala** [comment]
fixed in #1715

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
