### ISSUE TITLE
Problem: Blockrazor footer need to be updated.

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1718]
Problem: currently the application footer taking huge space and there's no content.

![screenshot from 2018-06-12 22-06-41](https://user-images.githubusercontent.com/27463355/41304213-25ed825c-6e8d-11e8-8eac-be509ebb00b2.png)

Possible Solution: add appropriate footer text (ex: `Copyright {{year}} Blockrazor.org. All rights Reserved.`)

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "UI-UX"

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in # 1755
@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done
