### ISSUE TITLE
Problem: extra margin on page when side menu is hidden

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1721]
Problem: extra margin on page when side menu is hidden

Solution: Find the reason & fix it. 
![screen shot 2018-06-12 at 10 38 16 pm](https://user-images.githubusercontent.com/12807846/41305730-6f166d5a-6e91-11e8-8a09-456eee7ec442.png)
![screen shot 2018-06-12 at 10 38 28 pm](https://user-images.githubusercontent.com/12807846/41305731-6f4550ac-6e91-11e8-96cc-e685a09428cb.png)

**Comment by geekyd** [comment]
@blockrazorbot label "UI-UX"

**Comment by chamidu-supeshala** [comment]
Hey @geekyd, this issue, already fixed in #1715 (which is yet to merge)

**Comment by geekyd** [comment]
@chamidu-supeshala Thanks for the update.
