### ISSUE TITLE
Problem: [/new-problem] validation errors not shown

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1722]
Problem: when adding a new problem, feature request or question, the backend validation errors not displayed in UI. (only shown in console)

Solution: Highlight and Show` inline `error messages

**Comment by geekyd** [comment]
@blockrazorbot claim

**Comment by geekyd** [comment]
fixed #1739 
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
