### ISSUE TITLE
Problem: [/exchanges] page has large gap at top

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1724]
Problem: top margin/padding of [/exchanges] page is too large.
Solution: use same common class/margin/padding as other pages

@blockrazorbot label "UI-UX"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed #1733
@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by Ayanrocks** [comment]
If its done,you should close the issue
