### ISSUE TITLE
Problem: [/moderator/changedCurrencies/] console error when loading the page

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1730]
Problem: following error occurs when accessing 'proposed changes' moderator page

![screenshot from 2018-06-13 01-25-58](https://user-images.githubusercontent.com/27463355/41313930-dd845682-6ea8-11e8-98f9-6f97b921e685.png)

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed #1732
@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by Ayanrocks** [comment]
Close the issue
