### ISSUE TITLE
Problem: blockrazor.org server unreachable

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1740]
Problem: I cannot access blockrazor.org since yesterday and am honestly not certain if am the only one who is experiencing this. Am getting the following error message
```
This site can’t be reached
https://blockrazor.org/ is unreachable.
ERR_ADDRESS_UNREACHABLE
```
ping @gazhayes @anbud

**Comment by samuelralak** [comment]
awesome 👍

**Comment by Ayanrocks** [comment]
is it working now?

**Comment by samuelralak** [comment]
Just noticing this. Blockrazor.org is back up
