### ISSUE TITLE
Problem: [/login] Create an account link cannot be seen

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1741]
Problem: Create account link in login page is not visible.

Solution: change font color of link in login page

**Comment by MadanBhandari** [comment]
Isn't this same #1744 ?

**Comment by samuelralak** [comment]
same solution should apply for both pages

**Comment by MadanBhandari** [comment]
@blockrazorbot label "done"

**Comment by MadanBhandari** [comment]
@samuelralak  blockrazorbot isn't working or It takes time to update ?
