### ISSUE TITLE
Problem: [/sign up] Sign in link on isn't seen

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1742]
Problem: the sign in link on sign up page is not visible.

Solution: change font color of link.

**Comment by MadanBhandari** [comment]
@samuelralak are you working on this ? I wanna get back to this project and this is easiest to re-start :wink:

**Comment by samuelralak** [comment]
@MadanBhandari knock yourself out chief 👍

**Comment by MadanBhandari** [comment]
@blockrazorbot label done

**Comment by MadanBhandari** [comment]
@samuelralak Now we are using CoreUI right ? Anything I need to keep in mind ?

**Comment by samuelralak** [comment]
@MadanBhandari yes sir, thats correct. You just need to be familiar with the CoreUI elements `https://coreui.io/demo/#main.html` and before adding extra css rules, first confirm whether or not you can actually do it with the existing css provided by CoreUI.

**Comment by MadanBhandari** [comment]
@samuelralak Thanks !!! I will ask you, in case I need any help :)

**Comment by MadanBhandari** [comment]
@blockrazorbot label "done"
