### ISSUE TITLE
Problem : [/] Price doesn't have currency symbol and sometimes black

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#1748]
Solution : Add currency symbol before (or after) price. And show N/A (Not Available) in case pricing is not available.

**Comment by MadanBhandari** [comment]
@blockrazorbot label "UI-UX"

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1787
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
@blockrazorbot done

**Comment by MadanBhandari** [comment]
What about showing NA (Not Available) when price is not available instead of 0.00, 0.00 can be refereed as as 0 value (free).

And everything has price, I don't think price 0.00 make sense here. What you think ?

**Comment by AshHimself** [comment]
Makes sense to me... bit of an oversight on my side.
