### ISSUE TITLE
Problem: footer conatins core UI context instead of blockrazor

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1756]
Problem: footer conatins core UI context instead of blockrazor

![screen shot 2018-06-17 at 2 21 15 am](https://user-images.githubusercontent.com/12807846/41502348-711906ac-71d5-11e8-81df-8403d3611724.png)

Solution: remove context of core UI from the footer & add blockkrazor

**Comment by geekyd** [comment]
@blockrazorbot label "UI-UX"

**Comment by gazhayes** [comment]
Add: "The content of this page is owned by Blockrazor and Contributors. It is licensed under Creative Commons Attribution-ShareAlike 3.0 License"

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1763.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
