### ISSUE TITLE
Problem: same color used for problem & question in problems 

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1757]
Problem: same color used for problem & question in problems 

Solution: Use different colors for the badges in problems.

**Comment by geekyd** [comment]
@blockrazorbot label "UI-UX"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
fixed #1769
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
