### ISSUE TITLE
Problem: misaligned text in /profile page

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1758]
Problem: misaligned text in /profile page
![screen shot 2018-06-17 at 2 26 50 am](https://user-images.githubusercontent.com/12807846/41502374-0d6888ca-71d6-11e8-99c3-18636f1b7a20.png)

Solution: left align the text on all the tabs in /profile page

**Comment by geekyd** [comment]
@blockrazorbot label "UI-UX"

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1764.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
