### ISSUE TITLE
Problem: auction form not working in /currencyAuction

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1759]
Problem: auction form not working in /currencyAuction

Solution: Add bootstrap styles validations & make the form functional.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by Ayanrocks** [comment]
@blockrazorbot  remove label "in progress"

**Comment by Ayanrocks** [comment]
@blockrazorbot remove "in progress"

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
@blockrazorbot abandon

Unclaiming this one until I find a solution for #11.

**Comment by anbud** [comment]
On it again.

**Comment by anbud** [comment]
Fixed in #1807.

**Comment by Ayanrocks** [comment]
If its done, why not close the issue
