### ISSUE TITLE
Problem: no way to notify user of assigned problem

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1760]
Problem: no way to notify user of assigned problem. 

Solution: add a notification count to the get help section. 

Steps to reproduce:
- Visit get help
- Claim a problem

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1762.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by Ayanrocks** [comment]
Kindly close all issues marked done.
