### ISSUE TITLE
Need minor ui improvements v2

### ISSUE THREAD

**Issue by Ayanrocks** [Blockrazor/blockrazor#1767]
Need Minor UI improvements v2

**Comment by Ayanrocks** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
What's the specific problem?

**Comment by Ayanrocks** [comment]
The share button on side bar has an icon that is not showing.

**Comment by Ayanrocks** [comment]
@blockrazorbot label "done"

**Comment by gazhayes** [comment]
You have to log an issue describing the actual problem, and your pull request has to contain a valid patch.

**Comment by Ayanrocks** [comment]
I have logged this issue and will open another one for that additional problem and my pr has a patch

**Comment by gazhayes** [comment]
The PR did not contain a valid patch.
