### ISSUE TITLE
Problem: elements on some pages are misaligned

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1794]
Problem: elements on some pages are misaligned
![screen shot 2018-07-10 at 11 19 25 pm](https://user-images.githubusercontent.com/12807846/42530403-b32d8212-849e-11e8-946b-336882159675.png)
![screen shot 2018-07-10 at 11 20 31 pm](https://user-images.githubusercontent.com/12807846/42530405-b36ab862-849e-11e8-827b-9d13ec673a49.png)

Solution: make sure that the design is consistent & properly aligned.

**Comment by Ayanrocks** [comment]
is this fixed?
