### ISSUE TITLE
problem: sometimes it hard to know where you are on the site

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1796]
Problem:  sometimes it hard to know where you are on the site

Solution: add the coreUI breadcrumbs element into the layout.

**Comment by samuelralak** [comment]
Can we deprecate page headers in favor of this?

**Comment by AshHimself** [comment]
I think so mate.. looks a lot nicer

**Comment by samuelralak** [comment]
I totally agree

**Comment by gazhayes** [comment]
Yep I agree, at the very least it's worth a try.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@Fixed in #1804
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
@blockrazorbot done
