### ISSUE TITLE
problem: no explanation on some pages

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1798]
Problem: some pages have no explanation on what the page is and its purpose. e.g. exchanges

Solution: not sure, would need some thinking as a team.

**Comment by gazhayes** [comment]
These should be logged individually to make it easier to discuss and fix.

**Comment by MadanBhandari** [comment]
What about adding just few lines to describe and link to FAQs section for detailed information on that particular topic ?
