### ISSUE TITLE
problem: bad UX in the menu

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1799]
Problem: For an unregistered user the menu is confusing and complex. 

Solution: The menu needs a little cleanup and restructured to offer a better UX. Not sure entirely but some ideas are to; 
- Fix the drop down to be the coreUI theme
- Move FAQ to possibly the footer
- Hide any other menu items that shouldn't be visible before logging in.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes did a first pass on this. I think its a lot better. I think what's missing now is the site explanation to really sell to first users on what blockrazer is. Its like you need a landing page prior to the actual site. Let's use segment as an example;

First time will see this, straight away you know what the site is and its purpose.
![image](https://user-images.githubusercontent.com/148682/42632124-c8080380-860e-11e8-82b9-bb787beeffe5.png)

Then when you log in you get all the funky user menus and even optional user tips to let people know what things are. 

![image](https://user-images.githubusercontent.com/148682/42632179-f81ff47e-860e-11e8-97f9-88040d6e9bcb.png)


Food for thought :)

**Comment by gazhayes** [comment]
Yeah I agree, its really not clear what it is right now

**Comment by gazhayes** [comment]
@AshHimself do you remember if you sent a PR for this one?

**Comment by AshHimself** [comment]
Nah sorry mate been out of country on third world internet. I'm back online from tomorrow. As for a PR, I think it needs a little discussion before I dive into it. My original thoughts was to have the home page changed a lot to advertise what blockrazor is in lamens terms as apposed to just giving the user mass amounts of graphs on the get go. 

What are your thoughts?

**Comment by gazhayes** [comment]
Yeah I agree with that approach. I was thinking of using a modal but people automatically close those things in general so a more traditional landing page might be needed. What do you think?

**Comment by AshHimself** [comment]
I'm thinking more like say... https://tron.network/ (crappy example but you get my idea of RIGHT IN YOUR FACE EXAMPLE OF WHAT BLOCKRAZOR DOES)

Good starting point in bootstrap (https://blackrockdigital.github.io/startbootstrap-heroic-features/)

Could have say a menu option "Explore" to then view some charts without signing up etc.

**Comment by AshHimself** [comment]
@gazhayes - Thoughts? Want me to make a first pass at something and go from there?

**Comment by gazhayes** [comment]
Yeah why not ;)

BTW I pinged on on the emurgolance repo but *you* should use emurgolance.org from august 1st  for tracking.

**Comment by AshHimself** [comment]
you got it mate.. is that for everything or just emurgo related?

**Comment by gazhayes** [comment]
For everything ;)
