### ISSUE TITLE
Problem: Blank screen when developing on Windows

### ISSUE THREAD

**Issue by anbud** [Blockrazor/blockrazor#1803]
Problem: When building Blockrazor locally on the Windows platform, I only get a blank screen when I try to open `localhost:3000`. 

I thought it was related to dynamic imports, as it would show the following error after a minute or so:
`http.js?hash=8a08f913bc9ee45ce8aae2cd9cd201e542e61e68:231 POST http://localhost:3000/__meteor__/dynamic-import/fetch 0 ()
http.js?hash=8a08f913bc9ee45ce8aae2cd9cd201e542e61e68:172 Uncaught (in promise) Error: network
modules-runtime.js?hash=d9c2212c27b8b694a403c725c46ea2897298b66e:241 Uncaught (in promise) Error: Cannot find module '/imports/ui/components/compatability/index.js'
modules-runtime.js?hash=d9c2212c27b8b694a403c725c46ea2897298b66e:241 Uncaught (in promise) Error: Cannot find module '/node_modules/bootstrap/dist/js/bootstrap.js'
modules-runtime.js?hash=d9c2212c27b8b694a403c725c46ea2897298b66e:241 Uncaught (in promise) Error: Cannot find module '/imports/startup/client/testingCollectionGlobals.js'
modules-runtime.js?hash=d9c2212c27b8b694a403c725c46ea2897298b66e:241 Uncaught (in promise) Error: Cannot find module '/node_modules/moment/moment.js'
modules-runtime.js?hash=d9c2212c27b8b694a403c725c46ea2897298b66e:241 Uncaught (in promise) Error: Cannot find module '/imports/api/indexDB.js'`

I've tried removing dynamic imports altogether, the blank screen persists, but the error disappears. I've also tried updating Meteor, updating NPM packages, resetting the project, but nothing helped so far. Google wasn't helpful either.

Since production is working correctly, I believe this is only Windows-related. If there are any developers working on Windows here, have you experienced this issue, and, if so, how did you fix it?

**Comment by AshHimself** [comment]
Just you mate... all clear skies and sun shine in OSX.

**Comment by anbud** [comment]
I wonder why it's only happening on this project, while others are working fine.

I'll have to try it on linux.

**Comment by anbud** [comment]
Got it working on WSL (Windows subsystem for Linux), but I'll leave this one open if somebody stumbles upon a solution.

**Comment by AshHimself** [comment]
I had no idea WSL even existed until you just told me :)
