### ISSUE TITLE
problem: bad UX on homepage for filter

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1805]
problem: bad UX on homepage for filter

solution: add the filter to the new header per the coreUI demo site to clear up the screen and make it completely obvious that filtering is possible therefore offer more value to the user.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes our bot broken?

**Comment by AshHimself** [comment]
@Fixed in #1806
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
@blockrazorbot done

**Comment by MadanBhandari** [comment]
Is this same #1775 right ?

Sorry, I didn't get to worked on that.
