### ISSUE TITLE
Rough Transitions on Homepage Icons

### ISSUE THREAD

**Issue by Ayanrocks** [Blockrazor/blockrazor#1814]
Problem: The icons in the homepage have rough transitions and are not smooth
Solution: Add transition property to the icons with ease-in-out.

**Comment by Ayanrocks** [comment]
@blockrazorbot claim

**Comment by Ayanrocks** [comment]
@blockrazorbot label "UI-UX"

**Comment by Ayanrocks** [comment]
@blockrazorbot label "done"

**Comment by Ayanrocks** [comment]
Isn't blocrazorbot working? @gazhayes

**Comment by anbud** [comment]
Don't worry about it, it'll start working again soon, @gazhayes needs to move it to a new server.
