### ISSUE TITLE
problem: blockrazor is not multilingual

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1818]
Problem: blockrazor is not multilingual

Solution: not sure, hoping for a discussion ;)

**Comment by anbud** [comment]
[TAPi18n](https://github.com/TAPevents/tap-i18n), a key based translation engine for meteor, could be a perfect solution here. It's simple to use and implement, it uses json or yaml for translation files.

**Comment by gazhayes** [comment]
Yeah that's probably the best way to go. Feel like doing it?

**Comment by AshHimself** [comment]
Worth breaking this up by pages ? Fair bit of hard coding right ?

**Comment by gazhayes** [comment]
Yeah, good idea. I guess do one page first, e.g. "currency detail page is not multilingual" and use that as a standard for people to follow when doing other pages.

**Comment by anbud** [comment]
Sure thing, I'll implement it on a couple of pages.

**Comment by anbud** [comment]
Implementation of TAPi18n on the first couple of pages (landing, home, and shared components (header, footer, ...)) is done in #1819.

As you can see, translation files have to be in the `i18n` folder and they have to have the `.i18n.json` or `.i18n.yaml` extension for JSON and YAML respectively. Before the extension is the language code (`en` for English, `fr` for French, `sr` for Serbian and so on). (e.g. valid translation file name is `home.en.i18n.json`)

When you change strings to translation keys in templates, make sure that you scope translation keys properly (you can see my scoping in this PR) as you can run into issues if translation keys happen to be the same in multiple files. Using translations is as easy as using `{{_ "translation_key"}}` in templates. Although it's not very recommended, you can also use HTML in translation strings, but then you have to use three { (`{{{_ "translation_key"}}}`) in templates.

**Comment by anbud** [comment]
I believe that individual folders in `/imports/ui/pages` are a nice way to divide the multilingual conversion work. So, here's the list of what needs to be converted to TAPi18n:

- [ ] activityLog          
- [ ] addCoin              
- [ ] addHashpower           
- [ ] allHashaverage         
- [ ] allHashpower           
- [ ] auctions               
- [ ] bounties               
- [ ] codebase               
- [ ] communities            
- [ ] compareCurrencies      
- [ ] currencyDetail         
- [ ] developers             
- [ ] distribution           
- [ ] editProfile            
- [ ] exchanges              
- [ ] faq                    
- [ ] landingpage            
- [ ] moderator                  
- [ ] prices                 
- [ ] problems               
- [ ] ratings                
- [ ] returnedCurrencies     
- [ ] signin                 
- [ ] signup                 
- [ ] suspended              
- [ ] transactions           
- [ ] userPendingCurrencies  
- [ ] userProfile            
- [ ] wallet

Please make sure to convert any literal strings in `.js` files as well. You can use `TAPi18n.__('key')` there.
Feel free to open a new issue (*problem: x is not multilingual*) when you start working on a given section and mark it as done here when you're done. :)
