### ISSUE TITLE
Problem: editing one data point for a currency forces user to use a more confusing form than necessary

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#183]
Problem: When editing or adding a data point on a currency page it directs a user to edit *all* the details for that currency.

**Comment by AshHimself** [comment]
Problem: Found a bug where the edit button is displayed on an attribute which should not be changable. e.g. gitUpdate, gitCommits.

Solution: Remove helper from these attributes and create a secondary helper which simply displays '-' instead of the propose change button.

**Comment by AshHimself** [comment]
Resolved in #195
