### ISSUE TITLE
Problem: currency logo image extension not always correct

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#184]
Problem: when a users adds a currency logo in jpeg format (for example) the filename is saved as .jpeg, however when the image is used the .jpg extension is called instead of .jpeg

**Comment by AshHimself** [comment]
@gazhayes I can't replicate this. Was there a certain file you were using that might have a weird MIME type? Can you share it so I can check it out and try catch the error? I tried a bunch of files and all were saved in JPEG on the server and in the collection.

**Comment by gazhayes** [comment]
I had 'wallet image' in the original description but I actually meant 'currency logo'.

Have a look at https://blockrazor.org/currency/test

It looks for https://blockrazor.org/static/images/coin/1b1cab96ee35a8735b6403dda3147bff.jpg but should actually look for https://blockrazor.org/static/images/coin/1b1cab96ee35a8735b6403dda3147bff.jpeg

(or save as .jpg instead of .jpeg)

**Comment by AshHimself** [comment]
Ok I eventually found the cause of this issue after debugging for a while. The server is using the mime-type library to figure out the extension from the mime-type (best way to do it) whereas on the client it was grabbing the extension from the users machine. e.g. you could rename a PNG to JPG and it would use JPG (wrong way to do it). 

The mime-types package is now being used on both server and client which is the best and most secure way to do it. PR inbound.
