### ISSUE TITLE
problem: [/hashpower] bad UI-UX

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#1844]
Problem: The hashpower isn't styled and therefore looks too plain, the `Add new data`, `Averages` and `Flagged data` look more like plain texts than actual links

**Comment by MadanBhandari** [comment]
@samuelralak are you working on this ?

**Comment by samuelralak** [comment]
yes I am

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

done in #1917
