### ISSUE TITLE
Adding image to the add coin bounty gives error 500

### ISSUE THREAD

**Issue by Ayanrocks** [Blockrazor/blockrazor#1845]
Problem: In step 5 of the add coin bounty page, while uploading image gives internal server error 500

Solution: The image is not uploading I guess, so need to change the code for image uploading.

**Comment by gazhayes** [comment]
this is probably an issue on the production server itself, I will check it out

**Comment by Ayanrocks** [comment]
still working @gazhayes  in this issue?

**Comment by gazhayes** [comment]
Yep, I'm slow ;)
