### ISSUE TITLE
Problem : Home page unnecessary horizontal scroll

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#1849]
Problem : Home page for not logged in users has unnecessary horizontal scroll

Solution : Figure out what cause that scroll, that should be minor css issue and Fix

**Comment by MadanBhandari** [comment]
@blockrazorbot label "UI-UX"

**Comment by MadanBhandari** [comment]
This is Fixed, Please check and close.

**Comment by Ayanrocks** [comment]
Please close the issue, it's fixed
