### ISSUE TITLE
Problem : Breadcrumbs are not clickable

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#1851]
Problem : Breadcrumbs are not clickable
Solution : They should be clickable, make breadcrumb `<a> `elements and pass `url` on `href`.

**Comment by anbud** [comment]
I'll add multilingual support for breadcrumbs as a part of this issue as well.

**Comment by anbud** [comment]
Done in #1855.

@emurgobot label "done"
@emurgobot remove "in progress"
