### ISSUE TITLE
Problem : No reset password option

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#1857]
Problem : Password reset option not available
Solution : Add password reset link in `/login` page

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@gazhayes : We need MAIL_URL to send, password reset link, do we already have any email services or any free/open source options ?

**Comment by Ayanrocks** [comment]
How about sendgrid?

**Comment by anbud** [comment]
I agree, sendgrid is perfectly fine.

**Comment by MadanBhandari** [comment]
Okay, I will update with sendgrid.

**Comment by MadanBhandari** [comment]
Currently I have updated with free account on Sendgrid.

**Sendgrid Details**
Username : blockrazor
Password : blockrazor123

Please check and close this issue.

**Comment by AshHimself** [comment]
Team, I understand we need to be 'open' but we should probably change ^^ password so people don't tamper with the account haha.

**Comment by MadanBhandari** [comment]
User Names and passwords, needs to be moved to `settings.json` file once we got our official account.
