### ISSUE TITLE
problem: UI on mobile is broken

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1860]
Problem: UI on mobile is broken, BlockRazor has had some major changes recently in the UI but testing the mobile UI has not been factored in.

Solution: Investigate the changes and update the UI to look professional again on mobile.

![image](https://user-images.githubusercontent.com/148682/45252071-9a8fc080-b383-11e8-8ba6-adf9f61b7bfc.png)

**Comment by AshHimself** [comment]
Ok, its looking a lot better already. @gazhayes the images in production look to be broken still but working on my local. Did we even get to the route cause of this? Do I need to upload any code locally in my PR? 

I have moved the search to a modal on 'mobile' only so the header isn't stressed for space. 

![image](https://user-images.githubusercontent.com/148682/45253159-26f6af00-b395-11e8-9962-c7b2059ae3b7.png)

**Comment by AshHimself** [comment]
Fixed in #1862
@emurgobot label "done"
@emurgobot done

**Comment by AshHimself** [comment]
@gazhayes I think our bot is broken again :(

**Comment by anbud** [comment]
@AshHimself, he's just moody, sometimes he wants to respond, sometimes he doesn't. :D 

On the serious side, he's online, but he's returning 500 error for most requests, there's probably an issue with underlying zulipbot.
@gazhayes, email me server details and I'll fix him up, I think I know what's going on.
