### ISSUE TITLE
problem: bad UX for language choice/selection

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1861]
Problem: bad UX for language choice/selection

Solution: Most sites these days don't leave it to the user to select the language, putting this one out there to the team. Why don't we check the browser language settings and if its not english we prompt a modal? I only pursue this as our nav bars real estate is hot property and we don't have room for another button nor do I think we should. I did some research into this whilst fixing the UI in #1860 

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages

@anbud @samuelralak  @gazhayes

**Comment by anbud** [comment]
I agree, the switcher up there is more of a temporary solution until we decide what's the best UX. 

We can detect user's language preference without an issue, and modal should be perfectly fine for choosing a language if it's not English. :)

**Comment by AshHimself** [comment]
I think this is the approach 'most' websites take. The only other solution is to pass the users IP address through a IP address lookup service and suggest a language but to me this is more phase 3 and this approach should be 100% suitable for now. 

I'm cleaning up the header UI and everything now as part of another ticket so makes sense for me to take this one unless others have any objections?

**Comment by anbud** [comment]
Sure thing, go for it. :)

**Comment by AshHimself** [comment]
Fixed in #1868
@emurgobot label "done"
@emurgobot done
