### ISSUE TITLE
Problem: something weird happening with graphdata collection 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#187]
Problem: Something weird is going on with the graphdata collection (which then breaks the UI/radar chart).

https://i.imgur.com/uMw13jf.png

**Comment by gazhayes** [comment]
While you're looking at that, can you make graphdata populate with minimum based on the real minimum from `currencies` collection, I made it use 400 as the lowest ELO but it can actually be lower in some situations. The problem is that the radar chart should end up displaying the correct 'spread' but it isn't.

**Comment by anbud** [comment]
Sure thing, I'm on it.

**Comment by anbud** [comment]
Fixed in #188. About the min value, it's generated from the currency collection (`_.min(allRatings)`), but, currently, there's not enough data for the ELO ranking to go under 400.
