### ISSUE TITLE
problem: bad performance with site

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1873]
problem: bad performance with site, its loading really slow for me. Loading a currency on my local instance is taking like 15-17 seconds.

Solution:  Ideally I would get Kadira going and see where its performing badly but I think we can all provide some input.

**Comment by Ayanrocks** [comment]
Changing from blaze to react can fix it with added ssr.

**Comment by gazhayes** [comment]
When did this change for you?

**Comment by AshHimself** [comment]
@gazhayes the speed? If so, then i'd say its been getting gradually slower and in the last month or so. Is it just me? or is it fast for everyone else. 

The currency view page does have A LOT of DOM elements and Blaze just craps itself with too many DOM elements.

**Comment by gazhayes** [comment]
Kadira to the rescue methinks

**Comment by AshHimself** [comment]
:) https://medium.com/@foodfitnesscode/setting-up-kadira-on-a-ubuntu-16-04-server-part-1-a821cdddd1e6

**Comment by gazhayes** [comment]
guess I better do it, unless someone else volunteers

**Comment by anbud** [comment]
I'm not sure what's different, but it still takes about 3-4 seconds to load a currency on a local server for me. But, Kadira will help us anyway. If you haven't started working on it @gazhayes, I can do it. :)

**Comment by gazhayes** [comment]
@anbud you want me to give you a fresh ububtu server to work with?

**Comment by AshHimself** [comment]
@gazhayes not sure if the box is ready but I can get the ball moving if it is.

**Comment by gazhayes** [comment]
I can have her fired up in an hour.

**Comment by AshHimself** [comment]
How'd yah get on mate? @gazhayes

**Comment by gazhayes** [comment]
oops: gareth@58.152.37.119
password sent by email

**Comment by samuelralak** [comment]
there’s been little change in regards to performance on my end, though am
assuming that the situation will change as blockrazor grows. good thing
this came up now

**Comment by AshHimself** [comment]
@anbud @gazhayes - I have Kadira running but getting some CORS issues which is stopping data being sent to the server. Anyone have experiance in this? I can keep looking but obviously looking for the fastest path to resolution :) 

http://58.152.37.119:4000/
admin@gmail.com
admin

**Comment by anbud** [comment]
Change this [line](https://github.com/kadira-open/kadira-server/blob/74a7fa8ca4f8f90d2ad0e35a42a8997152619861/kadira-engine/lib/utils.js#L11) to `'Access-Control-Allow-Origin': '*',`, restart the server and it'll probably fix the issue.

**Comment by AshHimself** [comment]
Let me have a look, I’m using a docket image so not sure I can just change
it easily ?

**Comment by AshHimself** [comment]
@anbud i've resolved this CORS issue, but i'm just getting NO data sent to Kadira :/

**Comment by anbud** [comment]
Hmm, yeah, email me the server details and I'll take a look what's happening. :)

**Comment by anbud** [comment]
I spent quite some time looking for a solution and it appears that it was as simple as adding `?replicaSet=kadira` to docker-compose.yml file. The UI and the engine were using different mongodb instances hence the discrepancies between data. 

It's fixed now, and in #1881 I've connected Blockrazor to our Kadira instance. It seems to be getting the correct data as far as I've tested it locally.

**Comment by AshHimself** [comment]
@anbud - nice work mate! 

Can you upgrade the account as well? I would but i'm traveling right now.

**Comment by anbud** [comment]
Sure thing. :)

**Comment by anbud** [comment]
Upgraded.

**Comment by gazhayes** [comment]
Closing this as Kadira is up, performance related issues can be logged separately.
