### ISSUE TITLE
problem: kadira requests are being blocked

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1887]
Problem: requests from/to kadira are being blocked because it's not using ssl.

**Comment by anbud** [comment]
Hmm, could you point a domain to the IP where Kadira is? 

Letsencrypt can't generate valid SSL certificates for an IP address, it needs a valid domain.

**Comment by gazhayes** [comment]
Ah yeah, will do that asap

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
@emurgobot abandon

**Comment by MadanBhandari** [comment]
Is this the reason for failed build ?

**Comment by anbud** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
> Hmm, could you point a domain to the IP where Kadira is?

Done. kadira.emurgolance.org

**Comment by anbud** [comment]
Thanks. I'll take care of it from here.

**Comment by anbud** [comment]
Done in #1957.

@emurgobot label "done"
@emurgobot remove "in progress"
