### ISSUE TITLE
problem: exchanges showing GUID resulting in bad UX

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1899]
Problem: exchanges showing GUID resulting in bad UX
![image](https://user-images.githubusercontent.com/148682/45402118-52301580-b697-11e8-88f4-f2e533dc5208.png)

Solution: guessing this should be showing the actual exchange name

**Comment by MadanBhandari** [comment]
Does this still exist ?

This is working as expected with me (local and online both).

**Comment by anbud** [comment]
This one is working for me as well, your data is probably old, old exchanges were randomly generated with random names that look like ids.

**Comment by gazhayes** [comment]
@AshHimself it's just legacy data, try using the latest dump from production.
