### ISSUE TITLE
Problem: missing page to approve users as developers

### ISSUE THREAD

**Issue by geekyd** [Blockrazor/blockrazor#1925]
Problem: missing page to approve users as developers

Solution: Enable moderator to approve/reject a user as a developer

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by anbud** [comment]
There's a page for this already (I believe it's/developers), the original idea was that other developers can approve developers.

**Comment by geekyd** [comment]
@anbud Yes the page exists but there is no way to reach the page currently. This will not allow users to complete the bounties for rating the currencies. I checked the page there is no listed pending approval on the page but there are some in the DB.

I think the idea of other developers approving is good. We should implement voting instead here just like we do for moderators.

@gazhayes What are your thoughts on this?

**Comment by gazhayes** [comment]
solved
