### ISSUE TITLE
problem: weird scroll length on mobile

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1929]
problem: when scrolling (any route) on mobile it scrolls a few pixels the locks, you need to lift up your finger and restart scrolling to continue scrolling down the page.

this happens at the very top and very bottom of the page.

**Comment by AshHimself** [comment]
@emurgobot claim 

leme take a looksy

**Comment by AshHimself** [comment]
@gazhayes - this was a super weird issue to fix (I think at least for me) the sticky footers fixed height was causing two scroll bars. I had to slowly remove each dom element till I found the culprit :/

Fixed in #1947
@emurgobot label "done"
@emurgobot done

**Comment by gazhayes** [comment]
Yeah I know the feeling, spent 6 hours once on an off-by-one error.
