### ISSUE TITLE
Problem: home route UX does not show enough scope

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#193]
Problem: the home route (blockrazor.org/) requires a lot of scrolling through currencies, it is not easy on the brain or the eye. As Blockrazor becomes populated with data, there will be 2000+ currencies in the database. Users should immediately understand when seeing the home route that *all* the currencies and blockchain projects are here.

Possible solution: rework the UX to look something like this (maybe):
 ![example](https://i.imgur.com/7tIhDaR.png)

**Comment by MadanBhandari** [comment]
What about the rest of info (like the Good, Bad etc) ? and I would I also suggest the navigation menu should be collapsible.

**Comment by MadanBhandari** [comment]
![blockrazor](https://user-images.githubusercontent.com/6429311/36606252-2f7353dc-18e9-11e8-94c4-6322703fd691.png)

Here is my solution

**Comment by gazhayes** [comment]
> I would I also suggest the navigation menu should be collapsible.   

I completely agree.

Your layout looks good. The only problem is that the most important graph for users to see quickly is the radar chart (the orange one), not the coin distribution chart.

> What about the rest of info (like the Good, Bad etc)

You can play around with it, but I think the smaller the tiles are, the better. Users can aways click in to each one to get the rest of the data but they need a quick way to view and filter through currencies on the home route.

**Comment by MadanBhandari** [comment]
> Your layout looks good. The only problem is that the most important graph for users to see quickly is the radar chart (the orange one), not the coin distribution chart.

This is done.

**Quick question :** Can I use Min Premine for Premine Greater Than and Min Circulation for Circulating Greater Than ? or can you suggest any shorten term for these search fields ?

**Comment by gazhayes** [comment]
> Can I use Min Premine for Premine Greater Than and Min Circulation for Circulating Greater Than ? or can you suggest any shorten term for these search fields ?

You can try and we'll see what it looks like. If it's no good it's not hard to change.

**Comment by gazhayes** [comment]
@MadanBhandari how are you going with this one?

**Comment by MadanBhandari** [comment]
@gazhayes I am working on this, will complete by this weekend, homepage alongwith top + side navigation. Side Navigation will be collapsible and common to all inner pages

**Comment by AshHimself** [comment]
@gazhayes - interested to know how these merges of multiple UI components (possible frameworks) will handle each other.

**Comment by gazhayes** [comment]
@AshHimself ultimately we'll go one way or another (one will reign supreme).

**Comment by MadanBhandari** [comment]
**More Improvements**
 1. Side + Top Navigation always fixed
Side Navigation Closed
![nav-close](https://user-images.githubusercontent.com/6429311/36943310-3be2eafe-1fad-11e8-8448-9b5fd8610b54.png)

Side Navigation Closed
![nav-open](https://user-images.githubusercontent.com/6429311/36943315-4eca8cc6-1fad-11e8-8ea6-be1eeed500ef.png)

2. Make Find/Filter single search bar and move to top navigation, which will also always fixed to top
![search-bar](https://user-images.githubusercontent.com/6429311/36943363-4869df70-1fae-11e8-865e-57a8dc8c6bd0.png)

**Comment by gazhayes** [comment]
Remember to add your name to the authors file with your next pull request.

**Comment by aamanatullah** [comment]
Hi, I want to start on this. Is there end date to this opening?

**Comment by gazhayes** [comment]
This one is already being worked on, but you can find something else to work on or even create your own issue.
