### ISSUE TITLE
problem: existing users are directed to landing page instead of home page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1943]
problem: existing (logged in) users are directed to landing page instead of home page. This is unnecessarily annoying for people who are already 'sold' enough to have created an account. 

<img width="1070" alt="screen shot 2018-09-16 at 11 23 49 am" src="https://user-images.githubusercontent.com/8143945/45592544-18b31f00-b9a3-11e8-89ea-446b1ba5735f.png">

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Fixed in #1949
@emurgobot label "done"
@emurgobot done
