### ISSUE TITLE
problem: search stats displayed always

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#1946]
problem: search stats displayed always even when a search is not in progress. I have commented it out but needs to be worked into the new UX.

Solution: only display search stats when search inprogress

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Someone can take this i'm offline for a day or so and do not want to hold up the project @emurgobot unclaim

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Fixed in #1973

@emurgobot done
@emurgobot label "done"
