### ISSUE TITLE
problem: breadcrumbs do not show what currency you are looking at

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1950]
Problem: 
<img width="419" alt="screen shot 2018-09-16 at 9 18 01 pm" src="https://user-images.githubusercontent.com/8143945/45596901-17f7a880-b9f6-11e8-9200-9b16dc8744a6.png">

**Comment by samuelralak** [comment]
@emurgobot label "done"

done in #1952
