### ISSUE TITLE
problem: total registered users not shown

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1951]
Problem: only the number of online users is shown but not the total number of registered users.
<img width="169" alt="screen shot 2018-09-16 at 9 19 10 pm" src="https://user-images.githubusercontent.com/8143945/45596910-3fe70c00-b9f6-11e8-8fbc-19e0a6036d20.png">

Solution: I guess display online users as a fraction (e.g. 5/80), people will probably get it

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot label "done"
@emurgobot remove "in progress"

done in #1953
