### ISSUE TITLE
problem: incorrect number of total users

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1959]
Problem: there are ~80 registered users, only 1 displayed

<img width="137" alt="screen shot 2018-09-17 at 9 33 07 am" src="https://user-images.githubusercontent.com/8143945/45603242-c9c9c000-ba5c-11e8-908a-a57b8495ead1.png">

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@gazhayes - This isn't a DB issue or something is it? I'm getting this locally;


![image](https://user-images.githubusercontent.com/148682/45611171-06171380-ba91-11e8-9e41-a9707d195723.png)

**Comment by AshHimself** [comment]
For some reason production isn't subscribing to all users collection where it is locally :/

**Comment by AshHimself** [comment]
Fixed in #1961
@emurgobot label "done"
@emurgobot done
