### ISSUE TITLE
problem: total currencies is incorrect

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1963]
Problem: total currencies is incorrect
<img width="193" alt="screen shot 2018-09-17 at 8 01 42 pm" src="https://user-images.githubusercontent.com/8143945/45621863-9155d080-bab4-11e8-82b3-a1e91f21704b.png">

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #1966.

@emurgobot done
