### ISSUE TITLE
problem: people who haven't created accounts might think blockrazor is inactive

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1964]
problem: people who haven't created accounts might think blockrazor is inactive

solution: add some site metrics to the landing page thing. suggestions: active + total users, signups this month, comments in the last month (this should obviously be obtained using a cron job to update something in a collection already used by that page rather than counting all the comments. If it's more than half an hour of work it's probably better to just leave this metric out for now.)

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #1965.

@emurgobot done
