### ISSUE TITLE
problem: some data cannot be public

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1968]
Problem: blockrazor needs to be totally transparent and open, but there are sometimes things that cannot be made public, such as passwords to third party services, server ssh credentials, etc. The problem is that going forward, I am a single point of failure if I'm storing all this data myself and no one else has access to it.

Solution: this is the best I've come up with so far: place an encrypted file stored in the source code which can easily be updated at any time through git. A deadman switch triggers a mongo insert with the decryption key. If a decryption key is found in the database, a vote is initiated allowing the community to vote for who the keys should go to.

**Comment by anbud** [comment]
I like this one, and the approach is perfectly fine. 
@emurgobot claim

Just one question about the deadman switch, do you have a suggestion what would it be? For example, it could be failure to login in, let's say, 14 days, failure to respond to a notification or an email, failure to enter a code of some sort every now and then or something similar.

**Comment by anbud** [comment]
You're right, it would be better if it's independent. Ok, I'll start working on the voting system.

**Comment by anbud** [comment]
Done in #1971.

Deadman switch should insert a record looking like this:
```
{
   decryptionKey: 'key'
}
```

to `encryption` collection and it'll trigger the voting system. It uses a cron job to check whether the switch was triggered every hour.

@emurgobot done
