### ISSUE TITLE
problem: incorrect image directory used in codebase

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1969]
Problem: the image directory used for uploaded images is now incorrect.

solution: update the codebase

It should now be:
/home/gareth/blockrazor_assets/static/images

All queries for /images are sent to a separate node instance serving the images in the above directory. 

This also means you cannot put images in /public/images in Meteor, anything in there should be moved to /public/codebase_images (or something) and then the codebase needs to be updated for these images.

Just to make it more clear: 
Be careful with any use of find and replace, dynamic (user uploaded) images are in /images which is the same location for static images in the /public/images directory (hence the need to change it to /public/codebase_images to differentiate this folder as containing images that can be updated using git.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Fixed in #1977. This should also fix #1681, #1808, #1838 and #1845.

@emurgobot done
