### ISSUE TITLE
problem: related github repos not considered

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1972]
Problem: for each blockchain project, there are usually people working on their own extensions etc. These are generally found on github. Blockrazor does not take these projects into account when providing the user with data.

solution:
use the github search API to populate a collection with relevant data. E.g search for "monero" and then for each result store:
html_url
fork
created_at
updated_at
stargazers_count
watchers_count
language
forks_count

github only supports 10 queries a second, this should be taken into account when constructing the cron job.

The results of this for each currency need to then be rendered in some meaningful way on the currency page. 

ping @anbud I'm guessing this one is for you.

**Comment by anbud** [comment]
Yap, I'm taking it.

@emurgobot claim

**Comment by anbud** [comment]
Done in #1976.

@emurgobot done
