### ISSUE TITLE
problem: no IP whitelist for banning system

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1978]
Problem: due to the use of reverse proxies etc, sometimes 127.0.0.1 or some other local addresses are flagged as being used by multiple users.

Solution: add an object to an existing collection or create a new collection for an IP whitelist. No GUI needed as it can be manipulated manually. Add a fixture to add 127.0.0.1 to the list if it's not already there. Check this list for addresses before using them on https://blockrazor.org/moderator/flagged-users

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #1980.

To add an IP to the whitelist just run this query:
```
db.activityips.insert({
   ip: 'ip-address',
   ignored: true,
   whitelist: true
})
```

@emurgobot done
