### ISSUE TITLE
Problem: bounty page does not encourage users to add new currencies

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#198]
Problem: The bounty page is currently used to encourage users to add data about existing currencies. It is important that new currencies are also added to the system.

The bounty reward can be set manually at first (no UI or algorithms needed) but will probably need to be controlled with an algorithm later on (an increasing amount of Krazor based on the last currency submission).

The bounty page displays bounties in order of reward (in Krazor) and this 'add currency' bounty should slot in at the correct place. I'm not sure of the easiest way to do this, bounties are currently in a single collection which makes it easy to sort them, however the add new currency bounty behaves differently to a normal bounty and is a different module + collection. Perhaps some jquery or something could be the simplest way to deal with this.

Currently assigned to me as I'm thinking about other yet undocumented but related problems, comments/suggestions appreciated. Ping @anbud

**Comment by anbud** [comment]
So, if I understood this correctly, the 'add currency' bounty would be a different module that's just similar to the current bounty system. And the bounty would be complete when the user actually adds a new currency and a moderator approves it? Just by browsing through the code, I've come across a collection named `BountyTypes`. If the behavior is not that different, we could just add a new type, the 'add currency' bounty, and define special rules.

Displaying bounties in order of reward is really not a big issue, as two (or even more) arrays can be easily merged into one (i.e. underscore's [union](http://underscorejs.org/#union) function) and then the data can be sorted by any given parameter. The most important thing here is that all arrays that will be merged contain the same sorting parameter, which is correct in this case (they'll all have the reward parameter). And, algorithmically increasing the reward for the bounty is a nice idea, we should definitely do that.

**Comment by gazhayes** [comment]
> the 'add currency' bounty would be a different module that's just similar to the current bounty system.

It's just the same (well, of course it can be modified) as the 'add currency' thing (https://blockrazor.org/addcoin) is now. Right now the problem is that it's not displayed on the bounty page (and the bounty reward is fixed).

>If the behavior is not that different, we could just add a new type, the 'add currency' bounty, and define special rules.

Would that still be ok, given the above?

**Comment by anbud** [comment]
Oh, I get it now. I thought that this 'add currency' bounty was something new that needed to be added. That's why I thought we could use `BountyTypes`.

In this case, however, the simplest way would be just to 'inject' the 'add currency' bounty on the bounties page on the client side, there's no need to complicate things on the server. Just extending the bounties array would be fine. 
And about algorithmically increasing the bounty reward, we could have a time-based thing. The number of days passed since the last added currency could be used as a multiplier for the bounty reward (or something of the sort) (e.g. the reward after 5 days would be 9 KZR (if the current reward is 1.8 KRZ)). I believe that would be the simplest solution for now.

**Comment by gazhayes** [comment]
Yeah I agree that's probably the simplest solution (but verify the reward rate on server to prevent fuckery).

FYI In the existing bounties I'm pretty sure I used exactly what you just described to calculate the bounties.

**Comment by gazhayes** [comment]
The reward for adding a new coin should be the same (at the same point in time) regardless of whether it was accessed from bounties, or the add currency button (which will later be prominently displayed somewhere).

**Comment by anbud** [comment]
The basic solution is in #204. 
I've just noticed that when we algorithmically calculate the reward, the reward can be quite small in some cases (right after a currency is added, the reward is about 0.000001). Should I set a minimum value of the reward to somehow fix this?

**Comment by gazhayes** [comment]
> Should I set a minimum value of the reward to somehow fix this?

Don't worry about that for now, I'll revisit it when working out overall bounty budgets later.
