### ISSUE TITLE
problem: weird right side border

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1982]
Problem: there's some weird double or triple border thing in the UX.

**Comment by MadanBhandari** [comment]
If you meant by extra scrollbars, that should be fixed in #1997

**Comment by MadanBhandari** [comment]
@emurgobot label "UI-UX"

**Comment by MadanBhandari** [comment]
Fixed in #2000 

it took me too much time to debug :/

@emurgobot done
