### ISSUE TITLE
problem: user's total KZR balance not shown on problem detail page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1985]
problem: user's total KZR balance not shown on problem detail page (/problem/x) in the "add credit to bounty" box.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@gazhayes this seems to work fine. anyone else experiencing the same @anbud @AshHimself @MadanBhandari?

The test mod account has also been suspended, can't test with that anymore

**Comment by samuelralak** [comment]
@emurgobot unclaim

**Comment by gazhayes** [comment]
Strange. It's not working for me. Could be some legacy DB thing or something, will wait to see if other people have the same issue. 

Try logging in with gareth:rodviv for mod stuff

**Comment by MadanBhandari** [comment]
@samuelralak looks like it's working for me too :D

**Comment by anbud** [comment]
It works for me as well.
