### ISSUE TITLE
problem: when a bounty is in progress, users can't easily find their way back after navigating away

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1987]
problem: when a bounty is in progress, users can't easily find their way back after navigating away. There's a target icon in the menu bar but the side menu goes to the bounty page.

solution: make the bounty menu items (top and side menu) redirect to the current bounty when a bounty is in progress.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot done

done in #1995
