### ISSUE TITLE
problem: no github project summary

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1988]
Problem: on the currency detail page there's no summary of github projects for this currency.

Solution: add a summary, something like this:

Related projects on Github: xxx
Watchers on all projects: xxxx
Likes on all projects: xxxxxx
Watchers per project: xxxx 
Top 5 languages: x, x, x, x, x.

This should probably be stored in the currency collection (or something else that's already used on this page) and updated daily with a cron job.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #2002.

@emurgobot done

**Comment by gazhayes** [comment]
@anbud  where is this actually visible?

**Comment by anbud** [comment]
Currency details page, related repos tab.
