### ISSUE TITLE
Problem: watermarked images have a very large file size

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#199]
Problem:   
Watermarked images are very large in comparison to the uploaded image. Some GM tweaking probably needed.

![](https://i.imgur.com/tA8LzJm.png)

**Comment by AshHimself** [comment]
@gazhayes - PR issued. Thoughts on another feature to create a thumbnail sized image as well? This would allow that to be used on initial load instead of the full image therefore increasing page load times, especially for future mobile use cases.

**Comment by gazhayes** [comment]
> create a thumbnail sized image as well    

Don't worry (for now).
