### ISSUE TITLE
problem: extra steps required for facebook or github signup

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1990]
Problem: extra steps are required for facebook or github signups, but email (which actually should be discouraged due to ease of creating multiple accounts) is easy.

solution: add sign in with github/facebook buttons to landing page. Remove email sign up from landing page. Add link to "sign up with email" instead of having it on the page itself.

Add the email sign-in (not sign-up) form to the landing page.

**Comment by geekyd** [comment]
@emurgobot claim

**Comment by geekyd** [comment]
Done in #1996 

@emurgobot done
