### ISSUE TITLE
problem: site stats on landing page are easy to miss

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1991]
problem: site stats on landing page are easy to miss because they are mixed in with other very similar looking things.

solution: not really sure, somehow make them stick out more, move them to the top of the page, change the styling, or something.

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
Just to clarify, I meant the landing page: 

<img width="1649" alt="screen shot 2018-09-26 at 1 54 07 pm" src="https://user-images.githubusercontent.com/8143945/46059943-e28c5100-c193-11e8-926f-3873b0160f45.png">

**Comment by samuelralak** [comment]
lol, worked on a totally different thing

**Comment by samuelralak** [comment]
I think the landing page is gonna need more graphics

**Comment by gazhayes** [comment]
> lol, worked on a totally different thing

Yeah I saw the currency listing page and immediately knew lol

**Comment by gazhayes** [comment]
> I think the landing page is gonna need more graphics

Yeah if you have any ideas feel free to play around

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
@emurgobot label "in progress"

**Comment by samuelralak** [comment]
@emurgobot done

done in #2026
