### ISSUE TITLE
problem: auction box at top of coin list doesn't really fit in

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1992]
problem: auction box at top of coin list doesn't really fit in. It looks good on small screens (single coin column) but not when there are multiple columns. 

solution: I'm not sure, I guess make it a full-sized box like the other coins when there's more then one column, that's a good start and new problems can be added when people have ideas of what to actually use to fill the space.

**Comment by MadanBhandari** [comment]
what about making other cards little smaller ? Any alternate graph options ?

@emurgobot label 'UI-UX'

**Comment by MadanBhandari** [comment]
@emurgobot label "UI-UX"

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #2011 

@emurgobot done
