### ISSUE TITLE
problem: it's difficult for non-tech people to add translations

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1994]
problem: it's difficult for non-tech people to add translations

solution: no idea, anyone have any ideas? Maybe a quick form or something that generates a translation file?

**Comment by geekyd** [comment]
@gazhayes We should add a page with a form to generate translation files seems a good idea. We can list all the text required to be translated & generate a file. This will enable anyone to add translation easily.

**Comment by anbud** [comment]
We used to use CrowdIn in one of the places I've previously worked, but it was free then, now it only has paid plans. It's a great solution, but I don't think it's worth the money.

Adding forms to generate translations is the easiest solution here, I've tried it a couple of times few years ago, non-tech people had no problems filling out the forms, while json can be tricky.

**Comment by gazhayes** [comment]
Can the forms be auto generated based on the existing files? otherwise every UI change requires manually adding new forms which then makes this more trouble than its worth to solve.

**Comment by anbud** [comment]
@gazhayes, I've just tried it on production, it's not loading data. Is `process.env.PWD` defined when the server is deployed? I'm using that variable to find the root of the project, it's the only variable that actually works in this situation. 

`__dirname` doesn't want to cooperate and absolute paths aren't working either.

**Comment by anbud** [comment]
@emurgobot claim

@emurgobot remove "done"

**Comment by anbud** [comment]
Done in #2025.

@emurgobot done
