### ISSUE TITLE
problem: after sign in, users are still shown the landing page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#2009]
problem: after sign in, users are still shown the landing page

<img width="1434" alt="screen shot 2018-09-26 at 1 56 20 pm" src="https://user-images.githubusercontent.com/8143945/46059983-08b1f100-c194-11e8-87e9-db4afcafa4b0.png">

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
claim the wrong issue @emurgobot unclaim

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #2012 

@emurgobot done
