### ISSUE TITLE
problem: statistics at top of page take up a lot of room

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#2010]
problem: statistics at top of page take up a lot of room

<img width="1448" alt="screen shot 2018-09-26 at 1 58 58 pm" src="https://user-images.githubusercontent.com/8143945/46060104-6f370f00-c194-11e8-8744-a9057c39b114.png">

Solution: do other people agree this is a problem? Maybe make them considerably smaller?

**Comment by samuelralak** [comment]
makes them more conspicuous IMHO 😄

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
@samuelralak yeah I kind of like it and the colors... or maybe you can make them shrinkable or closable or something

**Comment by samuelralak** [comment]
yeah sure, working on that

**Comment by samuelralak** [comment]
@emurgobot done

done in #2021
