### ISSUE TITLE
problem: total github watchers and likers are same number

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#2013]
problem: total watchers and likers are same number on each currency, I suspect something weird is going on.

ping @anbud

**Comment by anbud** [comment]
Hmm, it is weird, but `watchers` field is a sum of `watchers_count` and `likes` is a sum of `stargazers_count`. But, I've just discovered [this](https://github.com/milo/github-api/issues/19#issuecomment-357615223), it seems that `subscribers_count` is actually the number of watchers now. Nice way to name things. :D 

I'll fix it.

**Comment by gazhayes** [comment]
microsoft probably fucked it after taking over

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Of course, `subscribers_count` field is not available in search API and it would be quite a lot of fetching to fetch repo info for each related repo, and we would reach GitHub limits quickly, so I'm using `watchers` field which should be `subscribers_count` in the preview search API endpoint.

Done in #2016.

@emurgobot done
