### ISSUE TITLE
problem: signing in with email is too encouraged

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#2014]
problem: signing in with email is too encouraged

<img width="470" alt="screen shot 2018-09-26 at 4 09 01 pm" src="https://user-images.githubusercontent.com/8143945/46066149-926aba00-c1a6-11e8-9c19-930a0bf15e6e.png">

solution: put facebook and github buttons at the top of the box. Hide the email sign in form, add a third button 'sign in with email' which toggles it to display onclick.

**Comment by MadanBhandari** [comment]
@emurgobot label "UI-UX"

@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #2018 

@emurgobot done
