### ISSUE TITLE
Problem: users might add a currency that is already in the moderation queue

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#202]
Problem: users might add a currency that is already in the moderation queue.

Solution: when a user adds a new currency it already checks that one with the same name doesn't already exist in the `currencies` collection. This needs to be added for the currencies in the moderation queue that have not been approved or rejected.

**Comment by janat08** [comment]
Is there a check for if currency already exists/added?

**Comment by janat08** [comment]
Right, the unique name check already looks up pending. I will abort form submit if invalid, and use method again on server submit method.

**Comment by gazhayes** [comment]
> the unique name check already looks up pending

You added this, or it was already doing it?

**Comment by gazhayes** [comment]
> the unique name check already looks up pending

Ah, you're right. Its already doing it. This issue shouldn't have been logged.

>  I will abort form submit if invalid

It should already give the user an error onBlur, but yeah  good idea to abort if they still try to submit it.

**Comment by janat08** [comment]
close this.
