### ISSUE TITLE
problem: some dependencies have security issues

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#2020]
problem: some dependencies have security issues

<img width="752" alt="screen shot 2018-09-27 at 11 45 01 am" src="https://user-images.githubusercontent.com/8143945/46122370-dadbb380-c24a-11e8-9ddd-02d1f7a5e2a4.png">

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot done

done in #2022
