### ISSUE TITLE
Problem : Sign up link doesn't exist

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#2034]
Problem : Sign up link doesn't exist
Solution : Add sign up link on `/login` like there was earlier

**Comment by MadanBhandari** [comment]
@emurgobot label "UI-UX"
@emurgobot claim

**Comment by MadanBhandari** [comment]
Did I missed anything ? why the `/login` is completely changed after #2018 ? any specific reasons ?

ping @gazhayes @anbud @samuelralak

**Comment by MadanBhandari** [comment]
@emurgobot unclaim

**Comment by MadanBhandari** [comment]
@gazhayes  Should I add back signup link ?

**Comment by gazhayes** [comment]
Ah yeah, I guess so. I'm not sure what happened there

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #2036 
@emurgobot done
