### ISSUE TITLE
Problem : /login page UI-UX broken

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#2036]
Problem : /login page UI-UX broken

Solution : Update Layout and fix alignment issues

**Comment by MadanBhandari** [comment]
@emurgobot label "UI-UX"
@emurgobot claim

Since I am working on #2034 as well, I will send single PR for both

**Comment by MadanBhandari** [comment]
Done in #2037 

@emurgobot done

**Comment by samuelralak** [comment]
@MadanBhandari just realised that the PR submitted with this issue reversed my changes.

The Login Page wasn't broken, I had modified it to blend in the with the updated landing page. This is what I updated it to. The Login page was modified to reflect this as well.

<img width="1680" alt="screen shot 2018-10-05 at 2 50 32 am" src="https://user-images.githubusercontent.com/4476552/46509103-8091b280-c849-11e8-9c46-e7608dfffc72.png">

**Comment by MadanBhandari** [comment]
@samuelralak Oh I understand now, while changing on landing page it was also changed in `/login` too.

For this, we can create new template to render on landing page and update UI-UX accordingly.
Hiding email forms are explained her #2018

**Comment by samuelralak** [comment]
Will create an issue and submit a patch for this. Then we can look at how to hide the Login Form while keeping the UI consistent.
