### ISSUE TITLE
Problem: amount credited to users after a new currency bounty is approved is incorrect

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#211]
Problem: I just added litecoin as a test. The bounty was 18.59 however 0.00000039 was credited.

**Comment by anbud** [comment]
This one is mine, I'll check it out.

**Comment by anbud** [comment]
@gazhayes, Is there a way to access production server logs somehow? I can see that this doesn't work correctly in production, but I can't reproduce the bug locally, as it credits the correct amount on the local server.

**Comment by anbud** [comment]
Added a little bit more logging in #214 and a possible fix.

**Comment by gazhayes** [comment]
> I can't reproduce the bug locally

Weird. Maybe something client side is affecting it?

> Is there a way to access production server logs somehow?   

Do you still want that after the last PR? I can give you ssh access.

**Comment by anbud** [comment]
Thanks for the SSH access, it helped. I believe I got it, it should be fixed in #216. 
`Meteor.userId()` works correctly in methods called from the server locally, but apparently, it doesn't work correctly in production.

**Comment by gazhayes** [comment]
That's weird, I'll post to the meteor forum and ask if this is is a bug or a feature.

**Comment by AshHimself** [comment]
Could be a side bar comment but, you can use this.userId as well which is a lot less heavy.
