### ISSUE TITLE
Problem: proposed changes cannot be downvoted

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#212]
Problem: proposed changes (https://blockrazor.org/changedCurrencies) can only be upvoted but not downvoted. 

Solution: Allow downvoting and use a something along the lines of:

if (3+ upvotes and (downvotes/totalvotes < 0.2) then merge.

**Comment by AshHimself** [comment]
@gazhayes - Do you want to historically track if a user has voted and then downvoted and then say upvoted again or just track the users end result? The latter is obviously the easiest but the former will take a little more code. Let me know and i'll get this done.

**Comment by gazhayes** [comment]
Just track the end result, that should be enough. Also please now make it so only moderators can vote.

**Comment by AshHimself** [comment]
You got it!

**Comment by AshHimself** [comment]
@gazhayes - Fair bit of logic added into this one. 
- Can upvote and then revert your upvote which takes score back to zero
- Can now downvote
- If you are a moderator you should see the proposed changes view in the menu.
- If you are not a moderator and know the URL you still can't vote as error handling is done on method.
- Once merged a message is presented to the user.

Please note that once a merge is done you can't undo this.

**Comment by gazhayes** [comment]
> Please note that once a merge is done you can't undo this, if this happens then I suggest another edit be done? 

Yeah that's actually perfect and how the C4 works anyway.

Only had a cursory look but the PR looks good. 

One thing I noticed, I just tried to add a genesis block timestamp to Monero (as an example) but it doesn't make it into proposed changes. Any ideas?
