### ISSUE TITLE
Problem: github API request not automagically generated

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#215]
Problem: when adding a new currency it is reasonable to expect users to provide a github repository location but not the API endpoint to fetch the number of recent commits. 

API call: https://github.com/Blockrazor/blockrazor/blob/master/server/API_requests/github.js

**Comment by anbud** [comment]
@gazhayes, Can I take this one?

**Comment by gazhayes** [comment]
Yes, sure.

**Comment by anbud** [comment]
Done in #218.
