### ISSUE TITLE
Problem: decentralization measurements are nominal not comparative

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#219]
Problem: currently, decentralization measurements are taken absolutely instead of comparatively with ELO rankings. This means that when one currency has more users rating it than others it's very easy to skew the results.

Possible solution: fully implement ELO rankings for decentralization as with wallets and community etc. Have separate decentralization questions for users, even if some are the same questions as other categories. The questions which are absolute can be asked on the add currency form and stored in the currency collection itself and applied *once* as a multiplier. So far there's only one of these questions anyway.

Possible solution: another possible solution could be to generate full elo rankings instead of the nominal 'affects' thing that is currently used.

ping @anbud

**Comment by anbud** [comment]
@gazhayes,
Basically, the first possible solution is easier to implement, as it's fully compatible with the current ELO system. 
But, in my opinion, the second solution seems better, as users would only have to answer the same questions once. Will there be any comparative questions only about decentralization?

> The questions which are absolute can be asked on the add currency form and stored in the currency collection itself and applied once as a multiplier. So far there's only one of these questions anyway.

If there won't be many nominal questions, I agree, this is a better approach.

**Comment by gazhayes** [comment]
How about using the first solution but inject decentralization questions into the appropriate place (community/codebase/whatever) at the UI level? The decentralization questions can be written so they are specifically for the decentralization metric, but the context of community or  codebase (for example) is the right place to actually ask the user.

So far there's only one nominal question anyway so that part should be ok, at least for now.

**Comment by anbud** [comment]
Yap, that's a perfectly fine solution, I like it. I could add a context field to the 'add question' form that would determine where to actually show the question.
Should I go on with the implementation of this?

**Comment by gazhayes** [comment]
> Should I go on with the implementation of this?   

Yes absolutely :)

**Comment by anbud** [comment]
In #222 I've implemented the full ELO system for decentralization questions and I've removed the old nominal questions system.

Another PR will follow later for absolute questions on 'add currency' page.

**Comment by anbud** [comment]
Nominal questions on 'add currency' are implemented in #232.
