### ISSUE TITLE
Problem: comments on the currency detail page don't look very good

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#224]
Problem: the way comments/features/red flags are displayed doesn't look great. For example: https://blockrazor.org/currency/ethereum

**Comment by MadanBhandari** [comment]
I want to work on this, can you please assign this to me ?

**Comment by AshHimself** [comment]
@gazhayes - Should Wymi be mandated on every comment post?

**Comment by gazhayes** [comment]
Probably just going to remove it actually

**Comment by AshHimself** [comment]
Consider it gone...

**Comment by AshHimself** [comment]
@anbud - i'm trying to link to the users profile from the features page but you are using the slug package. I understand the concept of this package but on the features table we only seem to be logging the author. e.g. Ash Himself, but my slug would be ash-himself. 

Is that a safe business rule to assume its all lowercase and spaces replaced with - ?

Thanks mate.
