### ISSUE TITLE
problem: when coin changes are merged they are saved as arrays

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#230]
Problem: when coin changes are merged they are saved as arrays not strings. There is also an issue with the genisistimestamp not merging correctly.

Solution: Revise merge method to ensure they are saved in the correct format.

**Comment by gazhayes** [comment]
Was this fixed in one of the last PRs?

**Comment by AshHimself** [comment]
No mate, inbound as a seperate commit in another issue I just resolved.
