### ISSUE TITLE
Problem: no framework for to fetch current hash rate and compute power consumption

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#235]
Problem: In order to use a hashpower metric a standard unit of measure must be used to compare different algorithms and different currencies. The most ideal is probably the current power draw in kW.

https://blockrazor.org/hashpower will eventually be populated with a wide variety of ASIC and GPU data. That will (after some algorithm is written to generate a good value from the results) provide the algorithm + power consumption. Many coins use the the same algorithm (POW algorithm). 

The API to fetch the current hashrate is vastly different for each currency so in future there will probably be a bounty of some kind to provide a pull request for each currency as this is too complex to build into the UI. What's needed though is some kind of framework to handle this so that adding a new hashrate API is very simple. An API will provide the current hashrate in whatever unit, and then the site should automagically calculate the power consumption based on the hardware at https://blockrazor.org/hashpower

A good example to use is probably monero. I've added one hardware device with its power consumption on the cryptonight POW algorithm (which is what Monero uses), and the current hashrate can be found at https://moneroblocks.info/api/get_stats (full details: https://moneroblocks.info/api).

Ping @anbud

**Comment by anbud** [comment]
@gazhayes,
I agree, power consumption in kilowatts (or watts) would be an ideal metric, as we already capture it for each added hardware.
To get the algorithm + power consumption for each algorithm, I believe we could calculate an average power consumption for one hash/s (or solution/s?) based on the hardware data and go from there. That way, we could easily calculate the power consumption based on the currency's hash rate. 
That would mean, from current data, Cryptonight would consume 0.00015625 watts per one hash/s (70/448k). Based on the API response, if the hash rate is in hash/s, currently, the power consumption for XMR is 137039 watts (which seems kinda small, the unit is probably different).
Would the average value be sufficient, or do you have another idea? The median value could also be useful here.

As for the framework, all (or at least most) APIs return proper JSON (or maybe XML), so I could make a method that would accept the currency, API URL, type of data (JSON, XML, ...), actual hash rate unit (H/s, MH/s, ...) and a field where the hash rate actually is in the object. Field value would support nesting (`val.val1`) and array values (`val[0]`).
For the example you've given, it would look something like: `hashrate('Monero', 'https://moneroblocks.info/api/get_stats', 'json', 'h/s', 'hashrate')` which would then process the API data and return the required values. That way, the PR would only have to add a method call with appropriate parameters for currencies. Contributors could also easily test if the method call returns the right data right away. This would be quite simple for the contributors I believe.
Another idea for the framework would be to stub the method for hash rate power consumption calculation, fix the parameters and the return value, and leave it to the contributors to write the actual logic to parse the API call.

**Comment by gazhayes** [comment]
I used kH/s when adding that GPU, it should actually have been H/s. That yields a more realistic 138,203,125W (at the current hashrate).

Your first paragraph is precisely what I was thinking (and the whole reason for collecting the hashpower data). Average is probably the simplest thing to use for now that will actually work, as we get more date we can play around with it.

>  I could make a method that would accept the currency, API URL, type of data (JSON, XML, ...), actual hash rate unit (H/s, MH/s, ...) and a field where the hash rate actually is in the object. Field value would support nesting (val.val1) and array values (val[0]).   

That's probably the simplest solution, a stubbed method would be simpler but also wouldn't really solve the problem.

**Comment by anbud** [comment]
Done in #240.

**Comment by gazhayes** [comment]
@anbud could you do an example standalone pull request that can be used as a model for adding a hashrate API?

Ethereum: https://www.etherchain.org/api/basic_stats (current hashrate is in the first object).

The algorithm is EtHash and I've added some real world data for it.

**Comment by anbud** [comment]
@gazhayes, sure thing.

**Comment by anbud** [comment]
The example is in #362.
