### ISSUE TITLE
Problem: add currency and hashpower use different algorithm data source

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#241]
Problem: As we now use an API to fetch the current network hashrate for each currency and then use this along with the data in /hashpower to calculate power consumption in Watts, the algorithm list used when users add a new currency, and the algorithm list for adding the power consumption of a hardware device should be identical.

**Comment by anbud** [comment]
@gazhayes, noticed this while implementing #235. 
There are two obvious solutions here:
- use the user-generated list from hash power everywhere. 
- use the fixed list from 'add currency' page everywhere.

I believe the first solution would be better. The only problem I see with that is that users are only adding algorithms by name, while the 'add currency' page also needs the category (PoW, PoS, ...). Of course, I can extend the form for adding new algorithms to accept consensus security as well.

**Comment by gazhayes** [comment]
I also agree, the first solution is better and simpler.

The hashpower page only need PoW algorithms, so anything they type in is already PoW category (in reality). So maybe you could just insert it as PoW for the add currency page? And for 'hybrid' just concatenate them (or whatever)?

The only problem I can see is that we might at some point want to add the ability for users to add new algorithms on the add currency page itself.

**Comment by anbud** [comment]
Sure thing, I can insert the user-generated algorithms as PoW (and concatenate them for 'hybrid').
If we ever decide to let users add algorithms on the 'add currency' page, we can use the same method used to add algorithms on the hash power page, there's no big difference.

**Comment by anbud** [comment]
Done in #251.
