### ISSUE TITLE
Problem: rating wallets, communities, codebase is not bountified

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#243]
Problem: especially during the initial stages, to drive up user interaction there needs to be some reward for contributing. Comparative ratings of various aspects of each currencies used for comparison metrics are essential to blockrazor, however there are no bounties for rating wallets, communities and codebases. 

Dependency: #244

**Comment by anbud** [comment]
When #244 is solved,  this can easily use the same system as the bounty for adding new coins. It would require some modifications, but the basic idea is the same. Would we use fixed or time based bounty prizes?

**Comment by gazhayes** [comment]
We should use time based. The idea is that as more people start adding data the system will self-regulate the rate that coins are distributed. Similar to mining but for contributions instead.

**Comment by gazhayes** [comment]
Also slightly related: #245

**Comment by gazhayes** [comment]
@anbud are you doing this one?

**Comment by anbud** [comment]
@gazhayes, yap, I'm on it.
