### ISSUE TITLE
Problem: very easy to cheat on comparative ranking bounties if incentivised to do so

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#244]
Problem: bountifiying the elo ranking system is (probably) necessary (#243). This however introduces a new problem: many users will probably just randomly click through questions just to get the bounty. 

Possible solution: throw in some reverse questions to verify a previously answered question (ask the same question twice in a different way but reverse it and see if the answers match). Something like a checksum question. Perhaps it's not necessary to use the exact same question twice, maybe there are some XOR type questions where answering one question a certain way means another question can only be answered a certain way or it would be incongruent. If a user is caught providing "lazy answers" the penalty could be quite harsh (all of their answers get purged and they have to do the whole lot again).

**Comment by anbud** [comment]
@gazhayes, XOR questions would be a nice solution here. When adding a question I could add a field where you can select which questions are in XOR relation to that one. If we catch the user, we can purge his progress, and maybe we can even deduce some small amount of Krazors from his account as a penalty. Maybe even add a time based ban for other bounties if this happens multiple times.

**Comment by gazhayes** [comment]
> When adding a question I could add a field where you can select which questions are in XOR relation to that one.

OK that sounds like the best and simplest solution.

>If we catch the user, we can purge his progress

That should be enough to dissuade most. And if they get caught again add a time based ban and a permanent thing on their profile (profiles will come later).

**Comment by gazhayes** [comment]
This also raises a question in how to award bounties for answering questions in #243, if they are awarded immediately the amount would have to be deducted from their wallet when purging their answers. But if waiting till all the (unknown number) of questions are answered before transferring the bounty that introduces extra complexity.

**Comment by anbud** [comment]
My initial idea here was to wait until the user answers all rating questions on the given topic to give him/her the bounty (number of questions times the locked-in bounty amount). If the user happens to leave the page while answering the questions, he/she would be credited for the amount of questions he/she answered. And if we catch him/her cheating, it's easy to reset the money counter.

**Comment by gazhayes** [comment]
The problem (I think) is that the questions are not actually generated until the do x for currency y (e.g. upload a wallet image).

Is that a problem for the solution you are thinking of?

**Comment by anbud** [comment]
You're right, they are not generated until you make an action. (uploading a wallet image, adding a community,...) But, my idea is to have a bounty amount for answering one question and show that amount when accepting the bounty. The bounty text would, of course, say that the amount will be multiplied by the number of questions you answer.

**Comment by gazhayes** [comment]
Ah yes. Now I understand. Yeah that's probably the simplest solution.

**Comment by anbud** [comment]
Ways to prevent cheating are implemented in #260. Currently, when the user is caught, we only reset his answering progress. When we implement the bounty system for rating wallets, codebases, and communities, I'll also implement a way to reset bounties.
