### ISSUE TITLE
Problem: no coherent accounting strategy to track Krazor coins

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#245]
Problem: bounties etc are rewarded in Krazor (BlocKrazor) coins. As there is a finite number of Krazor coins and transfers happen on an immutable blockchain, its important not to make mistakes. For this reason it's best to have a fixed amount of coins in a 'main' wallet which are transferred to user's wallets when necessary in a kind of double-entry accounting fashion. This can all be done in Meteor as users must specifically 'withdraw' coins from their Blockrazor wallet into their Krazor (blockchain) wallet.

**Comment by anbud** [comment]
The solution you've described is what crypto exchanges mostly use. Basically, it wouldn't be optimal to use the chain for every transaction, and if you make a mistake, there's no going back. So, you never communicate with the blockchain unless a user wants to withdraw or deposit some coins (will we have deposits?). And that's all. That's what we should be using here as well. 
I haven't had a good look at the coin code, but, is there some kind of an API to easily communicate with the chain?

**Comment by gazhayes** [comment]
>  is there some kind of an API to easily communicate with the chain?

Yes, I'll publish details on how to consume the Krazor API. At this stage however, it's not even necessary. 

The main thing I'm worried about with this issue is tracking coins within Blockrazor itself.

**Comment by anbud** [comment]
You mean something like keeping a transaction log of all transactions happening on Blockrazor, so we can check if everything is ok?
Transactions are already kept in the `Wallet` collection (with lots of metadata), maybe we can just display them somewhere? We could also implement a way to nullify transactions if something goes wrong.

**Comment by gazhayes** [comment]
> Transactions are already kept in the Wallet collection (with lots of metadata), maybe we can just display them somewhere?

That's a good point actually. We can probably just make sure that any necessary data is logged to that collection and it should be enough for now. 

I'll sit on this and think about it for a while, there are some other complications such as users contributing to bounties for system improvements etc, tipping other users for useful comments, etc, so something more robust may be needed later.
