### ISSUE TITLE
Problem: cannot develop Blockrazor while offline because some libraries require connectivity

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#246]
Problem: some libraries (e.g. bootstrap) are fetched from a CDN which makes it hard to develop while offline.

**Comment by AshHimself** [comment]
Ideally we should be using packages for npm for all depencies and not cdn
at all imo. The root.html needs a bit of an overhaul.

**Comment by gazhayes** [comment]
@AshHimself completely agree.

**Comment by AshHimself** [comment]
@gazhayes - Sorry mate didn't see you added the low priority on this. You prefer these as NPM packages if available or atmosphere. NPM is better just more time consuming obviously as need to define in each file. Could probably do this slowly as well as required. e.g. do moment first etc.

**Comment by gazhayes** [comment]
> NPM is better

Can you elaborate on that one?


I remember trying to use NPM for bootstrap and it was a disaster, can't remember exactly why though.

**Comment by AshHimself** [comment]
Sorry let me clarify my statement. NPM is better for packages which may only be used in few areas of the site. e.g. moment or other larger packages, we can then use imports to only load them when needed and increase the performance of initial load. 

After doing an assessment of the packages we have so far in root.html it may just make sense to use atmosphere for now and any other 'future' packages should use NPM if it architecturally makes sense. 

https://docs.meteor.com/packages/dynamic-import.html
Is a good read for others interested.

**Comment by gazhayes** [comment]
Ah yes, we are going to want to be making use of dynamic imports so NPM makes more sense for most things.

**Comment by anbud** [comment]
Yea, in my experience, dynamic imports can improve performance and initial load times drastically, we should definitely start using them.

**Comment by AshHimself** [comment]
@gazhayes - we need to update the readme to state that meteor npm install chart.js --save is required. Currently chart.js is not being found.

**Comment by gazhayes** [comment]
I can't replicate that. A fresh clone works for me when running the instructions in the readme as they are now.

**Comment by AshHimself** [comment]
Looks to be all good now @gazhayes.
