### ISSUE TITLE
problem: filter on ratings page does not work

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#254]
Problem: filter on ratings page does not work

Solution: Looks to be a js related issue. I will resolve as I am currently working on another issue in same file.

**Comment by gazhayes** [comment]
Something recent must have broken that, it should be easy to cycle through commits with `git log` and `git checkout xxxxxx` or use git blame to find the offending commit.

**Comment by gazhayes** [comment]
It's not broken (on /ratings), could be a local issue on your fork?

**Comment by AshHimself** [comment]
This was actually on production but its working for me now so could of been related to a PR or reverted PR recently. All a ok now.
