### ISSUE TITLE
Problem: some modals broken

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#259]
Problem: there were some modals on the currency detail page, for example when a currency doesn't have any listed features, users are prompted to add some. When users click the textbox to add feature text, a modal gave them some instructions. 

These were broken in #256, probably something to do with the load order of jquery or bootstrap's javascript stuff.

**Comment by gazhayes** [comment]
Clicking into comments is also broken in the same pull request, probably the same cause.

 ![](https://i.imgur.com/LLSBCor.png)

**Comment by AshHimself** [comment]
Ok let me look into what's going on here.

**Comment by gazhayes** [comment]
Appears to still be broken. *some* modals are working (such as the help button), but not others. This doesn't look like a modal issue, maybe a jquery issue.

Modal should appear onFocus in this field:
![](https://i.imgur.com/qEo5iRE.png)

Comments and comment text box should be shown onClick:
![](https://i.imgur.com/gXvUdDX.png)

**Comment by AshHimself** [comment]
Ok I think I know the issue. Typically I import NPM packages like `import { Cookies } from 'js-cookie';` but this is causing issues; however in the NPM documention for js-cookie it stipulates to use` import  Cookies from 'js-cookie';`
