### ISSUE TITLE
problem: no way to know if user has uploaded images on ratings

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#267]
Problem: no way to know if user has uploaded images on ratings
Solution: add functionality for users to see what images they have uploaded therefore allowing them to upload more if required.

**Comment by AshHimself** [comment]
@gazhayes If a user uploads say a wallet images then clicks the next button and answers all the questions the currency is then moved to added wallets. At that point should he/she be able to add more screenshots to say 'CONFIGURATION OR OPTIONS'? I assume yes but in current workflow this isn't possible.

**Comment by AshHimself** [comment]
Additionally, a user can also upload multiple images for a wallet and multiple records get created in walletimages. I am thinking if the user attempts to upload another image for the same currency the old record should be deleted as well as the image on the server.

**Comment by AshHimself** [comment]
@gazhayes - understood, I think I am merging a few issues together here. So the uploaded images, where should they be able to see those?

**Comment by gazhayes** [comment]
> So the uploaded images, where should they be able to see those

Maybe in a modal or something when the user clicks the currency on the ratings page? It's really up to you, wherever you think it makes the most sense.

**Comment by AshHimself** [comment]
@gazhayes - Pushed a PR for this. I didn't do a modal at this point until another ticket is raised and we can find a good home. Users can see what images they have uploaded however prior to clicking the next button (is that the right word we need to use? Next?)

I'll raise another ticket to not process currencies with images until 3 images are created?

**Comment by gazhayes** [comment]
Ok, don't worry about the modal, but definitely do the 3 image check.

**Comment by AshHimself** [comment]
#281 raised to track 

> 3 image check.
