### ISSUE TITLE
Problem: currencies do not have logos

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#27]
Solution: ask user to add currency logo when adding a new currency

Related to #6 and #58

**Comment by AshHimself** [comment]
@gazhayes - For a solution, are you ok with the logo being captured within the form, uploaded to server and filename stored in the database? I can implement the same filesize and filetype validation for the wallet uploading form. 

Are there any particular views you would like the logo displayed?
Should we do any server side scaling of the images to ensure consistency? e.g. scale to 100x60 etc. Possibly use imagemagick and can then in turn resolve #32

**Comment by gazhayes** [comment]
> are you ok with the logo being captured within the form, uploaded to server and filename stored in the database    

Yeah that's fine. That's what I used for the wallet images.

> Are there any particular views you would like the logo displayed?    
The reason I created the issue was to get logo images to use on the rating/comparison page (when you actually run through the questions and it displays two currencies side by side). It's also probably a good idea to put them in the UI somewhere on the main page and the currency detail page.

> Should we do any server side scaling of the images to ensure consistency? e.g. scale to 100x60 etc. Possibly use imagemagick and can then in turn resolve #32    

Yes, have you used imagemagick with node before? You could also just log a new issue for that, it probably deserves its own thing.
