### ISSUE TITLE
Problem: No schemas on collections

### ISSUE THREAD

**Issue by anbud** [Blockrazor/blockrazor#272]
Problem: It is generally a good practice to use a schema to constrain the contents of collections to conform to a known format. When there's no schema, data can be anything, so whenever we read from the database, we have to write defensive code to check whether data exists and whether it's valid. Since we read data more often than we write it, it’s would be easier, and more optimal to use a schema when writing to prevent this.
(*this is probably low priority, but if it's not, I'm taking it*)

Solution: Implement a [SimplSchema](https://github.com/aldeed/simple-schema-js) constraint for collections

**Comment by gazhayes** [comment]
I looked at simplSchema for this and implimented it eariler on, I can't remember the reason right now but I removed it shortly after. I'll try to remember what it is. Even in the best case scenario this would be low priority however.

**Comment by anbud** [comment]
@AshHimself, yap, check package should also be used wherever possible, I agree.

**Comment by gazhayes** [comment]
I was confusing SimplSchema with Collection2. I think collection2 required using client side inserts which would have been an immediate deal breaker. I did also use SimpleSchema directly for a while but then decided not to use it because things were changing too often and I kept having to rewrite schemas. We should definitely use it as we get closer to production though. Low priority for now (for paid contributors) though.

**Comment by janat08** [comment]
Long ago.

**Comment by gazhayes** [comment]
related: #401

**Comment by gazhayes** [comment]
How does this sound:
@anbud could do an example schema and @janat08 can then use that as a reference to follow when implementing this everywhere.

What do you guys think?

**Comment by janat08** [comment]
currencies folder, activity log, bounty types, undone as it is broken.

**Comment by janat08** [comment]
votes undone

**Comment by janat08** [comment]
the above collections don't have example files from dump, and bounty types was said to be useless. It's ridiculous how you can't make circular schema reference since one of them won't exist when imports and yet DB relations.

**Comment by gazhayes** [comment]
Minor related dependency: #874

**Comment by gazhayes** [comment]
@janat08 any more to do on this one?

**Comment by janat08** [comment]
some from the list above

**Comment by gazhayes** [comment]
OK. Do you want to do it?

**Comment by janat08** [comment]
dump doesn't have any documents for those.

**Comment by gazhayes** [comment]
Ah I should have mentioned, I have updated this part of the readme. You can now fetch /static/dump.tar.gz and it will have the latest database up to the current hour.

**Comment by janat08** [comment]
bounty types, appLogs, formData, graphData, Problems: [taken, votes], and votes in general.

**Comment by janat08** [comment]
Problems: [taken, votes], and votes in general. not done.

**Comment by janat08** [comment]
@blockrazorbot unclaim.

**Comment by gazhayes** [comment]
OK, @janat08 when you see any specific schema problems just add a new specific issue for that particular collection.
