### ISSUE TITLE
Problem: no user profile page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#273]
Problem: users can't see other users' activity and statistics. This severely limits the "interaction" feeling. Currently, user actions (comments, currencies they added, number of ratings completed, etc) are not centrally tracked  so that probably has to happen first.

ping @anbud for ideas.

**Comment by AshHimself** [comment]
@gazhayes - I've done this before in two parts. 

**Part 1**
1. Log all activity points to mondoDB collection (we can use our existing logging component).
2. Display data on profile page, coin page.
3. Perhaps 'star/fav' coins to get all activity in a feed on your home page? 

**Part 2**
Capture all activity points as part of overall growth. e.g. track user activity and behavior into segment.io (or similar). This will allow emails like. "Congrats Gareth, you added your first coin", "Hey Gareth, here is a summary of your starred coins for the week etc.

**Comment by AshHimself** [comment]
I'll be honest i've not had to scale mongoDB before but it should be able to scale collections into the millions of records. The only advantage at this point is simplicity, decoupling into a more microservice architecture does have its benefits but obviously comes with more overhead in sysadmin. Getting the data tracked out of BR is easy I guess (intercom, mixpanel, GA), its just bringing it back in would then need an API/REST endpoint. I hope this makes sense as I am typing on a phone 

Having a user profile page with the stats above should be an easy thing to do.

**Comment by janat08** [comment]
There's article describing hell that came with doing social stuff with mongo (relations). I favour [peerdb](https://github.com/peerlibrary/meteor-peerdb) even if it pretty much results in you normalizing and denormalizing data simultaneously, but meteor as described in 1.3/2 release blog post doesn't handle updates that don't occur with id selector effectively so telling it to update all user documents that have this param is as worthless as document's array updating as a relation bind anyway (although I haven't gotten around to using peerdb and have vague impression of what it is).

**Comment by gazhayes** [comment]
Closing and moving to #330
