### ISSUE TITLE
Problem: no dedicated currency comparison page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#274]
Problem: it's difficult to compare two (or more) currencies. There's some functionality in the currency detail page but it's not robust enough. 

Ping @anbud 

Maybe something like this:
![](https://i.imgur.com/L3OOWaP.png)

**Comment by anbud** [comment]
@gazhayes, yap, I agree, the UI you've presented will be just fine for this, The other data in the image could be data about currencies shown on the homepage. (type of consensus, hash algorithm, hash rate,...)

**Comment by anbud** [comment]
@gazhayes, just to check, this will be on a separate dedicated page, right? (not on currency details)

**Comment by gazhayes** [comment]
Yeah on a new page.

**Comment by gazhayes** [comment]
The idea is for it to be independent of any currency. Users can start typing to filter and select currencies to compare (maybe use a modal or something).

**Comment by anbud** [comment]
Done in #311.
