### ISSUE TITLE
Problem: users can take a new bounty while an existing bounty is running

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#275]
Problem: the UI allows users to start a new bounty when another bounty is already running. Some bounty types prevent multiple bounties being run and other's don't. No errors etc are given when a user tries to start another bounty but things tend to go wrong, for example when starting a new currency bounty while another bounty is already in progress the countdown doesn't start and Krazor will not be awarded (I think).

Simplest solution is probably to grey out the 'take bounty' button if a user is already running a bounty in the background. Maybe give them an error or a tooltip telling them to cancel their existing bounty if they want to start a new one.

**Comment by anbud** [comment]
You're right, this needs a UI check, as the backend code checks if the bounty is active, that's why some other bounties are not starting. Greying out the 'take bounty' button is the simplest solution, both codewise and UX-wise.

**Comment by anbud** [comment]
Done in #285.

**Comment by gazhayes** [comment]
@anbud did you grey out the UI buttons on the bounty page for this one? Might not be working

**Comment by anbud** [comment]
@gazhayes, yap, the 'take bounty' button should be grey and disabled. I've just tested it on production, this is how it looks:
![imgur](https://i.imgur.com/dmW51vn.png)

What kind of an issue are you encountering?

**Comment by gazhayes** [comment]
Ah looks like it was a local problem for me, thanks.
