### ISSUE TITLE
Problem hashpower flagging does not allow removal of flag

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#276]
Problem: flagged hashpower values should allow removal of the flag as well as remove of the hashpower data point.

In order to prevent strange behaviour we should probably require 3+ moderators to remove the flag or to remove the data point.

**Comment by anbud** [comment]
@gazhayes, should I implement the same system here that is used in moderation of changed currency data?

**Comment by gazhayes** [comment]
Yeah I guess that's probably the best way to do it.

**Comment by anbud** [comment]
Done in #308.
