### ISSUE TITLE
No fixtures for hash algorithm

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#277]
Push a couple of strings on startup if none exist for testing.

**Comment by gazhayes** [comment]
This isn't necessary: I regularly update the /dump directory with the latest database for testing, when more hash algorithms are added these will also be in there.

**Comment by janat08** [comment]
I just realized I'm not complying with protocol, and missed the relevant instructions.

**Comment by gazhayes** [comment]
> I just realized I'm not complying with protocol

No but still good that you logged an issue :)
