### ISSUE TITLE
Problem: clicking on uploaded image in wallet rating modal produces strange results

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#282]
Problem: it's like a modal is trying to display (page is greyed out). Image exists, but isn't displayed.

**Comment by AshHimself** [comment]
Yeh I think this is issue with flow router and modals. I think I have a
solution.

**Comment by gazhayes** [comment]
FYI after the last pull request I'm seeing this: 
![](https://blockrazor.org/static/images/wallets/3a49d066a317971d9c9735a41b04a08c.jpeg)

**Comment by AshHimself** [comment]
Yeh looks like the OnRendered event wasn't init the tooltips once deployed to prod (due to delay for some reason) but does it locally. I've added a fallback init which should resolve this.

**Comment by AshHimself** [comment]
@gazhayes - this looks to be resolved now. Can you retest when you get a moment and close.
