### ISSUE TITLE
Problem: cannot use inverse elo rating for comparison questions

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#29]
When user is asked to subjectively compare two currency wallets the question must always be in the positive to satisfy the elo rating algorithm, but sometimes questions need to be asked in the negative.

Solution: add logic to reverse the elo rating selection so that questions can be asked in the negative.

**Comment by AshHimself** [comment]
@gazhayes - Could you please advise on where this logic is invoked in the UI mate?

**Comment by gazhayes** [comment]
At https://blockrazor.org/ratings if you add some wallet images it will populate the database with new 'rating questions'. These questions are then displayed to the user when they click next (or reload the page).

The way it currently works, the ELO rating accepts a 'winner' and a 'loser' based on user input. This problem is basically to avoid writing specially worded questions like "which wallet is the one that has the least number of problems and annoyances?" instead of "which one is the most annoying to use?" 

It's best to try it out with some fake images and see how it works.
