### ISSUE TITLE
problem: currency name check on /addcoin is case sensitive

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#292]
Problem: when adding a new currency the name is checked against active and pending currencies to make sure one with the same name doesn't already exist. The problem is that if you don't use the same case for any character it no longer matches and does not result in an error.

Solution: use a case insensitive check instead of a case sensitive check when checking if a currency name already exists.

@janat08

**Comment by janat08** [comment]
I could also check by symbol.

**Comment by gazhayes** [comment]
@janat08 when you submit a pull request please also comment on the issue so the original creator can close it. E.g. "fixed in #293.
