### ISSUE TITLE
Problem: "Please upload some wallet images to continue." doesn't always make sense

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#299]
Problem: /ratings page. Error does not always make sense. Should be something like "you haven't added enough wallets to....."

**Comment by AshHimself** [comment]
Can add a count to say "You must have two wallets to continue", then after adding one wallet it could then say "please add one more wallet to continue".

**Comment by gazhayes** [comment]
Yeah that would probably be better.

**Comment by AshHimself** [comment]
Fixed in #345 error messages could probably still be tweaked but the logic is there ready to go.
