### ISSUE TITLE
Problem: no testing

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#303]
Problem: there are currently no tests being run. This is going to start becoming a real problem as more people send pull requests to the project which could break existing code.

Anything important that we don't want to break should probably have an assert or something so that it doesn't get broken in future.

Tests however are a double edged sword and should be used with care. Whenever a test is added, whatever it's testing becomes harder to change. This slows down the evolution of the project. Projects often go overboard with testing, and there's a pitfall where projects become stagnant - less people are willing to change something (resolve a problem) when there's a test case for the existing way of doing it.

ping @anbud @AshHimself @sjmackenzie for any ideas.

**Comment by sjmackenzie** [comment]
Probably, mandating a test for every bugfix which grows over time is a good start. Once the project stabilizes; when it starts solving real end user problems, _then_ put down a battery of tests for important functionality. This approach eases the testing suite in with bite sized chunks allowing for adjustments and improvements.

**Comment by janat08** [comment]
jest snapshot testing.

**Comment by anbud** [comment]
I agree with @sjmackenzie, when the project stabilizes, we can introduce lots of new tests, but, for now, maybe we can just write tests for important new features.
I've used Mocha + Chai for Meteor testing before, it works perfectly fine for unit, integration and acceptance tests.

**Comment by gazhayes** [comment]
> I've used Mocha + Chai for Meteor testing before

Could you implement this and write an example test case that other people can refer to in future?

**Comment by anbud** [comment]
@gazhayes, yap, of course.

**Comment by janat08** [comment]
What method style is best so that I could convert to it, and run checks for delete operations as they may truly cause damage?

**Comment by gazhayes** [comment]
Related: #367 #368 #369
