### ISSUE TITLE
Problem: radar graph data not normalized

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#304]
Problem: the radar graph should have a maximum value of 10 on each axis, however I just did a codebase review of a few currencies and evidently this is not the case as the radar graph expands to accommodate the codebase ranking dataset.

**Comment by gazhayes** [comment]
Update: looks like this is only a problem *before* the graphdata cron job runs. Something to think about but not sure of the best solution, maybe just run the cron job more often. ping @anbud for ideas.

**Comment by anbud** [comment]
@gazhayes, the thing is, the 'graph data' cron job updates the upper and lower bound for graph values but until it's called, there can be issues like this if average ELO values change in the meantime. One solution is to run the cron job more often, and one solution is to call the `updateGraphData` method every time `averageElo` method is called to ensure that the graph data will be correctly displayed.

**Comment by gazhayes** [comment]
> call the updateGraphData method every time averageElo method is called to ensure that the graph data will be correctly displayed.

That's probably the best solution as increasing the cron job frequency still won't *really* fix it.

**Comment by anbud** [comment]
Done in #344.
