### ISSUE TITLE
Problem: two route configs, one with unmaintained fork

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#307]
Problem: There's new flow router fork installed with it's implementation in imports/both directory, deleting the older one will not result in links continuing to work.

Solution: Change imports of older package with newer.

**Comment by janat08** [comment]
@gazhayes can i work on this?

**Comment by gazhayes** [comment]
Sure

**Comment by janat08** [comment]
fixed in #312

**Comment by gazhayes** [comment]
Since you logged this issue you can also close it if you are sure it's solved.
