### ISSUE TITLE
problem: no wallet activity badge

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#309]
Problem: when users recieve Krazor for fulfilling a bounty (or whatever) it would be nice for them to see a badge showing that there's a new message (e.g. how it currently works for message notifications).

Update: appears to be broken for message notifications.

**Comment by janat08** [comment]
I'll take this.

**Comment by gazhayes** [comment]
Also please pay attention to this with your next one:

Tell other people what you're doing by putting very clear and descriptive comments in your code every 2-3 lines.
Add your name to the AUTHORS file so that you become a part owner of Blockrazor.

**Comment by janat08** [comment]
It appears to be working, do you mean wallet notifications, and are there any specific bounty transactions that don't show up?

**Comment by gazhayes** [comment]
What I mean is the notification badge showing how many new notifications there are. I tried to get you a screen shot but it appears to now be broken. It was introduced in #83.

So maybe you can fix it for the notification messages and also implement it for wallet messages.

**Comment by janat08** [comment]
I'll go and make it reactive by writing to user data, and subscribe to it globally.

**Comment by gazhayes** [comment]
Making it reactive is also good. The main thing though is that the badges start working again.

**Comment by janat08** [comment]
Or just read from activity log if that's a notifications collection. I belief meteor-peerdb would work nicely here.

**Comment by gazhayes** [comment]
> meteor-peerdb would work nicely here  

Yes but it's extra weight and not necessary.

Did you look at #83?

**Comment by janat08** [comment]
Yes, but I shouldn't count records reactively which is what this avoids, and then incrementing userData collection's field to show data is brittle. I could probably just find relevant records and count them server side, in lieu of counting (which I'm don't know if is justifiable).

Also, it looks like I'm in for layout work since that implementation just linked relevant page (there're two now). I could show a drop-down displaying all notifications within the drop-down.

**Comment by gazhayes** [comment]
> I could probably just find relevant records and count them server side, in lieu of counting (which I'm don't know if is justifiable).

Yeah that would be ok.

It is currently being done server side here: https://github.com/Blockrazor/blockrazor/blob/e42906aed4365e522481d832f3ea1925500e83a3/server/methods/notifications.js

>Also, it looks like I'm in for layout work since that implementation just linked relevant page (there're two now). I could show a drop-down displaying all notifications within the drop-down.

Don't you just need to add a badge to the UI?

**Comment by janat08** [comment]
I meant count on clientside, but I suppose I'll just make it work as per protocol.

**Comment by gazhayes** [comment]
Are you worried about server load doing it server side?

A small thing like this probably won't have much of an effect, but I'm a little worried about client side performance/loading times.

What do you think?

**Comment by janat08** [comment]
Just invoking minimongo is allegedly expensive while its' methods are cheap. There's a suspicion that counting in the publication will cause a disconnect to a degree that MDG dev release package for collections with 100 documents which is supposed to be an improvement: https://github.com/percolatestudio/publish-counts.

**Comment by gazhayes** [comment]
Oh wow ok I was completely unaware of this.

So are you saying that doing on server side is better, or client side, or you want to use another package?

**Comment by janat08** [comment]
I was going to do it client-side to revisit the topic, I don't think that using a package would be sensible as you intend for there to be more notifications in app at which point it would make sense to write to user field or use a single collection.

**Comment by gazhayes** [comment]
OK, yeah just follow the protocol then and use the simplest solution, we can revisit it later.

**Comment by janat08** [comment]
fixed in #319
