### ISSUE TITLE
Problem: [ratings] confusing response if a user tries to add wallet pictures for currency that they've already previously added images for

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#31]
On the ratings page (/ratings) (ratings.html template) if a user adds a currency that they've already added previously and click next it just goes back to the same page. 

Solution 1: add a list of currencies that this user has already added/rated to the top of the page and let them know they can add more if they want

Solution 2: show an error message when a user adds a currency that already exists under their username. This is more complicated than solution 1 due to the way the database is populated.

**Comment by anbud** [comment]
I'm taking this one.

**Comment by anbud** [comment]
Fixed in #119.
