### ISSUE TITLE
problem: strange reward amounts for ratings

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#310]
Problem: reward amounts for answering questions appear to have the decimal in the wrong place. 

![](https://blockrazor.org/static/images/wallets/312950fe9d9668336ac1be8990c4d434.jpeg)

**Comment by anbud** [comment]
@gazhayes, if you're answering them with no active bounty, without a fixed reward, these values are correct. I've set the reward multiplier to 0.3 so the values are quite small. Should I increase them to something more meaningful?

**Comment by gazhayes** [comment]
I tested it by launching through the bounty page (was about 5 Krazor at the
time).

What you have now is fine for launching without the bounty, but maybe
there's a nicer way to display small values?

On Mar 4, 2018 12:03, "Andrej Budinčević" <notifications@github.com> wrote:

@gazhayes <https://github.com/gazhayes>, if you're answering them with no
active bounty, without a fixed reward, these values are correct. I've set
the reward multiplier to 0.3 so the values are quite small. Should I
increase them to something more meaningful?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Blockrazor/blockrazor/issues/310#issuecomment-370186971>,
or mute the thread

**Comment by anbud** [comment]
I've tested it a few times with various bounties, they all started correctly, and the rewards were awarded correctly. But I may have an idea why the bounty didn't start at your end, and I'll send a PR shortly. Also, for displaying small values, I'll use `.toExponential(3)` which transforms, for example, `0.000000000122323232` to `1.223e-10`.

**Comment by anbud** [comment]
Should be fixed in #326.
