### ISSUE TITLE
Problem: home route search is too complicated

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#315]
Problem: Seaching for a currency on the home route is a little bit confusing/complicated/messy. It also doesn't scale well to different screen sizes.

![](https://blockrazor.org/static/images/wallets/cfcb91d7f1bebdb1a1e021a738c46426.png)

Possible Solution:   
Make a single 'search' input which renders the other fields (and anything we add later) when selected. This should also search onKeyUp (or whatever) so that a submit is not needed.

**Comment by AshHimself** [comment]
That should be easier enough, single query using mongoDB $or operator on all those fields and we can expand on that as we go scale.

**Comment by gazhayes** [comment]
Yeah, name and currency code is probably all that's needed for the main search bar.

**Comment by janat08** [comment]
Doing this.

**Comment by AshHimself** [comment]
Sorry forgot to assign this to me and already stated.

**Comment by janat08** [comment]
Stopping.

**Comment by gazhayes** [comment]
@MadanBhandari please take note of this one and discuss with @AshHimself

**Comment by MadanBhandari** [comment]
@AshHimself @gazhayes : what about fix search by name and symbol in top navigation ? This will be visible across whole website and should return to home route with results, whenever user search something.

**Comment by AshHimself** [comment]
Done in #342
