### ISSUE TITLE
Problem: publications unreactive check for meteor.userId

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#318]
Problem: publications aren't reactive so that if a user logs out, the session will continue behaving as if he's logged which is important for navbar items that don't reset on log out as templates, keeping subscriptions alive

Solution: use some sort of reactive package for publications, or tracker autorun on server (if the lib code is up to it).

**Comment by janat08** [comment]
My package of choice breaks on 1.6.1 awaiting comments from maintainer:  https://github.com/peerlibrary/meteor-reactive-publish/issues/33

**Comment by gazhayes** [comment]
I've had a look and I'm not seeing the actual problem, when I log out the menu is reset. Am I misunderstanding the issue?

**Comment by janat08** [comment]
https://guide.meteor.com/security.html#publications-user-id
I misconstrued the issue myself.

**Comment by gazhayes** [comment]
Does that mean this isn't really a problem?

**Comment by janat08** [comment]
No, not unless you intend to kick moderators a lot and then publish sensitive data.
