### ISSUE TITLE
Problem: easy for users to pull wallet images from site and re-upload

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#32]
Solution: watermark uploaded images to enable easy detection of re-used images.

**Comment by gazhayes** [comment]
http://www.imagemagick.org/Usage/annotating/

**Comment by gazhayes** [comment]
@AshHimself what's the status of this one?

**Comment by AshHimself** [comment]
I dropped you an email as I was having issues getting access to the meteor
logs, any chance you can help me out with that?

**Comment by gazhayes** [comment]
Does it work locally on your dev machine?

**Comment by AshHimself** [comment]
It does mate, can we check on the server if these dependencies are installed? It should console.logon the server if they are not found when attempting to upload an image but I can't confirm.

https://www.npmjs.com/package/gm

**Comment by gazhayes** [comment]
Reminder to self, this isn't working on server, need to check what's going on
