### ISSUE TITLE
Problem: Some routes are not rendering

### ISSUE THREAD

**Issue by anbud** [Blockrazor/blockrazor#322]
Problem: After #312, the following routes: `/add-hashpower`, `/flagged-hashpower`, `/hashpower`, `/changedCurrencies`, `/compareCurrencies`, ... are refusing to render as their templates are not imported into the new router.

Solution: Import the templates accordingly

**Comment by anbud** [comment]
Done in #323.

**Comment by gazhayes** [comment]
@janat08 please take note
