### ISSUE TITLE
Problem: Bubble notifications appear to be broken

### ISSUE THREAD

**Issue by anbud** [Blockrazor/blockrazor#327]
Problem: Bubble notifications (handled with `sAlert`) appear to be broken sitewide. I'm not sure what's the cause, but they are not showing anymore. 
I've tried calling them from the console, only notification id is returned.

**Comment by gazhayes** [comment]
Possibly related to #317

**Comment by gazhayes** [comment]
@janat08 do you want to see if you can fix this?

**Comment by gazhayes** [comment]
I just tried creating a new account with a username that is already taken (to produce an error). It's working there.

**Comment by janat08** [comment]
I'll do it last for when there're details forthcoming.

**Comment by gazhayes** [comment]
@anbud where did you notice it being broken?

**Comment by janat08** [comment]
sAlert wasn't included in the desktop layout.

**Comment by janat08** [comment]
fixed in #339
