### ISSUE TITLE
Problem: Users can't delete their own hash power data

### ISSUE THREAD

**Issue by anbud** [Blockrazor/blockrazor#328]
Problem: I've accidentally deleted the `deleteHashpower` method in one of the previous PRs, so users can't delete hash power data they've added.

Solution: Revert the deletion, add the method required again.

**Comment by anbud** [comment]
Done in #329.

**Comment by gazhayes** [comment]
I've been closing your resolved issues, but actually whoever logs an issue should close it when they believe it's resolved (even if they are the ones who resolve it with a pull request).
