### ISSUE TITLE
Problem: no size/type checks on wallet image uploads

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#33]

**Comment by AshHimself** [comment]
@gazhayes - To ensure the best security i've implemented checking on the client for extension and then on the server for the actual MIME type check using the NPM [mime-types](https://www.npmjs.com/package/mime-types) library. Few questions though,

- Success and failure of upload is not returned to the user for anything at present. Should we create a ticket for this?
- I have created a global variables folder to allow max file size and valid file types to be managed via global variables. Is this ok?

**Comment by gazhayes** [comment]
>Success and failure of upload is not returned to the user for anything at present. Should we create a ticket for this?    

Yes I forgot to create an issue for that, opening one now

> I have created a global variables folder to allow max file size and valid file types to be managed via global variables. Is this ok?    

Perfect! Thanks :)

**Comment by gazhayes** [comment]
Added #82 and #79 in relation to this issue.

**Comment by gazhayes** [comment]
Fixed in #81
