### ISSUE TITLE
Problem: no public user profiles

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#330]
Problem: there's no basic user profile page.

Solution: implement some kind of basic user profile page with username, profile image, currencies that this user has added to Blockrazor, and anything else that's easy to implement (e.g. maybe their comment history). This will probably be extended later with more stuff as things develop further. Would also be nice to have a an easy way to integrate a hover UI element in other pages (e.g. display user profile image when hovering over a username on a comment).

**Comment by AshHimself** [comment]
I’ll take this.

**Comment by janat08** [comment]
It's assigned

**Comment by gazhayes** [comment]
@AshHimself I'd prefer @anbud to do this one. I think you're working on some other stuff right now?

**Comment by AshHimself** [comment]
All good, I didn't see it assigned :)

**Comment by anbud** [comment]
The basic functionality is done in #346.
