### ISSUE TITLE
problem: no way to monitor and/or benchmark performance

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#332]
Problem: no way to monitor and benchmark performance.

Solution: Implement Kadira on a private instance. I understand this is low priority but project is scaling quite fast and would be good to know what methods are performing badly or if the overal site is loading slow due to bad mongoDB indexing etc.

Thoughts @gazhayes?

**Comment by gazhayes** [comment]
Definitely low priority for now, but yeah it's going to become necessary.

**Comment by AshHimself** [comment]
@gazhayes - so its an opensource project which was bought by Meteor and runs as an APM on Galaxy. From what I know its the only Meteor based APM tool out there. You can get it up and running on your own instance however. I always found it very helpful to spot slow running queries, bad performing methods or locks in the DB (bad indexing or horrible)

https://github.com/kadira-open/kadira-server
https://sergiotapia.me/how-to-setup-your-own-kadira-instance-on-a-vps-like-digitalocean-75ef1458adbd

**Comment by gazhayes** [comment]
Cool. Have you used it before in any projects?

**Comment by gazhayes** [comment]
Rightio, I'll set this up over the next few days and we can all see who's been writing slow code.

**Comment by AshHimself** [comment]
Haha not sure what the others think, they may know other tools or methods I
don’t?

If you want to test it you can deploy it to galaxy temporarily.

**Comment by janat08** [comment]
I think there's command that asks mongo about what abuse it took as far as indexes go.

**Comment by gazhayes** [comment]
This is a report from Pingdom:

<img width="1047" alt="screen shot 2018-04-19 at 6 52 04 pm" src="https://user-images.githubusercontent.com/8143945/38987555-ce64f8f8-4402-11e8-8b7e-8d15daad91d3.png">

It would kind of be cool to know why there are all these 1/2 second 'connect' and 'wait' periods which add about 2 seconds to load time. I guess it's just ping time which Meteor can do nothing about, but worth confirming. DNS lookup is also taking almost 700ms but again that's out of Meteor's control so I'll dig into that later.

**Comment by AshHimself** [comment]
@gazhayes we can close this if you want mate.

**Comment by gazhayes** [comment]
-
