### ISSUE TITLE
Problem: Signaling list's readiness state

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#334]
Problem: Combination of #192 and #68. 68 being about empty lists not saying anything, and 192 rendering DOM before subscription readiness (also an empty list).

Solution: Show spinner or no records found.

**Comment by AshHimself** [comment]
This is something which could be tackled as part of the UX overhaul within each template itself.

**Comment by janat08** [comment]
I'm switching out subscriptions anyway.

**Comment by janat08** [comment]
I was going to do subscriptions first since subs-manager will have its own subs ready method.
