### ISSUE TITLE
Problem: fast render isn't working for graphdata on / route

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#335]
Problem: Subscribing to graphdata to be fast rendered in routes fails. error:
```
Exception in defer callback: TypeError: Cannot read property 'getContext' of null
    at Blaze.View.<anonymous> (http://localhost:3000/app/app.js?hash=9c46df6c192d7fcd96cbe83f736b01df0020b41f:10851:73)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934:20
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1932:29
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271:12)
    at viewAutorun (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1931:18)
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:339:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:229:10)
    at Object.Tracker.autorun (http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:613:11)
    at Blaze.View.autorun (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1944:22)
```

Solution: I can't tell.

**Comment by janat08** [comment]
It's not precisely the graphdata sub that fails, a combination of returnedCurrencies and graphdata will fail, each alone/individually alone not causing errors (although obviously graphdata sub will not get used without returned currencies since lists are rendered by returnedCurrencies). The route for single currency doesn't cause errors although it subscribes to both graphdata and returnedcurrencies.

**Comment by janat08** [comment]
I will try and determine if it specifically error with blaze or graph- in which case I'll give up.

**Comment by MadanBhandari** [comment]
This is not in `/` route, it's on `currency/currencyName`.

Solution:  
Remove distribution chart in `currencyDetails.js` as we are not using distribution chart anywhere.
OR
Add distribution chart in `currencyDetails.html`

**Comment by janat08** [comment]
yes, ty, that indeed throws an exception too without giving blank screen.

**Comment by janat08** [comment]
I'm not working on this. @MadanBhandari

**Comment by janat08** [comment]
register graphdata subscription in '/' route when done.

**Comment by gazhayes** [comment]
The other thing we could do which would also speed things up is pre-render the chart in a cron job every x minutes and just send the image without the subscriptions.

**Comment by janat08** [comment]
I looked at SSR packages compatible with blaze and they don't much to help with the first load (although there's flow-router v4 branch that was suppose to do SSR), loading from the method instead. I could load with meteor's server-render and hyperhtml.

**Comment by gazhayes** [comment]
That seems like a lot of work, have you done something like this before?

> I can't use serrver-render since it requires conflicting package.

which package?

**Comment by janat08** [comment]
server-render needs static-html package which blaze's compiler conflicts with.

**Comment by gazhayes** [comment]
Ok. Maybe @anbud or @AshHimself have some ideas.

**Comment by janat08** [comment]
there's viperHTML which is meant for SSR, although I struggle to understand it (not that it's complex).

**Comment by gazhayes** [comment]
You could also post the error to the Meteor forums, someone might have seen something like this before and have some idea of what's going on.

**Comment by janat08** [comment]
static-html and blaze's compiler are competing packages.

**Comment by gazhayes** [comment]
@janat08 What if we denormalized graphdata into the currencies collection?

**Comment by janat08** [comment]
In case you're not aware MadanBhandari posted solutions above which are correct even if I don't know what he's talking about. I imagine what's happening is that the fast render code that runs to determine what data is needed to half-way render it is a whole lot less forgiving than blaze thus breaking. The reason why I indulged you is that I assumed you're not trying to solve topic's issue per se (which is that fast render isn't even enabled for graphs), but rather improve app load time at which point changing schemas is overkill.

**Comment by MadanBhandari** [comment]
If no one is working on this right now, I will do this tonight (GMT+5:30).

**Comment by MadanBhandari** [comment]
#363

**Comment by janat08** [comment]
I'm integrating #363 into consolidated graph template.
