### ISSUE TITLE
Problem: mongo subscriptions don't start and end correctly

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#34]
Possible solution: put subscriptions in a tracker.autorun function at the template level

**Comment by janat08** [comment]
ratings count is now observed which may not be the ideal solution, as it previously used onReady callback of subscription expression. I could stick it into nonreactive tracker within reactive subscription expression's callback instead.

Counting records, even in this manner, I hear is pretty bad I imagine as it may assume that there're filters set after which it will have to scan for edited documents upon reading about it in oplog to determine which filters apply to this record and consequently count.

**Comment by janat08** [comment]
This took me around 30 mins, at 12$ an hour, here's my upwork: https://www.upwork.com/freelancers/~01eb063baa9c98f0b0

Previous activities took me 70 mins some of it including rechecking protocols and familiarising with project.

**Comment by gazhayes** [comment]
Fixed in #65
