### ISSUE TITLE
Problem: add new coin page layout is nasty

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#347]
Problem:  the layout of the add new coin page is weird, its hard to know where to even look. There has to be a better way to do this. 

It's also using a different template to everything else so no menu etc, and it's not using bootswatch.

**Comment by AshHimself** [comment]
Done in #352 - Any feedback for changes? 

Which view would you like me to tackle next?

**Comment by gazhayes** [comment]
Ah yeah it broke the site, also I shouldn't have merged it as it's not following the protocol.

**Comment by gazhayes** [comment]
Reverting in #354

**Comment by AshHimself** [comment]
Fixed in #357
