### ISSUE TITLE
Problem: users cannot upload profile image

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#348]
There's some existing image upload boiler plate for wallet image uploads and coin logo image uploads.

**Comment by gazhayes** [comment]
If a user signs up from facebook or github it would be better to pull their profile picture from there first but allow them to change it later.

**Comment by AshHimself** [comment]
Can we pull github/facebook image profile image first?

**Comment by anbud** [comment]
Done in #351.
