### ISSUE TITLE
Problem: can't see Meteor CLI output without SSHing into server

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#355]
Problem: sometimes it's very useful to see the Meteor CLI output while it's running, but the only way to do this at the moment is by SSHing into the server and resuming a `screen` session. Maybe there's a way to output it to a text file or something (and put this in a directory served by Nginx).

**Comment by anbud** [comment]
The output of the meteor server can be easily redirected to a text file anywhere on the server using `>>` (append) operator on Linux. (e.g. `meteor --production >> /var/www/log.txt`)
