### ISSUE TITLE
Problem: when refreshing currency detail page, radar chart loses data

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#359]
Problem: when opening a currency detail page from the home route everything is fine, but going to the currency detail route directly produces strange results on the radar chart.

**Comment by janat08** [comment]
working on it

**Comment by gazhayes** [comment]
Related: #372

**Comment by gazhayes** [comment]
Related: #371

**Comment by janat08** [comment]
Will later on convert to making sure that graph only loads when subs are ready which is what caused the issue, once subs-cache is back in.
