### ISSUE TITLE
Problem: wallet images not shown on currency page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#36]
Solution: add wallet image gallery to currency detail page

**Comment by AshHimself** [comment]
@gazhayes - are you fussed on how these images are presented at the moment or just happy to have the images related to the currency returned. We can possibly display thumb nails in the future and use semantic-ui modals to enlarge them?

**Comment by gazhayes** [comment]
At this point it doesn't really matter because the UI will probably change beyond recognition anyway, it will just be used as a starting point for UI 'refinement'.
