### ISSUE TITLE
problem: votes are logged but not visually depicted in the UI

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#361]
Problem: when casting votes on the currencyDetail page they are logged in the database but if the page is refreshed you still have the ability to upvote or download again (though now allowed if tried)

Solution: display the tick if you have already voted or allow to change your vote (more complex)

@gazhayes

**Comment by gazhayes** [comment]
The simpler solution (displaying a tick) should do fine.

**Comment by AshHimself** [comment]
@gazhayes  - is it correct that you can only vote on one feature within the entire currency? or bug found/created.

**Comment by gazhayes** [comment]
I'm able to vote on multiple features on the production server, are you seeing something different?

**Comment by AshHimself** [comment]
try upvote on multiple comments sorry on different features.

**Comment by gazhayes** [comment]
OK, just tested quite comprehensively and everything is working.

Try making a new account (to rule out voting history etc) and see if you have the same issue.

**Comment by AshHimself** [comment]
Ok found the cause of the issue. The redflags.html comment template was actually using the same template as features when there is a redflags comment template.

**Comment by AshHimself** [comment]
Fixed in #390
