### ISSUE TITLE
Problem: Mocha + Chai not used for testing

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#367]

**Comment by AshHimself** [comment]
@anbud - Anyway to do tests which validates the data in mongoDB after a method has ran? Never really written tests in Chai or Mocha before.

**Comment by gazhayes** [comment]
@AshHimself what do you usually use for testing?

**Comment by anbud** [comment]
@AshHimself, you can import collections in Mocha, so you can query the database to see the changes after the method invocation.

**Comment by anbud** [comment]
This one is done in #376.

**Comment by anbud** [comment]
I forgot to say, this is the command to run the tests:  `meteor test --driver-package practicalmeteor:mocha`
