### ISSUE TITLE
Problem: repository does not use CI testing

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#369]
Problem: if you contribute to Blockrazor and send a patch, you probably don't want someone else to break your code later on. The solution to that is to write a test. However not everyone is going to run tests before sending a pull request, so it would be nice if tests were run automagically when sending a pull request.

Solution: Travis CI can hopefully be used with Meteor (or NPM) tests.

ping @anbud

**Comment by anbud** [comment]
@gazhayes, I've used GitLab CI runners for tests before, but I believe that Travis CI will work in the same way, I'll look into it. It's free for open source projects, so it's a perfect solution here.

**Comment by gazhayes** [comment]
We don't *have* to use Travis CI, but we do have to use something that's free.

**Comment by anbud** [comment]
@gazhayes,
I get this screen when I try to enable Travis CI on this repo. Can you give me the right access, or can you activate it, please?
![Image](https://i.imgur.com/l08ZOT8.png)

**Comment by gazhayes** [comment]
I activated it a few minutes ago, it might still be working its way though the tubes and pipes

**Comment by anbud** [comment]
Thanks. I've activated the repo, I'll run a build right now to see how it's working.

**Comment by gazhayes** [comment]
I can see it running now
