### ISSUE TITLE
Problem: radar chart on currency detail page different to home route

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#371]
Problem: the logic used to render the radar chart on the currency detail page is different to that of the home route (and the comparison page).

This should probably be modularized so that code is not repeated.

**Comment by gazhayes** [comment]
@janat08 do you think you could handle this one or too difficult?

**Comment by janat08** [comment]
It might take some time.

**Comment by janat08** [comment]
I could do it integrating #363, and possibly comparison page. I might just skip the ability to set width if just setting width/height to 100% of parent will not work.

**Comment by gazhayes** [comment]
Yeah that sounds good. Do you want to take it?

**Comment by janat08** [comment]
yes

**Comment by gazhayes** [comment]
> comparison page also

That would be pretty cool if you can do that, maybe too difficult though.

**Comment by janat08** [comment]
I suppose the comparison graph is undone.

**Comment by gazhayes** [comment]
Ah yes, that one is a bit more difficult. We can worry about that later.
