### ISSUE TITLE
Problem : Home page doesn't look nice on mobile devices

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#372]
Problem: Not fully responsive on mobile devices

Solution:
Add responsive meta tag
Update layout accordingly to adapt fully responsive.

@gazhayes : Assign this to me, I am starting working on this.

**Comment by gazhayes** [comment]
Are you still working on this one?

**Comment by MadanBhandari** [comment]
This has been updated on #413 and #514. Sorry, I forgot to update here.

Please check and close this issues.
