### ISSUE TITLE
Problem: user's proposed changes do not show up

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#373]
Problem: when proposing changes, a user's changes do not actually show up in the UI either on the page shown straight after submitting a change, nor on their pending changes/additions page.

**Comment by janat08** [comment]
I can see changes on page shown straight after, unless you use are adding data/filling in data rather than proposing actual changes.

Doing it.

**Comment by gazhayes** [comment]
I did a name change, can you try that and see if it works?

**Comment by janat08** [comment]
Works. Ill fix filling in data.

**Comment by janat08** [comment]
Actually, all of it works.

**Comment by gazhayes** [comment]
Ok must be something local to me.
