### ISSUE TITLE
Problem: when proposing changes, genesis block date month is off by one

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#374]
Problem: when proposing a change, the genesis block launch date shows the actual month -1

Haven't looked to see if this off-by-one error is created at the time of submitting a new currency, or at the time of converting epoch time to a human date on the 'edit currency' page.

**Comment by AshHimself** [comment]
Weird... i'll look into what I did wrong here..

**Comment by gazhayes** [comment]
It's just as likely to be my code on the add currency stuff

**Comment by AshHimself** [comment]
@gazhayes just trying to replicate this now. Can you still replicate? Possibly fixed as part of was anbud did with the new inline edits?
