### ISSUE TITLE
problem: / route is broken, no.currencies displayed

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#379]
Problem: / route just shows loading

![s80309-04185666](https://user-images.githubusercontent.com/8143945/37174422-66868142-2351-11e8-9010-f8da98c6ae90.jpg)

**Comment by janat08** [comment]
I think it's still the #335 if blockrazor has enabled graphdata for "/'' which it hasn't on github. Even if you disable it will cause issues navigating between pages and back to home.
