### ISSUE TITLE
Problem: currency detail page actions are broken (again)

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#384]
Problem: 

Modal should appear onFocus in this field:
![](https://i.imgur.com/qEo5iRE.png)

Comments and comment text box should be shown onClick:
![](https://i.imgur.com/gXvUdDX.png)

**Comment by gazhayes** [comment]
Exactly the same problem as #139 

Why is this so vulnerable?

ping @AshHimself @janat08

**Comment by janat08** [comment]
I couldn't find the route where this is.

**Comment by gazhayes** [comment]
Actually it's not broken. My mistake.
