### ISSUE TITLE
Problem: radar charts are misleading until there's enough data

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#385]
Problem: radar charts are misleading (and sometimes broken) before a currency starts getting ELO rankings.

Maybe dim/grey out the chart and put a notice saying more data is needed, until there's 'enough' data.

**Comment by sjmackenzie** [comment]
Thoughts: the notice could be a hyperlink to ELO rankings of that currency. I'm find there's too much clicking to get to the menu to add data to a coin. Probably every radar should have this link...

**Comment by gazhayes** [comment]
Yep not a bad idea at all.

**Comment by janat08** [comment]
Would using a median somewhere or adjusting rankings by relative amount of data or having elo ranking for data work? If you're investing money then our idea of what data is enough might be discouraging.

**Comment by gazhayes** [comment]
> our idea of what data is enough might be discouraging

I agree. Maybe some kind of metric underneath the radar chart to show how much data there is in comparison to the average (or median) of all currencies.

**Comment by gazhayes** [comment]
ping @MadanBhandari @anbud @AshHimself for any ideas

**Comment by MadanBhandari** [comment]
I am reading about these keywords mentioned in currency details page. Once I completely understood what each keywords means and it's importance, I will definitely suggest the layout. Currently on Reading/Research stage :)

**Comment by gazhayes** [comment]
Try (accurately and correctly) adding a new currency, that will lead you to research the right type of stuff.

**Comment by gazhayes** [comment]
ping @anbud can you link this to the metrics you just started collecting?

**Comment by anbud** [comment]
@gazhayes, surely. Should I just dim out the graph if the data quality rank is, let's say, below 1?

**Comment by gazhayes** [comment]
Yeah, that would do, we can fine tune it later or whatever

**Comment by gazhayes** [comment]
Oh and I guess it should be linked to the bounty page or something to suggest that users add more data

**Comment by anbud** [comment]
Done in #589.
