### ISSUE TITLE
Problem: comments cannot be posted on features 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#389]
Problem: adding comments to features is broken

**Comment by AshHimself** [comment]
Can't comment if you have already commented? perhaps a message stating that to users after posting?

**Comment by gazhayes** [comment]
I logged this too ambitiously, the message was too short so I was getting an error that's all

**Comment by gazhayes** [comment]
>perhaps a message stating that to users after posting? 

Probably better to do it before posting, so they choose their words carefully
