### ISSUE TITLE
Problem: users can create multiple accounts

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#39]
Possible Solutions:

- Log user IP address and check for multiple accounts using same IP
- Only allow sign up through other services (e.g. github/facebook/linkedin/google)
- Log user local timezone and cross reference with IP for people using VPN etc
- Tracking user hardware: http://yinzhicao.org/TrackingFree/crossbrowsertracking_NDSS17.pdf
- Tracking user interaction (e.g. if one user keeps approving another user's changes there might be a problem, especially if those changes are later flagged by other users as spam/incorrect/incomplete)
- canvas fingerprinting
- log-in times and relationships between log-in times of different accounts (if one account always logs in after another account they might be related)

**Comment by AshHimself** [comment]
@gazhayes - I am about to submit a PR for this ticket. I have implemented the following solution so far which should allow us to report on suspected users.
- Log user IP address on login and registration. 
- Raise warning in mongoLogger if you register a user and another user exists with the same IP address.
- Raise warning in mongoLogger if you login and the same IP was logged in with another account.

**Suggestions**
Validate users via SMS. https://www.twilio.com/authy offers an extremely simple NPM package.

**Comment by gazhayes** [comment]
Just realized I didn't explain why this is a problem.

Users could create multiple accounts and approve their own changes (especially when there's a bounty incentive).

**Comment by gazhayes** [comment]
SMS validation is not a bad idea at all.

I'm thinking:
User level 0: can follow other users, add favourites, etc. 
User level 1 (sms validation): Can earn bounties, and are eligible to become moderators (i.e. same as maintainers under the C4)
User level 2: these are moderators/maintainers who can approve "pull requests" (anything that adds or changes data)

**Comment by gazhayes** [comment]
https://receive-a-sms.com kind of destroys the sms idea

**Comment by AshHimself** [comment]
@gazhayes - we can validate mobile numbers on validation. e.g. only validate a number once.

**Comment by gazhayes** [comment]
Looks like SMS validation is not any more reliable than email validation. IP logging will do for now and I'll look at some more advanced  fingerprinting later. 

With IP logging though, suspect accounts need to be flagged and added to a list. This list will later be something like the moderation queue but instead show user history (a seperate issue) so its easy to see any accounts that are doing weird things (and ban them).

**Comment by AshHimself** [comment]
@gazhayes - It may be my local instance but I was able to sign up with two accounts with facebook and github. Are you getting the same results? I tried to test on production version and was not able to.

**Comment by gazhayes** [comment]
Do you mean you were able to sign up twice with, for example, the same facebook account?

That's probably just some quirk with changing hosts/domain, in that case it shouldn't affect production.

**Comment by AshHimself** [comment]
No I mean, I could signed up with two accounts; 1 account was facebook, the
other was github ,both with same email. I suspect this is just an issue
locally but thought i'd raise it none the less so we can test properly once
in production.

**Comment by gazhayes** [comment]
Oh ok, that's not surprising, there's nothing preventing it (yet). 

What's needed is a master list of email addresses and if a users tries to sign up with one that's already in use, prevent it. Same for IP addresses, except include not only signup IPs but also access IPs.

**Comment by gazhayes** [comment]
@anbud can you have a look at this and see if you have any ideas?

**Comment by anbud** [comment]
@gazhayes, basically, the solution with the email master list is fine for email checking, and it should be implemented. We could very well save the email for every user anyway since both Facebook and GitHub return the email amongst other data. Other than that, browser fingerprinting (both hardware and canvas) is also a nice way to prevent this and it's quite easy to implement. And SMS validation is also fine. I mean, you can never fully prevent this, but if we implement everything we can, at least we can reduce it to a small percentage.

**Comment by anbud** [comment]
@gazhayes, should I implement any of that?

**Comment by gazhayes** [comment]
> the solution with the email master list is fine for email checking, and it should be implemented

Definitely do that. And something similar for IP addresses (not just sign up and login but also access). I'm not sure exactly how to handle IP address control, I guess a first step is to set a flag for any accounts that use an IP address which has already been used and we can decide later how to handle it.

Don't worry about browser fingerprinting, but timezone logging would provide a very useful data point. 

The main thing we are fighting is people approving their own changes etc with a second account. The bar for becoming a moderator is very low (80% of users will probably be moderators). It's basically the C4 but for data control instead of code.

**Comment by anbud** [comment]
I'm on it then.

**Comment by anbud** [comment]
@gazhayes, done in #172. While working on it, I've got another idea on how to reduce multiple account creation. Should we check whether the email is disposable? (for example, @guerrillamail.info)

**Comment by gazhayes** [comment]
> Should we check whether the email is disposable?

Yeah that's a good idea. 

I'm just looking at #172, I'm running low on sleep but I can't see how you are storing and referring to a master list of IPs and email addresses?

**Comment by anbud** [comment]
Then it'll be implemented. 
For #172, instead of storing a master list (which would be a waste of memory, since we already have this data saved), I'm saving user's email address in `email` field in the user object. That way, we can easily query the database to see if the email is already in use. If you're worried about performance here, I can add an index on `email` field to improve search performance. As for IP addresses, they are stored in the `UserData` collection, in `sessionData` array. Each time the user logs in, his/her IP address and current timestamp will be saved (along with headers, which could impact performance). That way, we can also easily query the database to see whether an IP has been used before, either for signup or login.

**Comment by anbud** [comment]
Disposable emails check has been implemented in #174.

**Comment by gazhayes** [comment]
> As for IP addresses, they are stored in the UserData collection, in sessionData array. Each time the user logs in, his/her IP address and current timestamp will be saved (along with headers, which could impact performance). That way, we can also easily query the database to see whether an IP has been used before, either for signup or login.

Ok cool. Is that being done now with that PR?

**Comment by anbud** [comment]
@gazhayes, yap.

**Comment by anbud** [comment]
@gazhayes, in #177, I've implemented a page where moderators can easily see which users are flagged. How should the voting system work? More than 3 votes would result in a ban or? Should I go on with the banning system implementation, or should I leave it as is for now?

**Comment by gazhayes** [comment]
Leave this one as is for now. With real data the solution will become more clear.
