### ISSUE TITLE
problem: scroll position is not consistent

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#393]
problem: scroll position is not consistent when navigating from page to page. e.g. if you scroll down half way on one view, then navigate to addCoins its not scrolled to the top of the page where it should be. 

Solution: Implement something like https://github.com/tomwasd/flow-router-autoscroll

**Comment by janat08** [comment]
taking this.

**Comment by gazhayes** [comment]
I just sent you a message about another one, can you check first?

**Comment by janat08** [comment]
untaking this

**Comment by AshHimself** [comment]
Fixed in #473
