### ISSUE TITLE
Problem: currency detail graph is off center

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#396]
Problem: I made new graph template that went off-center even if I tried to preserve options and classes. in #395

@MadanBhandari

**Comment by MadanBhandari** [comment]
I'll take this

**Comment by gazhayes** [comment]
Related: #404

**Comment by gazhayes** [comment]
@MadanBhandari when you think you've fixed something, comment in the issue to let everyone know that it can be tested and closed.

**Comment by MadanBhandari** [comment]
Updated on #412  and will update overall layout while working on #440
