### ISSUE TITLE
Problem: no central place to view all transactions

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#399]
Problem: a page is needed where users can view all transactions on Blockrazor, and the sum total of all coins "moved" from the master wallet (which doesn't exist yet but will contain the maximum allowable coins provided to Blockrazor in the genesis block or Krazor) to anywhere else. This will essentially be the number of coins brought into circulation through bounties etc on Blockrazor (as opposed to the number of coins brought into circulation through mining).

**Comment by anbud** [comment]
Done in #420.
