### ISSUE TITLE
Problem: updating currency data is convoluted

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#405]
Problem: the UI for updating values about a currency is basically just the add currency form. This is more confusing than it needs to be. Maybe a modal or something for the specific value that is being updated (well, being proposed to be updated) would be better.

@AshHimself how much work is in this?

**Comment by gazhayes** [comment]
ping @anbud for any ideas

**Comment by AshHimself** [comment]
@gazhayes - we could do inline editing or a modal just how you suggested. Something like https://vitalets.github.io/bootstrap-editable/ should give you an idea.

**Comment by anbud** [comment]
@gazhayes, yap, when I logged the issue, I've had something like @AshHimself just suggested in mind. I believe that inline editing would be a sufficient solution here.

**Comment by gazhayes** [comment]
Yeah that library looks perfect. @AshHimself you're pretty busy on other issues right? @anbud do you want to do it?

**Comment by gazhayes** [comment]
Just to be a little more clear: I personally think the best place for this to happen is directly on the currency detail page rather than going to another page with all the values.

**Comment by AshHimself** [comment]
I'm happy to do it but won't get to it till tomorrow however as i'll be out today. @anbud if you want to do it today feel free to grab it :)

**Comment by anbud** [comment]
Sure thing, I can take it. I agree, the best place is the currency detail page, there's no need to take the user elsewhere.

**Comment by gazhayes** [comment]
@anbud while you're in there you might want to look at #403 too.

**Comment by AshHimself** [comment]
Should we retire the old changeCurrencies view at the same time? being that was a horrible way to do it to start with?

**Comment by gazhayes** [comment]
Yeah it will be redundant once this is solved.

**Comment by anbud** [comment]
@gazhayes, sure thing, I'll check that out as well.

**Comment by anbud** [comment]
Done in #447.
