### ISSUE TITLE
Problem: no tests to confirm correct file upload directory 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#408]
Problem: when working on the relevant methods on a local dev server people change file upload directories to work on their local system and quite often forget to change them back before sending a pull request.

Some simple tests should solve this.

**Comment by AshHimself** [comment]
Might take a go at this to learn mocha (no paid contribution) learning exercise for myself if that's ok with you.

**Comment by gazhayes** [comment]
Sounds like a great idea ;)

**Comment by AshHimself** [comment]
@anbud I just sent a PR through for this. Any suggestions? or this an ok first stab at a mocha script.

**Comment by anbud** [comment]
@AshHimself, it's perfectly fine for the first stab. Since `properties.js` is a javascript file, I would just import it with `import` and assert if variables are well defined and all. But, your solution is also fine, it basically does the same thing.

**Comment by AshHimself** [comment]
doh.. didn't even think of that. Must of been late last night :D
