### ISSUE TITLE
Problem: sessiondata is only being logged once

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#41]
Sessiondata should be logged at each login to capture user IP address (related to #39 )

Sessiondata logging starts here: https://github.com/Blockrazor/blockrazor/blob/master/server/main.js

**Comment by Fen747** [comment]
Should the sessiondata be updated at every user  login or every user connection to the server ?

In the first case, we might need to logout users after a certain timeout, or log them out of every session.
In the second case, we'll store data everytime the user open a tab to blockrazor.

What would be the exact benefits / use of saving every connection timestamp and headers ?

**Comment by gazhayes** [comment]
Sessiodata should be logged each time a user opens a new tab (or whatever). The reason is just to build up a user fingerprint for multiple account detection (see #39). Unless they are actually logging in (new browser or device) the IP is probably all that's needed.

**Comment by AshHimself** [comment]
@gazhayes - per [PR](https://github.com/Blockrazor/blockrazor/pull/86), IP address are now logged on each login event and session renewal. Can this ticket now be closed?
