### ISSUE TITLE
Problem: uploading wallet images not working

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#411]
Problem: when trying to upload wallet images it just keeps loading forever. Please try and replicate this in case it's just me. Looks to have started in #409

**Comment by AshHimself** [comment]
Yah this is broken, a lot of JS errors in console due to undefined variables. Looks like its broken in the import restructure.

**Comment by gazhayes** [comment]
OK, let's see if @janat08 can fix it

**Comment by janat08** [comment]
fixed
