### ISSUE TITLE
problem: profile popovers are broken

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#415]
Problem: On the currency detail page, when users add comments, features, or red flags, their username could be clicked to view their profile. You could also hover over their name to view their profile picture.

@AshHimself I *think* your PR broke this one

**Comment by AshHimself** [comment]
Yah.. I broke this. Looks like I actually forgot to merge the popover code in. Will move back in.

**Comment by AshHimself** [comment]
Done in #495
