### ISSUE TITLE
Problem: Nginx says nothing while Meteor is rebuilding

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#424]
Problem: when a pull request is merged, the production server rebuilds Meteor. It can sometimes take a while to rebuild.

This means blockrazor.org tries to load for a long time and then fails with a 502 error. 

As more people get involved, it would be nicer if instead, as soon (i.e. retry for 500ms instead of 5s or whatever it's doing now) as nginx can't find anything running on port 3000 locally, to say something like 'Meteor is restarting, please wait...'.

**Comment by anbud** [comment]
I believe there's a better solution, we can have absolutely no downtime while redeploying. It's done by running two meteor instances and a load balancer (nginx can act as one, caddy also). When redeploying, first deploy the first one, while the other one is still working, then deploy the second when the first one is up. It takes a little bit more resources, but it provides us with virtually no downtime at all.

**Comment by gazhayes** [comment]
Yeah that would be considerably better. And we should definitely do it that way before making it 'public'. The load balancing would be a good idea too just to provide a bit of redundancy and stability. 

It's not a big enough or near enough problem right now, so instead of solving it in a half assed way right now (as I described above) I'll just leave it be and stick it in low priority to track it for when it becomes a valuable enough problem to make it worthwhile to implement load balancing.
