### ISSUE TITLE
Problem: wallet images aren't displayed very nicely

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#425]
Problem: the wallet images in currency detail page aren't displayed very nicely. Should use a modal (or something).

**Comment by AshHimself** [comment]
We spoke about this before @gazhayes, but I propose that part of the upload process we create a thumbnail, this is fairly straight forward and will speed page load time & yep I totally agree that it should be in a modal, easiest and best way to do it.

**Comment by gazhayes** [comment]
Yes, at this point I completely agree

**Comment by AshHimself** [comment]
Done in #491

**Comment by gazhayes** [comment]
I'm guessing this is because thumbnail generation only runs after uploading? If so no need to fix it.

<img width="251" alt="screen shot 2018-03-11 at 9 37 36 pm" src="https://user-images.githubusercontent.com/8143945/37254025-743e4c46-2574-11e8-8a3a-d188514d65f5.png">

**Comment by AshHimself** [comment]
Yeh that's right mate.. next time you are cleaning up data maybe just blow away all the images in there now or something. File size on thumbnails is like 100 times smaller so page should load super fast now :)

**Comment by gazhayes** [comment]
Oh hold up, directory is incorrect.

<img width="515" alt="screen shot 2018-03-11 at 9 40 31 pm" src="https://user-images.githubusercontent.com/8143945/37254068-e2738514-2574-11e8-858d-c628bb57c880.png">
<img width="429" alt="screen shot 2018-03-11 at 9 40 17 pm" src="https://user-images.githubusercontent.com/8143945/37254069-e29bbd36-2574-11e8-8510-0ee2735aa4c6.png">
<img width="186" alt="screen shot 2018-03-11 at 9 40 03 pm" src="https://user-images.githubusercontent.com/8143945/37254070-e2c3e61c-2574-11e8-9a55-d0a4d82c2ed9.png">

**Comment by AshHimself** [comment]
Pushed another PR

**Comment by gazhayes** [comment]
Still wrong dir

**Comment by AshHimself** [comment]
Ws using wrong helper name :( PR inbound.

**Comment by AshHimself** [comment]
Looks to be fixed in #493

**Comment by gazhayes** [comment]
I'm getting this for the recent image you uploaded, but existing images are working.

<img width="177" alt="screen shot 2018-03-11 at 10 45 43 pm" src="https://user-images.githubusercontent.com/8143945/37254815-2fb49152-257e-11e8-8281-2146b88aab40.png">

**Comment by AshHimself** [comment]
@gazhayes this all ok for you now mate?

**Comment by gazhayes** [comment]
No, still broken. Try uploading to production site and testing.

**Comment by AshHimself** [comment]
This is now resolved, was an issue with the watermark image location.
