### ISSUE TITLE
problem: Krazor coins only flowing one way

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#427]
Problem: Blockrazor itself will need some income to pay for server upkeep etc. At the current time, Krazor coins are only flowing from Blockrazor to users (to pay for bounties etc).

One possible way to make coins flow back to Blockrazor is to have a running auction for a 'featured' currency/ICO/whatever. This would simply be the same as all the other tiles on the "/" route except that this would be pinned to the top until users start searching etc. This would require some form of ongoing auction to determine which one is 'featured'.

Logging this issue primarily to see what others think about this and if there are any better ideas floating around.

**Comment by anbud** [comment]
This is a nice idea, it could bring us some nice Krazors.

**Comment by gazhayes** [comment]
Any ideas about how to structure the auction side of things?

**Comment by anbud** [comment]
We could organize auctions to be pinned for a certain amount of time (maybe we can do this daily or something). For example, we can organize an auction every day, start at 1 KZR, and have increments of 1 KZR. When the auctions ends, the winner could choose a currency/token to pin and it will stay pinned for the next 24 hours (until the other auction ends). Time frame can of course be smaller or bigger. One nice thing here is that we have control over the user's wallet, so we know that he can fulfill what he bids. One side thing here, how will the users add new Krazors to their account?

**Comment by gazhayes** [comment]
> For example, we can organize an auction every day, start at 1 KZR, and have increments of 1 KZR. When the auctions ends, the winner could choose a currency/token to pin and it will stay pinned for the next 24 hours (until the other auction ends).

Another way would be to allow unlimited numbers of users to contribute to an auction to put their chosen coin at the top, i.e. a coin wins rather than a user. That way it can be more of a competition between currencies rather than between users. 

@sjmackenzie @anbud @AshHimself

**Comment by anbud** [comment]
Yap, you're right, that's probably better, more users would participate then, meaning more coins for us.

**Comment by gazhayes** [comment]
How would you structure it / build it in that case?

I was thinking about it and realized the coolest way (if we use the per-currency approach) could be to have an ongoing/continuous auction if we did it that way, instead of a once per day thing. Kind of like a parking meter to keep a currency at the top and the Krazor slowly drains away (into Blockrazor's wallet). That introduces a whole heap of difficulties though - multiple currencies will end up having their 'auction' coins drained to equal points and then start 'flipping' rapidly. 'Reserving' users krazor so that they can be drained if their chosen coin moves up to the top could also introduce difficulties. So maybe it must be some time-based thing to make it more simple.

**Comment by anbud** [comment]
So, if I understood this correctly, each currency would have its own auction coins which would drain slowly when the currency is on top? And the one that has the most would be at the top until another one gains the lead? It is the coolest solution, way better than the time based thing, I like it. Reserving user's coins wouldn't be such a big issue, everything that he/she bids would be reserved until it's spent. Maybe we can add a way for users to give up on auctions and release their unspent coins if they want. About the flipping, we could implement a grace period for change or something to prevent the sudden change of the top currency.

**Comment by gazhayes** [comment]
OK cool. Feel like building it?

**Comment by anbud** [comment]
Yeah, sure, I'll start soon.

**Comment by anbud** [comment]
Done in #494.
