### ISSUE TITLE
Problem: user name is not shown on hashpower page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#429]
Problem: each hashpower data point should also show the user who contributed it.

**Comment by janat08** [comment]
doing it.

**Comment by janat08** [comment]
Am I suppose to be able to assign myself to issues, the collaborator badge says I've been invited to collaborate yet the email invitation to accept does nothing.

**Comment by gazhayes** [comment]
You can assign yourself to anything you want to work on, or if you comment and say you are working on something I'll assign it to you. I mostly use assignments to keep track of what's currently being worked on. I don't think you need to worry about the email, other than looking at it as a notification.

**Comment by janat08** [comment]
Could you invite me to collaborators again, I can't accept it.

**Comment by gazhayes** [comment]
It looks like you've already accepted it, you're definitely on the collaborator list. What do you want to be able to do that you currently can't do? Self-assign?

**Comment by janat08** [comment]
yes

**Comment by gazhayes** [comment]
OK, can you try again now (try to self assign)

**Comment by janat08** [comment]
I can't following this: https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by gazhayes** [comment]
Still not working?

**Comment by janat08** [comment]
I see no checkbox in issues list to select.

**Comment by janat08** [comment]
fixed in 519

**Comment by gazhayes** [comment]
Not working

<img width="275" alt="screen shot 2018-03-14 at 6 40 44 am" src="https://user-images.githubusercontent.com/8143945/37373698-a974b974-2752-11e8-86ad-86e502240479.png">

**Comment by gazhayes** [comment]
Oh I see you are denormalizing so will work with new data points, ok no problem.
