### ISSUE TITLE
Problem: comments/red flags/features are not incentivised

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#430]
Problem: There's currently no incentive to add features/red flags/comments to currencies.

Possible solution:
reward (once a day or hour or whatever) the top comment, feature, and red flag.

**Comment by anbud** [comment]
I agree, rewarding the top comments once an hour with a small amount of Krazor is a perfectly fine solution for this, it would bring some incentive. Of course, this rewarding process should be stated somewhere in the text, maybe when adding the comment/feature/red flag.

**Comment by AshHimself** [comment]
Perhaps something like reddit gold where its visible as well that, that type of comment is rewardable?

**Comment by gazhayes** [comment]
> Perhaps something like reddit gold where its visible as well that, that type of comment is rewardable?

Can you post a screenshot?

**Comment by anbud** [comment]
What's the status on this one?

**Comment by gazhayes** [comment]
No status. Do you want to do it?

**Comment by anbud** [comment]
Yap, it seems interesting.

**Comment by anbud** [comment]
Done in #549.
