### ISSUE TITLE
Problem: bounties reward is broken

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#431]
Problem: bounties reward is broken, probably in the code refactor.

Notify: @janat08

**Comment by janat08** [comment]
```
Exception in template helper: TypeError: Template.instance(...).view.parentView.parentView.parentView.templateInstance is not a function
```
UI error. Unassign me.

**Comment by gazhayes** [comment]
ping @anbud @AshHimself @MadanBhandari

**Comment by gazhayes** [comment]
@janat08 this was broken in your commit: `e626b57f5c370a7927d27f25aa4c9ee561262ace`

https://github.com/Blockrazor/blockrazor/pull/377

**Comment by janat08** [comment]
I'll do this.

**Comment by janat08** [comment]
fixed in #477

**Comment by janat08** [comment]
not fixed

**Comment by janat08** [comment]
fixed.
