### ISSUE TITLE
Problem: Redflags collection broken

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#436]
Problem: Redflags is undefined in compare currencies route. My filesystem can't be trusted with capital case so I imagine in /imports/api/redflags/ file redflags.js is capitalized.

Solution: See if redflags.js is capitalized or what is happening, because I don't see a problem.

**Comment by janat08** [comment]
@gazhayes

**Comment by gazhayes** [comment]
You can check capitalization directly on github if Windows is causing you problems.

**Comment by janat08** [comment]
nm

**Comment by gazhayes** [comment]
Is this problem in the current MASTER, or only on your local machine?

**Comment by janat08** [comment]
will be fixed in the next push.

**Comment by gazhayes** [comment]
>  I'm done will all of the collection/lib stuff

Nice work. Please provide a general overview of what you did on the original issue, so that the others can look it over and see if it's going to affect them or if anything else should be done.

**Comment by gazhayes** [comment]
FYI:

```
[34mI20180310-03:20:03.238(-5)? [39mException from sub redflags id zdiwaJ5EP843mt9cN TypeError: Cannot read property 'find' of undefined
[34mI20180310-03:20:03.238(-5)? [39m    at Subscription.<anonymous> (imports/api/redflags/server/publications.js:10:21)
```
