### ISSUE TITLE
Problem: fetching usernames doesn't work for all users

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#44]
usernames are stored differently in the database depending on how the user created their account (github or facebook). Email sign ups will not be allowed in production but are used in development to make things easier, but this is a third way of storing usernames. 

An example of where usernames are used: https://github.com/Blockrazor/blockrazor/blob/3e38ca52a259ddd2b0027ed43b08012d127214e8/lib/database/Bounties.js#L46

Solution 1: UI logic should try and fetch the username from all possible database locations.
Solution 2 (adopted solution): Add a hook on user creation to copy their name/username to a default single location in profile data and just use that everywhere.

**Comment by janat08** [comment]
Would you be interested in using transform option that applies to any data consumption calls other than observechanges or publish cursors (ie db.find: username: exists: true.count). It doesn't denormalize (although by default SSO accounts won't merge anyway), and isn't complicated as changing UI logic.

**Comment by janat08** [comment]
I belief that's password package level implementation.

**Comment by gazhayes** [comment]
Facebook username fixed in #44 by @Fen747

**Comment by gazhayes** [comment]
The Github component of this issue is still open.

**Comment by madguy02** [comment]
I will shoot a PR soon

**Comment by AshHimself** [comment]
@madguy02 - what method did you use to solve this?

**Comment by gazhayes** [comment]
He didn't, but the solution is very obvious and simple (5 minutes max) so I'm leaving it open as an assessment for new contributors.
