### ISSUE TITLE
Problem: CryptoJS npm package in currencychoices.js

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#443]
Problem: Currencychoices.js holds CryptoJS in helpers which isn't imported. It has been moved into imports thus should be imported.

**Comment by janat08** [comment]
cryptoJS in user methods

**Comment by gazhayes** [comment]
@janat08 are you fixing this one?

**Comment by janat08** [comment]
Doing this.

**Comment by janat08** [comment]
is a global from jparker:crypto-md5
