### ISSUE TITLE
Problem: currency2 template deleted

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#444]
Problem: I deleted currency2 template within currency.html

**Comment by gazhayes** [comment]
That's a pretty confusing/bad name for a template anyway. What's it doing?

**Comment by janat08** [comment]
I was full of ipsum lorem, but also much more elaborate then currency template.

**Comment by gazhayes** [comment]
I think it was probably just me testing things earlier on, it's probably no longer used anywhere.
