### ISSUE TITLE
problem: test is failing

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#445]
Problem: #441 is failing a test, but it doesn't appear to be anything to do with the code in the commits. I'm not sure what's happening here.

```
$ git fetch origin +refs/pull/441/merge:
fatal: Couldn't find remote ref refs/pull/441/merge
The command "eval git fetch origin +refs/pull/441/merge: " failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/441/merge
The command "eval git fetch origin +refs/pull/441/merge: " failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/441/merge
The command "eval git fetch origin +refs/pull/441/merge: " failed 3 times.
The command "git fetch origin +refs/pull/441/merge:" failed and exited with 128 during .
Your build has been stopped.
```
https://travis-ci.org/Blockrazor/blockrazor/builds/351641052?utm_source=github_status&utm_medium=notification

@anbud @AshHimself any ideas?

**Comment by anbud** [comment]
Is it possible that it was merged before the test even ran? For some weird reason it can't fetch that pull request, but others are working fine.

**Comment by gazhayes** [comment]
Actually yes that's probably why.
