### ISSUE TITLE
Problem: users can't easily tell if they have new notifications

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#45]
Solution: add notification badges (i.e. like facebook notification icon) showing how many new notifications/messages they have which haven't been read yet. Bootstrap [badge](https://v4-alpha.getbootstrap.com/components/badge/) should be ok for UI element.

**Comment by AshHimself** [comment]
@gazhayes Do you want this next to the Notification menu item?
Do you want notifications marked as read as soon as the notification view is loaded? 
Do you want this to be reactive or simply using a meteor method on each page load? 

Thanks

**Comment by gazhayes** [comment]
>Do you want this next to the Notification menu item?
Yep that's fine till we clean up the UI
>Do you want notifications marked as read as soon as the notification view is loaded?
Yeah, that's probably the simplest way to do it
>Do you want this to be reactive or simply using a meteor method on each page load?
A meteor method will be fine

**Comment by matmello** [comment]
Are you working on this @AshHimself ? Or can i give it a try?

**Comment by AshHimself** [comment]
I am. Sending a PR today.

**Comment by gazhayes** [comment]
Fixed in #83
