### ISSUE TITLE
Problem: when changing the security model, no data is shown

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#450]
Problem: empty list
<img width="458" alt="screen shot 2018-03-11 at 7 26 31 am" src="https://user-images.githubusercontent.com/8143945/37247860-a26051cc-24fd-11e8-81fa-748c7e4ebc07.png">

**Comment by anbud** [comment]
This thing is populated on localhost, yet it's not populated in production. I'll check the subscriptions.

**Comment by anbud** [comment]
Done in #462
