### ISSUE TITLE
Problem: cannot add notes to proposed changes

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#453]
Problem: sometimes when proposing changes, a user may wish to add notes or provide supporting evidence for the maintainers to look at. 

@anbud not sure how best to go about this, what do you think?

**Comment by anbud** [comment]
This is a valid request, I had the same idea while implementing the page, but I really don't know where to place it in the UI. There's no space to put it inline, and a modal may look a little bit weird.

**Comment by gazhayes** [comment]
Yeah a modal would be weird. Maybe @MadanBhandari or someone else will have some ideas about where to put it.

**Comment by AshHimself** [comment]
You could do a confirmation modal after clicking save. e.g. you are proposing to change x to y and then have a notes field in the same modal.

**Comment by gazhayes** [comment]
That sounds like the best solution.

**Comment by AshHimself** [comment]
I'll take this then as I think @anbud was assign a biggish ticket recently for the crypto wallet side of thinks.

**Comment by AshHimself** [comment]
Done in #503
