### ISSUE TITLE
problem: when adding ICO, start time and end time of funding is needed

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#455]
Problem: When adding an ICO, users are asked for the start time (when funding or buying into the ICO can start) but not when funding will end. These dates will be used for countdown timers on the currency detail page.

currently:
<img width="894" alt="screen shot 2018-03-11 at 7 48 19 am" src="https://user-images.githubusercontent.com/8143945/37247990-b2465a84-2500-11e8-9ec0-d5b47672ac15.png">

The layout could also use a bit of work, genesis block ETA and ICO dates should be separate.

**Comment by AshHimself** [comment]
@gazhayes - This is done and i'll send a PR now. A few things to possibly discuss.

- This took ages to test as there was so much clicking to get a full date set. (Do you think this process is something users would be doing often? If could be worth investigating.

- Validation on client is confusing. The field names do not match the validation errors. Example; start time GMT is what the user see's but if they don't populate it and try to submit they are advised to populate 'iconext round'. Jquery validation on the client and highlighting the suspect woulds would be ideal.

- The start and end dates are currently not consumed on any views.

**Comment by AshHimself** [comment]
Fixed in #614

**Comment by gazhayes** [comment]
I'll log some new issues for these.
