### ISSUE TITLE
Problem: no tooltip for block time on add currency page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#459]
Problem: It's not clear what this is for. Should be something like "how many confirmations/blocks do exchanges or other services generally require before a transaction on this blockchain is accepted?"

<img width="275" alt="screen shot 2018-03-11 at 7 58 54 am" src="https://user-images.githubusercontent.com/8143945/37248056-4ea8d996-2502-11e8-9a20-d9890b44e30c.png">

**Comment by janat08** [comment]
doing this.

**Comment by janat08** [comment]
fixed.
