### ISSUE TITLE
Problem: no way for users to fund a bug bounty/feature request

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#46]
Development of blockrazor should be community driven, which means users should be able to contribute coins towards a new feature/bug fix if they can't actually write code themselves.

Solution: some kind of bounty funding page. Any solution must avoid the [Cobra Effect](https://en.wikipedia.org/wiki/Cobra_effect).

**Comment by janat08** [comment]
bountysource.com has integrations with github
