### ISSUE TITLE
Problem: /server/imageUpload.js is full of random methods that belong in /imports

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#468]
Problem: imageUpload.js has lots of random methods that should be moved into appropriate api folders in imports.

Solution: someone who has clear idea what they do or where they belong might want to split them.

**Comment by gazhayes** [comment]
That was me being lazy.

I'll have a look and either fix it or provide more info.

**Comment by samuelralak** [comment]
@gazhayes whats the progress on this?

**Comment by gazhayes** [comment]
No progress. I've been working on the c++ side of things (Krazor) and haven't had much time to deal with this and a few other issues. 

It's spaghetti code and needs sorting out, I wrote it but it shouldn't be *that* hard to deal with if you want to do it.

**Comment by samuelralak** [comment]
yeah sure, will take this one after am done with [#640](https://github.com/Blockrazor/blockrazor/issues/640)

**Comment by samuelralak** [comment]
@janat08 @gazhayes I have split the code inside imageUpload.js into their respective contexts. I have also discarded the imageUpload.js file itself. kindly review :)

**Comment by samuelralak** [comment]
@gazhayes wont be making any more commits
