### ISSUE TITLE
Problem: no hash power metric for currency comparison

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#47]
Solution:
- hash power itself can be obtained from various APIs. Maybe add bounties for git pull requests that add a needed API call.
- Hash power means nothing if you don't know how much electricity is consumed for each algorithm. Need some kind of page and bounty for people to add hardware, hashrate and power consumption.
- When there's a list of hardware/hashrate/power consumption and also reliable and up to date network hash rates for each currency it's simply a matter of computing the overall power consumption for each currency.

**Comment by anbud** [comment]
@gazhayes, I'll take this one, if it's not low priority. Can you explain in little more detail how is it supposed to look?

**Comment by gazhayes** [comment]
This one can start with a simple form to populate a new hashpower collection.

The data points are:

hardware category (ASIC or GPU)
hardware device (see below),
algorithm (select from list, e.g. sha-256),
hash rate and unit, (unit should be selected from list, I'll add a comment here later with them all),
power consumption (Watts).

Hardware device input should allow users to add a new device or select from any device that someone else has added in the past.

**Comment by gazhayes** [comment]
Also can you use the new imports structure for this.

**Comment by anbud** [comment]
@gazhayes, ok, I'll implement accordingly. I've already started using the new imports structure for this. :)

**Comment by anbud** [comment]
The first basic solution is in #176.
