### ISSUE TITLE
Problem: no logging system

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#48]
Logging is very important to keep track of failed log-in attempts, errors, failed form requests, etc etc.

Solution: possibly this: https://atmospherejs.com/ostrio/logger

**Comment by AshHimself** [comment]
@gazhayes - I have implemented ostrio:logger using the mongoDB logging mechnism as this will be the best option to report on and it'll also allow us to use the data to resolve other issues. e.g. #39 

The following events are being captured.
- Failed login attempts
- User created
Please let me know what other events you would like monitored and I can slowly start adding these when it makes sense.

**Comment by gazhayes** [comment]
Fixed in #86
