### ISSUE TITLE
Problem: addCoin field messages glitch

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#485]
Problem: If you enter duplicate currencyname then glitch happens

**Comment by gazhayes** [comment]
Can you post a screen shot of what you mean? Or you just want to fix it yourself?

**Comment by gazhayes** [comment]
I see it now.

<img width="951" alt="screen shot 2018-03-11 at 9 07 00 pm" src="https://user-images.githubusercontent.com/8143945/37253711-2af46b00-2570-11e8-970b-0fc522defec7.png">

**Comment by janat08** [comment]
It looks like there're bunch of those in the form. I don't do CSS.

**Comment by gazhayes** [comment]
Yeah that's ok, it's good that you reported it, someone will fix it.

**Comment by AshHimself** [comment]
Done in #538

**Comment by AshHimself** [comment]
@janat08 - I believe you need to close this as you raised it.
