### ISSUE TITLE
Problem: /addcoin unresponsive

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#488]
Problem: Fields don't collapse on smaller resolutions. tooltips will also get in the way.

Solution: tooltips top. and something to do with the fields.

**Comment by janat08** [comment]
doing it.

**Comment by janat08** [comment]
@gazhayes would you consider help-text instead of tooltips as I think tooltips in here are bad UX: https://getbootstrap.com/docs/4.0/components/forms/#help-text

**Comment by gazhayes** [comment]
In many places the tooltips get in the way, but help-text deforms the page (a lot) because some items require a lot of explanation.

**Comment by janat08** [comment]
moved tooltips to top.

The layout doesn't use bootstrap, so I'm not doing rest of it.

**Comment by gazhayes** [comment]
Responsiveness for anything other than "/" route is very low priority anyway.
