### ISSUE TITLE
Problem: nowhere for users to get help

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#49]
Solution: maybe a forum to discuss 'meta' issues, or perhaps a simple comment system built into the application

**Comment by anbud** [comment]
@gazhayes,
I'm taking this.
I think implementing a simple forum would be a sufficient solution here. I just have one question, should the forum have some kind of categories, or would simple topics be enough?

**Comment by sjmackenzie** [comment]
feature requests you do on your own dime/time, or you contract someone to do it for you. Otherwise please don't solve things that aren't a problem.

**Comment by gazhayes** [comment]
Yeah don't work on this one.

**Comment by anbud** [comment]
Ok, I'm stopping activities on this one.
