### ISSUE TITLE
Problem: currency detail page subscribes to all currency and comment data

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#50]
Route location: https://github.com/Blockrazor/blockrazor/blob/be508d2bcee5507f20632364ae168d5a28cbfdcd/lib/routes.js#L53

The currency detail page subscribes to all available currency and comment data. This will quickly degrade the speed of the site for users.

Solution: only publish/subscribe to data for the _current_ currency when in a currency detail page.

**Comment by AshHimself** [comment]
@gazhayes who should be able to view bounties? I put a restriction on the subscription but now I am not getting any data as someone has restricted the cursor to only return it if the username is true?

`      return Bounties.find({_id: id, currentUsername: Meteor.user().username});
`

Thanks mate.

**Comment by gazhayes** [comment]
Fixed in #78
