### ISSUE TITLE
problem: users can propose multiple changes on same data point

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#505]
Problem: when a user proposes a change on the currency detail page, it's still possible for them (or anyone else) to continue to propose more changes to the same data point. This could very easily create multiple changes for the same data point at the same time, or a 'conflict' in git pull request terms.

**Comment by AshHimself** [comment]
Some ideas;
1. Prompt the user that a change already exists to discourage them for making another if its the same?
2. Easily group similar changes somehow in the UI to best choose what needs voting up or down.
3. ???

**Comment by gazhayes** [comment]
The simplest solution I believe is to just disable any further changes until the previous change has been merged or deleted.

**Comment by gazhayes** [comment]
Remember to comment when solved
