### ISSUE TITLE
Problem: users cannot directly compare currencies

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#51]
Currencies can be viewed individually but there's no way to compare two (or more) currencies with each other, for example no way to display and overlaid radar chart showing two or more currencies.

**Comment by anbud** [comment]
I'll take this one. I believe that the easiest solution here would be the overlaid radar chart with multiple currency details. That way, the user could compare as many currencies (each would get its own color) as he wants until the chart gets cluttered.

**Comment by anbud** [comment]
This is almost done in #113. 
The only thing left is the actual chart data, and I'll update the code accordingly when the chart data per currency becomes available. As on the other parts of the site, I've stubbed the chart data (except the wallet parameter which is available).
