### ISSUE TITLE
Problem: searching for currency on comparison page is tedious

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#518]
Problem: searching on the currency comparison page is tedious, the filter field modifies the dropdown list. Ideally this would be a dynamically filtered dropdown instead.

<img width="347" alt="screen shot 2018-03-12 at 9 49 06 pm" src="https://user-images.githubusercontent.com/8143945/37287312-826f30b6-263f-11e8-8831-05c812691289.png">

**Comment by AshHimself** [comment]
@gazhayes select2 would do an awesome job here..

**Comment by janat08** [comment]
doing this

**Comment by AshHimself** [comment]
Doing what? UX type issues like I think deserve a little discussion.

**Comment by janat08** [comment]
He's basically asking for autocomplete. I've made a bunch of issues for the page and would like to own it ;).

**Comment by janat08** [comment]
I'd opt for typeahead as we need fairly custom solution, trying to style it as a combo box.

**Comment by janat08** [comment]
fixed in #546
