### ISSUE TITLE
Problem: no way to filter currencies by different metrics

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#52]
No way to filter through all available currencies to find one with specific metrics.

Solution: add a search bar to the main page. When the search bar is activated, display an advanced search form with a variety of criteria.

**Comment by gazhayes** [comment]
Related pull request: #95

**Comment by AshHimself** [comment]
@gazhayes - was there anything left to do on this ticket? or leaving open so we can complete once we move ahead on the UX?
