### ISSUE TITLE
Problem: currency detail tabs under graph broken

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#524]
Problem:  Selecting tabs like coin destribution or code quality under graph doesn't open anything.

**Comment by janat08** [comment]
doing this

**Comment by gazhayes** [comment]
Don't do this, just delete them.

**Comment by gazhayes** [comment]
@MadanBhandari might already be doing it, this was mentioned in another issue #440.

This is an example of why it is important to keep up to date with all the issues.

**Comment by MadanBhandari** [comment]
I am gonna re-work everything on currency details page [UI/UX]. One thing I did't understand is why there are wallet images, what does this mean ?

**Comment by gazhayes** [comment]
Wallet images are just images of cryptocurrency wallets.

When reworking, make sure to use bootswatch to the maximum level.
