### ISSUE TITLE
Problem: difficult to quickly add currencies to compare currencies page

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#526]
Problem:  Selecting currency closes dropdown and it then veers outside the window if there're enough currencies which is aweful on mobile.

Solution: on selection clear filter text and enter/clear/focus input, or don't close dropdown. make currency selection stick to the left, and add currencies to the left of currency row.

**Comment by janat08** [comment]
doing this.

**Comment by gazhayes** [comment]
#518 should be done at the same time, otherwise let someone do 518 first.
