### ISSUE TITLE
Problem: users cannot rank a currency's community

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#53]
Solution: add a community ranking system (ELO) based on the wallet ranking system. Some example questions to ask:

- Which one has the friendliest community?
- Which community talks most about the price or when to buy/sell?
- Which community talks most about new features, security issues, plans for the future, etc?
- Which community has the most experienced people? 
- Does one community have stronger leadership than the other? (negative)
- Which community is most friendly and helpful to newcomers who ask a lot of questions?
- Is one community more active than the other?

**Comment by anbud** [comment]
@gazhayes,
I'll take this one. 
This rating process should also be in the ratings (ratings.html) page, right?

When rating wallets, the user has to upload wallet images to prove ownership of a wallet. Should a user provide some proof that he/she's part of the community, and, if so, what kind of a proof would that be? (i.e. reddit, bitcointalk, cryptocompare,... username or something?)

**Comment by anbud** [comment]
@gazhayes,
For a simpler solution, users could be asked to rate communities of cryptocurrencies whose wallets they've already added.
Which solution would you prefer?

**Comment by gazhayes** [comment]
This should be on a different page to the wallet rating. Instead of uploading wallet images, there will be something similar (I'm not sure exactly what, probably links and images though, you could use some kind of placeholder for now).

You might want to look at the inverse elo rating problem too, this issue will have the same problem.

**Comment by anbud** [comment]
Yap, I'll do the inverse ELO rating in a separate PR. Other than that, the basic functionality (with stubbed proofs) is implemented in #129.

**Comment by gazhayes** [comment]
Problem: community rankings do not appear to be populating the elorankings collection. 

graphdata and currency collections are also not updated when running appropriate methods but this is probably because of the elorankings collection issue.

@anbud

**Comment by anbud** [comment]
@gazhayes,
As far as I remember, it populated the database correctly. It's probably some regression. I'll check it out and a PR will follow.

**Comment by anbud** [comment]
@gazhayes,
I've tested it out, and the only bug I've found is that the button on the communities page had a wrong ID, so it wasn't doing anything. But, by fixing that in #149, it calls the correct method now.
Elorankings collection has data in it, and the graphdata is also updated, so, it should be working fine. I've checked both on localhost and production (with DrMongo), the data is there.
