### ISSUE TITLE
problem: currency comparison page cannot be shared

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#530]
Problem: users can't share the currency comparison page when comparing currencies

possible solution: rewrite route when adding currencies on compare page.

**Comment by gazhayes** [comment]
ping @anbud

**Comment by anbud** [comment]
Should we use something like `/compareCurrencies/ETH-XMR-...`? Maybe it would be prettier to do `/compareCurrencies/ETH/XMR/...`, but multiple optional values in the router can cause issues.

**Comment by gazhayes** [comment]
Just use the simplest (ETH-XMR...)

**Comment by janat08** [comment]
there's already issue for it, and i took it.

**Comment by janat08** [comment]
in #523

**Comment by gazhayes** [comment]
#523 isn't very clear about that, try to be more clear and specific with your issues.

**Comment by janat08** [comment]
I take this?

**Comment by gazhayes** [comment]
Yep that's fine.

**Comment by janat08** [comment]
I'd like to use flow router api which will produce "?symbols=ETH+XMR".

**Comment by gazhayes** [comment]
Yeah try to use flow route API without adding anything extra, if possible. @anbud how would you go about this?

We should probably try to make it as search engine friendly as possible.

**Comment by anbud** [comment]
For SEO purposes, I believe it would be prettier to use something like `/compareCurrencies/ETH-XMR...`, where `ETH-XMR` would be an optional parameter.

**Comment by gazhayes** [comment]
Yeah I agree

**Comment by janat08** [comment]
I think SEO will be more likely to interpret conventional urls correctly, and I'd rather not have to play with regex to implement this.

**Comment by anbud** [comment]
No need to use regex, just split the param at `-` and you're good to go. FlowRouter supports optional parameters out of the box.

**Comment by gazhayes** [comment]
@janat08 if you are doing the #543 next please leave this one to @anbud

**Comment by janat08** [comment]
I'd like to see him do this.

**Comment by anbud** [comment]
Done in #551.

**Comment by janat08** [comment]
you can't navigate back to a route with these params if you left it. the new params don't overwrite navigation history, or that is every time you pick or delete the browser history is spammed.

**Comment by anbud** [comment]
Yap, you're right, should've used the `replaceState` instead of `pushState` to prevent history spamming. PR will follow soon.

**Comment by anbud** [comment]
Fixed in #553.

**Comment by janat08** [comment]
did replace state just fix the going back issue?
