### ISSUE TITLE
problem: not enough digits after decimal place on currency auction page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#532]
Problem: users can't 'feel' the Krazor draining away at /currencyAuction, maybe a few more decimal places will help

**Comment by gazhayes** [comment]
ping @anbud and @janat08 very simple one but not sure who wants to do it

**Comment by anbud** [comment]
Fixed in #573.

**Comment by gazhayes** [comment]
I haven't looked at the code for that page, how did you do the timing?

What I was hoping for was something like the bounties ticking up (except in the opposite direction)

**Comment by anbud** [comment]
Sorry, I misunderstood the issue, I thought the point was just to increase the number of decimal spaces. I'll implement the timer accordingly. Since it's draining by the minute, I can simulate the drainage per second without a problem.

**Comment by gazhayes** [comment]
It's my fault, I wasn't specific enough about the actual problem and assumed too much about how this was working without actually looking at the code

**Comment by anbud** [comment]
Done in #588.
