### ISSUE TITLE
problem: specific areas on canvas rendering of chart.js radar graph are not independently actionable 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#537]
Problem: in order to provide help functions these areas on the graph need to be independently actionable. I only highlighted the chart area itself as actionable so it can go to the currency details route, but we could also just make it more clear with an icon or something next to the currency name that more details are available.

<img width="518" alt="screen shot 2018-03-13 at 8 43 25 am" src="https://user-images.githubusercontent.com/8143945/37316552-bf08f222-269a-11e8-93e2-3c513f6af571.png">

**Comment by janat08** [comment]
we could try and use template literals to embed html with links or tooltips as labels, although i don't know if it will work on canvas.

**Comment by gazhayes** [comment]
Yeah, the combination of chart.js and canvas makes this a bit more difficult. If we can't crack this one ourselves I'll find someone who specializes in this field.

**Comment by anbud** [comment]
Since HTML canvas is basically an image, the only way to track clicks (actions) on it is to mathematically calculate where each element is (basic 2d space calculations), which shouldn't be that hard in our case, as labels are fixed and always in the same place.

**Comment by gazhayes** [comment]
My concern with that would be flexibility when adding/removing things from the graph. I'll look at the chart.js code and see if there's something I can do from that angle.

**Comment by janat08** [comment]
I'll give this a look tomorrow unless I forget.

**Comment by gazhayes** [comment]
If nothing happens within a week from now let's just use 2d space calculations instead.

**Comment by gazhayes** [comment]
If we are going to use 2d space calculations to solve this one, #726 is a dependency.

**Comment by gazhayes** [comment]
This issue now also affects the bar chart on [/comparecurrencies]

**Comment by anbud** [comment]
@gazhayes, what's the status on this one?

**Comment by gazhayes** [comment]
I think we have to just use space calculations. I had a look at chart.js and realized there are a heap of hurdles, as cool as it would be, the space calcs are the simplest solution here.

**Comment by anbud** [comment]
Ok, I'm taking it then, it seems fun. I'll try to make it as scalable as possible.

**Comment by anbud** [comment]
It only seemed fun. :) Getting indexes to scale with the chart size was quite a bit of work, even when using chart.js' internal APIs. When you click on a label on either the radar or the bar chart, it's console.log-ed for now, as a placeholder handler.

Done in #876.
