### ISSUE TITLE
Problem: users cannot rate the codebase of a currency

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#54]
ELO ranking of each currency's codebase is needed as a metric but there's no way for users to participate in this process.

Something based on the wallet ranking system can be built quite easily and simply however the following should be kept in mind:

- Most users don't know how to code, but questions about the codebase should be answered only by people who have at least some programming experience. The best way to deal with this could be to allow all users to 'apply' to be allowed to rank codebases, part of that would be providing their github/bitbucket/etc profile so that moderators can see that they actually have some experience, and then approve them to be able to answer codebase related comparative questions.

**Comment by anbud** [comment]
The proposed solution is exactly the one I had in mind before you've edited the text. I'm on it.

**Comment by gazhayes** [comment]
One small update:

Instead of moderators (level 1 in the userdata collection) approving people to become 'developers', a better way is going to be to set a `developer` flag in the userdata collection (manually for the first time (me)), and anyone who has that flag set can also approve new 'applicants' who then have the `developer` flag set and they can also approve new developers, hopefully this will become self-perpetuating.

**Comment by anbud** [comment]
Done in #163.
