### ISSUE TITLE
Problem: master wallet not properly accounted for

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#544]
Problem: currently, the total number of coins spent from the master Blockrazor wallet are calculated by taking the sum of the value of users wallets (I think, @anbud to confirm).

When users withdraw their Krazor to their Krazor wallet (not their Blockrazor wallet), it will throw this calculation off because the value of users Blockrazor wallets will drop, making it look like the master Blockrazor wallet hasn't spent these coins.

In addition, when Krazor is sent from users wallets back to the Blockrazor master wallet (such as in the case of draining coins in the top currency auction), these coins at present just vanish instead of being accounted for.

The only solution I can see is to have an actual blockrazor master wallet and log all incoming and outgoing transactions (its own collection).

ping @anbud

**Comment by anbud** [comment]
Currently, the total sum on the transactions page only includes transactions coming from or to the main wallet (where `from` field is either `System` or `Blockrazor`), so if a user withdraws coins to his/her Krazor wallet, the sum won't change.
The current system for draining works like this: The user bids a certain amount, and that amount is reserved from his wallet (transferred to the main wallet). If he/she cancels the bid, only the remaining coins are returned from the main wallet, so the drained difference stays in the main wallet. If his/her bid is completely spent, everything stays in the main wallet and it will appear correctly on the total sum. So, they are accounted for, but only implicitly

**Comment by gazhayes** [comment]
Ah ok, thanks for that explanation.

That should be ok then.
