### ISSUE TITLE
Problem: currency comparison typeahead is not styled

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#547]
Problem: typeahead styles don't work. the original typeahead from twitter is unmaintained, and there's one from algolia (although it's a genuine fork, so it may break).

**Comment by gazhayes** [comment]
ping @AshHimself

**Comment by AshHimself** [comment]
I'll take a look tonight @gazhayes. I personally thought typehead just worked out the box with bootstrap but I could be wrong :)

**Comment by gazhayes** [comment]
Thanks. Also ping @MadanBhandari

**Comment by AshHimself** [comment]
I got a solution for this. Taking :)

**Comment by AshHimself** [comment]
Fixed in #552
