### ISSUE TITLE
Problem: /compareCurrencies typeahead unlimited

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#548]
Problem: there's no limit on the length of the options shown or searched.

**Comment by gazhayes** [comment]
We can't really limit the length searched, otherwise people might not be able to find the currency they're looking for. We can limit the length displayed in the UI though.

**Comment by janat08** [comment]
what sort order do you want for ui?

**Comment by gazhayes** [comment]
It doesn't really matter, I guess alphabetical makes the most sense

**Comment by janat08** [comment]
what limit?

**Comment by gazhayes** [comment]
For the UI? Just see what you think works well.

But for search it's important that the entire collection is searched. I'm not sure about the performance implications and what we can do about that though.

**Comment by janat08** [comment]
if you pass a limit into search it will search entire database untill there're enough matches, if youre limiting UI it doesn't make a difference. although i suppose it's better if the entire collection is just loaded from method since you'd have limits on publications which will then be adversely affected I suppose, and create a local collection with results and operate from that.

**Comment by gazhayes** [comment]
> it's better if the entire collection is just loaded from method
> create a local collection with results and operate from that

Yes that sounds good

**Comment by gazhayes** [comment]
You could also denormalize just the names and _id and only fetch the rest of the data after they have selected a currency.

**Comment by janat08** [comment]
gonna check if this actually works

**Comment by gazhayes** [comment]
It does appear to work, at least from the UI standpoint.

**Comment by janat08** [comment]
it might not be actually making the switch to local collection even if it doesn't really use tracker.

**Comment by gazhayes** [comment]
Ah I see. You're testing this now?

**Comment by janat08** [comment]
I assumed it would just work, on every keystroke it invokes an object. I reconsidered after the blaze test failed. fixed.
