### ISSUE TITLE
Problem: users cannot add red flags to currencies

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#55]
Users can add features to currencies but not warnings or red flags. Something similar to the features system should be used because this would be easy to adapt.

**Comment by AshHimself** [comment]
@gazhayes - Could you expand on this a little? Is it simply the same as the below screenshot but for red flags? 
![image](https://user-images.githubusercontent.com/148682/35036698-1a2bb01a-fbb0-11e7-9ed1-f1b32f5ac232.png)

**Comment by gazhayes** [comment]
>Is it simply the same as the below screenshot but for red flags?    

Yes, that would do (at least for now).

**Comment by AshHimself** [comment]
I have already started :)

On Mon, Jan 22, 2018 at 3:47 PM, Andrej Budinčević <notifications@github.com

**Comment by anbud** [comment]
@AshHimself, no problem then, that's why I wanted to check. :)

**Comment by AshHimself** [comment]
@gazhayes - just wanted to get something clarified. When we say red flags, are we talking about the users typing something in and posting something about the currency they want to flag? Or, red flagging features and comments with the flag icon? 

![image](https://user-images.githubusercontent.com/148682/35265626-9c4b59e2-005b-11e8-91db-7d6e52d8b60b.png)

**Comment by gazhayes** [comment]
> are we talking about the users typing something in and posting something about the currency    

Yes, that's the one.

**Comment by AshHimself** [comment]
Ok great i have not wasted my time. Should we raise another ticket for the flag button doing nothing then? We could just raise log a warning for now and then later on we can create a ruleset to say hide a comment `if(flag) > x hideComment()`

Thoughts?

**Comment by gazhayes** [comment]
Absolutely yes, that should be a new issue. I'll log it myself so I can describe what it should do. 

The original issue was basically me making a note to myself, if you see other vague-ish things like that created before today definitely don't hesitate to get some clarification.
