### ISSUE TITLE
Problem: no metric to determine quantity/quality of existing data

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#550]
Problem: the radar chart displayed for each currency needs some indication of how much data there is behind it in comparison to the amount of data behind other currencies.

For example the number of individual ELO rankings, whether or not APIs are working, etc.

This metric can probably be calculated with a cron job and inserted into the currencies collection, and the global min/max put into graphdata. This metric could then then be used in the UI somewhere (I guess underneath the radar chart or whatever).

It can also be used to decide when to grey out the radar chart for issue #385 

ping @anbud

**Comment by anbud** [comment]
Yap, the easiest solution here is to count ELO rankings for each currency, and use it as we use other metrics (calculate global min and max in graph data, and place a field in the currencies collection to indicate the value). That way it would require minimal modifications to the current metrics infrastructure.

Stating it underneath the radar chart seems perfectly fine for now. Maybe we should grey out the graph only if the value is close to the global minimum or something.

**Comment by gazhayes** [comment]
That sounds pretty good. Want to do it?

**Comment by anbud** [comment]
Yap, I'm taking it. :)

**Comment by anbud** [comment]
Done in #569.
