### ISSUE TITLE
Problem : Home page broken

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#561]
Problem : Error: Cannot find module 'ScrollMagic'

Solution : Not sure which PR broke this, Investigate and fix the issue.

**Comment by janat08** [comment]
npm install

**Comment by gazhayes** [comment]
Fixing now

**Comment by gazhayes** [comment]
@janat08 

ScrollMagic would not install, only scrollmagic

I changed the import but forgot to change the usage. Can you check if it is working and update if not?
