### ISSUE TITLE
Problem: defer call to set user preference for when to open/close sidebar

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#565]
Problem: the sidebar currently saves at which screen width it was opened or closed to then act accordingly on a repeat visit, but it will also update the preference on DB if the user just opens and closes the sidebar.

Solution: save the value locally, and upset when the client closes tab.

**Comment by janat08** [comment]
So I'm overwriting Meteor.logout() before I import router config on client index and with import from client folder that uses Meteor.startup and I expect this to load before layout does, yet it is not the case as it doesn't recognize my added methods.

**Comment by gazhayes** [comment]
@anbud

**Comment by janat08** [comment]
https://github.com/janat08/blockrazor/commit/938ba7a5c43643a9fde7d72c9f9841384c28744d

**Comment by anbud** [comment]
I'll check it out to see if I can help somehow.

**Comment by gazhayes** [comment]
Any change in status for this one?

**Comment by anbud** [comment]
@janat08, could you please send a PR with that code, so I can try to debug it? :) Sorry, I forgot about this one.

**Comment by janat08** [comment]
So it just decided to work with adding hooks before logout, but:
```
$(window).on( "unload", saveSidebarPreference)
window.addEventListener('beforeunload', saveSidebarPreference)
window.addEventListener('unload', saveSidebarPreference)
```

Doesn't appear to call callback that will diff Session var for preference that is updated during session against whats on record in DB and update if there's a difference. You can debug by comparing session variables and userSession data. screenSize and once they change after you open/close sidebar at a window screen.

I decided to change the field name for preference so it broke on me again.

**Comment by janat08** [comment]
Still incomplete as it is impossible to capture logginIn event with Meteor.logginIn() changing immediately to false within autorun despite triggering it by changing to true.

**Comment by janat08** [comment]
https://github.com/meteor/meteor/issues/340
I went without Meteor.logginIn(), but unload event doesn't work in Meteor.

**Comment by janat08** [comment]
we could subscribe to separate publication that would keep the setting in memory and then commit when publication dies :P. https://docs.meteor.com/api/pubsub.html#Subscription-onStop

**Comment by gazhayes** [comment]
Ha! that would probably work.

**Comment by janat08** [comment]
the publication thing wasn't the brightest idea as you can not definitively have a single callback for when user disconnects, although user presence package, that usersStats.js uses, likely uses publications and it's on disconnect callback is reliable.

**Comment by gazhayes** [comment]
It doesn't have to be 100% accurate, just indicative.

**Comment by gazhayes** [comment]
Things go stale because people don't know what's happening after all the comments and pull requests and it becomes too hard to work it out.

Instead of tagging with stale, just close the issue and log a new one. Describe the *current* problem as a completely new problem, as if you are encountering it for the first time and had never seen this thread. Be very very clear, use code examples if necessary.

**Comment by janat08** [comment]
I'll close this after opening.
