### ISSUE TITLE
Problem: top nav bar is too light in color

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#576]
Problem: bootswatch generally has 3 navbar colors: light, medium, dark.

The dark one looks better, we should switch to that.

ping @MadanBhandari

**Comment by MadanBhandari** [comment]
I got it, I will do this as part of #577 , Overall UI-UX will be updated as per Bootswatch.

**Comment by AshHimself** [comment]
@gazhayes This is fixed but can't seem to find the PR it was fixed on :/
