### ISSUE TITLE
Problem: some users are signing up

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#578]
Problem: some new users are signing up and the won't know the site is currently being worked on or that the database will be purged before being made made 'public'.

Solution: 
Add these somewhere very prominent. 

![activedevdark](https://user-images.githubusercontent.com/8143945/37496855-eec0cd58-28ef-11e8-9de3-b0df665daa67.png)
![activedevlight](https://user-images.githubusercontent.com/8143945/37496856-eeefa3c6-28ef-11e8-9d0e-b2233ba7e2a8.png)

### Use a model to explain that:
"Blockrazor is under active development. The site goes down often. Things break at least once a day. Bounty rewards and wallets are reset often. Follow @blockrazor on Twitter to be notified when we go 'live' and you can earn real Krazor. Check out the code on Github."

ping @MadanBhandari

**Comment by AshHimself** [comment]
I can do this right now if you like

**Comment by gazhayes** [comment]
Yep, it's only a little one but pretty important. You should probably replace the existing github logo

**Comment by gazhayes** [comment]
While you're at it, can you make appropriate twitter and github links :)

**Comment by AshHimself** [comment]
You got it

**Comment by AshHimself** [comment]
Being this is temp, should we just put this above the search bar on the home page, say 100px high? If needed I can create a quick cookie for them to dismiss it and not see it again.

**Comment by gazhayes** [comment]
Yeah that'll do it!

**Comment by AshHimself** [comment]
Fixed in #581

**Comment by gazhayes** [comment]
Don't worry about the cookie (unless you've already done it)

**Comment by AshHimself** [comment]
Nope, I didn't start it.

**Comment by gazhayes** [comment]
Can you remove the button as well as the twitter + github links and just use the image itself, also remove " marks from the modal. (Keep the github and twitter links in the modal though)

**Comment by gazhayes** [comment]
On second thoughts, don't worry, just leave it, good enough for now.

**Comment by AshHimself** [comment]
You sure? I have already done it.

**Comment by gazhayes** [comment]
Ah ok, may as well then ;)

**Comment by AshHimself** [comment]
Removed other components  in #612
