### ISSUE TITLE
Problem: "Found ... results" doesn't look good

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#579]
Problem: while waiting for collections to load, the text underneath the search bar says "found...results".

Possible solution: it would be nice if the entire text could be replaced with "loading" or something while waiting.

<img width="177" alt="screen shot 2018-03-16 at 11 15 00 am" src="https://user-images.githubusercontent.com/8143945/37501975-a7b7182e-290b-11e8-8e42-c167f66c0b9e.png">

**Comment by janat08** [comment]
I'll do this. and that the count doesn't update if local collection has already loaded.

**Comment by janat08** [comment]
fixed in #582
