### ISSUE TITLE
Problem: add currency page is ugly

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#58]
Problem: the add currency page (/addcoin route) is remarkably ugly. The 'tooltips' also make things jump around quite a lot.

**Comment by gazhayes** [comment]
Removing bounty until a decision is reached about Semantic-UI vs Bootstrap.

**Comment by gregorymendoza** [comment]
Hello. I'll work on this issue. The interface is free for me to redesign?

**Comment by gazhayes** [comment]
Yes, totally free and open for however you want to tackle it, you can do anything you want :)

**Comment by AshHimself** [comment]
Question to the team; how are we handling interface changes? Are we just doing a mockup in html then someone else merging into meteor? Interested to know how we are handling this following C4.

Ping @gazhayes

**Comment by gazhayes** [comment]
Just the usual C4 fork/pull should work, do you foresee a problem?

**Comment by gregorymendoza** [comment]
For the UX/UI development, can I commit more than once or I have to save all changes in a single commit?

**Comment by gazhayes** [comment]
You _can_ break down a large problem into multiple smaller problems (which means multiple commits). This is especially useful for larger problems when it makes sense to divide things into smaller problems. 

The important thing is that each individual commit must follow the C4; each commit must be solving a clearly defined problem (explained in the commit message).

**Comment by gregorymendoza** [comment]
Alright, so the main problem is the ugly interface, if I want to commit a series of changes to the design, I should first write "Problem:" followed by the description of the changes made, correct?

**Comment by gazhayes** [comment]
Yes, so the main problem you are solving is the one described in this issue. If you want to break down the problem into smaller problems you should define each one (in each commit message). 

For example you might want to fix the layout in one commit:
"problem: layout doesn't allow scaling for different screen sizes"

then you might want to use floating tooltips instead of inline tooltips:
"problem: tooltips mess up the layout"

Then keep solving more problems until you think the main problem (ugly interface) is solved, and send a pull request with all the commits.

You could also just do everyone in one single commit if it isn't too big. Have a look at the commit history for the project and look at the code changes, you'll start to get a feel for how big the changes in a single commit should be.
