### ISSUE TITLE
problem: side menu doesn't close automatically on small screens

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#590]
Problem: when using a small screen, the side menu takes up most of the page width. When clicking a menu item users have to then close the menu to see the page.

Solution: make the side menu close automatically after clicking a menu item if screen resolution is less than x (whatever x should be)

**Comment by AshHimself** [comment]
Am I the only one who can't see the full menu when on a small screen? I can see more menu items. 

Solution: Use nested menu or scrollable menu.

![image](https://user-images.githubusercontent.com/148682/37550850-770a173e-29cf-11e8-94d6-0a9659fc9120.png)

**Comment by gazhayes** [comment]
We should start using the top menu in addition to this, it would have to be quite different depending on screen size though.

**Comment by AshHimself** [comment]
That massive "Welcome Ash Smith" can probably be removed as well.

**Comment by gazhayes** [comment]
@madan will probably do that stuff, but he probably can't do the auto close part.

**Comment by MadanBhandari** [comment]
Yes, there is no need to welcome message in side navigation, as user name already exist in top navigation (user to know about they are logged in).

**Comment by gazhayes** [comment]
On small screens the username is too long usually, we should probably use the welcome thing on small screens instead of username at the top. Could have a user icon at the top though.

**Comment by AshHimself** [comment]
When you say small, do you mean mobile? or like 13" mac

**Comment by gazhayes** [comment]
Mobile.

And small tablets I guess. Basically anything that doesnt fit 2 tiles in width.

**Comment by anbud** [comment]
@AshHimself, you're not the only one, I don't see all items on the menu as well, on a 13" Dell laptop. Scroll would be lovely here.

**Comment by gazhayes** [comment]
@anbud can you log that as a new issue?

**Comment by gazhayes** [comment]
We can also combine all the moderator menu items as one

**Comment by janat08** [comment]
It's actually already the case that sidebar will close on mobile resolution (besides the fix already pushed). To be able to see two columns of stuff on main page you basically have to be at 1200px :D the highest breakpoint, you can check it out with session variable the defines breakpoints.

**Comment by gazhayes** [comment]
On small screens the menu should not stay open at all, it should close when a menu item is clicked.

**Comment by gazhayes** [comment]
Your last PR doesn't look like it solved the issue

**Comment by gazhayes** [comment]
Was just cache on my phone.
