### ISSUE TITLE
Problem: no currency summary

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#591]
Problem: there are features and red flags, but no summary for currencies. 

This would have to be done in a similar way to features and red flags in that the best summary makes it to the top. 

However, it wouldn't make sense to have more than one summary displayed. This introduces a UX problem: _how do we encourage users to vote on summaries when only one is displayed?_ 

Maybe a 'load more' thing at the bottom of the leading summary would be all that's needed, users who click it will see the rest of the summaries and might vote on them. But maybe someone has a nicer idea.

**Comment by janat08** [comment]
https://www.agolo.com/splash

**Comment by gazhayes** [comment]
@janat08 that looks very cool. I'm doing a bit of investigation into it now.

**Comment by AshHimself** [comment]
What about just creating another attribute and then people can propose changes to it. Could even use our current inline editor with the html5 editor;

![image](https://user-images.githubusercontent.com/148682/37552896-89cba54e-29f8-11e8-87f4-accf3ce6b260.png)

**Comment by gazhayes** [comment]
> use our current inline editor 

Where is that?

**Comment by AshHimself** [comment]
We are not using that right now, that’s just a screenshot from the inline
editor documentation.

**Comment by gazhayes** [comment]
Ah ok.

We shouldn't use WYSIWYG, too easy to make things look weird.

Some very basic and limited markdown might be a good idea though, but no reason to think that far ahead.

**Comment by gazhayes** [comment]
ping @anbud and @MadanBhandari

**Comment by anbud** [comment]
@gazhayes,
Yap, the simplest solution here would be what @AshHimself suggested, add a new summary attribute and let users propose changes to it. That sounds perfectly fine and that would require minimal changes to the current codebase.
 
But, we lose two things in that solution. First is the ability for users to vote on summaries, which may be a little bit against the community-driven approach we have, and the other is that, currently, there's no real incentive for users to propose changes, there's no reward for it, while there would probably be a reward for the top summary (like for the top comment) if we used the first solution. The 'load more' or 'see all' button would probably work fine UX-wise.

About WYSIWYG support, markdown is sufficient here, but, we have to keep in mind that, no matter how simple markdown is, not everyone is familiar with it. So maybe a limited markdown support (e.g. for bolding and stuff) and plain text is fine here.

**Comment by gazhayes** [comment]
@anbud @ashhimself 

The simplest solution to adding a summary would definitely be the "propose change" way, however that would't be the simplest solution if we want this to produce a hill climbing algorithm so that we end up with the *best possible* summary.

So I think copying the features/red flags approach would actually be the simplest solution to the real problem.

**Comment by AshHimself** [comment]
Roger that. I've done the red flag section so happy to take it.

**Comment by gazhayes** [comment]
Your existing open ones are starting to pile up, can you close them off first before taking a new one?

**Comment by anbud** [comment]
@AshHimself, if you're busy with other issues, I'll be happy to take it. :)

**Comment by gazhayes** [comment]
@anbud please take it

**Comment by anbud** [comment]
Done in #607.
