### ISSUE TITLE
Problem: errors with github API are not self-corrected

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#594]
Problem: when the github API poll runs, it doesn't ask users to update the repo url.

Possibly better solution: add the error to applog, and if it happens x times automatically remove the github repo from the currency's collection so that the currency detail page asks users to provide the repo. That way incorrect repos will automatically be fixed. If the server can't reach github or something however, we don't want it to accidentally purge all github repo data from the database.

**Comment by gazhayes** [comment]
ping @anbud

**Comment by anbud** [comment]
I'm on it.

**Comment by anbud** [comment]
Done in #597.
