### ISSUE TITLE
problem: 'features' section on currencydetail route is collapsible

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#595]
Problem: this requires extra unnecessary clicks. Things should be as simple as possible. 

Possible solution: limit results to x and use a 'load more' button to show more.

@janat08 you might like this one.

**Comment by janat08** [comment]
Ill take it

**Comment by janat08** [comment]
not taking

**Comment by janat08** [comment]
did the load more logic.

**Comment by gazhayes** [comment]
ping @MadanBhandari

**Comment by samuelralak** [comment]
well, the features section is still collapsible and in my opinion non-intuitive. It simply looks like an ordinary section header and one would easily assume that this particular section has no content. Personally I didn't know I to click on it to see content until I came across this issue.

<img width="1241" alt="screen shot 2018-03-18 at 7 49 15 pm" src="https://user-images.githubusercontent.com/4476552/37568422-f68cac80-2ae5-11e8-9fb7-9ffa3c29b06d.png">

The `load more` button could also use some styling.

If no one else is actively working on this, I would like to pick it up. Guys let me know your thoughts. ping @gazhayes @MadanBhandari @janat08

**Comment by gazhayes** [comment]
I'm not sure what @MadanBhandari is doing, but solving this problem should not cause any issues.

When doing *any* styling on Blockrazor please use bootswatch to the maximum amount possible, this allows us to switch the 'theme' very simply and easily. Avoid using any custom css for styling wherever possible.

**Comment by samuelralak** [comment]
alright, taking this

**Comment by samuelralak** [comment]
fixed with [#643](https://github.com/Blockrazor/blockrazor/pull/643), won't be making any more commits here @gazhayes
