### ISSUE TITLE
problem: weird wallet layout on mobile

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#596]
Problem: 
![s80317-19201024](https://user-images.githubusercontent.com/8143945/37554801-c90e7ca2-2a18-11e8-887b-cc5056e28499.jpg)

Anyone else getting this?

**Comment by anbud** [comment]
@gazhayes, this is what I get, it's basically the same.
![img](https://eu1rgn-api.samsungcloud.com/ors/v2/public/download/1jALU0xtI4xg_760?auth_code=3356)

**Comment by janat08** [comment]
its the bad merger of layout components. the wallet and notification pages acted as if they're alone on the page previously (i got the same error when trying to migrate classes from original navbar to new one in imported). I speculate that this is from when scss styles were merged into a single file.

**Comment by gazhayes** [comment]
Ping @MadanBhandari

**Comment by MadanBhandari** [comment]
![](https://i.imgur.com/L5DqUgD.jpg) Looks good on my phone, can you tell me which phone you are using ?

**Comment by gazhayes** [comment]
Log in with frank:rodviv

**Comment by MadanBhandari** [comment]
@gazhayes looks fine on my mobile :thinking: ![](https://i.imgur.com/YkI9J3a.jpg)

**Comment by anbud** [comment]
@MadanBhandari Samsung S8 in my case, it has quite a big screen.

**Comment by gazhayes** [comment]
I dont have access to a computer right now, maybe you can check the resolution of those screen grabs and see if there's something there.

**Comment by MadanBhandari** [comment]
I have checked all the available devices on Chrome, I will also check on some manual screen sizes too.

**Comment by gazhayes** [comment]
Strange. @janat08 can explain more about what you think is causing this?

**Comment by janat08** [comment]
if you apply some class that used to be on topbar or sidebar before the migration to imports, you'd get this look. then we MadanBhandari combined layout styles where he could've merged class styles, although i was also using chrome.

**Comment by janat08** [comment]
PS: that is combined styles from the old primary layout into new one that he recreated in imports folder that we're using.

**Comment by gazhayes** [comment]
@MadanBhandari since you are redoing everything with bootswatch you should take this one and see what happens when you restyle it. Maybe it will resolve itself.

**Comment by MadanBhandari** [comment]
Yes, I will check and will remove all unused css as well, I have checked on chrome responsive with s8 dimensions, it's also looks fine here.

**Comment by samuelralak** [comment]
applying `width: 100%` to the `.card` seems to fix this issue. Its a quick fix and works fine on all layouts. checkout screenshot below:

<img width="1187" alt="screen shot 2018-03-17 at 4 47 15 pm" src="https://user-images.githubusercontent.com/4476552/37556178-3ff0a43c-2a03-11e8-8546-6d508d852022.png">

**Comment by gazhayes** [comment]
That is definitely the simplest solution!

**Comment by gazhayes** [comment]
Yep! Perfect :)

**Comment by samuelralak** [comment]
@gazhayes I would also suggest truncating the total balance after x characters. on smaller devices the total balance value seems to overflow outside the `alert.alert-info` div when characters(digits) are too many. kindly let me know your thoughts on this or if its worth creating a seperate issue of its own?

**Comment by gazhayes** [comment]
You should create a new issue for that.

Also, the way we usually do things is to comment on an issue that you have solved to let the person who logged the issue know that there are no more pull requests coming and they can test + close the issue. 

You're finished with this particular issue, right?

**Comment by samuelralak** [comment]
@gazhayes got it 👍. Yes, am done with this issue
