### ISSUE TITLE
Problem: add currency form jumps around on input

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#6]
When selecting any input field, some help text is shown below. Due to the layout of the form, this reshuffles things around to make everything fit (every time you mouse or tab through form elements).

Solution: make the form items the full width of the form panel instead of half width, arrange form elements in a nice way.

**Comment by janat08** [comment]
Do you think that an aside my do a better job of displaying help info? Are you open to using CSS framework such as semantic ui?

**Comment by janat08** [comment]
I'm looking to work on this, seeking bounty.

**Comment by gazhayes** [comment]
Yes that would probably be much better.

If you want to use Semantic-UI that's perfectly fine with me, I was already leaning towards it anyway for some other elements :)

**Comment by gazhayes** [comment]
Temporarily removing this from bounty list until a decision is reached about site-wide use of Semantic-UI vs Bootstrap.
