### ISSUE TITLE
Problem: Manual CSS work needed to improve layout

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#60]
Adding Semantic-UI. Taking care of it without any theming, and installing as framework using atmosphere package as there's special integration taking advantage of meteor bundler allowing selection of framework components for smaller bundle.

**Comment by janat08** [comment]
Bootstrap is already loaded from cdn, with layout classes applied on top templates within routes (editAnything) which then interferes with semantic-ui (making sticky rail for add coin form: https://github.com/Blockrazor/blockrazor/issues/6.

**Comment by gazhayes** [comment]
Can you dynamically load semantic-ui on that page alone (for now)? It does indeed break some other things (such as modals) used elsewhere.

**Comment by janat08** [comment]
There's an issue with it's layout (column classes) conflicting with sticky rails, so I could instead load bootstrap on separate routes, and semantic-ui on that one which I suppose will involve setting semantic-ui layout.

**Comment by janat08** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/6086
Packages have to support dynamic import.

**Comment by gazhayes** [comment]
Reference #64

**Comment by janat08** [comment]
I stopped working on this although CSS grid could be used.
