### ISSUE TITLE
problem: no sample login credentials

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#601]
Problem: new developers need to see moderator and user views with populated data.

Solution: add exampele creds to readme.

I'll take this.

**Comment by janat08** [comment]
the constellation package has accounts option which isn't enabled by default in config, that will let you switch accounts.
![screenshot 24](https://user-images.githubusercontent.com/11337345/37699328-41c29caa-2d11-11e8-953a-27bafde3c66e.png)

**Comment by gazhayes** [comment]
Ok that's a better solution. Can you take this one?

**Comment by janat08** [comment]
Fine, I'll go find user that did a lot of things in a DB dump, and suggest using him, but providing password too wouldn't be bad (which I can't get to).

**Comment by gazhayes** [comment]
I guess for the production server just giving a user\password is a good solution, but it's definitely good to be able to switch users when developing, this would have made life much easier for me before.

**Comment by janat08** [comment]
you can't permanently switch to a certain user, so you'll have to constantly switch to admin user after every refresh.

**Comment by gazhayes** [comment]
OK, I'll fix this with some login credentials in the Readme.
