### ISSUE TITLE
Problem: proposed changes being merged after just one approval

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#606]
Problem: proposed changes should (and were) being merged after 3 approvals. However they seem to be merged after the first approval.

ping @AshHimself

**Comment by AshHimself** [comment]
Hey @gazhayes, this is just a config item in properties.js Its set as 0 right now so we can test changes straight away without having to wait for someone else to vote on it.

**Comment by gazhayes** [comment]
Ah cool, ok that's actually perfect anyway.
