### ISSUE TITLE
problem: radar charts on home route do not always render

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#609]
Problem: when going to the home route from most other routes using the browser's back function radar charts are not rendered.

**Comment by AshHimself** [comment]
I have a fix to get this working.

**Comment by AshHimself** [comment]
Ok so I could replicate this before but now I can't.. are you still able to replicate this @gazhayes ?

**Comment by gazhayes** [comment]
Huh, weird, it was 'working' earlier today. Maybe someone snuck in a sneaky fix.
