### ISSUE TITLE
Problem: features/red-flags/summaries/comments are not sorted by rating

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#611]
Problem: When I originally built the features section I sorted comments and features by `rating`. The rating is a ratio between upvotes and total votes. This has been lost somewhere along the way.

https://github.com/Blockrazor/blockrazor/blob/0df2d3e1bf15c130b1d4222af33955c0498d3881/imports/api/features/methods.js#L5-L20

This means that brand new summaries/features/comments/whatever SHOULD *always* go straight to the top but then move down the list very quickly if people downvote them. The problem this solves is that new features/comments/whatever will never make it into a visible section to be voted on if they are not inserted at the top of the list.

**Comment by gazhayes** [comment]
@AshHimself I haven't checked if summaries are using this logic or not, you might have to add it.

**Comment by gazhayes** [comment]
@AshHimself if you're doing #619 instead of this, @janat08 might want to do it.

**Comment by AshHimself** [comment]
I got about 70% into this last night before falling asleep. I am sending a PR through for 619 and this within the hour, Anud answered my question on 619 so its good to go.

**Comment by gazhayes** [comment]
Ok cool.

**Comment by gazhayes** [comment]
I guess there's a fine line somewhere between hogging issues and "I'm waiting for a reply to get going on that other one and have nothing to do".

**Comment by AshHimself** [comment]
Just looking at this again and doing testing with multiple accounts and our rating is always staying as 1. 

You stated about that the old calculation was a ratio of total votes + and upvotes? I don't think we are even storing what type of vote it even is, just that the user has voted (stored in [appealVoted] ?)

Perhaps this is the problem ? or maybe i'm on the wrong path, thought i'd check before putting more time in.

**Comment by gazhayes** [comment]
The `vote` method above isn't being used?

**Comment by gazhayes** [comment]
I went back in history to confirm, it was definitely being used here: https://github.com/Blockrazor/blockrazor/blob/95934d84257f025b33f3f4ac2eb5cd443092fa45/client/normal/currencyDetail/fundamentalMetrics.js#L233-L247

If someone removed it I'm going to be very annoyed with whoever it was.

**Comment by AshHimself** [comment]
No no, that is still there. I think am confusing yourself and myself a little bit here. I am doing tests on comments and features and downvoting and upvoting and rating is being updated. Maybe I got the problem understanding wrong?

**Comment by gazhayes** [comment]
Hmmm ok. As long as the rating is being updated, then it's just a matter of sorting by rating in the UI.

**Comment by gazhayes** [comment]
The expected behaviour is that brand new ratings/comments/whatever *always* go straight to the top but then move down the list very quickly if people downvote them.

**Comment by AshHimself** [comment]
Ok so @gazhayes I think its working correctly (at least I think it is)

I created a feature with account1. Post a comment with account one and it went to the top. Posted a comment with account 2 and it went above the first comment. Down-voted second comment which was at the top and now its at the bottom.

**Comment by gazhayes** [comment]
I just tested on Monero adding "RANKING TEST" as a feature and it looks like it's not working.

**Comment by gazhayes** [comment]
Did the same thing in summaries and it also isn't working.

**Comment by AshHimself** [comment]
Got it! I was testing the ordering of comments against the features :( Great news.. that is working I believe :)

**Comment by gazhayes** [comment]
I haven't tested comments actually, so they are working?

**Comment by AshHimself** [comment]
I believe so. I posted my simple test script above of what the test case I
went through.

**Comment by samuelralak** [comment]
Voted for `RANKING TEST` under Monero using two seperate accounts, it changed its position to second; however, wouldn't it be useful knowing exactly what number of votes(up/down votes) a votable collection e.g `Feature` has? Currently its a bit confusing.

Should user's be allowed to retract their votes e.g lets say I upvoted a feature instead of a downvote, what would a user do in such a case?

**Comment by gazhayes** [comment]
OK looks like this original issue is fixed. Thanks @AshHimself 

> Should user's be allowed to retract their votes 

Yeah, that should be added.

> wouldn't it be useful knowing exactly what number of votes(up/down votes) a votable collection e.g Feature has? 

Maybe, but that could also confuse people because things aren't sorted that way. Something with 100 upvotes and 2 downvotes will still be below something with 2 upvotes and 0 downvotes.
