### ISSUE TITLE
problem: no official logo

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#613]
Problem: blockrazor does not have an official logo. 

A few different logo formats are required but all must be very recognizable as the same thing:
1. Horozontal logo - used in nav bars etc
2. Square logo - used for profile picture type places, e.g. Twitter, github, maybe other places
3. Icon - used for favicon or other places that require a small icon type logo
4. All 3 of the above must have dark and light versions so they can be used on a variety of background colours.

Imagery: blockrazor is essentially a social + API driven database of blockchain projects which can provide a very broad view of the entire blockchain landscape while also allowing filtering (not built yet). The 'filtering' is the 'razor' part, allowing users to slice through the data to find what they're specifically looking for, e.g. "show me what can I mine right now with my specific GPU that is currently undervalued but will probably be worth a lot in the future". 

So blockrazor is a combination of broad and up-to-the-minute vision, as well as the slicing/razoring/filtering thing. I'm not sure what the best route to go is with the logo, but I guess the choice comes down to highlighting the 'vision' thing (e.g. the eye of horus) or the 'razor' thing (a razor blade or something). 

Possible solution: use a logo competition with prize money for whatever logo wins. All developers and everyone else involved can look through the entries to see what they like the best.

**Comment by gazhayes** [comment]
A logo competition is running here: https://www.freelancer.com/contest/Design-a-Logo-for-Blockrazor-1286618.html

**Comment by AshHimself** [comment]
156 submissions already lol, really?

**Comment by gazhayes** [comment]
Yeah 95% BS

**Comment by gazhayes** [comment]
If anyone likes any of these logos please comment.

ping @samuelralak @AshHimself @sjmackenzie @clacke @kevgathuku @anbud @janat08 @MadanBhandari @chamidu-supeshala 

<img width="567" alt="screen shot 2018-04-05 at 12 16 36 pm" src="https://user-images.githubusercontent.com/8143945/38467809-44e924ea-3b70-11e8-8606-d0b289606412.png">
<img width="595" alt="screen shot 2018-04-05 at 12 16 46 pm" src="https://user-images.githubusercontent.com/8143945/38467810-4514d23e-3b70-11e8-9889-d350f640ca84.png">
<img width="458" alt="screen shot 2018-04-05 at 12 16 58 pm" src="https://user-images.githubusercontent.com/8143945/38467811-453d773e-3b70-11e8-9d14-364593dae6a0.png">
<img width="661" alt="screen shot 2018-04-05 at 12 17 32 pm" src="https://user-images.githubusercontent.com/8143945/38467812-45654da4-3b70-11e8-9493-b5738175fdff.png">
<img width="390" alt="screen shot 2018-04-05 at 12 18 05 pm" src="https://user-images.githubusercontent.com/8143945/38467813-458c81c6-3b70-11e8-8105-4c1be7a3a6cb.png">
<img width="382" alt="screen shot 2018-04-05 at 12 18 21 pm" src="https://user-images.githubusercontent.com/8143945/38467814-45b9163c-3b70-11e8-8a9f-223c3e51add3.png">
<img width="359" alt="screen shot 2018-04-05 at 12 19 22 pm" src="https://user-images.githubusercontent.com/8143945/38467815-45e1af16-3b70-11e8-8967-048f59a0136d.png">
<img width="340" alt="screen shot 2018-04-05 at 12 19 40 pm" src="https://user-images.githubusercontent.com/8143945/38467816-46094a12-3b70-11e8-8bb0-e35ff62dec06.png">
<img width="334" alt="screen shot 2018-04-05 at 12 19 50 pm" src="https://user-images.githubusercontent.com/8143945/38467817-4630c100-3b70-11e8-9f9e-4bede376fcca.png">
<img width="675" alt="screen shot 2018-04-05 at 12 20 03 pm" src="https://user-images.githubusercontent.com/8143945/38467818-4658134a-3b70-11e8-8f1b-827b3f9d79d8.png">
<img width="415" alt="screen shot 2018-04-05 at 12 20 26 pm" src="https://user-images.githubusercontent.com/8143945/38467819-467fdaba-3b70-11e8-8820-c262b2e10d47.png">
<img width="430" alt="screen shot 2018-04-05 at 12 20 39 pm" src="https://user-images.githubusercontent.com/8143945/38467820-46a908cc-3b70-11e8-97fd-1341c6eabc95.png">
<img width="251" alt="screen shot 2018-04-05 at 12 21 48 pm" src="https://user-images.githubusercontent.com/8143945/38467821-46d12bb8-3b70-11e8-9a5f-c2632c52d19c.png">
<img width="610" alt="screen shot 2018-04-05 at 12 22 14 pm" src="https://user-images.githubusercontent.com/8143945/38467822-46f9e30a-3b70-11e8-9f1e-a4a1292054db.png">
<img width="400" alt="screen shot 2018-04-05 at 12 22 39 pm" src="https://user-images.githubusercontent.com/8143945/38467823-4722f97a-3b70-11e8-91ee-1a996eef8739.png">
<img width="429" alt="screen shot 2018-04-05 at 12 23 22 pm" src="https://user-images.githubusercontent.com/8143945/38467824-474b6ce8-3b70-11e8-9d52-caca77c30b14.png">
<img width="440" alt="screen shot 2018-04-05 at 12 23 45 pm" src="https://user-images.githubusercontent.com/8143945/38467825-47745798-3b70-11e8-8006-7d4ad57c3beb.png">
<img width="621" alt="screen shot 2018-04-05 at 12 23 55 pm" src="https://user-images.githubusercontent.com/8143945/38467826-479bf8ca-3b70-11e8-84ef-b839a605b6da.png">
<img width="304" alt="screen shot 2018-04-05 at 12 24 06 pm" src="https://user-images.githubusercontent.com/8143945/38467827-47c3a8a2-3b70-11e8-8cec-fc10c73b886e.png">
<img width="347" alt="screen shot 2018-04-05 at 12 24 17 pm" src="https://user-images.githubusercontent.com/8143945/38467828-47ece06e-3b70-11e8-940a-5a35c07c2db2.png">
<img width="442" alt="screen shot 2018-04-05 at 12 24 29 pm" src="https://user-images.githubusercontent.com/8143945/38467829-4815a256-3b70-11e8-82ec-51182fc3848d.png">
<img width="351" alt="screen shot 2018-04-05 at 12 24 46 pm" src="https://user-images.githubusercontent.com/8143945/38467830-483e87fc-3b70-11e8-8885-029711eecd1e.png">
<img width="334" alt="screen shot 2018-04-05 at 12 24 53 pm" src="https://user-images.githubusercontent.com/8143945/38467831-48677720-3b70-11e8-95e4-9ebe6c2f6a46.png">
<img width="679" alt="screen shot 2018-04-05 at 12 25 03 pm" src="https://user-images.githubusercontent.com/8143945/38467832-48b528d0-3b70-11e8-9723-80fbeda53126.png">
<img width="465" alt="screen shot 2018-04-05 at 12 25 11 pm" src="https://user-images.githubusercontent.com/8143945/38467833-48dd3f0a-3b70-11e8-8f4c-a9614ed5165e.png">

This one made me laugh:
<img width="427" alt="screen shot 2018-04-05 at 12 26 13 pm" src="https://user-images.githubusercontent.com/8143945/38467834-490516ba-3b70-11e8-98e9-86b58246cb9a.png">
<img width="475" alt="screen shot 2018-04-05 at 12 27 36 pm" src="https://user-images.githubusercontent.com/8143945/38467835-492cf9dc-3b70-11e8-8671-dd30750546e5.png">
<img width="388" alt="screen shot 2018-04-05 at 12 29 14 pm" src="https://user-images.githubusercontent.com/8143945/38467836-49549438-3b70-11e8-9992-1a957aa3b8a7.png">
<img width="410" alt="screen shot 2018-04-05 at 12 29 30 pm" src="https://user-images.githubusercontent.com/8143945/38467837-497c03e2-3b70-11e8-923b-7e2c76343176.png">
<img width="342" alt="screen shot 2018-04-05 at 12 29 42 pm" src="https://user-images.githubusercontent.com/8143945/38467838-49a8c8aa-3b70-11e8-8a82-1c7520f4a410.png">
<img width="299" alt="screen shot 2018-04-05 at 12 29 56 pm" src="https://user-images.githubusercontent.com/8143945/38467839-49d0c652-3b70-11e8-93c5-265ed5b7abea.png">

**Comment by AshHimself** [comment]
I actually don't mind the last two.. and the one that made you laugh gave me a right giggle too.

**Comment by samuelralak** [comment]
these two look alright
<img width="700" alt="screen shot 2018-04-08 at 4 13 05 pm" src="https://user-images.githubusercontent.com/4476552/38467946-c83e04ec-3b47-11e8-8a4e-40c8ecc9634a.png">

**Comment by chamidu-supeshala** [comment]
For me, 
![image](https://user-images.githubusercontent.com/27463355/38468730-b080c798-3b67-11e8-9a41-5d09fba2f6c0.png)

and 

![image](https://user-images.githubusercontent.com/27463355/38468743-ec06fada-3b67-11e8-9c62-d7985763f32c.png)

feels good

**Comment by clacke** [comment]
I want logos where the letters interact with some item that represents the subject. These have a razor/blade in there, and I don't like how those gaping K razors look.

![razor A](https://user-images.githubusercontent.com/8143945/38467812-45654da4-3b70-11e8-9493-b5738175fdff.png)


![safety razor BR](https://user-images.githubusercontent.com/8143945/38467813-458c81c6-3b70-11e8-8105-4c1be7a3a6cb.png)

**Comment by anbud** [comment]
I've just noticed that I haven't posted here. I like the following:

![this](https://user-images.githubusercontent.com/8143945/38467811-453d773e-3b70-11e8-9d14-364593dae6a0.png)

![this](https://user-images.githubusercontent.com/8143945/38467837-497c03e2-3b70-11e8-923b-7e2c76343176.png)
