### ISSUE TITLE
Problem: clicking usernames does not go to user profile page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#619]
Problem: users should be directed to user profile pages onClick (anywhere that usernames are displayed).

Pretty sure this was working on the currency detail page but is now broken.

**Comment by AshHimself** [comment]
Taking this. @anbud we don't have a sub setup for the users collection and that is the only table which seems to old the users slug. For example. To link to the users profile from the features table all we have is the author name and id. Thoughts?

**Comment by anbud** [comment]
@AshHimself,
The idea here was to have a popover whenever you hover over a username, and then it could take you to user's profile. To use the `userHover` template, you just need to pass the `_id` and it would do the rest (subscribe to users collection, get profile image and link to user's profile).

But, if you want to just link to user's profile, and you have the username, you can generate the slug yourself from the username.
You can see how it's generated [here](https://github.com/todda00/meteor-friendly-slugs/blob/master/slugs.coffee#L274-L279) (it's basically a one-liner). Maybe we can make a utility function for slugifying or something.

**Comment by gazhayes** [comment]
I'm not sure if the original issue was clear enough, but can you check that this works site wide not just the currency detail page (I just used that as an example). For example hashpower, etc.

**Comment by AshHimself** [comment]
Yup... what I am doing is creating a global helper which allows us to get
the slug URL from the {{author}} and then i'll update it wherever
{{author}} is found.

**Comment by AshHimself** [comment]
Fixed in #628
