### ISSUE TITLE
Problem: slow meteor reloads

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#62]
qualia:reval allows you to only reload relevant template without having meteor rebuild everything and is dev only package.

**Comment by gazhayes** [comment]
You can go ahead and install that if you want.

**Comment by janat08** [comment]
Any change this could go into packages folder for I don't know how to keep it out of pull requests without deleting/adding it for every branch (along with babrahms:constellation).

**Comment by gazhayes** [comment]
If you want to use it locally you could try using .gitignore
