### ISSUE TITLE
problem: @ashhimself's commits are not showing up in the contributor graph

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#623]
Problem: commits from @AshHimself are not showing up [here](https://github.com/Blockrazor/blockrazor/graphs/contributors)

@anbud or @sjmackenzie might know why.

**Comment by AshHimself** [comment]
Ok I just went through some of the steps in this page https://code.bradymower.com/why-arent-my-commits-showing-up-on-my-contributions-graph-52141efa7542 and my emails for whatever reason did not match. Let's check after my next PR.

**Comment by gazhayes** [comment]
Ah yes that would explain it.

**Comment by AshHimself** [comment]
@gazhayes - this looks to now be resolved.
