### ISSUE TITLE
Problem: no currency comparison prices

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#627]
Problem: At the moment, currencies are priced as the current price per coin. The calculation is: 
```
price = market cap / number of coins in circulation
```

The problem is, the number of coins in circulation varies from currency to currency, so comparing prices is really comparing nothing. 

Even though this is how everyone is doing it now, it really isn't a good way to compare currencies to other currencies. What's really needed is to compare how much it costs for x% of the total network.  Something like this perhaps: 
```
Comparison Price (Circulation) = (coins in circulation / 100000000) * (current price per coin)
```

and:
```
Comparison Price (Total) = (total supply / 100000000) * (current price per coin)
```

Total supply is the maximum ever number of coins on that blockchain. Coins in circulation is the total number of coins currently in circulation. Coins in circulation is pulled through an API. Maximum number of coins is a data point provided by users.

Prices compared in this way will be the price for a 100,000,000th share in the coins in circulation (or the coins in total).

We could then use CPC and CPT as comparison indicators along with the PPC (price per coin) on the home route and elsewhere.

**Comment by anbud** [comment]
I'll take this one.

**Comment by anbud** [comment]
Done in #720.
