### ISSUE TITLE
Problem: no bounties to add hashpower API pull request 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#629]
Problem: the hashpower metric relies on having up to date network hash rates for each currency. An example pull request doing this for Ethereum is here: https://github.com/Blockrazor/blockrazor/pull/362

We need to somehow add a new bounty for each currency that does not have a hashpower API call, or any currency where the hashpower API call hasn't been working for a while, maybe 24 hours, as this would indicate that the API endpoint has changed or died.

It has to be on a per-currency basis, because some are much harder than others (finding an API endpoint, maybe have to sign up for an account to use it, etc etc). 

The bounty would have to be locked to prevent other users doing the same one at the same time. Though the lock time would have to be long enough for people to work this one out, I guess 2 hours. It shouldn't be available to other users until the previous user has had 10 minutes to renew their lock (because this bounty type could take a while in some situations and we don't want to annoy developers too much by having them lose their work if they are actually actively doing it).

To complete the bounty, a user should put in a link to their pull request, and it should be removed from the bounty page but not actually awarded until merged (github API).

@anbud you're probably going to like this one.

**Comment by anbud** [comment]
@gazhayes, yap, you're right, I like this one. :) When I finish #580, I can start working on it.
I just have one question. Since bounties will be on a per-currency basis, how will we determine the bounty reward for each individual currency? Manually adding it wouldn't be feasible, and to automate it we need some sort of criterion. Maybe the amount of data we currently have on the currency (all data or hash power data) could be inversely proportional to the bounty reward for hash rate API calls?

**Comment by gazhayes** [comment]
>  Since bounties will be on a per-currency basis, how will we determine the bounty reward for each individual currency?

I saw we just add them at creation time and use the same uptick timer. The easy ones will go first, and the more difficult ones will accumulate more of a reward, it should hopefully reach some kind of equilibrium.

**Comment by anbud** [comment]
@gazhayes, I'll send another PR shortly, it appears that a bounty is not locked when someone is working on it. It should be an easy fix.

**Comment by anbud** [comment]
Done in #715.
