### ISSUE TITLE
Problem: [/bounties] cannot filter bounties by type

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#632]
Problem: some bounties are not applicable to some users. For example some bounties require you to be a developer. Users should easily be able to filter out bounty types that they don't want to work on.

**Comment by janat08** [comment]
if you mean: http://localhost:3000/bounties

then putting a header for technical bounties would be enough?

**Comment by gazhayes** [comment]
You mean a header on each bounty? No it wouldn't solve the problem because there are about to be a lot more individual bounties (that bounty page could end up having 1000+ bounties on it).

**Comment by AshHimself** [comment]
@gazhayes do we know all the different types of bounty types? 

Should these types be something we manage as a collection or global array in properties.js?

**Comment by gazhayes** [comment]
There's an existing bounty types collection, I haven't looked at it for a while though.

**Comment by AshHimself** [comment]
Just just looking at that now actually.. looks like it has one record. If
this is something you see being managed often then a collection will do the
trick otherwise its best to keep it static on the server.

How is the bounties page populated at the moment? bounty types in the
bounties collection don't seem to correlate.

**Comment by gazhayes** [comment]
Actually, @anbud built most of that, it will probably take him 10 minutes to add filtering because he knows that part of the codebase very well. May as well leave it for him.

**Comment by anbud** [comment]
@gazhayes, I haven't used BountyTypes collection, as it wasn't compatible with the idea at the time. Currently, I can say that we have three types of bounties, bounties to answer questions, bounties to add new data (hash power, currencies), and the old bounty system used for feature requests I believe. There will be a fourth type soon, bounties that would link to problems. 

Would this be a sufficient separation for filtering?

**Comment by gazhayes** [comment]
That might be enough. The most important ones to be able to filter by are the ones that require coding skills (codebase ratings, problems)

**Comment by anbud** [comment]
Done in #719.
