### ISSUE TITLE
Problem: [/bounties] reason for resetting bounty value is not clear to users

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#633]
Problem: when users go to the bounty page and someone *else* completes a bounty, the bounty reward is reset. To the user, this is just looks like the number goes back to 0 and starts ticking again.

Possible solution: overlay the bounty item on the bounty page with a notification saying that xxxx user has claimed this bounty for xx KZR and the bounty reward has been reset.

It would also be cool to somehow show what the last bounty amount was, so that users have some idea how high they should 'bid' to complete a bounty.

**Comment by janat08** [comment]
I could try this?

**Comment by gazhayes** [comment]
Yeah, sure.

**Comment by janat08** [comment]
The schema for bounties is wild. In short I can't begin to presume what the schema is, and if it's correct as I think that "Blockrazor needs new codebase ratings" stands for currency rather than website. I can't complete a bounty either since it requires approval and they don't show up in moderator dash.

**Comment by janat08** [comment]
there're no bounties in dump.

**Comment by gazhayes** [comment]
I'll update the database dump.

The codebase ratings are to rate the codebase of a currency. It's just like the other bounties (wallet, community) except it's for the codebase. The only difference is that users need to apply to be allowed to rate codebases.

**Comment by gazhayes** [comment]
Do you still want this one? #69 is more important, but I'm not sure how much time you need to spend on it.

**Comment by janat08** [comment]
I unassigned myself, but will take it after disabling validation and 69, and validating #649

**Comment by janat08** [comment]
where do you approve community ratings?

**Comment by janat08** [comment]
I couldn't test anything, since bounties wouldn't reset, and previous reward payout isn't styled and I just alert saying bounty was reset.

**Comment by gazhayes** [comment]
> where do you approve community ratings?

Actually, don't worry about community/wallet/codebase stuff because the approval process hasn't been finalized yet anyway.

You should be able to do the add currency one though, you could send a PR just for that one first.

**Comment by janat08** [comment]
yes I can't test that as bounty won't actually reset on blockrazor master.

**Comment by gazhayes** [comment]
Ah ok I get what you mean now. I just discovered another related problem that I will log in a few minutes, that one may need to be solved before you can solve this one.

**Comment by janat08** [comment]
anyway, that code is fairly nasty. there're 3 collections involved, 2 of which are then mapped like every 10 ms into a bounty.

**Comment by gazhayes** [comment]
related: #718

**Comment by gazhayes** [comment]
@janat08 where does this number come from?

<img width="1120" alt="screen shot 2018-03-25 at 9 43 48 am" src="https://user-images.githubusercontent.com/8143945/37870812-4322f5ec-3011-11e8-986f-81ab31610eae.png">

**Comment by samuelralak** [comment]
Hey @janat08 whats progress with this one? I would like to take a stab at it after am done with [#727](https://github.com/Blockrazor/blockrazor/issues/727)

**Comment by gazhayes** [comment]
@samuelralak you can just go ahead with this if you want :)

**Comment by janat08** [comment]
the 2nd number is the previous bounty amount when it was taken

**Comment by janat08** [comment]
still can't be tested, since  items are immidiately approved likely thanks to validation skip code.

**Comment by janat08** [comment]
@samuelralak the UI/CSS still needs work, I just planted last bounty near current bounty.

**Comment by gazhayes** [comment]
OK, so the last bounty amount is incorrect. I tested it twice to make sure.

The last bounty for addcoin was 14.516209 however 18.593672 is displayed.

**Comment by janat08** [comment]
@samuelralak and this part has no CSS  it just calls sAlert: 

> overlay the bounty item on the bounty page with a notification saying that xxxx user has claimed this bounty for xx KZR and the bounty reward has been reset.

**Comment by gazhayes** [comment]
Things go stale because people don't know what's happening after all the comments and pull requests and it becomes too hard to work it out.

Instead of tagging with stale, just close the issue and log a new one. Describe the current problem as it exists right now, without the history of this issue. Look at it as a completely new problem, as if you are encountering it for the first time and had never seen this thread.

Be very very clear, use code examples if necessary.

**Comment by janat08** [comment]
Will close after new issue.

**Comment by janat08** [comment]
@samuelralak did you make a proper overlay for when the bounty is reset?
