### ISSUE TITLE
Problem: applog user field may be embeded in itself

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#635]
Problem:  Some log type can have it's user field embeded in itself.

**Comment by gazhayes** [comment]
Embedded as an object? Or embedded in the message?

**Comment by janat08** [comment]
additional.user.user

**Comment by gazhayes** [comment]
Can you post a screen shot?

**Comment by janat08** [comment]
![screenshot 23 _li](https://user-images.githubusercontent.com/11337345/37594397-327fd0fa-2b9f-11e8-9f94-59ae0dc6d3b7.jpg)

**Comment by janat08** [comment]
i restored dump before posting.

**Comment by gazhayes** [comment]
We can safely leave this the way it is (for now). I will reopen it later though.
