### ISSUE TITLE
Problem: [/bounties] add hashpower bounty resets reward on cancel

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#637]
Problem: picking and canceling add hashpower bounty will reset reward.

**Comment by gazhayes** [comment]
Good catch

**Comment by janat08** [comment]
the problem went away when I updated dump. On another hand, if you "meteor reset" it will totally break.

**Comment by janat08** [comment]
and it's back

**Comment by janat08** [comment]
so yea, you have to make sure there's createdAt field.

**Comment by janat08** [comment]
PS: all bounties assume there's already a record, or use Date.now() except add new coin.

**Comment by gazhayes** [comment]
Is this happening on the production server or only locally on your dev server?

**Comment by janat08** [comment]
dev server, if there're no completed bounties it will basically break.

**Comment by gazhayes** [comment]
Ok. Then it should be ok once there are some completed bounties so don't worry. If it works on the production server then its working.

**Comment by janat08** [comment]
I don't think createdAt field is inserted when hashpower is added.
