### ISSUE TITLE
Problem: UI is generally very ugly

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#64]
The UI at present is very basic. 

Bootstrap is currently used but may not be the best thing to use long term. It doesn't appear to be all that easy to build something that scales well, and tends to have a 'bootstrap' look and feel which is hard to avoid.

Comments about the usefulness of other CSS frameworks in this situation are very welcome.

**Comment by janat08** [comment]
https://developers.google.com/web/fundamentals/design-and-ux/responsive/#set-the-viewport
