### ISSUE TITLE
problem: [/currency] when upvoting/downvoting a comment, all comments are marked as "voted"

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#640]
Problem: when upvoting/downvoting a comment, all comments are marked as "voted"

I voted on one of these comments and they were all marked as voted.

Need to also verify if this problem affects the database or only the UI.

<img width="392" alt="screen shot 2018-03-19 at 9 48 04 pm" src="https://user-images.githubusercontent.com/8143945/37599270-4bf01638-2bbf-11e8-8f1d-0e1328adcb7d.png">

**Comment by samuelralak** [comment]
it affects the database the as well
- I voted on a comment and it automatically applied my vote all other comments; I was unable to cast any more votes even after page refresh.
- I also added a comment on a feature and it and voted and got same results as above ☝️ 
- I checked the database - features collection - and inside the `appealVoted` property value I noticed my id being added to feature documents that I didn't vote on.
- I would also advise having a comments sub document; currently all features and their respective comments are bundled in one collection. the same applies to the redflags collection.

**Comment by samuelralak** [comment]
and I'll be taking this issue as well 😄

**Comment by samuelralak** [comment]
@gazhayes submitted a PR fixing the original issue [not merged yet]. I would love to know your thoughts on this:

> we could better architect comments by having an embedded comments collection on each commentable collection or alternatively decouple comments into a collection of its own. Taking the Features collection as an example, this collection bundles all the features and their comments at root level - comments exist as feature documents.

ping @AshHimself @anbud @janat08

**Comment by janat08** [comment]
I don't know what "embedded comments collection" means, but I guess anbud didn't want to wright voting mechanic for different fields/collections, otherwise, the schema is neither optimized for meteor or for mongodb, nor convenient besides the voting methods. I already suggested using libraries that deal with relations that were only taken into consideration by gazhayes.

**Comment by gazhayes** [comment]
We could decouple comments, but then we'd have multiple comment collections (features, red flags, problems, questions, etc). 

If there are *proven* ways to increase performance, we definitely need to look at that. Apart from that, we always use the simplest possible solution.

**Comment by janat08** [comment]
the simplest solution would be to embed this comments as array :P which just runs fewer queries.
