### ISSUE TITLE
Problem: [/currency] users cannot change their vote on comments/features/red flags/summaries

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#644]
Problem:  once users have voted for a comment, feature, red flag, or summary they can't change their vote.

**Comment by AshHimself** [comment]
IMO I think it would make sense to be able to change your vote or at least have a grace period. If not, then at least give them a modal the first time to warm them of this and then not show the modal again.

**Comment by gazhayes** [comment]
OK, may as well implement this, it's quite trivial and should take less than an hour anyway.

**Comment by samuelralak** [comment]
@AshHimself @gazhayes I have the following questions:
- are we showing a modal to let the user know they cannot change their votes or are we notifying of the change vote grace period?
- are we keeping of the type of vote the user casts (upvote or downvote)?

If we are going to allow users change their votes, I would proposing having a different for the type of vote cast i.e if a user downvotes thumbs down icon should be highlighted or colored different and vice versa. This also involves keep track of the type of vote has cast (if we are not doing this already).

**Comment by gazhayes** [comment]
> If we are going to allow users change their votes, I would proposing having a different for the type of vote cast i.e if a user downvotes thumbs down icon should be highlighted or colored different and vice versa. This also involves keep track of the type of vote has cast (if we are not doing this already).

Yep I agree. You want to do it?

**Comment by samuelralak** [comment]
@gazhayes yes I do, will start working on this one tomorrow

**Comment by samuelralak** [comment]
@gazhayes whats the scale of the rating in features/summaries/comments i.e */5, */10 or */100?

**Comment by gazhayes** [comment]
The rating is `upvotes / total votes` and it works well, looks like it didn't break with that update.
