### ISSUE TITLE
problem: [/problem] headings and body show as editable in UI for users who can't edit

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#647]
Problem: the UI for users who cannot edit a problem (because they are not the creator) still looks like it can be edited. 

<img width="1153" alt="screen shot 2018-03-20 at 10 34 08 am" src="https://user-images.githubusercontent.com/8143945/37632686-68889cf0-2c2a-11e8-89c1-d64eb8410384.png">

**Comment by janat08** [comment]
@anbud would you try and use blaze, jquery makes me cringe. I'm going to refractor $.fn out of this.

**Comment by anbud** [comment]
That's part of the x-editable package that's also used when editing currency details. A simple if around it fixes this. 
How would you solve inline editable fields with Blaze only? I agree, jquery isn't perfect, but it does the job here.

**Comment by janat08** [comment]
It's fairly roundabout with different templates for editing and info display. the x-editable package is deprecated: "project is currently frozen".

**Comment by janat08** [comment]
I'll wait for gazhayes's word on this, I filed an issue: #655.

**Comment by gazhayes** [comment]
What's the absolute simplest solution to this problem?

**Comment by janat08** [comment]
I suppose looking for a disabled field and pressing on.

**Comment by gazhayes** [comment]
Zipfs law: You'll spend most of your effort on a fraction of the software. Over-engineering code that isn't in the critical path is a waste of time. It will probably end up being replaced by something else later anyway, no matter how good it is.

Lesson: if shitty code solves the problem, it's not shitty code. Use the simplest possible solution. If the simplest possible solution becomes a problem later, we'll fix it later, if we still exist.

**Comment by anbud** [comment]
I agree, one if fixes this issue (Meteor.userId() === problem.createdBy).

**Comment by janat08** [comment]
it's not reactive, I just tested it :D, the autorun will rerun, but the jquery will not care.

**Comment by janat08** [comment]
@andbud I didn't check the edit method for if it verifies access.

**Comment by gazhayes** [comment]
It verifies server side. Reactivity shouldnt be a problem on this particular route, as long as it renders correctly on load.

**Comment by janat08** [comment]
what about currency details?

**Comment by gazhayes** [comment]
No that's ok, no problems with that part
