### ISSUE TITLE
Problem: [/new-problem] users are not guided enough when reporting problems

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#649]
Problem: 

bug report and feature request types are actually the same type, we don't need to distinguish between them on the backend, but the users need to be given different kinds of encouragement to think through their report in a C4 style before submitting it. 

possible solution: 

Put the 'problem type' selector at the top so that the rest of the form can be populated accordingly.

**case: feature request**
field 1 placeholder: describe the problem you are facing that your feature request will solve
field 2 placeholder: if you have thought of a potential solution to this problem, describe it here. You can attache pictures below.
field 3 (header)  placeholder: summarize the problem from step 1 in less than 60 characters [simplSchema limit]

Field 1 and 2 can be concatenated into one, with 'problem:' and 'potential solution:' prepended appropriately.

**case: bug report**
field 1 placeholder: describe the problem you are facing, you can attach pictures below.
field 2 placeholder: explain step-by-step how others can reproduce this bug to see the same problem.
field 3 (header)  placeholder: summarize the problem from step 1 in less than 60 characters [simplSchema limit]

Field 1 & 2 concatenated into one, with 'problem:' and 'steps to reproduce:' prepended.

**Comment by janat08** [comment]
you think it might be better if steps to reproduce or solution be a separate field, since you could then edit out the text.

**Comment by gazhayes** [comment]
Yes they should be different fields (this is in my proposed solution above).

The prepended text has to be added after otherwise there can be no placeholder text.

**Comment by janat08** [comment]
I don't know how schema validation failure should interact with fields, so I'd rather wait for example.

**Comment by janat08** [comment]
waiting for #580 to close, to see how to do validation.

**Comment by gazhayes** [comment]
I just closed #580

**Comment by janat08** [comment]
aded simple schema, didn't use jquery since #580 hasn't used it, and simplschema has integration with tracker and so much have ability to be used to validate ui, and I'd like to think there's integration of some sort with validated-methods that I've integrated.

**Comment by janat08** [comment]
are images required?

**Comment by gazhayes** [comment]
> are images required?

No, not strictly required.
