### ISSUE TITLE
problem: [/new-problem] users can only upload one image

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#650]
Problem: users can only upload one image, but multiple images may be needed.

solution: dynamic 'add more' button or something.

**Comment by AshHimself** [comment]
Is this for all views? where only a single option is available?

**Comment by gazhayes** [comment]
No I've started to use [/xxxxxx] to designate routes

**Comment by gazhayes** [comment]
This one and that other image one are probably perfect for you though.

**Comment by AshHimself** [comment]
Right!!! sure I can take them. Currently traveling at the moment but I got wifi which is great.

**Comment by anbud** [comment]
This one is also already there. When you upload the first image, it gets added to uploaded images and the button turns to 'upload more'. Haven't tested it in production, that's how it works on localhost.

**Comment by gazhayes** [comment]
Woops.
