### ISSUE TITLE
problem: [/problem] question asker cannot award best answer

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#653]
Problem: the user who asked a question cannot award the answer that solves the question. 

solution: answers/comments should use the same ranking system as comments on the currency detail page, however the user who asked the question should be able to select one of the comments/answers as the "solution" to close the question (so they can either award a solution, or cancel the question).

This is not applicable to problem/bug types.

On a side note, given the difference between questions and bug reports, we should maybe use different routes to make this kind of thing easier.

**Comment by anbud** [comment]
This is already implemented, it's just I've put a limitation that a user can't accept his own answer. The user can choose to accept comments made from others, which automatically marks the issue as closed. Should I lift the limitation?

**Comment by gazhayes** [comment]
Oh ok, no leave it as is. I thought I checked under a different account but must have been mistaken.
