### ISSUE TITLE
Problem: editable field template

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#655]
Problem: make editable field template to replace jquery in currency detail and problem/:id routes. The current method relies on jquery to manipulate view, and is repeted throughout codebase rather than using a reusable template.

Solution: Make a template that is extensible and hopefully uses blaze to make a field editable rather than jquery. That would entail accepting params to make it truly reusable such as conditionals for when it should denote field as being editable and what it should do when it is edited.

**Comment by gazhayes** [comment]
This is a really badly logged issue.

Please state the problem very clearly, then state the proposed solution.

**Comment by janat08** [comment]
@gazhayes edited.

**Comment by gazhayes** [comment]
What is the core problem here?

"code is repeated throughout the codebase"?

**Comment by janat08** [comment]
Yes, for if you decided to switch out package later on and to at least hide away the jquery unpleasantness.

**Comment by gazhayes** [comment]
OK, we can deal with that later, if it becomes a bigger problem. Right now there are more important issues.
