### ISSUE TITLE
Problem: add problem link in /problems doesn't stand out, and will hide in long list

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#660]
Problem: the add it link in text "YOUR PROBLEM IS NOT ON THE LIST? ADD IT!" at the route /problems has very heavy font weight, which makes link blend it with the text. Also, it's at the very bottom of the list, so with list long enough it will hid.

Solution: prompt user to search for a problem before adding it, showing add it at bottom after search text filled in search input?

**Comment by gazhayes** [comment]
Yep, agreed.

**Comment by AshHimself** [comment]
Fixed in #693

**Comment by janat08** [comment]
the problem title isn't saved if the button is pressed (the title input isn't visible until type is selected).

it also doesn't tip of as to why button is deactivated.

**Comment by AshHimself** [comment]
> the problem title isn't saved if the button is pressed (the title input isn't visible until type is selected).
Can you please elaborate. Is this a new issue? or existing.

**Comment by janat08** [comment]
it's irritating that we demand that user first enters problem text before adding a problem to then not save it. This issue's solution suggestion is aweful and incomplete. The summary input should be visible before type is selected.

add title property to the button prompting user to search first.

Also you could use session variable to make the button deactivate if text is cleared (it doesn't), since it's to be used on another page (or wtv u like really).

**Comment by gazhayes** [comment]
> it's irritating that we demand that user first enters problem text before adding a problem to then not save it. 

I think it's ok, they would need to reword it anyway. If it can be fixed really simply and easily then ok just send a PR, but otherwise don't worry.
