### ISSUE TITLE
Problem: validation, and image validation blocks from testing user flows

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#667]
Problem: validation,  especially such that requires that images are submitted when the code is broken in development prevents devs from testing methods/website.

Solution: Remove validation using variable devValidationEnabled exported from indexDB that is false in the development environment.

**Comment by gazhayes** [comment]
We would also require the Readme to be updated with how to use this.

**Comment by janat08** [comment]
when you run meteor it launches in the development environment.

**Comment by gazhayes** [comment]
Yes, but people might try to "fix" it later if its not being validated.

**Comment by janat08** [comment]
you could also check by variable that determines if validation should be on

**Comment by gazhayes** [comment]
Ok. This is worth fixing. It's really annoying to test things when validation is required. But you have to document your code very carefully if you do this one, make sure it's really easy to understand what's happening.

**Comment by anbud** [comment]
I agree, this would be quite useful, especially for preventing uniqueness validation when uploading images that one is most annoying when testing.

**Comment by janat08** [comment]
disabled validation in most bounties other than ratings which are just all about images.

**Comment by janat08** [comment]
I'll swap this out for devValidationEnabledFalse
