### ISSUE TITLE
problem: [/problem] text in edited fields gets duplicated when editing

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#673]
Problem: 
When editing text on the /problem route the text becomes duplicated.

Edit the message and change to a single "A":
<img width="424" alt="screen shot 2018-03-21 at 8 32 31 am" src="https://user-images.githubusercontent.com/8143945/37689871-90afddd4-2ce2-11e8-8b3c-ed2476c2294f.png">

After submitting, the "A" is doubled to "AA":
<img width="447" alt="screen shot 2018-03-21 at 8 32 39 am" src="https://user-images.githubusercontent.com/8143945/37689915-cbb84286-2ce2-11e8-8bcd-6af7b91a4bc4.png">

**Comment by anbud** [comment]
I believe this is due to Meteor's reactivity not cooperating with x-editable. One possible solution is to temporarily disable Meteor's reactive updates for these two fields, which should prevent text duplication.

**Comment by samuelralak** [comment]
is this fixed? if not, how do I replicate?

**Comment by gazhayes** [comment]
Ah it appears to be fixed now.

**Comment by janat08** [comment]
it's not fixed for me.

**Comment by gazhayes** [comment]
Not fixed for you on the production server?

**Comment by janat08** [comment]
it's still issue everywhere.

**Comment by anbud** [comment]
Fixed in #717.

**Comment by gazhayes** [comment]
@janat08 is it fixed for you now?

**Comment by janat08** [comment]
yes
