### ISSUE TITLE
problem: [/problems] no line break between problem and solution statement

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#676]
Problem: no line break between problem and solution statement

<img width="1126" alt="screen shot 2018-03-21 at 11 18 34 am" src="https://user-images.githubusercontent.com/8143945/37693305-b8406398-2cf9-11e8-80a3-91a9fabe4711.png">

**Comment by AshHimself** [comment]
Fixed in #692

**Comment by janat08** [comment]
you could use: style="white-space: pre-wrap"
