### ISSUE TITLE
problem: [/problems] not clear which items are problems and which are questions

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#677]
Problem: on the /problems page it's not clear which items are problems and which are questions.

potential solution: use a bootswatch label in the header to designate whether an item is a question or problem.

**Comment by AshHimself** [comment]
Taking this

**Comment by AshHimself** [comment]
Fixed in #691

**Comment by gazhayes** [comment]
Can you update to only use [problem] and [question] but not [bug] [feature] [question]?

**Comment by AshHimself** [comment]
So you want a mapping of bug,feature,question? or just;

question = question and bug = problem.

**Comment by gazhayes** [comment]
Bug and feature request should be labeled as [problem] (they are the same thing under the C4, it's just that we need to ease users into this style of thinking gently)

Question should be [question]

**Comment by AshHimself** [comment]
Fixed in #710
