### ISSUE TITLE
problem: [/problems] datestamp used on items is not very nice

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#678]
Problem: at present, a date stamp is used to show when an item on the /problems page was created. This is not very meaningful to users.

potential solution: use momentjs (already installed) to show time since creation time (e.g. created 1 day ago)

**Comment by AshHimself** [comment]
I have already created a helper for this on another ticket Suggest we make
it global and reusable.

**Comment by gazhayes** [comment]
OK.

Also can you document all global helpers that you've made, and how to use them? I guess /docs/helpers.md or whatever

**Comment by AshHimself** [comment]
Roger that.

**Comment by AshHimself** [comment]
Fixed in #686
