### ISSUE TITLE
Problem: Empty lists don't inform of absence of records

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#68]
Empty lists may come across as bugged, should display a message about there being nothing to show.

**Comment by gazhayes** [comment]
Can you link to an example in the codebase to make sure I understand what you mean?

**Comment by janat08** [comment]
The approved/rejected moderation page.

**Comment by Fen747** [comment]
A proper way to handle this in laze is :
```
Template.tmp.onCreated(function(){
    this.subHandler = this.subscribe( '...' );
});

Template.tmp.helpers({
    subscriptionIsReady(){
        return ( Template.instance().subHandler.ready() );
    },

    getSubscriptionData(){
        return ( Collection.find({ ... }) );
    },
});

<template name="tmp">
    {{#if subscriptionIsReady}}
        {{#each getSubscriptionData}}
            [...]
        {{/each}}
    {{/if}}
</template>
```

Wich, to say the truth, is not really elegant nor efficient. THe best alternative here would be to switch to react or inferno or vuejs

**Comment by AshHimself** [comment]
Are low_priority tags ok to start work on @gazhayes

**Comment by gazhayes** [comment]
Not for paid contributors. I'll be adding more issues very shortly though.
