### ISSUE TITLE
Problem: validation methods are needlessly server-heavy

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#681]
Problem: some methods use simple checks or their own validation methods on the server. This needlessly increases server load.

Partial solution: make a comment `//server-only validation, no optimistic UI #681` while going through codebase addressing other issues.

Partial solution: all new code should use mdg:validated-methods and simplSchema for validation.

Solution: change instances of server-only validation to use mdg validated-methods that have the assumed advantage of being both non-bypassable and also not sending data to the server for validation unless it passes client-side validation first (reduction in server load).

**Comment by gazhayes** [comment]
Any new validation added to the codebase should use validated-methods and simplSchema.

Existing code can slowly be reworked slowly whenever we need to update validation on any forms etc.

**Comment by gazhayes** [comment]
I updated your first comment to make it more clear.

**Comment by janat08** [comment]
If there's already a way in which to bind simpl-schema to jquery UI, I could go through method calls, methods and schemas (as they're pretty rough atm, without looking at methods to create the fields).

**Comment by jigartankhupp** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
@jigartankhupp you're probably better off to log an issue for a specific form (or whatever) and do them one at a time to avoid having a lot of changes with conflicts.
