### ISSUE TITLE
problem: blockrazor.org white screen

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#687]
Problem: something is dead. Please fix asap. Im on phone and cant do much.

**Comment by AshHimself** [comment]
On it

**Comment by AshHimself** [comment]
Uncaught Error: Cannot find module '/.typeahead.css'

**Comment by samuelralak** [comment]
<img width="968" alt="screen shot 2018-03-21 at 2 11 00 pm" src="https://user-images.githubusercontent.com/4476552/37706779-c07c92a8-2d11-11e8-9f9e-88bdec469e30.png">

**Comment by AshHimself** [comment]
Fixed in #688

**Comment by AshHimself** [comment]
@anbud - Possible to right a test script to catch errors from Meteor being able to even start?

**Comment by AshHimself** [comment]
@gazhayes - I merged this myself due to the severity and blockrazor.org looks to back online.

**Comment by anbud** [comment]
I'll look into it, I believe we can do something like that with full app testing in mocha.
