### ISSUE TITLE
Problem : cursors are not optimized for server performance

### ISSUE THREAD

**Issue by Fen747** [Blockrazor/blockrazor#70]
Solution : for every use of the `collection.find` method in a publication / observer, always add a projection as second argument with a `sort` and a `limit` and a `fields` fields.

e.g. :
```
return Bounties.find({_id: id, currentUsername: Meteor.user().username}, {
    sort: { _id: -1 },
    limit: 999,
    fields: { ... }
});
```

**Comment by gazhayes** [comment]
Quite often I've done this on the publication side instead (and intended to do more of it as we refine things).

Does doing this on the client actually change what the server sends over the wire? I was under the impression this only filters (client side) and that everything is still sent over the wire?

**Comment by Fen747** [comment]
For performance purpose, you need to do it in the Meteor.publish, on the server. Then, how you get your data client-side does not affect server performance, but it is still a good habit to use the same queries for isomorphic purpose

**Comment by gazhayes** [comment]
@janat08 do you want to make some improvements here?

**Comment by janat08** [comment]
I will.

**Comment by janat08** [comment]
features have comments and stuff, yet I can't even tell where it's rendered. If we had snapshotting testing I could just go and modify every helper that renders in each and then work my way from there, although I'm trying to only modify things that are not unimportant.

**Comment by janat08** [comment]
I think this is still less impact than trying to reuse components more, I spend 90 mins on this and only changed two helpers.

**Comment by gazhayes** [comment]
Yeah I'll close it for now. Send a PR for what you have done though.
