### ISSUE TITLE
problem: [/auction] dropdown box used (bad UI)

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#702]
Problem: the currency selector on /auction uses a search field and a dropdown box which is a bad UI pattern.

solution: use typeahead (already installed)

ping @janat08

**Comment by AshHimself** [comment]
@gazhayes - so you only want one element? or still the search element but the dropdown to be typahead ?

**Comment by gazhayes** [comment]
Should probably do the same thing as on the comparecurrencies route

**Comment by AshHimself** [comment]
Sorry deleted my comment as I totally get what needs to be done.
