### ISSUE TITLE
problem: [/currency/x] wallet image modal does not expand to enclose entire image

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#703]
Problem: 
<img width="923" alt="screen shot 2018-03-22 at 9 48 27 am" src="https://user-images.githubusercontent.com/8143945/37746665-4a42163a-2db6-11e8-84a3-a5d9bc61d1b9.png">

**Comment by AshHimself** [comment]
Looks like the modal is fixed pixel. We should watch out fixing widths.....
I’m here all week folks.

**Comment by gazhayes** [comment]
The images might need to be resized too on upload to maintain some kind of normalcy.

**Comment by AshHimself** [comment]
Fixed in #706

**Comment by gazhayes** [comment]
Is that you who keeps posting pictures of watches?

**Comment by AshHimself** [comment]
hahaha no..
