### ISSUE TITLE
problem: Travis CI tests are breaking

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#707]
Problem: Travis CI tests are breaking, not sure exactly why.

**Comment by gazhayes** [comment]
Travis CI error:
```
W20180322-05:29:23.402(0)? (STDERR) ReferenceError: ValidatedMethod is not defined
W20180322-05:29:23.403(0)? (STDERR)     at methods.js (imports/api/problems/methods.js:5:27)
```
cannot replicate locally or on production server.

**Comment by gazhayes** [comment]
ping @anbud @AshHimself

**Comment by anbud** [comment]
On it.

**Comment by anbud** [comment]
It was just a cache issue, solved it by cleaning Travis' cache.

**Comment by gazhayes** [comment]
How do you do that?

**Comment by anbud** [comment]
There's an option to clear cache on the Cache page. You can access it in one of the sidebar links.

**Comment by gazhayes** [comment]
Cool, thanks.
