### ISSUE TITLE
problem: currency ratings do not use currency logos

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#711]
Problem: when rating currencies on the codebase, wallet, and community ELO ranking system  the currency's logo isn't used.

<img width="1055" alt="screen shot 2018-03-22 at 5 09 37 pm" src="https://user-images.githubusercontent.com/8143945/37761208-ff52ecb0-2df3-11e8-9a1a-71da235b5a2f.png">

**Comment by samuelralak** [comment]
@gazhayes how do I navigate to this page?

**Comment by samuelralak** [comment]
@gazhayes this should be fixed in [#725](https://github.com/Blockrazor/blockrazor/pull/725). Kindly confirm
