### ISSUE TITLE
Problem: [/] comparison prices not shown on home route

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#723]
Problem: comparison prices (cpc, cpt) are in the currencies collection but are not displayed on the home route. 

solution: remove the `$180/10m`. Insert CPC $XXXX, CPT $XXXX. The actual price should go in there somewhere too.

Figures should be limited to 4 significant figures so that the UI doesn't break.

**Comment by AshHimself** [comment]
Fixed in #775

**Comment by gazhayes** [comment]
Where are you getting the price from?

**Comment by AshHimself** [comment]
price column.. should it be another field?

**Comment by gazhayes** [comment]
Everything is 0

**Comment by AshHimself** [comment]
Fixed in #779

**Comment by gazhayes** [comment]
Was this working locally for you?

**Comment by AshHimself** [comment]
Yep, its working on production for me as well. Some coins don't actually have a price though.

![image](https://user-images.githubusercontent.com/148682/37954730-41aceafa-31d9-11e8-83ed-af102a0e1771.png)

**Comment by gazhayes** [comment]
Oh I see what's going on now. You need 3 *significant* digits. Many prices are below 0.XX

**Comment by AshHimself** [comment]
ohhh right.. i'll remove that then..

**Comment by gazhayes** [comment]
Ah actually it's going to have to be more digits for *price*. Bitcoin is regularly XXXXX long. I guess 5 digits will do for now.

**Comment by gazhayes** [comment]
On second thought, CPC and CPT will also need 5 digits. Thanks Bitcoin.

**Comment by AshHimself** [comment]
Can you have another test with #789 I changed it to 5 and it was 3

`return Number(val.toPrecision(5));`

**Comment by gazhayes** [comment]
@janat08 can you have a look at this? For example, Cardano should be something like $0.18
