### ISSUE TITLE
problem: radar chart not compatible with all blockchain projects

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#726]
Problem: the radar chart we are currently using is not compatible with all blockchain projects. This is because there are different types of projects, and different stages of development.

An ICO, for example, may not have a wallet that can be rated. 

Solution: I have gone through all scenarios I can think of to come up with the lowest common denominator - the maximum amount of metrics we can have on the radar chart which is applicable to all projects.

Here they are:
1. Ongoing development - this comes straight from the github API
2. Codebase - this comes from ratings 
3. Community - this comes from ratings, but we should also incorporate some activity metric (e.g. reddit posts, number of tweets, etc)
4. Distribution - what percentage of the coins go to the founder(s), how many are distributed in an ICO, how many can be mined.
5. Decentralization - this is mostly calculated through ratings by asking strategic questions

This will affect the home route, the currency comparison route, and the currency detail route.

Once this problem is solved, it will introduce more problems:
There are many types of metric that are only applicable to certain types of blockchain project, but these other metrics all need to be displayed to users. Whenever possible, they should also be incorporated on the currency comparison page.

One way to deal with this would be a new radar chart for each type of project. That way every project can be compared in broad terms (using the 5 metrics above), but any projects of the same type can also be directly compared.

Another way would be one multi-axis bar chart with each bar group representing a different metric. If one currency doesn't have that metric that column will just be left empty. This might work well on the currency comparison page.

ping @anbud @AshHimself @samuelralak @janat08

**Comment by anbud** [comment]
@gazhayes, I agree, those 5 data points seem sufficient.

About the problems this introduces, I like the multi-axis bar chart solution better, it seems a lot simpler than creating a new radar chart for every group, and I believe it would provide more information for comparison.

**Comment by gazhayes** [comment]
Do you want to start on it?

**Comment by anbud** [comment]
Yap, taking it.

**Comment by anbud** [comment]
Done in #730.
