### ISSUE TITLE
problem: hard for user to navigate back to a bounty that is in progress

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#727]
Problem: if a user starts a bounty and then leaves the page, its really hard for them to get back to it.

Possible solution: add a UI element at the top of the bounties page if the user has a bounty in progress. This could possibly be a site-wide thing instead.

**Comment by anbud** [comment]
@gazhayes, how about adding it as an icon to the navbar stating that you have a running bounty? Maybe we can even show the remaining time as well.

**Comment by gazhayes** [comment]
That would solve it on large screens, but on small screens the top nav bar is basically full already.

The UI guys can probably work that out though if you do the logic.

**Comment by samuelralak** [comment]
Space can still be created on the top navbar for smaller screens
- we could eliminate the caret next to the user icon
- we could also reduce space between the user icon and notifications icon, IMO the space unnecesarily large
- the right padding for the div that contains the navbar icons can be reduced as well, moving the icons closer to the right while creating space at the same time
- there is also the possibility of adding a notification badge on the hamburger icon for smaller screens and have a link to the user's running bounty on the side nav.
<img width="100%" alt="screen shot 2018-03-24 at 9 50 20 pm" src="https://user-images.githubusercontent.com/4476552/37867726-7aa530ca-2fad-11e8-951f-43364896b8f6.png">

I would like to take this issue if @anbud hasn't started working on it yet

Quick question:
- how do you start a bounty?

**Comment by anbud** [comment]
Sure thing, you can take it, I still haven't started. 
You can start the bounty at `/bounties`, and you can see how to check if there's an active bounty in `activeBounty` helper on, for example, community ratings page.

**Comment by samuelralak** [comment]
@anbud ok cool, thanks.

I would also suggest putting activeBounties at the top of the list in `/bounties` page and possibly having a different color for the cards.

@anbud another question, when the user clicks on an active bounty, should it redirect to the bounty type page e.g when a bounty is for `addCurrency` should the user be redirected to the `addCoin` page?

**Comment by anbud** [comment]
@samuelralak, I agree, it can be on top of the `/bounties` page as well.

Yap, that's the idea I believe. For most bounties, you have an `url` field available, that's where you should redirect them.

**Comment by gazhayes** [comment]
#633 is related

**Comment by samuelralak** [comment]
done in [#744](https://github.com/Blockrazor/blockrazor/pull/744)
