### ISSUE TITLE
Problem: wallet transfers do not have discrete reasons for transfer

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#733]
Problem: wallet transfers in both users' wallets and also as displayed on the /transactions page do not show discrete reasons for the transfer. This means that:

- Wallet items cannot be sorted or grouped by transaction type/reason
- the only way for users to see the reasons for transations on the /transactions page would be to add the whole comment associated with the transfer, instead of just something like "reward for top comment" or "reward for bounty".

**Comment by AshHimself** [comment]
@gazhayes - are you just wanting to show the 'message' field on these pages which is display the reason/type of the transaction? or looking for something a little more structured?

**Comment by gazhayes** [comment]
No, something more structured. I guess we need to define some Types for transactions that can be used site wide. At least that gives us a starting point.

The types so far (off the top of my head) would be something like: bounty reward; comment reward; problem reward.

**Comment by AshHimself** [comment]
Got it, well let's make it scalable so if we need to add to this its easy enough. I am assuming we are going to have to modify all methods to include the relevant transaction types as well. Shouldn't be too hard to identify these.

**Comment by gazhayes** [comment]
Yeah I'm pretty sure you got it.

**Comment by AshHimself** [comment]
@gazhayes i've made an initial PR on this. Is this a long the lines on what you were thinking?

**Comment by gazhayes** [comment]
Yep that looks like it will do it.
