### ISSUE TITLE
problem: data quality metric does not check for github repo

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#736]
Problem: the data quality metric does not incorporate the github repo data point. If a github repo is included (and the API has validated that it works) it is valid, if not it is invalid. This data point should be given equal weight with everything else.

**Comment by anbud** [comment]
@gazhayes, currently, the data quality metric is just a sum of ELO ratings (questions answered) for the given currency. 
How much weight should the GitHub API validity have? I believe it should weigh more than a single answer.

**Comment by gazhayes** [comment]
Yes I absolutely agree. I should probably weigh the same as 1/4 of all answers (so one catagory).

**Comment by gazhayes** [comment]
@anbud do you feel like doing this one?

**Comment by anbud** [comment]
Yap, I'll take it.

**Comment by anbud** [comment]
Done in #763.
