### ISSUE TITLE
problem: [/comparecurrencies] ease of use metric doesn't appear to be using correct data

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#745]
Problem: there should be quite a few ELO rankings for ease of use (wallet) but something weird is happening with the bar chart as it it's getting data from somewhere but it's quite different to the data that was originally used on the radar chart.

ping @anbud

**Comment by anbud** [comment]
I've used the same value as it was on the radar chart, but something could have gone wrong, I'll check it out.

**Comment by anbud** [comment]
@gazhayes, I've just had a look and I've tried it out, the data seems fine. The value is correct, it's calculated from `walletRanking` field. 
Maybe some testing with questions messed up ELO values a little bit.
