### ISSUE TITLE
problem: [/wallet] cannot filter transactions by Type

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#746]
Problem: transactions in /wallet cannot be filtered by Type of transaction. 

ping @AshHimself

**Comment by AshHimself** [comment]
Got it!

**Comment by AshHimself** [comment]
Fixed in #788

**Comment by AshHimself** [comment]
@gazhayes - Ever consider using a table component to streamline adding matrix of data to the site? I've used both (https://github.com/aldeed/meteor-tabular) which is simpler and the more complex dataTables.

Thoughts?

**Comment by gazhayes** [comment]
Definitely keep that in mind for wallet and messages/notifications, it will probably solve a problem sooner or later.

**Comment by AshHimself** [comment]
https://github.com/aldeed/meteor-tabular is insanely simple to implement so we should do that for the next view that makes sense.
