### ISSUE TITLE
problem: use of slugs as unique id for usernames causes problems when two people have same name

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#747]
Problem: we are using slugs as the unique id for fetching user data, but this does not allow two people with the same name to have an account (or causes problems anyway).

ping @anbud for ideas

**Comment by samuelralak** [comment]
I would advise that usernames remain unique, upon registration we could prepend the username with a number or unique code if a user with the same username already exists i.e if username `samuel` already exists then another user who registers with the same name would be assigned `samuel-123` as username/slug.

**Comment by gazhayes** [comment]
Yeah that would probably be the simplest solution here.

**Comment by gazhayes** [comment]
Do you mean for email signups? Or do you mean when facebook/github provide an email address?

**Comment by samuelralak** [comment]
I mean the email signups

facebook/github signup already provide a seperate email and username

**Comment by gazhayes** [comment]
Oh it doesn't matter then, email signups are only temporary while we are developing, they won't be used in production.

**Comment by anbud** [comment]
The `friendlySlugs` package we are using actually solves this by adding `-1, -2, ...` to the slug if the string is not unique. So, it's saved correctly in the `slug` field in the user object.
The only problem here could be caused by our `slugify` helper that's used for linking to user profiles. To solve that, we would have to subscribe to user data or have a sitewide subscription for user slugs so we can link to user profiles.

**Comment by gazhayes** [comment]
> The only problem here could be caused by our slugify helper that's used for linking to user profiles. 

The only place I've seen this problem is on the user profile, so that's probably the only actual issue here then.

> we would have to subscribe to user data 
Only on the templates that link to profiles?

**Comment by anbud** [comment]
@gazhayes, yap, we only need to subscribe to user data on templates that would link to profiles in order to fix this one.

**Comment by anbud** [comment]
Solution in #764.
