### ISSUE TITLE
problem: [/transactions] no reason shown for transactions

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#748]
Problem: no reason is shown for each transaction. 

ping @AshHimself you might have some ideas

**Comment by AshHimself** [comment]
Are you talking about on the page itself mate? displaying the reason itself on the page prior to filtering?

**Comment by gazhayes** [comment]
Some kind of info is needed on the page itself. You could use the Type system that you already built and do a different message for each type, that's *probably* enough, at least for now.

**Comment by AshHimself** [comment]
Fixed in #774
