### ISSUE TITLE
problem: profile pictures are not displaying

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#749]
Problem: profile pictures are not displaying

**Comment by gazhayes** [comment]
It's working here: https://blockrazor.org/profile/gareth-hayes

The tooltip thing is working too.

**Comment by AshHimself** [comment]
Can you try change it? I just tried in production and getting 404. The URL is looking in root as well which isn't right.

![image](https://user-images.githubusercontent.com/148682/37893661-4f085d4a-310e-11e8-94dd-fdb0d59511a2.png)

**Comment by gazhayes** [comment]
Ah yeah, it's broken.

Strange that the correct location is used for https://blockrazor.org/profile/gareth-hayes but not for https://blockrazor.org/profile/gareth

**Comment by gazhayes** [comment]
When you fix this (if you fix it) can you use the same progress displaying uploady thing you used elsewhere?

**Comment by AshHimself** [comment]
haha will implement the uploading thing.

**Comment by AshHimself** [comment]
@gazhayes should we really be having md5 hash checking on user profile pictures?

**Comment by gazhayes** [comment]
No, I only really implimented it for images where we don't want duplicates (e.g wallet images). The only reason for md5 otherwise would be to verify data integrity in the upload, but I think that's handled by the library that handles uploads anyway?

**Comment by AshHimself** [comment]
Yeh I think it was carried over from your code but it really doesn't need to be there. I am reviewing the profile picture upload code now and its a little weird. Its updating the user collection, but its also storing historical records in the ProfileImages collection. That's a wee bit overkill if you ask me.

**Comment by gazhayes** [comment]
Yeah may as well nuke that part while you're in there and keep things streamlined. 

Can you also make the hash rig pics embiggenable like wallet images?

**Comment by gazhayes** [comment]
Just a reminder too: do these things in separate commits so that each commit is solving a discrete problem. Can all be in the same PR though.

**Comment by AshHimself** [comment]
Fixed in #749 everyone will need to change their display pictures for this work otherwise it'll display a placeholder (didn't before).

**Comment by gazhayes** [comment]
There's something weird going on.

When I upload a profile pic it works and displays properly, but only till the page is refreshed. Then it's back to the default pic.

**Comment by AshHimself** [comment]
super weird.. happening to me now too. Looking into it.

**Comment by AshHimself** [comment]
Can you try again @gazhayes  in #757 

When saving it was nulling out profilePicture object which is bad. It only populates that field on an image upload now.
