### ISSUE TITLE
problem: [/profile/x] comment history layout is bad

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#753]
Problem: comment tags are flowing over to the next line making them look like they are associated with the wrong comment.

<img width="693" alt="screen shot 2018-03-26 at 5 23 36 pm" src="https://user-images.githubusercontent.com/8143945/37898136-9949ce50-311a-11e8-82f6-fcf276601c77.png">

**Comment by AshHimself** [comment]
Fixed in #758
