### ISSUE TITLE
problem: no incentive for users to invite friends

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#756]
Problem: there's currently no incentive for users to invite their friends to join Blockrazor. In the early stages, we should try everything possible to get new users.

Requirements for solution:
- a direct "invite someone and get x Krazor" is no good because the incentive will simply be to create fake accounts

Possible solution: invite a friend and you get awarded x% of whatever they earn (not deducted from their friend, but in addition to). In order to remove the incentive to create fake accounts, maybe there should be a requirement that the user being awarded this x% must also have earned more than their friend during the same period.

Caveats: if we use say, a tokenized url, we need to make sure there's a cookie or something in case that user doesn't sign up straight away but comes back later.

ping @anbud

**Comment by AshHimself** [comment]
Off topic, but related. Not only is getting new users important, but its important to keep users  that do sign up (user retention). I've worked in this a lot so happy to discuss it in another ticket.

**Comment by anbud** [comment]
@gazhayes,
I agree with the proposed solution, a percentage of friend's earnings is sufficient, it's simple enough and it will prevent fake account creation. 1-5% would be enough in my opinion.

A tokenized URL is the simplest way to share I believe, and we can store the token in either cookies or localStorage for later usage. We could also let users invite friends by email or something possibly, and we can let them share their URL easily on, let's say, Facebook or Twitter.

@AshHimself,
User retention is also a big part here, I agree, it deserves a separate issue.

**Comment by gazhayes** [comment]
@anbud ok cool, we're on the same page, this is all yours if you want it.

**Comment by gazhayes** [comment]
One thing to be careful of is that we don't award Krazor for the next level of 'friend', so that it doesn't turn into some weird pyramid scheme. So I guess create a new transaction Type (check #741) for this and don't include that type when calculating. 

I also have no idea how often we should be calculating this, probably once a day so that the numbers are large enough to have some meaning, but frequent enough to give instant gratification.
