### ISSUE TITLE
Problem: [/currency/:slug] currencyDetail page not responsive

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#762]
Problem: The currencyDetail UI page isn't responsive. The UI breaks on smaller devices and elements don't fit on screen

Solution: use Bootswatch UI to improve currencyDetail page responsiveness.

**Comment by gazhayes** [comment]
It's also pretty bad on desktop too, that page needs some serious work.

**Comment by gazhayes** [comment]
#440 is related. I closed this due to staleness but you might want to look at the thread.

**Comment by AshHimself** [comment]
Are you looking at this @samuelralak being you removed the in progress label away?

**Comment by samuelralak** [comment]
Yes sir, am still looking at that. Had a bit of a road block but I have
made some progress

**Comment by samuelralak** [comment]
I'll have to finish this one today before picking any other issue. It seems that the radar charts is responsible for breaking the responsiveness of this page. a fix to this will be to figure out how to make those charts responsive

**Comment by gazhayes** [comment]
> a fix to this will be to figure out how to make those charts responsive
@anbud might have some ideas for you about that.

**Comment by anbud** [comment]
@samuelralak, check [this](https://www.chartjs.org/docs/latest/general/responsive.html#configuration-options) out, it should be helpful. :)

**Comment by samuelralak** [comment]
thanks @anbud having a look

**Comment by samuelralak** [comment]
done in [#970](https://github.com/Blockrazor/blockrazor/pull/970)
