### ISSUE TITLE
problem: [/communities] no validation that users are part of the communities they are ranking 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#782]
Problem: when users add wallets to rank they have to send screen shots of the wallet. Nothing like this is done for communities.

Solution:  require users to make a comment in the community they are ranking (they must mention Blockrazor) and take a screen shot. This image must be uploaded as part of the community ranking thing.

**Comment by AshHimself** [comment]
So just an upload element with your instructions here? 

![image](https://user-images.githubusercontent.com/148682/37970266-a28aedbe-3205-11e8-8886-272df3c6223c.png)

**Comment by gazhayes** [comment]
Yep, you got it.

**Comment by AshHimself** [comment]
Taking this.

**Comment by gazhayes** [comment]
Oh and it probably goes without saying but we need to handle the approval process, I guess just the same way as wallet images are handled (if they are rejected by moderators later the user loses the Krazor they earned). In addition to this, another follow up pull request will probably be needed once @anbud is done with #800 which is directly relate. Don't need to wait for that one to get started though.

**Comment by AshHimself** [comment]
@gazhayes - ok I did a PR for this but soon as I did it I realised I missed something... images are added with approved:false

Assuming we need to add an additional section to https://blockrazor.org/moderator where they would approve these community images?

Also, I tried added URL's to the coin on both prod and locally and they never appeared under the heading "You have already added communities for the following cryptocurrencies:" I am assuming they should?

**Comment by gazhayes** [comment]
> Also, I tried added URL's to the coin on both prod and locally and they never appeared under the heading "You have already added communities for the following cryptocurrencies:" I am assuming they should?

Try using a new account with no baggage in the database.

For the other stuff, I'm not sure what you are actually asking, but I suspect my previous comment answers it already.

**Comment by AshHimself** [comment]
@gazhayes you ok with this one sir or want some changes made?

**Comment by gazhayes** [comment]
What's the current status? I haven't actually looked at your code.

**Comment by AshHimself** [comment]
Just clarification on 
>Assuming we need to add an additional section to https://blockrazor.org/moderator where they would approve these community images?

**Comment by gazhayes** [comment]
Ah, yeah, for now (if that's the simplest way to deal with it).

That moderator section needs some work, but it also needs some thinking. So just provide a really basic starting point and we can work the rest out later.

**Comment by AshHimself** [comment]
Fixed in #906

**Comment by AshHimself** [comment]
@gazhayes - you good to close this?

**Comment by gazhayes** [comment]
Will validate and close today
