### ISSUE TITLE
problem: [/currency/x] cannot add exchanges to coins

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#783]
Problem: it's not possible for users to add exchanges to coins on the currency detail page.

possible solution: Allow users to add an exchange to a currency from the existing list of exchanges or add a new exchange. Ideally this would be a typahead list with "add" if what the user types isn't found (e.g. how Github works with adding branches).

Any solution should also denormalize the data into the currencies collection so that currencies on the home route can be filtered by "is currently listed on an exchange".

**Comment by janat08** [comment]
you mean currently listed in some exchange?

**Comment by gazhayes** [comment]
Yeah exactly

**Comment by janat08** [comment]
The issues with the issue:

- using typeahead template in one of those currencyInfo templates will make suggestion template invisible (not render it), thus it's at the very top of the page.

- I couldn't bind an event to nothing found template inserting typeahead text into exchanges collection.

- passing current typeahead value into thing template isn't possible as it nothing found template is only run once, so I pass typeahead id to get value from for method call.

- reactively displaying current typeahead text in nothing found template could be tried in less then elegant way by binding current typeahead value to parent template as reactive var and trying to pass tracker for interpolation into nothing found template, or renitializing typeahead on every keypress once no records are found.

**Comment by janat08** [comment]
FYI, zcash has some starting exchanges. and I used "name" for exchange name in schemas everywhere instead of tag, although it currencyDetail shows both tag and name fields.

**Comment by gazhayes** [comment]
@janat08 why are _id numbers populating the typeahead?

**Comment by janat08** [comment]
Something to test with, in /startup/server/fixtures.js.

**Comment by gazhayes** [comment]
Oh ok.

If you are done with this one, I'm going to close it and log a new issue based on the current status so this doesn't go stale.

**Comment by janat08** [comment]
I'm done.

**Comment by gazhayes** [comment]
Cool, thanks.
