### ISSUE TITLE
Problem: home route does not show off best features of blockrazor

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#784]
Problem: there are already plenty of sites comparing cryptocurrencies using APIs and similar metrics to Blockrazor. The difference with Blockrazor is that it is community driven (e.g. like Wikipedia). This human element should be immediately obvious when seeing blockrazor for the first time.

Partial solution: put the top "red flag" for each currency on the home route. Real estate on this page is limited, so we need the most powerful human generated content to be shown first (and negative stuff usually gets people interested more than positive stuff).

Anyone have any other crazy ideas about how to differentiate blockrazor?

**Comment by AshHimself** [comment]
This is 100% clear to me but how are we communicating the purpose of krazor
to them or it exists ? And what it means to them?

**Comment by gazhayes** [comment]
> how are we communicating the purpose of krazor

I have another issue for menu restructuring so that we can put "bounties" right at the top-left next to the logo where it's impossible to miss (on screens that can fit it), that should take care of that (for desktop & tablet users anyway).

**Comment by gazhayes** [comment]
FYI here are the main competitors:
https://coincheckup.com/analysis
https://www.coingecko.com/en

**Comment by AshHimself** [comment]
What about sentiment analysis on comments and the community within BlockRazor to gauge a score on its popularity? Quick example below of what we could implement fairly easily (hard part will be how we score it and present it)

![image](https://user-images.githubusercontent.com/148682/37969676-e7b61348-3203-11e8-9c48-d2f11fdc4e8b.png)

![image](https://user-images.githubusercontent.com/148682/37969707-fadf10b4-3203-11e8-8469-66d3c19f9cfe.png)
![image](https://user-images.githubusercontent.com/148682/37969726-0e40f028-3204-11e8-980f-d84718d319d9.png)

![image](https://user-images.githubusercontent.com/148682/37969748-1e2c6b84-3204-11e8-80be-100e6ca20005.png)
![image](https://user-images.githubusercontent.com/148682/37969771-31735d56-3204-11e8-8ed7-49172155e4d3.png)

**Comment by gazhayes** [comment]
Nah too complicated and also not uncommon. Start with top red flags and see what happens.

**Comment by gazhayes** [comment]
Temporarily assigning this to me to keep it reserved for a new contributor who's about to take it.

**Comment by jmspsi126** [comment]
hello
Nice to meet you.
I checked #784 issue.
As you can see, issue's title is...
<home route does not show off best features of blockrazor>
So we have to update function to show off all best features of blockrazor.
I checked project basically.
I think there are function for comparing cryptocurrencies using api.
You explained on solution...
put the top "red flag" for each currency on the home route
So home route.?
What does this mean?

Thanks.1

**Comment by gazhayes** [comment]
If you have a look at the currency comparison page you'll see there are 3 red flag items (some currencies don't have any test data for this but the element is there, go through till you find a currency with data to see an example). These are the top ranked red flag items from the currency detail page.

The very top item should be put on the / route.

**Comment by jmspsi126** [comment]
I understand.
I think...
We have to show values for top three flag items.
I created test account.
There are not test data.
I want to check comparing state with test data.
And i want to check flag items on currency comparison page.
So can you send me test account info that i can use?

**Comment by gazhayes** [comment]
You can create an account on blockrazor.org.

A currency that has some red flags is Monero (as an example).

> We have to show values for top three flag items.

Only the top red flag, not 3.

**Comment by jmspsi126** [comment]
Yeah
I am checking flags on Monero.
You added test values on top red flag.
Top red flag 1 - testing 123
Top red flag 2 - Test Red FLag
Top red flag 3 - ____________

There are five values for flags on radar.
Code quality,Ongoing development,decentralization,community,coin distribution
These have values.

In Monero case.
We have to show 10 for Code quality on Top red flag 1 ?
Another question is...
I think we  have to show values for Top red flag 2,3 too?

And...
Using select currency tab, we can add NEO,Bitcoin,etc on list more.
If we add these values, we have to show their flag values too?

**Comment by gazhayes** [comment]
From the first post:
> put the top "red flag" for each currency on the **home route**.

The home route is "/" that's the only thing that needs to be changed for this issue.
/compareCurrencies route is simply to show an example of red flags.

In Monero's case, the top red flag is "testing 123". That's what would be shown on the home route on Monero's panel.

**Comment by jmspsi126** [comment]
Ok
I understand.
https://www.screencast.com/t/asUfIM6gQvrt
Please check this screen.
I want you confirm about this again.
I have one question more.
How can we get top red flag?
I can show "testing 123" as top red flag in Monero's case.
There are not value in another's case.
But we need to show this value for each case correctly?
I want you confirm about this again.
Thanks.

**Comment by gazhayes** [comment]
You can use your own judgment to decide what to do when there's no data.

**Comment by jmspsi126** [comment]
Ok
Thanks :+1:

**Comment by jmspsi126** [comment]
hello
I fixed issue.
If you agree me, i am going to commit code on github.

**Comment by gazhayes** [comment]
No one has to agree, you just have to send a pull request that complies with the C4 :)

**Comment by jmspsi126** [comment]
Ok.
I will send pull request.

**Comment by jmspsi126** [comment]
Yeah
I will not commit those files.

**Comment by jmspsi126** [comment]
hello

I added .idea on gitignore file

**Comment by jmspsi126** [comment]
hello
Did you check code?
And if you have free time, i want to discuss about next issue.

**Comment by gazhayes** [comment]
Your pull request did not comply with the C4.

**Comment by jmspsi126** [comment]
For now...
How can i solve this problem?

**Comment by gazhayes** [comment]
Read the readme file.

**Comment by gazhayes** [comment]
You're applying for a paid contributor position, and you haven't even read the contribution policy. You've sent two incorrect pull requests, and I told you both times that they do not comply with the C4 and that you need to read the Readme. I'm not spending any more time one this. You get one more chance to get it right, I'm not willing to spend any more time on this.

**Comment by jmspsi126** [comment]
I understand.
I want to read Readme carefully again.
Thanks

**Comment by jmspsi126** [comment]
I checked Readme file yesterday and understood about that process basically.
I am going to fix all problem today.
BTW...
I think you closed this issue.
I didn't work with this good process yesterday.
I need to fix this problem today.
Can i work on this closed state?

**Comment by jmspsi126** [comment]
I have to stop to work on this issue?

**Comment by gazhayes** [comment]
I closed this issue because it's full of very annoying and useless messages.

You can do it in #835 instead.

> I checked Readme file yesterday and understood about that process basically.

Let's see. You said that the other two times as well.

**Comment by jmspsi126** [comment]
Yeah
I have been worked to fix that issue.
And i fixed that issue and i committed code.
But i didn't send pull request.
So i could solve this problem today.
You closed issue suddenly.
If you close this, i have to start to work on next issue from scratch.
So who can pay about 784 issue?

**Comment by jmspsi126** [comment]
I didn't work with C4 process.
But i can fix that problem again.
Can you create 784 issue again?

**Comment by jmspsi126** [comment]
It will take some hours to fix new issue.

**Comment by gazhayes** [comment]
#835 is the same issue, with the same solution.

**Comment by jmspsi126** [comment]
Do you have $kype id?
Can we discuss about some problems on $kype?

**Comment by jmspsi126** [comment]
hello

When commit code, can i create new issue?
for example...
problem:you can save a sss  …
solution: Implement xxx  #xxx
