### ISSUE TITLE
problem: [currency/x] users can 'camp' on the top feature/red flag/summary

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#785]
Problem: users can camp on the top feature/red flag/summary by continually submitting new summaries etc. 

Possible solution: limit user's contributions to one a week (or whatever). Though this would create a problem at the start when people want to add a heap of new features etc for their favourite coin. Maybe the limit could come into effect only after there are x number of items.

**Comment by anbud** [comment]
Done in #796.
