### ISSUE TITLE
problem: problem page is ugly

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#786]
Problem: problem page is ugly and isn't conforming to bootstrap 4 class standards.

Solution: Bootwatchify the page

@gazhayes - Few comments that I think still needs to be done.
- There is no form validation. e.g. when github validation on server fails. User never knows.
- The Krazor figure needs to stand out a lot more right?
- I think we need an overal standard to how commenting works? If a problem start's getting a lot of comments the over all UX atm is bad to follow and use.

**Comment by gazhayes** [comment]
I'm about to change this page actually, just hold off on it and I'll update this one tomorrow.

**Comment by AshHimself** [comment]
oh dear...

**Comment by gazhayes** [comment]
Oh youve already done it

**Comment by AshHimself** [comment]
Was working on it as part of 577 but raised another ticket so we could keep
track of comments and commits better.

**Comment by gazhayes** [comment]
This can be worked on now.

**Comment by samuelralak** [comment]
Taking a look

**Comment by gazhayes** [comment]
@samuelralak if you do this one, while you're there can you remove the ability for users to change the problem Type after they've already chosen it?

I.e. they currently choose the problem Type first, then the form is populated, but they can change types after that and things don't update. The simplest way to fix it is to just prevent them from being able to change it (this feature seems unnecessary anyway)

**Comment by samuelralak** [comment]
@gazhayes is this part of the `add Problem` process? If so, I can see the form fields update accordingly based on the chosen problem type; though the only difference I see between the bug report form and feature request form is the `Steps to Reproduce the Bug/Potential Solution` field. We could make  *read-only* after the user selects the problem type.
> I.e. they currently choose the problem Type first, then the form is populated, but they can change types after that and things don't update. The simplest way to fix it is to just prevent them from being able to change it (this feature seems unnecessary anyway)

**Comment by gazhayes** [comment]
Oh yeah, you're right. That's strange, I swear it wasn't updating last time I looked.

**Comment by samuelralak** [comment]
I think I'll just leave this one to @AshHimself, he'll be at a better position to comment on whats done and whats pending

**Comment by AshHimself** [comment]
@gazhayes are you talking able disabling changing the problem type when creating it? or after the fac. As you can't change it after the fact that I can see.

**Comment by gazhayes** [comment]
That part is ok (I've since learned).

So this issue really just comes down to what's in your first post.

**Comment by AshHimself** [comment]
Fixed in #884

**Comment by AshHimself** [comment]
Fixed in #885
