### ISSUE TITLE
Problem: [dev environment] add new coin bounty doesn't reset, nor reward

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#793]
Problem: adding new bounty will not reset bounty timer, or reward user, but will register as complete in ux. relevant issues:
bounty reset logic #718 
bounty reset ui #633 
add new coin submit redirect misleading #792

**Comment by anbud** [comment]
The bounty timer is reset when a new currency is added, and the user is rewarded when the currency is approved by a moderator. That's how it worked last time I've checked.

**Comment by janat08** [comment]
My timer continues running, but I didn't refresh DB dump.

**Comment by gazhayes** [comment]
It should be working locally too.

**Comment by gazhayes** [comment]
Basically if anything works on production then it works. It's only a problem if it doesnt work on production. If it's not working locally it's something to do with your environment, you might need help getting it working but you should be clear that its only with your environment and not blockrazor itself.

**Comment by gazhayes** [comment]
I just confirmed on the production server, everything works as normal.

**Comment by janat08** [comment]
I was on the wrong branch.
