### ISSUE TITLE
problem: [/addcoin] off-by-one error on genesis block

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#797]
Problem: it's not possible to add the genesis block for anything where genesis happened in January, form validation fails. I strongly suspect this is an off-by-one error.

ping @janat08

**Comment by janat08** [comment]
I just added things on january the 1st, but there're limits on genesis block time by year.

**Comment by gazhayes** [comment]
You mean the problem is actually year not day?

**Comment by janat08** [comment]
it is possible to select a year that will fail at validation as far as I remember.

**Comment by gazhayes** [comment]
Oh ok, that's probably an additional problem. There are some restrictions (intentional), for example a currency that has already launched must have a date in the past.

**Comment by gazhayes** [comment]
OK, I just tried again and it's working. I need to document these things more scientifically.

When I find the actual problem I'll reopen this with specific instructions on how to reproduce.

If you've encountered a separate problem please log it.
