### ISSUE TITLE
Problem: UX issues with new share button

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#799]
Problem: UX issues with new share button, click the profile button sometimes for me opens the share button and visa versa. Share button could also do with a but of a style.

Solution: Refactor the html/CSS.

P.s. is this feature all complete? Close if its not :)

**Comment by AshHimself** [comment]
Fixed in #804

**Comment by gazhayes** [comment]
That's about 8 billion times better.
