### ISSUE TITLE
problem: community metric does not take size of community into account

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#801]
Problem: the community metric at present is simply a subjective comparison between communities. This doesn't take size into account (which should probably be a multiplier). We could get representative sizes from the Reddit API and maybe some other things like that. Getting the size of telegram groups would also be cool but I don't know if there's an API for that or what's needed. In the worst case, telegram group size could be added manually by users.

As well as this, it's not fair to compare the size of a community that has existed for 3 years with one that has existed for a month, this also somehow needs to be taken into consideration. Maybe some kind of size / time metric, I don't know.

ping @AshHimself @anbud @janat08 @samuelralak for ideas.

**Comment by anbud** [comment]
@gazhayes,
Group size divided by time would be better here, it's more informative.
As far as I've checked, the Telegram API doesn't support groups at all. We should probably have a list of community websites where we can use the API to fetch data (e.g. Reddit), so we can let users enter group size and group creation time if the API for their community is not available. Also, if the user entered the data manually, there should be some kind of a flagging process in case the data is invalid.

**Comment by gazhayes** [comment]
OK. I guess as a start the best thing to do is implement this for reddit since everyone seems to be using it and the API looks pretty clear. Reddit should also be representative even if it is only one data point.

Twitter is probably another relatively easy one, I guess just search for <currencyname> over x time period?

**Comment by anbud** [comment]
@gazhayes, Yap, I'll take it after.
You're right, Reddit and Twitter will be enough for now.
