### ISSUE TITLE
problem: not enough filtering on / route

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#802]
Problem: in order to expand on the whole 'razor' concept we need to be able to slice and dice the blockchain projects.

At this stage, I'm looking for any ideas on how this could be done, what we should be slicing/dicing by, etc.

E.g. I have x GPU card, I'm looking for something that I can mine. I want something that isn't well established yet so I can actually grab a fair chunk of the total total network hashpower. But I also want to know it has some good fundamental attributes that make it likely that these presently worthless coins might be worth something later. 

ping @anbud @AshHimself @janat08 @sjmackenzie @samuelralak

**Comment by AshHimself** [comment]
Ok this is interesting. It needs to offer advanced functionality to search multiple attributes but at the same time it has to be easier enough that it won't scare people away (e.g. not a form with 100 attributes to filter on).

This [article](https://uxdesign.cc/death-to-complexity-how-we-simplified-advanced-search-a9ab2940acf0) explains it pretty well on how we could tackle it. We can track searches as well and this will give us an idea on what people are looking for so we can improve the interface based.

**Comment by gazhayes** [comment]
Good article there.

**Comment by gazhayes** [comment]
This is a very simple and cool idea:

> By providing a floating button at the bottom of the page, we allow users to browse, and access filters at any point in their browsing experience. For example, if they scroll through 30 results and realize their search is futile, they can quickly access Advanced Search and refine their query.

![](https://cdn-images-1.medium.com/max/1200/1*xlIExbgP0Ktuz5wP6LQtnQ.gif)

Left is before, right is after.

**Comment by AshHimself** [comment]
Yeh it’s pretty slick. What I propose is that we perhaps prototype up the
ui on this first and keep it agile. Once we are happy we can then create
the methods for the filtering.

Happy to mock something up (4 day weekend for me !! Whoop)

**Comment by gazhayes** [comment]
Not yet, I want to discuss this with a few more people first. There are a large number of new issues though so that long weekend will come in handy ;)

**Comment by AshHimself** [comment]
@gazhayes - How'd you get on with this? Not sure if following you up is against C4 policy :)

**Comment by gazhayes** [comment]
> Not sure if following you up is against C4 policy

Definitely not.

You (or whoever) could start building the framework and we can let the filtering part evolve over time. 

I guess the next step is to choose some things to filter by.

**Comment by AshHimself** [comment]
Taking this.

**Comment by AshHimself** [comment]
@gazhayes Thoughts for the filter. Let me know if you got any suggestions. I'm going to try logically group these so its ok for us to provide a lot of options just as long as we group them into logical groups for the user to choose from.

- Currency name and symbol
- Price (Ability to choose less than greater than)
- Consensus
- Genesis Timestamp (Ability to look for new coins to mine)
- ???

**Comment by gazhayes** [comment]
> Currency name and symbol

This can be done through search, the way it works now

Instead of filtering by price a simpler way would be to just sort by price, especially since people will probably want to look at nominal/cpc/cpt prices and not just nominal.

Consensus can simply be proof of stake/proof of work/hybrid at this stage, no need to get into the muck. I'm not sure the best way to do this but maybe 3 checkboxes that are all initially checked, then users can uncheck them to hide what they don't want.

Genesis timestamp is a good one. A slider to hide coins with a genesis older than x would probably be enough for now. You could look at multi axis slider to also hide 'newer than', but if it smells difficult don't bother.

**Comment by gazhayes** [comment]
Remember that dates are stored in epoch time, so the filtering is actually pretty simple. The C4 will make the UI pretty later anyway (i.e. display human dates in the UI).

The modal is probably a good idea.

**Comment by AshHimself** [comment]
@janat08 - Any idea why the field consensusSecurity isn't available in your local collection but is available in the mongoDB collection :/ the below isn't working with my filter, but changing it to Currencies.find does. Thoughts?

`            let templateVars = Currencies.findLocal(filter, { sort: { featured: -1, quality: -1, createdAt: -1 }, limit: templ.limit.get(),
              fields: {
                consensusSecurity: 1,
                _id: 1,
                eloRanking: 1,
                slug: 1,  
                currencySymbol: 1,  
                marketCap: 1,  
                maxCoins: 1,  
                hashpower: 1,  
                genesisTimestamp: 1,  
                circulating: 1,  
                currencyName: 1,  
                communityRanking: 1,  
                codebaseRanking: 1,  
                walletRanking: 1,  
                decentralizationRanking: 1,  
                gitCommits: 1,  
                featured: 1,
                premine: 1,
                cpc: 1,
                cpt: 1,
                price: 1
                
              }
             }).fetch()`

**Comment by gazhayes** [comment]
Resolving #874 would probably help, I'll try and get to that ASAP.

**Comment by AshHimself** [comment]
Never mind.. after burning a few hours of debugging I figured out the issue. consensusSecurity was being explicitly defined to not be available therefore filtering would not work :(

>     fetchCurrencies(){
>         return Currencies.find({}, {fields: {consensusSecurity: 0, hashAlgorithm: 0, gitAPI: 0}}).fetch().map(i => _.extend(i, {
>           quality: quality(i)
>         }))

**Comment by AshHimself** [comment]
@gazhayes first PR #959

We can add more attributes in logical groups and perhaps easily group them in something like;
https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

Sorry this took a while, I was learning how all these local collections worked and drove me nuts.

Welcome changes and suggestions from all.

**Comment by gazhayes** [comment]
> Sorry this took a while, I was learning how all these local collections worked and drove me nuts.

Yeah, some parts of the codebase are pretty confusing, this is a byproduct of the C4 (its much easier to keep the codebase nice and clean when you're centrally planned, but then you end up solving problems that aren't really problems and building stuff no one wants).

This is the reason for this rule in the readme:
>Your code should be very well commented and easy to read. It should be immediately clear what your code is doing. You should be able to look at your code a year later, in the morning before coffee, and immediately know what it's doing. Write code and comments like you are teaching someone else how to do what you're doing.

**Comment by janat08** [comment]
It does load the whole collection, that method, and then:
```
@@params
  Name: name of collection in DB,
  methodName: method to fill in local collection with
```

**Comment by AshHimself** [comment]
Were you happy to close this @gazhayes or were there other attributes you wanted to add or change of functionality?
