### ISSUE TITLE
problem: bounty icon doesn't do anything when there are no bounties running

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#803]
Problem: the bounty icon (target) in the top navbar doesn't do anything when there are no bounties running

solution: I guess link it to the bounties page? Unless there's something better to do.

**Comment by AshHimself** [comment]
I think hide it, clear up the UI a little bit, unless you want it to display zero and display a one off tooltip "You have no bounties, head over to the bounties page". @gazhayes

**Comment by gazhayes** [comment]
Yeah hiding it is probably better

**Comment by gazhayes** [comment]
Actually, we're going to want a bounty menu item in the top nav bar on large screens, so maybe just set this as a dependecy to the menu bar issue (will update this witb the issue number.)

**Comment by AshHimself** [comment]
I posted I PR about 20 seconds before I got this notification :/
