### ISSUE TITLE
problem: you can save a community url with no values

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#808]
Problem: When adding a community URL you are actually able to click save and save a null record.

Solution: Add form validation

**Comment by AshHimself** [comment]
Just using jQuery validation at this stage. Its 2 lines of code. When those packages are implemented it'll be a side wide change I imagine after the schemas are defined for every collection. Please correct me if I am wrong?

**Comment by gazhayes** [comment]
How are you doing server side?

**Comment by gazhayes** [comment]
I think we should go straight to using validated-method on anything new, unless it makes things uncomfortable.

**Comment by AshHimself** [comment]
@gazhayes - Agree, but to my understanding we need simpleSchema implemented to use validated-method. (Source: https://github.com/meteor/validated-method) 

Even with this implemented it still won't solve our client-side validation issues. This article describes pretty much exactly what I am trying to say :)

https://themeteorchef.com/tutorials/validating-forms-with-jquery-validation

**Comment by AshHimself** [comment]
Ideally both packages should complement each other. e.g. if I write a jquery validation ruleset to define 5 fields as for example, int, int, email, int, text (max 20) it should validate on client first and simple schema should replicate my already defined rules (if they make technical sense ofcourse)

**Comment by gazhayes** [comment]
@janat08 used validated-method and simplSchema here: https://github.com/Blockrazor/blockrazor/blob/fafe03bf926f8eb329c3963510d65f2d8c3bab56/imports/api/problems/methods.js

And it's called from here: https://github.com/Blockrazor/blockrazor/blob/fafe03bf926f8eb329c3963510d65f2d8c3bab56/imports/ui/pages/problems/newProblem.js

With validated method the same validation is done on the client and server. If validation passes on the client it then goes to the server for server side validation. (https://github.com/meteor/validated-method#validation-and-throwstubexceptions)

Jquery (or whatever) can then be used to handle the DOM (report errors).

**Comment by AshHimself** [comment]
Ok awesome I did not know that. Let me review the code and i'll implement.

**Comment by gazhayes** [comment]
If you think it through carefully and make it a **very** well documented commit then your pull request can as a model for everyone else to follow when they are trying to do the same thing later.

**Comment by janat08** [comment]
simpleSchema doesn't readily support cleaning of values in method call (like for converting NaN to null and then ignoring that if not required, otherwise it fails as it's not a Num), but there're packages that do that. You can also define a schema for collection and then pick necessary fields for the method call.

**Comment by AshHimself** [comment]
@gazhayes - Fixed in #817

I am going to look at optimising the error validation on the client so it highlights the attributes itself (bootstrap CSS) instead of showing a popup notification which offers zero UX.

However I am having a few minor issues. @janat08 - Any ideas why when I set optional:false on the image attribute its not flagging an issue when its empty?

**Comment by AshHimself** [comment]
@janat08 - you should find it pretty easy but this is where I am talking about. 

`    validate:
        new SimpleSchema({
            currencyId: { type: String, max: 17, optional: false},
            url: {type: String, regEx:SimpleSchema.RegEx.Url, optional: false},
            image: {label:'Your Image',type: String, optional: false, regEx: /\.(gif|jpg|jpeg|tiff|png)$/
},`

**Comment by AshHimself** [comment]
Will raise another issue to track the simpleschema validation issues as this is working right now.

**Comment by janat08** [comment]
@AshHimself don't know how I missed this but you should use required if there's requiredByDefault option specified, and obviously, the value for requiredByDefault is devValidationEnabled which is false in a development environment with a toggle in startup folder. It's not just plain Meteor.isDevelopment which is all it is to demonstrate the intent of enabling validation only in production.
