### ISSUE TITLE
Problem: [/wallet] can't sort values by amount

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#811]
Problem: in /wallet users cannot sort transactions by amount. This would probably require an extra column displaying the amount.

@AshHimself this could be the right place to introduce that cool package you mentioned the other day, I can't remember the name

**Comment by AshHimself** [comment]
Yup you got it.. i'll sort it out and we can review!

**Comment by AshHimself** [comment]
Fixed in #813 
@gazhayes take a look. Its pretty configurable so let me know what you are after or take a look at https://github.com/aslagle/reactive-table

**Comment by gazhayes** [comment]
Definitely good enough to start with.

**Comment by AshHimself** [comment]
@gazhayes - It does come with a filter that works just like the home page. e.g. type anything and it'll query ALL visible fields. Maybe not much user on this page but it is cool.
