### ISSUE TITLE
problem: [/wallet] sorting transactions by time doesn't work

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#815]
Problem: when sorting transactions by time/date, they aren't sorted by epoch time (unix timestamp) but instead by the text value that momentjs provides.

**Comment by AshHimself** [comment]
Good catch!! I got an idea to fix it.

**Comment by AshHimself** [comment]
Fixed in #825 (Turns out the package has a param to fix this exact issue. #winning)

**Comment by gazhayes** [comment]
Pretty cool package
