### ISSUE TITLE
problem: [/communities] adding new community has a really bad UX

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#818]
Problem: the UX for adding a new community to rate has a really bad UI/UX.

<img width="486" alt="screen shot 2018-03-29 at 5 40 50 pm" src="https://user-images.githubusercontent.com/8143945/38082168-73798552-3378-11e8-84a4-71bd93c620cb.png">

Possible solution: use a modal. Also change the filename field to something other than an input field.

**Comment by AshHimself** [comment]
Sorry i'll do a PR for this now. I won't spend too much time making the rest pretty as this page itself needs a revisit as a whole. That ok?

**Comment by gazhayes** [comment]
Yeah that's cool

**Comment by AshHimself** [comment]
Fixed in #822
