### ISSUE TITLE
Problem: all uploaded images are given jpg extension

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#82]
https://github.com/Blockrazor/blockrazor/blob/36dc5b77eee538c8b0d2868497e3c60cef705412/server/methods/imageUpload.js#L134
Possible solution: detect image mime type and add appropriate extension.

**Comment by AshHimself** [comment]
@gazhayes the mime-types package can do this easily. I will implement whilst working on #79 as its the same file.

https://www.npmjs.com/package/mime-types#mimeextensiontype

**Comment by gazhayes** [comment]
@AshHimself  If you believe this is fixed, just comment on the issue (in addition to tagging the commit or PR as you have already done) so that whoever logged the original issue knows it's safe to confirm the solution and close it. I know it's solved in this case but just for future reference.

**Comment by gazhayes** [comment]
Fixed in #84
