### ISSUE TITLE
Problem: [/currency/x] Recaptcha has bad UI/UX

### ISSUE THREAD

**Issue by anbud** [Blockrazor/blockrazor#823]
Problem: On the currency detail page, a recaptcha form is shown if the user tries to post red flags/summaries/features/comments too fast (10 seconds between is the threshold). But, it's UI and UX are quite bad, as I've just placed it on the page without styling it or anything. To trigger it, you just need to post two things in less than 10 seconds.

Solution: I believe that the best solution here would be to put it in a modal or something so it can draw user's attention, but anything prettier (both UI and UX-wise) than the current solution will work.

**Comment by AshHimself** [comment]
@anbud trying to see the Recaptcha locally and i'm getting the error that i'm posting too fast but can't see the captcha. I did install not node module too. Thoughts?

**Comment by anbud** [comment]
Try increasing the threshold here: https://github.com/Blockrazor/blockrazor/blob/master/client/main.js#L130. 
Currently, it's 10000ms, increase it to 100000ms and you'll definitely see it. :)

**Comment by AshHimself** [comment]
Apologies if i'm missing something here.. its been a long day :) 

I am spamming red flags now and getting the error 'You have to wait until you can post another red flag.' but I still see no captcha. :/ i'll dive into the code more unless you can point me and save some time

**Comment by anbud** [comment]
That's from another issue, you can post only 1 red flag per 3 days when you pass 10 red flags. Try spamming comments, there's no limit there. I've placed the captcha (the `{{{captcha}}}` helper) above `Summaries` header, maybe that's why you're missing it, it's not very visible, which should be fixed in this issue. 

The above advice about changing the threshold should also help, as the captcha will currently only appear if the difference between last two activities is less than 10 seconds, which is sometimes hard to achieve if you're not a bot. :)

**Comment by gazhayes** [comment]
> when you pass 10 red flags

10 red flags based on the User or based on the Currency?

**Comment by anbud** [comment]
10 red flags based on the currency.

**Comment by gazhayes** [comment]
@chamidu-supeshala are you able to self assign yourself to tasks or it doesn't let you?

**Comment by chamidu-supeshala** [comment]
fixed in #921

**Comment by chamidu-supeshala** [comment]
Thanks @gazhayes  and now i can self assign tasks. So after i completing a task, do i need to close it? or the person who raised the issue need to verify before closing it?

**Comment by gazhayes** [comment]
> So after i completing a task, do i need to close it? or the person who raised the issue need to verify before closing it?

The person who opened it *should* close it.
