### ISSUE TITLE
problem: hashpower API bounty doesn't end when valid pull request provided

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#830]
Problem: when a valid pull request is provided for an API bounty, a success notification is displayed but the bounty keeps running and eventually times out.

**Steps to reproduce:**
Select an API bounty from the bounty page   
Submit a valid pull request (grab a merged one from blockrazor)   
Click submit.

**Comment by anbud** [comment]
I'll take this one, it was working last time I've tried, so it's probably something small.

**Comment by anbud** [comment]
@gazhayes,
I've just tried it out on a couple of coins on production, but every time I click Submit PR link, it submits, shows the success message and ends the bounty. The user is rewarded only when the bounty is merged, when GitHub notifies our webhook of this event. I've just tried it with #843, and I've manually redelivered the event notifications, and I've got the reward. So, it appears to be working properly.

**Comment by gazhayes** [comment]
Did you try adding an already merged issue? That's when it failed for me.

**Comment by anbud** [comment]
Yap, all tries were with already merged issues from this repo. Which currency did you try?

**Comment by gazhayes** [comment]
Hmmm ok. Zcash I think. I'll try again and see if I can replicate.

**Comment by gazhayes** [comment]
Must have been a freak thing, I can't replicate it now.
