### ISSUE TITLE
Problem: no user-based average comment/summary/feature/red flag ranking

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#832]
Problem: to foster some competition between users, there should be a variety of metrics about users (which can be displayed on their profile page). A good metric to start with would be their overall comment/summary/feature/red flag ranking, this would give a good indication of how valuable their input is in general.

possible solution: use a cron job to count total upvotes and downvotes for each user's item. `Ranking = total upvotes / total votes`.

**Comment by AshHimself** [comment]
This is a good idea. Could also do something similar to stackoverflow to
foster trust and respect between users instead of just activity.

E.g commment upvotes 10 times and you get a trusted poster badge.

**Comment by anbud** [comment]
Yap, this is a good idea, I agree. I'll take it.

**Comment by anbud** [comment]
Done in #847.
