### ISSUE TITLE
problem: [/] prices are not accurate

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#834]
Problem: prices on the / route are not accurate because they do not allow decimal places.

We should be using a fixed number of digits so that the UI doesn't get messed up. As Bitcoin has recently been up to 5 figures we should use that.

For example, Cardano should be $0.XXXX (decimal), Bitcoin XXXXX (no decimal).

**Comment by AshHimself** [comment]
I can take a look at this as I wrote the helper which isn't work as it should.

**Comment by AshHimself** [comment]
Fixed in #905 pending testing

**Comment by gazhayes** [comment]
Yep looks good to me.
