### ISSUE TITLE
problem: [/] user generated content not shown on home route

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#835]
Problem: there are already plenty of sites comparing cryptocurrencies using APIs and similar metrics to Blockrazor. The difference with Blockrazor is that it is community driven (e.g. like Wikipedia). This human element should be immediately obvious when seeing blockrazor for the first time.

Partial solution: put the top "red flag" for each currency on the home route.

**Comment by jmspsi126** [comment]
Let's start to work together on here :)

**Comment by jmspsi126** [comment]
master branch is exclusively used to accept incoming changes from upstream:master
so i created my new branch and committed code on that branch.
Before commit code, i pulled code.
My question is...
I have to send pull request from my new branch?

**Comment by jmspsi126** [comment]
I sent pull request.

**Comment by jmspsi126** [comment]
before i send pull request, i want to ask some question
I mentioned on last message.
but you didn't check that.
I want to discuss about project with real time.

**Comment by jmspsi126** [comment]
There are some problem on communication.

**Comment by jmspsi126** [comment]
I fixed all issue but i can't show you that results to you.
When start to work, you need to help me and guide me.
?

**Comment by jmspsi126** [comment]
I checked C4 carefully.
First i will fork and work on my github.
I think...
After fix issue on local, i can commit code on my github.
When commit code, i need to check code and test on my local again.
That MUST be Solid and Good code.
After confirm code again, i will commit code.
Then i can send you pull request.
When send pull request, you will check code carefully and send me feedback like today.
When send pull request, i MAY comment on pull request, on the commit.
You will check my code and if that is good code, you will confirm.

**Comment by jmspsi126** [comment]
Hello

I checked your message 
I am going to clone git and to send pull request without conflict issue.
Can i try once more?
I don't have enough experience to work with this process.
Sorry.
After learn this process, i can work well.
I await your reply again

Best Regards!

**Comment by gazhayes** [comment]
You applied for a position as a paid contributor. You sent 3 pull requests. None of complied with our contribution policy. We are no longer considering you for that position at this time.

You may contribute to the project, it's open source. The rules in the C4 are very clear, they are also repeated throughout throught the readme. Your code is *not* the problem (well, apart from committing your IDE configuration files). The problem is that you are not following the contribution protocol. For a small patch like this there should only be *one* commit, it should have *no* conflicts, and it should follow the problem/solution format as described in the Readme (and the C4).

**Comment by jmspsi126** [comment]
Thanks for your reply.
I am trying to send pull request again.
I am working for that.
If learn this process, we can start to work again?

**Comment by jmspsi126** [comment]
I checked all on Readme file carefully.
I have learned so much in the meantime.
I have learned all rules in the C4 well.
What is next process?

**Comment by gazhayes** [comment]
When you finish an issue, you can say something like "fixed in #846"

**Comment by jmspsi126** [comment]
fixed in #835

**Comment by jmspsi126** [comment]
What is next issue?

**Comment by gazhayes** [comment]
Your patch broke other functionality. It has been reverted.

**Comment by jmspsi126** [comment]
Can you explain about that?
There are not issue on my local now.

**Comment by gazhayes** [comment]
No. Look through the recent issues and commits and work it out for yourself. I am not spending another minute on this.

**Comment by jmspsi126** [comment]
ok
understand you.
Can you send me screenshot that can check issue?

**Comment by gazhayes** [comment]
Screen shots are not necessary. Everything is already documented. I refuse to treat you like an infant and I refuse to spoon feed you. 

Look at the comments on your pull request. Look at *why* your patch was reverted. **Take responsibility** for your own education about how to use Git and Github, **do not** continually put the burden on everyone else around you.

**Comment by jmspsi126** [comment]
Did you close #835 issue?
When you close #835, may i try to fix issue?

**Comment by jmspsi126** [comment]
hello

Are you there now?

**Comment by jmspsi126** [comment]
hello

Did you close #835 issue?
When close issue, can i start to work.
I think you need to open new issue on gitlub.
This is right?

**Comment by jmspsi126** [comment]
Are you there now?
Did you check my message?

**Comment by jmspsi126** [comment]
I have to stop to work now?
Or i have to work on closed issue state again?

**Comment by jmspsi126** [comment]
I didn't find cause of issue why you removed code i committed yet.

**Comment by jmspsi126** [comment]
Can i start to work on another issue list?

**Comment by jmspsi126** [comment]
Are you there now?
