### ISSUE TITLE
Problem: lazy answering errors aren't clear enough

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#836]
Problem: when users are caught lazy-answering (/rankings, /communities, /codebase) they are shown a quick sAlert notification and all their questions are reset. This could be very confusing for some people.

possible solution: launch a modal for these errors instead and explain what's going on.

**Comment by samuelralak** [comment]
done in [#842](https://github.com/Blockrazor/blockrazor/pull/842)
