### ISSUE TITLE
problem: [/problem] users can add bounties to cancelled problems

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#837]
Problem: users can add more bounties to cancelled problems.

**Comment by samuelralak** [comment]
@gazhayes do you mean this part here?
<img width="1111" alt="screen shot 2018-03-30 at 11 45 33 am" src="https://user-images.githubusercontent.com/4476552/38131475-f2f239e0-340f-11e8-9d83-7a98607bb4ba.png">
> Problem: users can add more bounties to cancelled problems.

**Comment by gazhayes** [comment]
Yeah that's where I encountered it.

**Comment by samuelralak** [comment]
cool, will be taking this one completing [#836](https://github.com/Blockrazor/blockrazor/issues/836)

**Comment by samuelralak** [comment]
checking whether the problem is solved/closed/cancelled in server  and hiding this section completely on the ui  if problem is solved/closed/cancelled

**Comment by gazhayes** [comment]
Good solution

**Comment by samuelralak** [comment]
done in [#843](https://github.com/Blockrazor/blockrazor/pull/843)

**Comment by samuelralak** [comment]
this can be closed if the solution is satisfactory
