### ISSUE TITLE
problem: [/problem] users can comment on cancelled problem

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#838]
Problem: users can comment on problems that have been cancelled. This makes it easy to have confusing and stale issues.

possible solution: prevent commenting on cancelled problems, and encourage users to open a new issue instead.

**Comment by samuelralak** [comment]
@gazhayes should we also disable comments on solved and closed problems as well?

**Comment by gazhayes** [comment]
Yeah, that makes sense.

**Comment by samuelralak** [comment]
ok cool, what brief but yet awesome message should we display to users who wish to comment on a closed/cancelled/solved issue?

Was thinking something close to this 👇 
*Didn't solve your problem? You can create a new one here for it*

What did you have in mind?

**Comment by samuelralak** [comment]
done in [#840](https://github.com/Blockrazor/blockrazor/pull/840)
