### ISSUE TITLE
problem: [/problem] cancelling an issue does not refund bounty deposits

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#839]
Problem: based on https://blockrazor.org/problem/WWb9AHxLSCFQpRBDL it looks like bounty deposits aren't being refunded when a problem is closed.

**Comment by samuelralak** [comment]
taking this one next

**Comment by samuelralak** [comment]
this one seems to work fine. here are the tests I ran
- created problems and closed each one - bounty deposits got refunded each time [passed]
- topped up bounty on an open problem closed it - bounty deposits got refunded [passed]
- deposited bounty using different account then closed it - bounty got refunded to all users that made a deposit [passed]
everything seems to be ok but you can test it again to confirm

**Comment by gazhayes** [comment]
OK. It's probably just an artefact from database experimentation earlier on or something.
