### ISSUE TITLE
problem: haspower API bounty is awarded even if pull request doesn't solve problem

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#849]
Problem: the hashpower API bounty is awarded as soon as the Pull Request is merged. However some people might submit a PR that doesn't actually work. These bounties can sometimes be pretty big so they would be a lucrative target for some form of cheating.

possible solution: put something in the hashpower API update that awards the contributor on the first successful API call for that currency

possible solution: add to moderation queue and ask a human to validate that the API call worked. First solution would be much better of course.

**Comment by gazhayes** [comment]
ping @anbud

**Comment by anbud** [comment]
I agree, the first solution is a lot better. How about letting PR contributors put their own username / _id as the last parameter of the `hashrateApi` method call in `hashpower.js`, so we know who's the one that authored it and we know who to reward? 
It appears as the easiest solution.

**Comment by gazhayes** [comment]
Actually that's not a bad idea, then if it breaks later because someone took down the endpoint or whatever the user can be sent a message.

**Comment by gazhayes** [comment]
Should probably print their _id on the bounty thing somewhere to make it easier for them.

**Comment by gazhayes** [comment]
And also link to the model pull request you did for this before.

**Comment by anbud** [comment]
Done in #866. I've actually found an easier solution than forcing them to include their user _id, I realized that we can get the _id from the bounty itself.
