### ISSUE TITLE
Problem: Notification badge is not cleared when logging out

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#85]
Problem: When logging out the notification bubble in the menu is not removed.

Solution: Need to clear the reactiveVar which stores the notification count on logout.

**Comment by gazhayes** [comment]
@AshHimself FYI if this is solved you (as the issue creator) can leave a quick comment (e.g. fixed in #90) and close it.

**Comment by AshHimself** [comment]
Fixed [#90](https://github.com/Blockrazor/blockrazor/pull/90)

**Comment by AshHimself** [comment]
Fixed in [#90](https://github.com/Blockrazor/blockrazor/pull/90)
