### ISSUE TITLE
problem: no user generated content is shown on home route

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#854]
Problem: no user generated content is shown on home route

Solution: display top red flag on home route.

**Comment by AshHimself** [comment]
Top red flag for each currency? Real estate is getting tight if so, may need to make those radars 10-15px smaller.

**Comment by jmspsi126** [comment]
I already tried to add top red flag.
As Ash mentioned above, after add top red flag,  real estate was getting tight.
But i think we have one method.
We can increase the height value of each block.

**Comment by jmspsi126** [comment]
https://www.screencast.com/t/5JqrjM40y

Please check this screen.
I added function to show top red flag like this screen.

**Comment by gazhayes** [comment]
You again? As I mentioned in numerous places, after 3 or 4 failed pull requests in your attempt to be brought onboard as a paid contributor you finally sent one that complies with the C4 but your code broke existing functionality, so I reverted it. This was well documented and discussed between myself and anbud at the time, I tagged your pull request with these conversations. I mentioned them in the revert commit. It is YOUR responsibilty to work this stuff out, you aren't a baby and no one here is going to spoon feed you like one. 

You can send another pull request to fix this issue if you want, but this is your final warning - if you waste another minute of my time with code that creates new problems or questions that show you have not read something you should have then I'm blocking you from my personal account and from this repository.

**Comment by jmspsi126** [comment]
Yes.
I checked code carefully and found cause.
When fix issue correctly, i will send pull request again.

**Comment by gazhayes** [comment]
@jmspsi126 when you have completed an issue you can mention that it is complete so that everyone knows you aren't sending more pull requests.

**Comment by jmspsi126** [comment]
what do you mean?
There are issue on committed code now?

**Comment by gazhayes** [comment]
No. I mean that if you have completed an issue, you should say so. Then we can validate it and close the issue.

**Comment by jmspsi126** [comment]
Ok.
Did you test about committed code again?
If you find new issue, ping me.
How long it will take to test?
I think...
When fix issue, i have to mention like "Fixed in #854."

**Comment by gazhayes** [comment]
> When fix issue, i have to mention like "Fixed in #854."

correct.

> Did you test about committed code again?

Yes. That's why I closed the issue, it's solved.

**Comment by jmspsi126** [comment]
Ok.
Even if it 's a little late, I want to say this. :)
Fixed in #854

**Comment by jmspsi126** [comment]
what is next task?

**Comment by gazhayes** [comment]
We don't assign tasks, if you want to work on a new task you can choose whatever looks interesting to you.

**Comment by jmspsi126** [comment]
yeah
I understand.
umm...
May i ask this question?
Who is CFO of blockrazor?
I mean...
Who can pay about my working times?

**Comment by gazhayes** [comment]
We aren't bringing you on as a paid contributor, so nobody can pay you.

**Comment by jmspsi126** [comment]
umm...
I understand you enough.
This is not problem to discuss with you.
How can i contact with Client?
Can you send him message?
I fixed one issue.
Client need to pay for this.
If client not paid, how can i work for project?
If client not paid, you can work for project with free?
This is not reasonable contract.
Right?
Can you send client's email or $kype id on here?

**Comment by jmspsi126** [comment]
Are you CTO or developer of team?

**Comment by MadanBhandari** [comment]
@jmspsi126 you should first read and understand about what is Open Source and how it's works.

**Comment by jmspsi126** [comment]
@gazhayes 
I understand you.
But i fixed issue finally.
If there are not any another client on this team...
I think...
As client you have to pay about this.
If you want, i will send you my paypal email.
Please pay about my working hours.

@MadanBhandari 
I know about Open Source well.
So i tried to work for project.
And i learned all process and fixed issue finally.
If you devoted yourself with free, can you try ?
No you can't try.
You will not want.

**Comment by gazhayes** [comment]
> If you want, i will send you my paypal email.

No, I want to leave you a review when I pay :)

I'm guessing you saw this through upwork or freelancer? What's your username? You've had your fun, it's my turn now.

**Comment by jmspsi126** [comment]
I think you are also developer like me.
right?
Who is client?

**Comment by sjmackenzie** [comment]
@jmspsi126 why are you deliberately stirring up chaos in this project? Are you working on a competing project maybe? Shouldn't you be pushing your own features instead of focusing on creating a cacophony in your competitor's hallways?

**Comment by samuelralak** [comment]
@jmspsi126 the gods my good sir...the gods
> Who is client?

**Comment by jmspsi126** [comment]
I completed 600 projects perfectly.
Actually i have been programming for over 10 years.
But i didn't have this experience.
After fixed issue, all clients paid for that.
But i didn't have any.
This is reasonable contract?

**Comment by jmspsi126** [comment]
If didn't fix issue, i will not request this.
Sorry.

**Comment by jmspsi126** [comment]
@gazhayes 
When can you pay?

**Comment by jmspsi126** [comment]
I think client is located in United Kingdom.
You are asian.
I want to discuss with client directly.

**Comment by francisalmighty** [comment]
I don't remember why I started following this repo, but damn this is good entertainment. @jmspsi126 have you ever considered a career in standup comedy?

**Comment by jmspsi126** [comment]
@francisalmighty
You can think about this project.
I devoted myself for project, but i didn't get any yet.
So i am requesting this.
Sorry.

**Comment by jmspsi126** [comment]
Please pay about my working hours.
I don't want another.

**Comment by jmspsi126** [comment]
I devoted myself to fix issue.
Please pay for me.

**Comment by jmspsi126** [comment]
If didn't fix issue, i will not request this.
I can't request this.

**Comment by jmspsi126** [comment]
@gazhayes 

Hi Gareth 

For now.
How can i help you?
I want to work continuously on reasonable contract.
I think  you can  understand me because you have experience to work as developer too.
First of all...
I want client pay to me for first contract.
After pay, i want to work on another task with all team members.
Please help me.

Regard!

**Comment by gazhayes** [comment]
Just for the record:

#784 is the issue where I said:
> You're applying for a paid contributor position, and you haven't even read the contribution policy. You've sent **two incorrect pull requests**, and I told you both times that they do not comply with the C4 and that you need to read the Readme. You get **one more chance** to get it right, I'm not willing to spend any more time on this.

You then sent a third pull request (#841), and again you hadn't read the readme, I replied with:
>1. Your commit messages are not valid under the C4. You also have 4 commits when 1 single commit is more than enough.
>2. Your pull request has conflicts and cannot be merged.
>3. You're applying for a paid contributor position and this is your 3rd failed attempt. I've spent far more time dealing with you than it would take to fix the issue myself. This is not good enough, **we will not be hiring you**.

Then in issue #835 I said, just to reiterate:
> You applied for a position as a paid contributor. You sent 3 pull requests. None of which complied with our contribution policy. I told you each time to go back and read the Readme. **We are no longer considering you for a paid position** at this time.

> **You may contribute to the project, it's open source**. The rules in the C4 are very clear, they are also repeated throughout throught the readme. Your code is not the problem (well, apart from committing your IDE configuration files). The problem is that you are not following the contribution protocol. For a small patch like this there should only be one commit, it should have no conflicts, and it should follow the problem/solution format as described in the Readme (and the C4).

You replied:
> Thanks for your reply.
I am trying to send pull request again.
I am working for that.
If learn this process, we can start to work again?

I did not at any time after this point indicate that you would ever be paid for anything.

You then sent your fourth pull request (#846 ) which caused issue #798 to be reopened and debugged because you rolled back its solution.

You then sent your final pull request, which got it right, after wasting hours of my and other contributors time.

In this thread, I said:
> Which site did you come through to apply to be a paid contributor? Perhaps I'll pay you through there just so I can leave you a horrific review.

You declined to provide this information and instead asked me to send you money on Paypal.

**Comment by MadanBhandari** [comment]
> If you devoted yourself with free, can you try ?
> No you can't try.
> You will not want.

Well, In my case, I have started working on this because I never worked on any Open Source Projects and I wasn't sure about the process and money was never my main priority for this project (because this is Open Source). 

@gazhayes helped me to understand the process and to make my first PR. He is been very supportive and always encourage me to learn, participate in discussion, better understanding of decentralize development process.

To answer your question in one sentence, Yes I can and I'll do this for any open source project, as long as I have my day job [for my daily expenses] and something to learn and supportive community.

Now @jmspsi126 stop posting nonsense, there are clear [conditions to be eligible for paid contributor](https://github.com/Blockrazor/blockrazor#contributing-to-blockrazor).
