### ISSUE TITLE
Problem: bounties not visible unless signed in

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#858]
Problem: bounties are only visible when users are signed in. This doesn't offer new people enough of a 'tease' to make them want to sign up.

**Comment by engyash** [comment]
I am working on this issue.

**Comment by gazhayes** [comment]
FYI once you solve an issue you can say something like "fixed in #XXX". Then whoever opened the issue knows you aren't planning on sending any more pull requests and they can verify the solution and close the issue.

**Comment by engyash** [comment]
Fixed in #6e62ed66363249e4811eca9173414a4185b7e358 [6e62ed6].
