### ISSUE TITLE
problem: logout is broken

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#862]
Problem: logout no longer works. There is a recursion error. Most browsers die with memory issues, e.g. chrome: `Uncaught RangeError: Maximum call stack size exceeded`

ping @janat08 this probably happened in #857

**Comment by anbud** [comment]
I'll take this one as well, as part of #857 debugging.

**Comment by anbud** [comment]
This is fixed in #867. 
@janat08, Can you please check if it fixes the original issue (#565) as well? I've tried it out, it appears to be calling the callback correctly, both on window unload, and on Meteor.logout, but maybe I'm missing something.

**Comment by janat08** [comment]
removing () didn't work for me.
