### ISSUE TITLE
Problem: hashpower API bounties that have timed out are flagged as in progress

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#869]
problem: in-progress and timed out bounties are shown on the bounty page when no user is signed in.

I'm logging this issue because I suspect an underlying problem with the "timed out" items being displayed.

ping @anbud

**Comment by anbud** [comment]
I'll check it out. This only happens when you're not signed in?

**Comment by gazhayes** [comment]
Yeah, it's kind of weird.

There's also #858 to take into consideration when looking at this, the main reason I logged it was because I think it's a symptom of some deeper issue as it's showing bounties that have timed out (which by the way, don't seem to be showing up on the normal bounty page when logged in).

**Comment by gazhayes** [comment]
Ok I did a bit more research.

It turns out that it was any "in progress" bounties that were being shown (not a problem). The actual problem ia that timed out hashpower API bounties are incorrectly counting as "in progress".

**Comment by gazhayes** [comment]
This one is really in progress
![s80401-201008](https://user-images.githubusercontent.com/8143945/38173014-6b02f5b6-35e9-11e8-88ca-05b6ace5ffe3.jpg)

But this one has timed out (something weird with username still being displayed)
![s80401-200951](https://user-images.githubusercontent.com/8143945/38173020-871ac134-35e9-11e8-868b-a7cb70e57301.jpg)

**Comment by anbud** [comment]
Fixed in #877.
