### ISSUE TITLE
problem: development database keeps getting out of date

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#874]
Problem: the dev database needs to be updated periodicallly to preven errors in development.

Solution: add a cron job to dump the database and then tar and gzip it to a file in /static. Part of the troubleshooting process when developers have a local problem which doesnt exist on the server will be to update their db.

**Comment by AshHimself** [comment]
and prevent negative krazors :D

**Comment by gazhayes** [comment]
Note to self: this is now very urgent.

**Comment by gazhayes** [comment]
Fixed in #1016
