### ISSUE TITLE
Problem: travis test is breaking, but production doesn't break

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#880]
Problem: travisCI is breaking in #879 onwards. It looks like master *should* break, but it doesn't, only breaks when running `meteor test --driver-package=meteortesting:mocha --once`

ping @anbud @AshHimself

**Comment by anbud** [comment]
I'll check it out,

**Comment by anbud** [comment]
Should be fixed in #886. I'm not sure why was the error happening, and the solution given in the PR was the only thing that wanted to work.

**Comment by gazhayes** [comment]
I'll post an issue on mocha and see what happens.

**Comment by anbud** [comment]
I'm guessing it has to do something with the load order, but I couldn't seem to find out why.
