### ISSUE TITLE
Problem: not immediately clear that a commit is a "patch" in the c4 and not a pull request

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#881]
Problem: not immediately clear that a commit is a "patch" in the c4 and not a pull request.

ping @sjmackenzie

**Comment by sjmackenzie** [comment]
Patch is a commit, otherwine known as a changeset. Patch, commit, change change set are pretty much interchangeable. A PR is irrelevant to the process, all the information shoild be present at commit message level. Information at a PR level is a nice to have and generally being polite usage.

**Comment by sjmackenzie** [comment]
Fun fact, the name patch was derived from the days of punch cards whereby a programmer would use tape to literally patch or cover a hole in the punch card.

**Comment by gazhayes** [comment]
The problem is that this language difference makes things difficult for new contributors, especially those who are englishly challenged.

**Comment by sjmackenzie** [comment]
Quite likely, have you had experience of people not understanding what a patch is?

**Comment by gazhayes** [comment]
Yes, it's a regular occurance. Confusion about patch/commit/pull request. It's actually rare that someone doesn't ask and just gets it right.

Not sure what the ZMQ guys have experienced, they seem to be straying from the C4 lately anyway.

**Comment by sjmackenzie** [comment]
Okay then, how about setting up a github account dedicated to the C4 and other development processes then maintain it there?

**Comment by gazhayes** [comment]
Yeah that's probably the best idea. I'll do that tonight then.
