### ISSUE TITLE
Problem: edits from observeChanges will make all instances call same edit

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#882]
Edit: The scope of this issue has narrowed, scroll down.

Problem: It's not clear to casual viewers how active the site is. 

possible solution: display number of users online / number of registered users in total

possible solution: some kind of activity log

**Comment by AshHimself** [comment]
Number of registered users is easy enough; or could go a little deeper

https://github.com/mizzao/meteor-user-status/

**Comment by gazhayes** [comment]
Yeah that looks like it will work.

**Comment by AshHimself** [comment]
Looks like it'll only work for a single instance therefore when/if we break out to multiple meteor instances it'll be borked. i'll keep looking.

**Comment by gazhayes** [comment]
Ah yeah, that's not a solution then. We'll be using multiple instances from day 0 just to stop downtime with every merge.

**Comment by AshHimself** [comment]
https://github.com/VeliovGroup/Meteor-user-status/ looks a lot better.. Giving it a test locally now.

**Comment by janat08** [comment]
https://atmospherejs.com/socialize/user-presence
lets you pass callbacks so that you can just increment a field in a separate collection and is supposedly more scalable.

**Comment by AshHimself** [comment]
socialize/user-presence looks good but it has a lot of dependencies. I ponder if there is something more lightweight :/

**Comment by gazhayes** [comment]
Total users should be easy, in the worst case we can just count once an hour in a cron job and denormalize it somewhere.

So doing online users efficiently is what matters here.

**Comment by janat08** [comment]
It does add server-presence package, and is not reliable in informing only once that the user is online. I think it would've made more sense to make a global publication to keep track of users online, but it's done.

**Comment by gazhayes** [comment]
Well, if it doesnt work well enough at least there are other options. Let's see how it goes.

**Comment by janat08** [comment]
Actually, it appears to use publications already, I ran into same chaos trying to use them.

**Comment by janat08** [comment]
Make edits from observeChanges will make all instances call same edit.

**Comment by MadanBhandari** [comment]
Sorry for late response.

I think showing online users are not enough. What about showing activity instead of online users. 

Example : 
New coin added 3 minutes ago by _username_.
Coin info updated 3 minutes ago by _username_ etc.

**Comment by janat08** [comment]
So I think it would be best if publication for this would just send the variable instead of fetching from DB on every subscription.

**Comment by gazhayes** [comment]
Solved now right?

**Comment by janat08** [comment]
I was going to optimize it further as per last comment.

**Comment by janat08** [comment]
i'll assume that publication is smart enough to catch this.
