### ISSUE TITLE
problem: cursor on chart does not change when hovering over chart labels

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#883]
Problem: Its not clear to the user that the labels on charts can be clicked.

**Comment by AshHimself** [comment]
Should we just make the element clickable then?

**Comment by gazhayes** [comment]
Yeah can do, it's probably just going to be used for a modal anyway.

**Comment by AshHimself** [comment]
Ok maybe i'm not following then.. what should happen when you click the
chart labels. Mine just navigates to /currency/{{coin}}

**Comment by gazhayes** [comment]
Ah, forgot to mention that #876 is related. Look at the console when clicking radar and bar chart labels.

**Comment by AshHimself** [comment]
ohh I get it.. so the radar being clicked now is just opening the currency page but it'll soon be opening a modal..?

**Comment by gazhayes** [comment]
Yeah you got it

**Comment by anbud** [comment]
@AshHimself, have you started working on this one?

If not, I'll take it, I have a simple solution in mind.

**Comment by AshHimself** [comment]
I had a tinker but didn't find anything elegant to solve it. Its all yours.

**Comment by anbud** [comment]
Done in #918.
