### ISSUE TITLE
Problem: [/addCoin] doesn't use typeahead for exchanges

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#891]
problem: typeahead is not used when adding exchanges at the /addcoin route.

solution: make /addCoin use typeahead for exchanges

**Comment by gazhayes** [comment]
I edited this to show you how it should have been logged.

**Comment by janat08** [comment]
#783 is dependency

**Comment by samuelralak** [comment]
@janat08 is the dependency for this issue resolved?

**Comment by gazhayes** [comment]
I'll close this one for now as it's adding some confusion.
