### ISSUE TITLE
problem: [/auction/x] incorrect momentjs calculations

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#896]
problem: the momentjs calculations seem to be inverting past and future dates.

**Comment by nsec-pilot** [comment]
HI @gazhayes, could you tell me a little more about this issue?
Exactly, where do you mean for this calculation issues?

**Comment by gazhayes** [comment]
for example:
https://blockrazor.org/auction/zcqotYh4kNtPrfh3o
<img width="209" alt="screen shot 2018-04-03 at 12 01 16 pm" src="https://user-images.githubusercontent.com/8143945/38228587-c235be56-3736-11e8-8d0b-5902f08db483.png">

I created this test auction, it ends *in* 2 years.

**Comment by nsec-pilot** [comment]
What is the correct value?

**Comment by gazhayes** [comment]
We will not be playing this little game again. You may have changed your github username but I know exactly who you are.

All the information you could ever possibly need is above.

**Comment by nsec-pilot** [comment]
What do you mean? I am new in this project. I think you misunderstood.

**Comment by gazhayes** [comment]
It should say "in two years", but it's reporting "2 years ago". I havent looked but I guess it's reversing the time calculation somewhere.

**Comment by gazhayes** [comment]
Ah ok. I just merged a pull request that changes the date selector, this might be resolved then, will know in a few minutes.

**Comment by gazhayes** [comment]
Could it just be appending "ago" to everything?

**Comment by chamidu-supeshala** [comment]
Shall i work on this?

**Comment by gazhayes** [comment]
I was just chatting to @nsec-pilot and he is already working on it but forgot to follow the readme and claim it first ;)

**Comment by chamidu-supeshala** [comment]
Ok no issues.. it is just an issue with the function i think.. will be fixed if we use fromNow() instead toNow()

**Comment by kevingilliard** [comment]
I found a problem with using moment.js
For example, below url shows "in in"
https://blockrazor.org/auction/zcqotYh4kNtPrfh3o

![image](https://user-images.githubusercontent.com/13878119/38282797-04cd2e5e-3780-11e8-8a56-9bd1cbf97d31.png)

**Comment by nsec-pilot** [comment]
Ok, let me see and fix it.

**Comment by gazhayes** [comment]
Also @nsec-pilot when you have finished an issue and aren't sending any more pull requests you shoud mention that you have fixed it so that everyone knows they can check it and close the issue. Also mention the pull request number with a # at the front so that it's easy to find the pull request (#916 in this case)

**Comment by nsec-pilot** [comment]
Ok, then, after fixing this issue, shall I send pull request again.

**Comment by gazhayes** [comment]
@nsec-pilot I'm not sure if you fully understand. You need to make a comment when you have finished. Sometimes some issues require many pull requests, so no one knows what you are thinking unless you say it. It's very important to tell everyone when you've finished working on any issue so that people can check the result and close the issue. Otherwise we have a lot of 'dead' issues and it's very confusing.

Have you finished with this one?

**Comment by nsec-pilot** [comment]
Yes
