### ISSUE TITLE
Problem: Toaster error is displayed behind navigation bar

### ISSUE THREAD

**Issue by kevingilliard** [Blockrazor/blockrazor#898]
Problem: When user input invalid data into form and click submit button, it shows error message as toaster.
![image](https://user-images.githubusercontent.com/13878119/38226158-27971e96-36c6-11e8-9e8e-2ce8079ebe71.png)

The toaster is behind navigation bar and user cannot read text.

Solution: Adjust toaster position to be below navigation bar.

**Comment by AshHimself** [comment]
@kevingilliard - I would also review the z-index of the topnav and toaster element. Could be a simpler fix that way possibly.

**Comment by kevingilliard** [comment]
@AshHimself - Thank you for your suggestion.
Now the z-index of navigation bar is top-most.
I'm going make it lower than before and make toaster to top-most.

**Comment by AshHimself** [comment]
@kevingilliard - If you are happy this is solved you should close the ticket as you created it :)

**Comment by kevingilliard** [comment]
Hi, @AshHimself 
How can I assign me to issues?  I don't have permission now.

**Comment by AshHimself** [comment]
You will need to reach out to @gazhayes for this one mate.

**Comment by gazhayes** [comment]
@kevingillard I'll fix that up for you as soon as I get back to a computer (using phone now).
