### ISSUE TITLE
Problem: no layer for maintainers to merge changes

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#9]
When users add a currency it goes straight into the database without a second person checking if it complies with the protocol for updates.

Solution: something like git fork/pull (maybe).

**Comment by sjmackenzie** [comment]
Potentially a minimal solution might be to only accept PRs to canonical from maintainers. The non-maintainers send PRs to maintainers. This is the linux kernel lieutenant model. Kinda messes with C4 but it's minimal.
