### ISSUE TITLE
problem: blockrazor.org whois is private

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#903]
Problem: whois lookup cannot be performed on blockrazor.org. This could somewhat undermine the openness and transparency of the project.

**Comment by nsec-pilot** [comment]
Could you let me know a little more about this issue?
Like screenshots or a little more spec.

**Comment by AshHimself** [comment]
@nsec-pilot This isn't something you will be able to resolve which is why its assigned to @gazhayes.

**Comment by nsec-pilot** [comment]
Ok, I see.

**Comment by gazhayes** [comment]
Fixed. Whois is now public.
