### ISSUE TITLE
problem: cannot test new auction system effectively 

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#904]
Problem: it's hard to test the new auction system effectively because no one has any other currencies other than krazor.

solution: on the wallet page add some buttons like "I can has USD?" for all logged in users to increment different currencies by 10 (or whatever). Make it very clear that this is for testing and will be removed for production, so that casual browsers dont get weird ideas.

**Comment by anbud** [comment]
I've added a deposit form on the Wallet page (above the filter), where you can select the amount and the currency and "deposit" it immediately.

**Comment by gazhayes** [comment]
You're like 3 steps ahead of me. I didn't even look.
