### ISSUE TITLE
problem: approval images are using static urls

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#907]
Problem: approval images are using static urls

`<img src="/static/images/wallets/{{_id}}.{{extension}}" width="400px" height="auto"><br />
`
Solution: Update code to use global params

**Comment by AshHimself** [comment]
Taking this as working in file.

**Comment by nsec-pilot** [comment]
Hi @AshHimself, do we need to change static url to global value like next values?

**Comment by AshHimself** [comment]
I have already resolved this and pushing a PR later.

**Comment by gazhayes** [comment]
@nsec-pilot when something is assigned it means someone is already working on it. Or if someone says something like "taking this" it means they are working on it.

**Comment by AshHimself** [comment]
Fixed in #936
