### ISSUE TITLE
problem: [/] warning modal is displayed under navbar

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#911]
Problem: 
<img width="696" alt="screen shot 2018-04-03 at 5 38 34 pm" src="https://user-images.githubusercontent.com/8143945/38241927-0f06d808-3766-11e8-9579-05f083fe5408.png">

(warning modal triggered by orange image)

solution: move it or change z-index.

Also: remove quotation marks, and make it a link (or whatever) so that the hand cursor is displayed so so users know to click it.

**Comment by chamidu-supeshala** [comment]
I will work on this:)

**Comment by chamidu-supeshala** [comment]
fixed in #912
