### ISSUE TITLE
Problem: a server file makes it into client bundle

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#913]
Problem: /imports/api/users/usersStats.js makes into client bundle, because if you remove Meteor.isServer it will fail as it contains server only packages, yet as this file is concerned it's only imported into the server.

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1121. Had to move the server part to a separate file, as `usersStats.js` has to be loaded on the client since `UsersStats` variable is imported a few times on the client.

@blockrazorbot label "done"
