### ISSUE TITLE
the UI design is not awesome(as of now). Is there any kind of focus to be laid on the UI or set as a roadmap soon?

### ISSUE THREAD

**Issue by madguy02** [Blockrazor/blockrazor#92]
Problem: clearly describe the problem you are reporting. Include references to the codebase where applicable.

Solution: describe the _simplest possible solution_ to the problem (if you know of a solution).

**Comment by AshHimself** [comment]
Hi @madguy02, 

Yes there UX framework is being looked at now by the repo owners. Also you need to read the README as there is a process documented on how to raise problems correctly.
