### ISSUE TITLE
Problem : [/wallet] UI/UX isn't good

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#923]
Problem :  `/wallet` UI/UX isn't good

1. - [ ] Every currency balance says: Total Balance: _0000_ USD (Repeated Total Balance:)
**My Proposal** : May be we can make cards for each currency, as containing only values like 680.60 USD, 8.00000987 BTC
2. - [ ] Currency amount is not practical : eg. we can not have 9.9887 USD (decimal values should be fixed based on currency)
**My Proposal** : Fix max decimal value allowed based on currency, like 2 decimal value for USD and 8 for BTC
3. - [ ] Filter is confusing, like Why there is comment, this doesn't explain wallet transaction due to comment
**My Proposal** : I am still not sure about this.
4. - [ ] Repeated information : Eg. xx USD has been deposited to your account, there is separate column for amount
**My Proposal** : If this is notification (wallet logs), then we don't need table, just show message with all required information like : _5 mins ago_ [from BlockRazor] 800 USD has been Deposited into your account.
5. - [ ] Purpose of table is not clear : is it notification or statement ?
**My Proposal** : If this is notification (wallet logs) same as on point 4. **IF** this is wallet statement, we need exact date and time not how long ago, and may be export/save as PDF/Excel option !?

ping @gazhayes @AshHimself @samuelralak

**Comment by gazhayes** [comment]
These should mostly be separate issues rather than one huge issue.

For example, I just created #924.

**Comment by gazhayes** [comment]
> may be export/save as PDF/Excel option

this doesn't solve any immediately clear problem.

**Comment by MadanBhandari** [comment]
> These should mostly be separate issues rather than one huge issue.

I created this for discussion purpose first and I thought creating single issue would help to keep related issues at same place.

> Purpose of table is not clear : is it notification or statement ?

@gazhayes Did you got my point ? or I am the one who is confused ?

> That definitely needs some UI work. ....

I will look into this and will share my solution for this.

**Comment by gazhayes** [comment]
> I created this for discussion purpose first and I thought creating single issue would help to keep related issues at same place.

Yep, I know, I'm not saying you did anything wrong just saying yeah I agree and these are real problems so we can make them official.

> Did you got my point ? or I am the one who is confused ?

I get it, and yes it's confusing. We need to keep the notification badge for transactions, and its too much data to put into 'real' notifications. But we also don't need a separate list of wallet notifications, only the table. Maybe just order them by date by default and make new transactions since list visit a different colour or something. This could be done in #924.

**Comment by MadanBhandari** [comment]
> this doesn't solve any immediately clear problem.

Yes, this isn't a problem for now, just an feature request (If the purpose of table is account statement)

**Comment by gazhayes** [comment]
OK. If blockrazor becomes a thing and people want pdf/excel transaction output they'll ask for it.

**Comment by gazhayes** [comment]
@MadanBhandari You should log point 1 as a new issue too, that's definitely an annoying problem.

**Comment by MadanBhandari** [comment]
> Yep, I know, I'm not saying you did anything wrong just saying yeah I agree and these are real problems so we can make them official.

What about adding Discussion instead of Problem in title ? For discussion purpose and make new issues to make it official.

**Comment by MadanBhandari** [comment]
Like, Just I did.

**Comment by gazhayes** [comment]
> What about adding Discussion instead of Problem in title

What happens when you do this is two negative things:
1. it degrades the issue list, makes it longer than necessary and requires more brain cycles to process because some things aren't really problems. It also opens the door to all kinds of sillyness because it implies that we have permission to start putting *anything* on the issue tracker, things degrade very quickly.

2. It very quickly leads to [bikeshedding](https://www.urbandictionary.com/define.php?term=bikeshedding). Everything must be centered around clear and describable problems.

**Comment by gazhayes** [comment]
Is everything covered by those other issues I logged? Or is there still more to resolve?

**Comment by MadanBhandari** [comment]
> What happens when you do this is two negative things:

Got it, thanks for the clarification :)

> Is everything covered by those other issues I logged? Or is there still more to resolve?

Filter is not included yet and still I am not sure about solution, I will update here, once I figured out.

**Comment by gazhayes** [comment]
Ah yeah, that filter thing. I have no idea what to do. However I suggest creating a new issue and closing this one, that we it's more inviting and specific enough that others will probably pitch in with some ideas. I don't think it's possible for anyone to come up with a simple elegant solution to this problem though.

**Comment by MadanBhandari** [comment]
Created new issue for filter #929.

Closing this.
