### ISSUE TITLE
problem: too much data in wallet

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#924]
Problem: there's too much data in /wallet, it's overwhelming. 

Possible solution: use cards or something on the main wallet page to show total balances. Clicking on one of these can lead users to a table view of all transactions for that currency.

**Comment by chamidu-supeshala** [comment]
Done in #937

**Comment by gazhayes** [comment]
REALLY nice work :)

**Comment by chamidu-supeshala** [comment]
Thank you for the appreciation :) :+1:
