### ISSUE TITLE
problem: wallet transactions shown in relative time

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#926]
Problem: Wallet transactions are more of a statement rather than a notification, having transactions displayed as relative time (e.g. 3 weeks ago) instead of absolute time is confusing.

solution: display as datetime

**Comment by chamidu-supeshala** [comment]
done in #927

**Comment by MadanBhandari** [comment]
I think we should also add timezone, OR somewhere on whole website to set timezone or let user know about default timezone.

I have no idea about date and time as user.

Any better idea ?

png @gazhayes @chamidu-supeshala

**Comment by gazhayes** [comment]
Timestamps are epoch time, so they are displayed in the users local timezone already (I think). Maybe you should verify that though and log an issue if not.

**Comment by chamidu-supeshala** [comment]
@MadanBhandari   I initially added GMT with timezone, then changed it to Local time with timezone. Finally removed timezone, thinking that there is no need to show timezone, as this is already converted to local time. If need it, i will add it along with my next PR.

**Comment by MadanBhandari** [comment]
Yes, it is based on my local time. By default it wasn't sorted by time, that was the reason behind my confusion. Making sorted by time default will solve problem.

**Comment by MadanBhandari** [comment]
> Finally removed timezone, thinking that there is no need to show timezone, as this is already converted to local time.

By default sorting by date/time should be enough.

**Comment by chamidu-supeshala** [comment]
Ok i will work on it :+1:
