### ISSUE TITLE
Problem: It's not clear to casual viewers this site is managed by community, decentralise and open initiative

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#928]
Problem: Not clear about site is open initiative, community driven

Solution : Add short about us paragraph on bottom (footer) and link licence information, privacy policy and terms of use.

I have no idea about legal process and content for documentation but in my view these are complete necessary.

This can be low priority issue for now, as we are still in active development.

ping @gazhayes

**Comment by MadanBhandari** [comment]
Let's keep this on low priority for now and wait for better ideas.

> The footer would be no good due to infinite scroll but it could be a help thing in the not nav menu that opens an about us page.

I agree on this, I just wanted to put one paragraph to tell exactly what is Blockrazor and more details on about-us page. So that user will get some idea before going through very long content.

**Comment by gazhayes** [comment]
Actually I wouldn't call this one low priority. It's probably the most commonly suggested thing people tell me when I show them blockrazor.

**Comment by gazhayes** [comment]
Closing in preference of #1014
