### ISSUE TITLE
Problem : Filter transaction in wallet is not clear

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#929]
Problem : Filter in /wallet is not clear how it works, eg. Top Comments doesn't explain that wallet transaction because of top comment.

Solution : Share your ideas, this is basically some UX update, may be just updating content (text) should be enough.

**Comment by samuelralak** [comment]
@MadanBhandari been playing around with the filter  and am not entirely sure that it works the way its supposed to i.e data is not correctly filtered. I think this needs to be addressed as well.

I also think that the position of rows per page should be easily accessible, having at the very bottom of the page IMO may not be the best user experience.
<img width="418" alt="screen shot 2018-04-04 at 7 24 16 pm" src="https://user-images.githubusercontent.com/4476552/38320645-d3d0c90a-383d-11e8-84f0-6cdcc533514d.png">

**Comment by MadanBhandari** [comment]
I do not have enough data to check all sort data.

One quick question : how can I become moderator on local? I want to check UI/UX of moderator only pages and see other problems.

> I also think that the position of rows per page should be easily accessible, having at the very bottom of the page IMO may not be the best user experience.

Yes, rows per page can be placed on top, on same row as filter, currently filter is also too long.

**Comment by samuelralak** [comment]
if you have restore the database dump you can use these credentials

**Comment by MadanBhandari** [comment]
Updated on #930

**Comment by MadanBhandari** [comment]
Please verify the changes and update if anything else can be done for this, other we should close this one.
