### ISSUE TITLE
Problem: radar chart tries to render before subscription is ready

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#93]
The radar charts for each currency on the main (/) route try to render before the subscription to graphdata is ready.

https://github.com/Blockrazor/blockrazor/blob/7036d8140f53b75ab40289b1146b3c27bcca5d2a/views/templates/normal/currency.html#L1

https://github.com/Blockrazor/blockrazor/blob/7036d8140f53b75ab40289b1146b3c27bcca5d2a/client/normal/currency.js#L48

Possible solution: wait for subscription to be ready before trying to render the chart.

**Comment by madguy02** [comment]
@gazhayes  can you please elaborate on this issue. Some more insight on the problem will be helpful

**Comment by gazhayes** [comment]
It's quite straight forward, the chart cannot render if the subscription isn't ready. So what happens is most of the time the charts simply don't render. If you refresh the page over and over again, some charts for some currencies *will* render because the universe aligned in such a way that the subscription happened to be ready before the chart tried to render.

**Comment by gazhayes** [comment]
@AshHimself don't do any issues with the `paid_contributor_assessment` in future.
