### ISSUE TITLE
problem: [/currency/] exchange typeahead display id instead of name

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#945]
Problem: exchange typeahead display id instead of name

Solution: Unknown

**Comment by gazhayes** [comment]
The idea here is to let the user select from an existing exchange or add a completely new one. @janat08 used those _id values as random data just to have something in the UI (I think).

**Comment by janat08** [comment]
yes, typeahead shows name fields that are random IDs.

**Comment by janat08** [comment]
fixtures.js
