### ISSUE TITLE
Problem: can't login and logout thrice on [/]

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#948]
Problem: You can't login and then logout thrice, on 3rd time logout getting broken on route [/]. Occurred after meteor reset.

**Comment by gazhayes** [comment]
> Occurred after meteor reset.

After database reset, or after rebuild? Does this happen on production?

**Comment by janat08** [comment]
You did reproduce it on dev though? "meteor reset" command, but maybe not exclusively then. I'd try deleting constellation package with it's account module, and then I messed about with Meteor.logout().

**Comment by gazhayes** [comment]
It's only on dev environment? I wouldn't worry about it then.

**Comment by gazhayes** [comment]
Going to close for now, reopen if it causes serious issues.
