### ISSUE TITLE
Problem: add new currency for blockrazor bounty last reward is incorrect

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#951]
Problem: there's a last reward element in the UI on the new currency bounty. It appears to be displaying perhaps the highest reward issued for this bounty, but it should display the *last* reward.

<img width="1132" alt="screen shot 2018-04-06 at 8 21 20 am" src="https://user-images.githubusercontent.com/8143945/38398062-a9e0b894-3973-11e8-9b46-00af435b1583.png">

**Comment by chamidu-supeshala** [comment]
fixed in #965
