### ISSUE TITLE
Problem: [/communities] "=" is not clear

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#956]
Problem: the text and equality symbol are hard to see. 

<img width="234" alt="screen shot 2018-04-06 at 12 24 43 pm" src="https://user-images.githubusercontent.com/8143945/38403488-5d55386a-3996-11e8-8aa6-b8b8f1ff0c1f.png">

possible solution: this needs to be easily differentiated from the other two choices, but should also be easy to read. I guess another background colour would work, or maybe light text or something.

**Comment by gazhayes** [comment]
This might also affect codebase and wallet rankings, I haven't checked.

**Comment by chamidu-supeshala** [comment]
I'm Taking this

**Comment by chamidu-supeshala** [comment]
modified UI in #963

**Comment by gazhayes** [comment]
Very nice work, yet again :)
