### ISSUE TITLE
problem: community rating questions cannot be rejected by moderators

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#961]
Problem: when completing community rating bounties, users must upload a picture of the community with a comment they have made. Moderators can then approve these images as legitimate. They are currently unable to reject them.

Upon rejection of a community image, the user should have their bounties associated with that community removed from their wallet. The ELO rankings should also be removed.

I believe this is already been done for wallet rankings.

ping @anbud

**Comment by anbud** [comment]
I'll take it.

**Comment by anbud** [comment]
Done in #969. I've implemented it for both community and wallet images as it wasn't implemented before for any of them.
