### ISSUE TITLE
problem: confusing UX on wallet notifications

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#968]
Problem: Confusing UX on wallet notifications, Let me best describe this, I had a notification bubble of 30 on my wallet side menu item. I clicked it. It opened the new wallet page but I had no idea what those 30 notification were directed at. 

I assume these notifications are due to notification for a certain coin, but I don't know which one.

This should be more obvious to the user, or maybe i'm just tired :)

Solution: Display notification bubbles on each coin?

**Comment by gazhayes** [comment]
Was thinking the same thing today.

**Comment by samuelralak** [comment]
lol, you are not just tired mate :), its a good catch. its not so obvious to which currency the notification belongs. adding a notification badge to each currency would definitely do.
> This should be more obvious to the user, or maybe i'm just tired :)
looking into this one

**Comment by MadanBhandari** [comment]
What about adding some indication on all new notifications ? Like unread notification/msg ?

**Comment by samuelralak** [comment]
@gazhayes am not sure I understand though I believe we already have the badge that pops up indicating the number of all unread notifications/messages. is it the same thing you are talking about?

**Comment by gazhayes** [comment]
@samuelralak I think you meant to reply to @MadanBhandari not me?

**Comment by samuelralak** [comment]
right @gazhayes  🤦‍♂️ my apologies

**Comment by samuelralak** [comment]
fixed in [#1005](https://github.com/Blockrazor/blockrazor/pull/1005)

**Comment by gazhayes** [comment]
Someone broke this.

A test is needed.

**Comment by gazhayes** [comment]
I wouldn't unassign you even if someone else can do this more efficiently - it's a good learning experience.

**Comment by AshHimself** [comment]
Help me out here @gazhayes .. what exactly is broken? I see notification bubbles against the correct currency?
![image](https://user-images.githubusercontent.com/148682/38682310-51d9e9a2-3e9d-11e8-9330-5b4582eed804.png)

**Comment by AshHimself** [comment]
ok so I get it now. The problem @gazhayes is that when you view the page the notifications are not being cleared?

**Comment by gazhayes** [comment]
Thought I replied to this.

I _think_ it's just database artefacts that will self-fix when we nuke all user data later.

**Comment by AshHimself** [comment]
got it! @blockrazorbot unassign

**Comment by AshHimself** [comment]
@gazhayes what did you want to do with this ticket then mate? Did you want to leave it open until we confirm its a database issue?

**Comment by gazhayes** [comment]
I'll close it, hopefully it's just a database thing.
