### ISSUE TITLE
problem: side menu does not automatically close on small screens

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#971]
Problem: side menu does not automatically close on small screens. The side menu should automatically get out of the way on small screens when you click an item.

This was working before, I believe it was broken in #967 (but haven't verified).

**Comment by gazhayes** [comment]
OK I'll try on a few more phones and see what happens.

**Comment by gazhayes** [comment]
Could you log the z-index issue?

**Comment by samuelralak** [comment]
@gazhayes you are right. the sidenav doesn't automatically close.  Clicking on a side nav item doesn't automatically  close the side menu.

**Comment by chamidu-supeshala** [comment]
fixed #974
