### ISSUE TITLE
problem: [/currency/x] graphs don't scale well

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#972]
Problem:
![s80406-23394188](https://user-images.githubusercontent.com/8143945/38430539-1c3052da-39f4-11e8-985b-4618dd0b857c.jpg)

**Comment by samuelralak** [comment]
changing responsive option to true and maintainAspectRatio to false, yields the below results. though these options may have to be toggled based on the screen size since they don't do well on large screen sizes.
<img width="378" alt="screen shot 2018-04-06 at 6 51 06 pm" src="https://user-images.githubusercontent.com/4476552/38431031-a49755b6-39cb-11e8-8d20-db5d7d8fdcea.png">

**Comment by chamidu-supeshala** [comment]
@samuelralak are you going to correct this issue?

**Comment by chamidu-supeshala** [comment]
I've mistakenly assigned this tasked to myself. Then saw, you have suggested the solution. So, solution is already yours, you can correct that. :) I'm going to sleep now :)

**Comment by samuelralak** [comment]
@chamidu-supeshala  no worries chief. Though it really doesn't matter who suggested the solution, if you are in a position to do it and its not already taken then there's no harm in assigning yourself to it 😉. no mistake was made my good sir

**Comment by chamidu-supeshala** [comment]
Haha :jack_o_lantern: You are very funny.  Good to know the procedure, however brother, I'm just going to sleep now, so its up to you :)

**Comment by bstarr322** [comment]
let me do that then :)

**Comment by samuelralak** [comment]
@bstarr322 am working on this already and am about to make a PR in a few

**Comment by bstarr322** [comment]
oh really
ok then I will leave this

**Comment by bstarr322** [comment]
anyway if you haven't completed this then let me know, I've finished this on my local.
thanks

**Comment by gazhayes** [comment]
FYI @bstarr322 watch out for these:
<img width="411" alt="screen shot 2018-04-09 at 9 15 47 am" src="https://user-images.githubusercontent.com/8143945/38474932-ac915548-3bd6-11e8-844f-2000f00875a8.png">
<img width="224" alt="screen shot 2018-04-09 at 9 15 33 am" src="https://user-images.githubusercontent.com/8143945/38474933-acbfd652-3bd6-11e8-954c-2df15b247043.png">
