### ISSUE TITLE
Problem: [/currency/x] Red flags still has show/hide button

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#976]
Problem: [/currency/x] Red flags still has show/hide button while rest of the other sections has been updated with load more options to load more content.

Solution : Remove show/hide button and make similar layout to Features

**Comment by samuelralak** [comment]
@MadanBhandari I think a `load more` button would also be handy here

**Comment by MadanBhandari** [comment]
Yes, all the section of similar type should follow same pattern.
