### ISSUE TITLE
Problem: [/currency/x] Add exchange UI/UX is not good

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#977]
Problem: [/currency/x] Add exchange UI/UX is not good

Solution : Added exchange options should have some separations (like commas or something) and separate with enough space to show add new exchange.

**_Question_** : What it is mean by exchange ? Like Coinbase, Kraken etc. ? or something else ?

ping : @gazhayes @samuelralak

**Comment by gazhayes** [comment]
Check #891

**Comment by gazhayes** [comment]
> Question : What it is mean by exchange ? Like Coinbase, Kraken etc. ? or something else ?

Yeah you got it.

**Comment by gazhayes** [comment]
Also check #783

**Comment by MadanBhandari** [comment]
One more question : What does current values mean ? Like 4fy5ev5QFApkRXYQt, 66yQHqJ6jNBkgcBRT, 2LAkibNeKp3zGoB7A etc.

**Comment by gazhayes** [comment]
Nothing, just random data for testing

**Comment by gazhayes** [comment]
Closing in favour of #997
