### ISSUE TITLE
Problem: [/currency/x] Repeated No matching results founds message

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#978]
Problem: Repeated No matching results founds message

Solution : This message should be there only if there is no information available.

**Comment by janat08** [comment]
This message is meant for comments, it is rendered as part of each for commentRender.js with no separate template for showing list of these comments, yet they're shown conditionally. The code about which issue is, is located in feature.html.

**Comment by gazhayes** [comment]
The message could be updated to something like "There's nothing here yet, why don't you add something?" to make it nicer.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@MadanBhandari - This has been done.
