### ISSUE TITLE
Problem: no query projection limit on [/bounties]

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#980]
Problem: There's not any limit to query on [/bounties] page.

**Comment by gazhayes** [comment]
Do you mean limiting the number of results?

**Comment by janat08** [comment]
limit results, projection is limit, sort, fields etc.

**Comment by janat08** [comment]
[/bounties] uses several collections so unless you're okay with just passing the limit and sort even if you're passing it to several collections which means you actually x*limit number of documents then it's best to make sure that you only have to query bounties in [/bounties], although gazhayes thinks that will be next to impossible.

**Comment by janat08** [comment]
btw another problem here is that the sort values are also calculated client side, so you can't readily sort large collections either.

**Comment by gazhayes** [comment]
What we'll probably do is sort each individual collection by bounty value (somehow, the value isn't in the collection but the timestamp is and that's how the value is calculated) and limit each collection to the x top items. It's important not to cut off whole categories of bounties that are all lower value than another catagory, but it's also important not to try and load 50,000 bounties at once of course.

**Comment by janat08** [comment]
they supposedly will have different gradients of bounty growth. as in different modifiers and such.

**Comment by anbud** [comment]
Yap, currently, different collections have different multipliers, multipliers vary by collection.

**Comment by anbud** [comment]
I'll take this one then, I'll implement a way to limit them and sort them server side.

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1075.

@blockrazorbot label "done"
