### ISSUE TITLE
problem: recapture imported globally on client

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#981]
Problem: recapture is imported in the headers here https://github.com/Blockrazor/blockrazor/blob/6dd1fb652f0ef20a3596923a050adcfba69a419e/client/root.html#L4

possible solution: dynamic import that is only triggered when it is required.

**Comment by anbud** [comment]
I'll take this one, dynamic import is a better solution, I agree.

**Comment by anbud** [comment]
Done in #1046.
