### ISSUE TITLE
Problem: active development image is not global

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#982]
Problem: the active development image is not global, it also interferes with the layout.

solution: Remove the orange warning image at [/]. Trigger a modal on load (globally) that displays the existing modal, add the orange image to the modal. Use cookies so that user can close it and not see it again. Maybe set a timeout on the cookie for 5 days or something so that it comes back after a while.

**Comment by janat08** [comment]
this is hiden in dev env.
