### ISSUE TITLE
problem: [/] genesis timestamp currency filter is hard to use

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#984]
Problem: picking two dates is hard to do and not very dynamic.

possible solution: use a slider, see example 2 [here](http://seiyria.com/bootstrap-slider/). Genesis dates are timestamps, so for now the number range can be from 1233619200000 to Date().getTime(). 

The C4 will eventually make it look more date-like (instead of number-like) if not done in this issue.

**Comment by AshHimself** [comment]
Agree that would be nicer. I do find though however these to be a little dicky on mobile devices. Just something we need to be mindful of if desktop and mobile are requirements.

**Comment by gazhayes** [comment]
Mobile can have a cut down version, maybe a checkbox "hide anything older than 6 months"

**Comment by chamidu-supeshala** [comment]
I'm going to try this as suggested..

**Comment by chamidu-supeshala** [comment]
fixed in #985

**Comment by gazhayes** [comment]
Continued in #986
