### ISSUE TITLE
problem: [/] date filter only works in one direction

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#986]
Problem: the date filter only filters out currencies with a genesis block after x date, it does not remove currencies with a genesis before x date. In other words, the left hand side of the slider has no effect.

**Comment by chamidu-supeshala** [comment]
fixed in #987

**Comment by chamidu-supeshala** [comment]
I think this issue still not fixed :(

**Comment by chamidu-supeshala** [comment]
BTC is missing.

**Comment by chamidu-supeshala** [comment]
Unfortunately BTC not present in my local DB. I have re-executed the dump files, still no help. I can reduce the minimum value to January 2009 or something, however couldn't test in locally without having BTC in my DB. If somebody can tell me the exact genesis timestamp of BTC, it will help me a lot.

**Comment by chamidu-supeshala** [comment]
Unfortunately BTC not present in my local DB, Even after re-executing dump files, still no help. Without having it in the DB, there is no way to test in locally. I'm also thinking that above mentioned boundary issue may be the case. However it is not good enough to create a PR without testing in DB. So i'm lost here

**Comment by gazhayes** [comment]
Fetch /static/dump.tar.gz

**Comment by chamidu-supeshala** [comment]
Thanks @gazhayes , It helped and issue fixed in #988 :)
