### ISSUE TITLE
Problem: the sidebar constantly updating the preference on DB if the user just opens and closes the sidebar.

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#989]
Problem: the sidebar currently saves at which screen width it was opened or closed constantly updating the preference on DB if the user just opens and closes the sidebar.

Solution: Use publication and subscription to store preference on the server, since methods can't be called on window destroy events: https://github.com/meteor/meteor/issues/340, but it's difficult to reliably use publication for these purposes even if there's a hook for when WebSocket connection closes.

This is what I have than isn't reliable, especially onStop hook as it's called every time parameters change:

```
  Meteor.publish("trackUserSideBarPref", function(pref, prefOnRecord){ 
    Meteor.onConnection((connection)=>{ 
      console.log("opening", pref, prefOnRecord, connection.id) 
      connection.onClose(()=>{ 
        console.log("closing", pref, prefOnRecord, connection.id) 
      }) 
    }) 
    this.onStop(function(){ 
      console.log("connection", pref, prefOnRecord, this.connection.id) 
      if (pref != prefOnRecord){ 
        Meteor.call("sidebarPreference", pref, Meteor.userId()) 
      } 
  }) 
```

**Comment by gazhayes** [comment]
What do you mean by 'stale' exactly? What do you want to happen?

**Comment by janat08** [comment]
if any1 has a better way.

**Comment by gazhayes** [comment]
OK. In these situations, you should ping people for ideas instead to get the desired result (feedback from others). Otherwise it's not clear what you want to do.
