### ISSUE TITLE
Problem: [/bounties] last reward shown is false

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#990]
Problem: [/bounties] last reward shown can be false, use add coins since bounty won't reset for any other bounty.

Solution: The code that shows last rewad was written before bounty reset logic was implemented, and it assumed that the bounty would have to be approved which it doesn't (for add coins bounty).

**Comment by gazhayes** [comment]
@anbud I think this was fixed in #991, just noticed it seems to be working now.

**Comment by anbud** [comment]
Done in #1033. The previous solution wasn't entirely working, as individual bounties are removed from the database when the user has been rewarded, so the data about previous bounties wasn't always available. Note that this solution is not backward compatible and it will start working when a new bounty is completed.
