### ISSUE TITLE
Problem: [/bounties] reason for bounty value resets not clear to users

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#991]
Problem: Currently when a bounty is reset an sAlert is shown. This is easily missed by the user and is not linked in the UI to the actual bounty being rest.

solution: use an overlay over the item that was reset. 

Test with add coin bounty as it will reset on submission. The text for overlay should be something like: > xxxx user has claimed this bounty for xx KZR and the bounty reward has been reset.

The logic that deals with this so far is in: https://github.com/Blockrazor/blockrazor/blob/a9e63ab6f4099945b356e0259babc6ad2b3090f3/imports/ui/pages/bounties/bounties.js#L152

**Comment by samuelralak** [comment]
looking into this now

**Comment by samuelralak** [comment]
@gazhayes and @janat08 kindly review changs made by [#1008](https://github.com/Blockrazor/blockrazor/pull/1008); this issue can be closed if there are not other requirements

**Comment by gazhayes** [comment]
Is it meant to stay pinned there like that? I think it should stay up for x seconds then go away (leaving the last bounty amount there).
<img width="914" alt="screen shot 2018-04-08 at 10 33 53 pm" src="https://user-images.githubusercontent.com/8143945/38468762-338b0ea4-3b7d-11e8-93f8-0def3b127f04.png">

**Comment by samuelralak** [comment]
@gazhayes yeah currently its meant to stay pinned. This makes it obvious for other users who visit and scroll down the bounties page. A bounty that has been reset is pushed down the page so if it were to disappear after x seconds, chances are other users may not see the notification when they scroll down to that particular bounty.
> Is it meant to stay pinned there like that? I think it should stay up for x seconds then go away (leaving the last bounty amount there).

An alternative solution would be to display the notification when user hovers on the bounty item card

**Comment by gazhayes** [comment]
Ok, what do you think about leaving it pinned for a few hours instead?

**Comment by samuelralak** [comment]
@gazhayes is there a specific number of hours you had in mind?

**Comment by gazhayes** [comment]
Not really, but I guess we could start with 2 and see what happens.

**Comment by gazhayes** [comment]
By the way, where are you pulling the username from? (undefined)

**Comment by samuelralak** [comment]
sounds good. we set it 2hrs then observe. i’ll make the update

**Comment by gazhayes** [comment]
The other bounties that repeat ("Add new hash power data for Blockrazor", "Rate cryptocurrency wallets for Blockrazor", "Rate cryptocurrency communities for Blockrazor") should probably do the same thing, the same problem affects them.

**Comment by gazhayes** [comment]
OK, it probably happens for that particular add coin bounty because you can complete it without actually doing it through the bounty page.

**Comment by gazhayes** [comment]
I see the overlay is removed after 2 hours, but the 'last bounty reward' is also removed. We should keep that part permanently so that users know how high to 'bid'.

**Comment by samuelralak** [comment]
@gazhayes thats strange, I haven't pushed the patch for this yet. Someone either accidentally fixed this one or broke it or both 😅. let me see what has changed
> I see the overlay is removed after 2 hours, but the 'last bounty reward' is also removed. We should keep that part permanently so that users know how high to 'bid'.

**Comment by gazhayes** [comment]
Huh, it's back again. Could be something local for me.

So you haven't changed the timeout to 2 hours either?

**Comment by anbud** [comment]
Apparently, I've added the 2 hour limit while working on another issue. I had to change the way we get the previous reward amount (as it's now in the bounty object itself), but I've thought that the 2 hour limit was already implemented before, that's why I wrote it. :)

**Comment by samuelralak** [comment]
lol, there's our curlprit 😂
