### ISSUE TITLE
Problem: block razor isn't pwa- installable on mobile.

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#992]
Problem: Block razor can't be installed on mobile, and given we have Localizable Collection we might look at making blockrazor offline ready, which would require web worker.

Solution: uses google's workbox to make manifest for installation to home screen. It's sad that we can't use meteor's cache for this instead of web worker's one.

**Comment by gazhayes** [comment]
This isn't an issue right now, it could be later on if blockrazor becomes popular.
