### ISSUE TITLE
problem: [/currency/x] not possible to propose adding exchanges to a currency

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#997]
Problem: it's not possible for users to add exchanges to coins on the currency detail page.

possible solution: Allow users to add an exchange to a currency from the existing list of exchanges or add a new exchange. Ideally this would be a typahead list with "add" if what the user types isn't found (e.g. how Github works with adding branches).

Any solution should also denormalize the data into the currencies collection so that currencies on the home route can be filtered by "is currently listed on an exchange".

**Comment by janat08** [comment]
All the logic for this is done, except for the add template. Notes in last comments of #783.

**Comment by samuelralak** [comment]
whats the progress on this one? is anyone actively working on this one?

**Comment by gazhayes** [comment]
No, no one has claimed it

**Comment by janat08** [comment]
I think I saw jquery typeahead that was reactive for meteor.

**Comment by gazhayes** [comment]
Can you find it again?

**Comment by samuelralak** [comment]
ok cool. can't claim now though but will take a look if its not claimed before finishing my current issues
> No, no one has claimed it

**Comment by janat08** [comment]
https://atmospherejs.com/sergeyt/typeahead
I'll take it if we're converting.

**Comment by gazhayes** [comment]
Just remember there are no secret updates and no discussions outside of the issue tracker, so what you see here is what you get. If it's not claimed, no one is working on it. And if there are no attached pull requests and no comments, there are no updates ;)

**Comment by janat08** [comment]
It said it supported blaze templates for autocomplete suggestions.

**Comment by gazhayes** [comment]
@janat08 That looks like the simplest solution :)

**Comment by gazhayes** [comment]
If there are any problems with that package and you want to modify it I'll fork it here and C4 it, it looks like there's a good pull request just waiting to be merged but the maintainer is being picky about silly things.

**Comment by janat08** [comment]
Still can't have reactive value since I can't bind an event to typeahead input: https://github.com/sergeyt/meteor-typeahead/issues/161

**Comment by janat08** [comment]
@blockrazorbot claim

**Comment by janat08** [comment]
I couldn't pass in a event or reflect current value of typeahead in empty template.

**Comment by gazhayes** [comment]
>  in empty template.

Can you explain more here, a template referring to an empty data set?

**Comment by janat08** [comment]
empty result set.

**Comment by gazhayes** [comment]
OK. I don't know how far along you are with this, but a simpler solution will be to just add a "add new" button next to the typeahead dropdown (similar to /add-hashpower).

**Comment by janat08** [comment]
The package is in place, the fact that I can't select typeahead element or update the value aside. The typeahead('val') will work, it's more about other options I like custom events and updating the value.

**Comment by gazhayes** [comment]
OK. Stay focussed on the problem. This solution is probably too complicated and not worth it.

If you have to make *something* work in an hour and close this issue what would you do?

**Comment by janat08** [comment]
``Ideally this would be a typahead list with "add" if what the user types isn't found (e.g. how Github works with adding branches).``
Do you want a separate button?

**Comment by gazhayes** [comment]
Oh ok, well element selection would be better :)

**Comment by janat08** [comment]
I'm just waiting for someone to respond to https://github.com/sergeyt/meteor-typeahead/issues/161 though.

**Comment by gazhayes** [comment]
It's safe to say no one is going to respond. So just do whatever the simplest thing is to close this off.

**Comment by gazhayes** [comment]
Closed and moved to #1236
